In [ ]:
library(numbat)
library(dplyr)
library(Seurat)
library(data.table)
library(future)
plan("multicore", workers = 12)
options(future.globals.maxSize = 10000 * 1024^10,
        future.rng.onMisuse = 'ignore')
sessionInfo()

Loading required package: Matrix


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: SeuratObject

Loading required package: sp


Attaching package: ‘SeuratObject’


The following objects are masked from ‘package:base’:

    intersect, saveRDS


Loading Seurat v5 beta version
To maintain compatibility with previous workflows, new Seurat objects will use the previous object structure by default
To use new Seurat v5 assays: Please run: options(Seurat.object.assay.version = 'v5')


Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last

R version 4.2.3 (2023-03-15)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Rocky Linux 8.7 (Green Obsidian)

Matrix products: default
BLAS/LAPACK: /gpfs/home3/cruiz2/miniconda3/envs/r_python/lib/libopenblasp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] future_1.32.0           data.table_1.14.8       Seurat_4.9.9.9040
[4] SeuratObject_4.9.9.9081 sp_1.6-0                dplyr_1.1.1
[7] numbat_1.2.3            Matrix_1.5-3

loaded via a namespace (and not attached):
  [1] uuid_1.1-0             spam_2.9-1             parallelDist_0.2.6
  [4] fastmatch_1.1-3        plyr_1.8.8             igraph_1.4.1
  [7] repr_1.1.6             lazyeval_0.2.2         splines_4.2.3
 [10] RcppHNSW_0.4.1         listenv_0.9.0          scattermore_0.8
 [13] ggplot2_3.4.1          digest_0.6.31          yulab.utils_0.0.6
 [16] htmltools_0.5.5        viridis_0.6.2          fansi_1.0.4
 [19] magrittr_2.0.3         tensor_1.5             cluster_2.1.4
 [22] ROCR_1.0-11            globals_0.16.2         graphlayouts_0.8.4
 [25] RcppParallel_5.1.7     matrixStats_0.63.0     spatstat.sparse_3.0-1
 [28] colorspace_2.1-0       ggrepel_0.9.3          crayon_1.5.2
 [31] jsonlite_1.8.4         progressr_0.13.0       spatstat.data_3.0-1
 [34] survival_3.5-5         zoo_1.8-11             phangorn_2.11.1
 [37] ape_5.7-1              glue_1.6.2             polyclip_1.10-4
 [40] gtable_0.3.3           leiden_0.4.3           future.apply_1.10.0
 [43] abind_1.4-5            scales_1.2.1           spatstat.random_3.1-4
 [46] miniUI_0.1.1.1         Rcpp_1.0.10            viridisLite_0.4.1
 [49] xtable_1.8-4           gridGraphics_0.5-1     tidytree_0.4.2
 [52] reticulate_1.28        dotCall64_1.0-2        htmlwidgets_1.6.2
 [55] httr_1.4.5             RColorBrewer_1.1-3     ellipsis_0.3.2
 [58] ica_1.0-3              pkgconfig_2.0.3        farver_2.1.1
 [61] uwot_0.1.14            deldir_1.0-6           utf8_1.2.3
 [64] ggplotify_0.1.0        tidyselect_1.2.0       rlang_1.1.0
 [67] reshape2_1.4.4         later_1.3.0            munsell_0.5.0
 [70] tools_4.2.3            cli_3.6.1              generics_0.1.3
 [73] ggridges_0.5.4         evaluate_0.20          stringr_1.5.0
 [76] fastmap_1.1.1          goftest_1.2-3          ggtree_3.6.2
 [79] RhpcBLASctl_0.23-42    fitdistrplus_1.1-8     tidygraph_1.2.3
 [82] purrr_1.0.1            RANN_2.6.1             ggraph_2.1.0
 [85] pbapply_1.7-0          nlme_3.1-162           mime_0.12
 [88] aplot_0.1.10           compiler_4.2.3         plotly_4.10.1
 [91] png_0.1-8              spatstat.utils_3.0-2   treeio_1.22.0
 [94] tibble_3.2.1           tweenr_2.0.2           stringi_1.7.12
 [97] RSpectra_0.16-1        logger_0.2.2           lattice_0.20-45
[100] IRdisplay_1.1          vctrs_0.6.1            pillar_1.9.0
[103] lifecycle_1.0.3        spatstat.geom_3.1-0    lmtest_0.9-40
[106] RcppAnnoy_0.0.20       cowplot_1.1.1          irlba_2.3.5.1
[109] httpuv_1.6.9           patchwork_1.1.2        R6_2.5.1
[112] scistreer_1.1.0        promises_1.2.0.1       KernSmooth_2.23-20
[115] gridExtra_2.3          parallelly_1.35.0      codetools_0.2-19
[118] fastDummies_1.6.3      MASS_7.3-58.3          withr_2.5.0
[121] sctransform_0.3.5      parallel_4.2.3         quadprog_1.5-8
[124] grid_4.2.3             ggfun_0.0.9            IRkernel_1.3.2
[127] tidyr_1.3.0            Rtsne_0.16             pbdZMQ_0.3-9
[130] spatstat.explore_3.1-0 ggforce_0.4.1          shiny_1.7.4
[133] base64enc_0.1-3

In [ ]:
dmg <- readRDS('/projects/0/einf2548/cruiz/dmg/data/merged_dmg_atlas_qc_filtered.rds')
dmg

An object of class Seurat
38576 features across 409561 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

In [ ]:
dmg$numbat_id <- recode(dmg$predicted.annotation_level_3,
                         `AC-like` = 'Malignant',
                                       `MES-like` = "Malignant",    
                                       `OPC-like` = "Malignant", 
                                       `NPC-like` = "Malignant",    
                                       `Astrocyte` = "Glial_Neuronal", 
                                       # `Oligodendrocyte` = "Glial_Neuronal",    
                                       `OPC` = "Glial_Neuronal", 
                                       `Neuron` = "Glial_Neuronal",
                                        `Mono` = "Myeloid",
                                       `TAM-BDM` = "Myeloid",    
                                       `TAM-MG` = "Myeloid", 
                                       `DC` = "Myeloid",    
                                       `Mast` = "Myeloid",
                                       `CD4/CD8` = "Lymphoid",    
                                       `NK` = "Lymphoid", 
                                       `B cell` = "Lymphoid",    
                                       `Plasma B` = "Lymphoid",
                                       `Endothelial` = "Vascular",    
                                       `Mural cell` = "Vascular"
                         )
Idents(dmg) <- dmg$numbat_id
table(dmg@active.ident)

      Malignant  Glial_Neuronal        Vascular         Myeloid Oligodendrocyte
         231886           78710            7188           60905           25955
       Lymphoid
           4917

In [ ]:
`%nin%` <- function(x, y) !(x %in% y)
dmg <- subset(dmg, Study %nin% c('Filbin2018', 'Liu2022'))
dmg
gc()

An object of class Seurat
38576 features across 397794 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

       used        (Mb)    gc trigger  (Mb)     max used    (Mb)
Ncells     8382606   447.7    15954808    852.1    15954808   852.1
Vcells 12653726388 96540.3 16213889224 123702.2 12897181286 98397.7

In [ ]:
dmg <- subset(dmg, Study == 'Ruiz2023')
dmg

An object of class Seurat
38576 features across 205805 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

In [ ]:
ref_internal = aggregate_counts(GetAssayData(subset(dmg, 
                                                   idents = c('Malignant', 'Glial_Neuronal'),
                                                   invert = TRUE),
                                             slot = 'counts'
                                            ), 
                               as.data.frame(dmg@active.ident) %>% 
                                `colnames<-`('group') %>% 
                                tibble::rownames_to_column('cell') %>%
                                filter(!group %in% c('Malignant', 'Glial_Neuronal'))
                               )
ref_internal

Warning message:
“The `slot` argument of `GetAssayData()` is deprecated as of SeuratObject 5.0.0.
ℹ Please use the `layer` argument instead.”

cell_dict
       Vascular         Myeloid Oligodendrocyte        Lymphoid
           5538           35409           18407            3682

         Vascular     Myeloid      Oligodendrocyte Lymphoid
A1BG     6.210648e-06 6.937543e-06 1.800258e-05    1.096939e-05
A1CF     3.382036e-07 2.559213e-07 7.373789e-08    4.387757e-07
A2M      8.043712e-04 4.919084e-04 2.396482e-05    1.562041e-04
A2ML1    2.920850e-06 2.427794e-06 1.590632e-06    6.581635e-07
A3GALT2  1.199086e-06 3.057222e-06 7.479129e-07    8.775513e-07
A4GALT   3.609555e-05 3.596732e-07 4.318934e-07    3.290817e-07
A4GNT    3.074578e-08 1.245023e-07 5.266992e-08    1.096939e-07
AAAS     1.159116e-05 8.237900e-06 1.669637e-05    7.897962e-06
AACS     1.641825e-05 1.660722e-05 3.225506e-05    2.884950e-05
AADAC    2.767121e-07 2.628381e-07 6.320391e-08    1.096939e-07
AADACL2  1.045357e-06 8.991830e-08 2.106797e-08    0.000000e+00
AADACL3  3.074578e-08 4.150075e-08 2.106797e-08    0.000000e+00
AADACL4  3.074578e-08 5.533434e-08 5.266992e-08    1.096939e-07
AADAT    4.796342e-06 1.175855e-07 1.791831e-05    2.193878e-07
AAGAB    4.925475e-05 4.912306e-05 3.524671e-05    7.579849e-05
AAK1     3.297485e-04 4.878898e-04 2.878095e-04    8.741508e-04
AAMDC    6.960846e-05 4.810629e-05 1.008208e-04    3.850256e-05
AAMP     1.349740e-05 1.439384e-05 1.284093e-05    1.305358e-05
AANAT    4.611868e-07 8.514571e-06 1.790777e-07    9.872452e-07
AAR2     1.159116e-05 1.054811e-05 1.530588e-05    1.360205e-05
AARD     3.689494e-07 1.867534e-07 4.740293e-07    2.193878e-07
AARS     3.422006e-05 3.902454e-05 4.220968e-05    3.455358e-05
AARS2    8.270616e-06 1.196605e-05 8.490392e-06    8.665819e-06
AARSD1   1.506543e-05 1.668330e-05 1.699132e-05    1.338266e-05
AASDH    4.525779e-05 4.533266e-05 6.254027e-05    3.016583e-05
AASDHPPT 3.913938e-05 2.019703e-05 5.121623e-05    2.906889e-05
AASS     1.404160e-04 9.828762e-06 1.616651e-04    1.974490e-06
AATF     5.558838e-05 8.751126e-05 7.860459e-05    1.205536e-04
AATK     1.423530e-05 1.991345e-05 4.278799e-04    9.872452e-07
ABAT     1.807852e-05 7.107004e-05 3.580501e-05    3.927042e-05
⋮        ⋮            ⋮            ⋮               ⋮
ZSCAN26  2.484259e-05 2.096480e-05 5.279633e-05    1.096939e-05
ZSCAN29  8.824040e-06 1.166171e-05 1.298840e-05    9.872452e-06
ZSCAN30  4.940848e-05 3.658291e-05 1.024746e-04    1.217602e-05
ZSCAN31  2.139907e-05 3.444563e-06 8.371358e-05    4.387757e-06
ZSCAN32  1.165265e-05 1.153721e-05 1.702292e-05    1.294388e-05
ZSCAN4   1.229831e-07 2.766717e-08 1.053398e-08    0.000000e+00
ZSCAN5A  3.741762e-05 4.520124e-05 3.706909e-05    1.513776e-05
ZSCAN5B  3.074578e-08 4.841755e-08 6.320391e-08    0.000000e+00
ZSCAN5C  0.000000e+00 0.000000e+00 3.160195e-08    0.000000e+00
ZSCAN9   1.629527e-05 1.968519e-05 1.382059e-05    5.484696e-06
ZSWIM1   1.875493e-06 1.909035e-06 1.653836e-06    1.426021e-06
ZSWIM2   6.149157e-08 4.841755e-08 3.160195e-08    0.000000e+00
ZSWIM3   7.532717e-06 6.695455e-06 8.069032e-06    6.801023e-06
ZSWIM4   2.133757e-05 1.303815e-05 3.434079e-06    6.033165e-06
ZSWIM5   1.403238e-04 2.040454e-06 1.178016e-04    3.422450e-05
ZSWIM6   4.586656e-04 1.085514e-03 6.856044e-04    1.795689e-04
ZSWIM7   4.491959e-05 5.924924e-05 5.157439e-05    2.961736e-05
ZSWIM8   4.116861e-05 6.397341e-05 4.260997e-05    3.192093e-05
ZSWIM9   1.048431e-05 1.191072e-05 1.621180e-05    1.798980e-05
ZUP1     3.240606e-05 5.639952e-05 3.594196e-05    4.508420e-05
ZW10     1.786330e-05 1.910418e-05 2.486020e-05    1.426021e-05
ZWILCH   8.762549e-06 1.141271e-05 4.729759e-06    1.184694e-05
ZWINT    1.414306e-06 2.379377e-06 6.320391e-07    1.206633e-06
ZXDA     2.767121e-06 9.683509e-07 2.981118e-06    2.852042e-06
ZXDB     3.720240e-06 1.625446e-06 2.391215e-06    4.278063e-06
ZXDC     7.142246e-05 9.953956e-05 9.336271e-05    9.532401e-05
ZYG11A   1.322069e-06 6.847624e-07 6.741750e-07    1.426021e-06
ZYG11B   6.478137e-05 7.353242e-05 7.007207e-05    3.192093e-05
ZYX      3.126846e-05 3.907988e-05 3.233933e-06    2.490052e-05
ZZEF1    9.002366e-05 1.364614e-04 1.014949e-04    1.486353e-04

### Process Ruiz2023

In [ ]:
ruiz <- SplitObject(dmg, split.by = 'SampleID')
ruiz
gc()

$BT042_PD
An object of class Seurat
38576 features across 105 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$BT042_pons_1
An object of class Seurat
38576 features across 116 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$BT042_pons_2
An object of class Seurat
38576 features across 553 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$BT072_region_1
An object of class Seurat
38576 features across 1444 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$BT072_region_2
An object of class Seurat
38576 features across 7019 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$BT789AAQ
An object of class Seurat
38576 features across 5413 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$GNG_region_10
An object of class Seurat
38576 features across 5749 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$GNG_region_11
An object of class Seurat
38576 features across 6457 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$GNG_region_12
An object of class Seurat
38576 features across 5708 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$GNG_region_6
An object of class Seurat
38576 features across 1724 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T19-90627_466AAL`
An object of class Seurat
38576 features across 2056 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T19-90673_577AAL_section_1`
An object of class Seurat
38576 features across 372 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T19-90673_577AAL_section_2`
An object of class Seurat
38576 features across 4917 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T19-91014_635AAM_core`
An object of class Seurat
38576 features across 2941 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T19-91014_635AAM_edge`
An object of class Seurat
38576 features across 2421 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T20-01237_291AAN`
An object of class Seurat
38576 features across 3568 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T20-90005_998AAH`
An object of class Seurat
38576 features across 4277 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T20-90151_212AAK`
An object of class Seurat
38576 features across 1094 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T20-90239_175AAA`
An object of class Seurat
38576 features across 718 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T20-90296_472AAL_autopsy`
An object of class Seurat
38576 features across 5902 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T20-90296_472AAL_diagnosis`
An object of class Seurat
38576 features across 2455 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T20-90296_472AAL_relapse`
An object of class Seurat
38576 features across 2201 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T20-90372_190AAO`
An object of class Seurat
38576 features across 3728 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T20-93210_698AAO_region_1`
An object of class Seurat
38576 features across 4372 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T20-93210_698AAO_region_2`
An object of class Seurat
38576 features across 2760 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T20-93369_977AAO`
An object of class Seurat
38576 features across 6223 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T20-93623_348AAP`
An object of class Seurat
38576 features across 3008 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T21-90437_071AAQ`
An object of class Seurat
38576 features across 3848 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T21-90517_099AAQ`
An object of class Seurat
38576 features across 3951 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T21-90581_212AAQ_region_1`
An object of class Seurat
38576 features across 922 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T21-90581_212AAQ_region_2`
An object of class Seurat
38576 features across 913 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T21-90610_232AAQ`
An object of class Seurat
38576 features across 5816 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T21-90717_MIMIC002`
An object of class Seurat
38576 features across 3841 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T21-90789_MIMIC005`
An object of class Seurat
38576 features across 6911 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T21-90813_MIMIC006`
An object of class Seurat
38576 features across 1785 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T21-90868_448AAQ`
An object of class Seurat
38576 features across 6506 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T21-91022_MIMIC008`
An object of class Seurat
38576 features across 6106 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T21-91074_MIMIC010`
An object of class Seurat
38576 features across 4889 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T21-91160_MIMIC013`
An object of class Seurat
38576 features across 6581 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T22-90003_MIMIC014`
An object of class Seurat
38576 features across 6705 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T22-90066_MIMIC015`
An object of class Seurat
38576 features across 4467 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T22-90221_148AAR`
An object of class Seurat
38576 features across 6497 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`T22-90282_MIMIC023`
An object of class Seurat
38576 features across 4082 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$VU248
An object of class Seurat
38576 features across 5124 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$VU266
An object of class Seurat
38576 features across 6839 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4

       used        (Mb)    gc trigger  (Mb)     max used    (Mb)
Ncells     8162620   436.0    15954808    852.1    15954808    852.1
Vcells 12757798946 97334.3 19456747068 148443.2 16213886992 123702.2

In [ ]:
table(dmg$SampleID)

                  BT042_PD               BT042_pons_1
                       105                        116
              BT042_pons_2             BT072_region_1
                       553                       1444
            BT072_region_2                   BT789AAQ
                      7019                       5413
             GNG_region_10              GNG_region_11
                      5749                       6457
             GNG_region_12               GNG_region_6
                      5708                       1724
          T19-90627_466AAL T19-90673_577AAL_section_1
                      2056                        372
T19-90673_577AAL_section_2      T19-91014_635AAM_core
                      4917                       2941
     T19-91014_635AAM_edge           T20-01237_291AAN
                      2421                       3568
          T20-90005_998AAH           T20-90151_212AAK
                      4277                       1094
          T20-90239_175AAA   T20-90296_472AAL_autopsy
                       718                       5902
T20-90296_472AAL_diagnosis   T20-90296_472AAL_relapse
                      2455                       2201
          T20-90372_190AAO  T20-93210_698AAO_region_1
                      3728                       4372
 T20-93210_698AAO_region_2           T20-93369_977AAO
                      2760                       6223
          T20-93623_348AAP           T21-90437_071AAQ
                      3008                       3848
          T21-90517_099AAQ  T21-90581_212AAQ_region_1
                      3951                        922
 T21-90581_212AAQ_region_2           T21-90610_232AAQ
                       913                       5816
        T21-90717_MIMIC002         T21-90789_MIMIC005
                      3841                       6911
        T21-90813_MIMIC006           T21-90868_448AAQ
                      1785                       6506
        T21-91022_MIMIC008         T21-91074_MIMIC010
                      6106                       4889
        T21-91160_MIMIC013         T22-90003_MIMIC014
                      6581                       6705
        T22-90066_MIMIC015           T22-90221_148AAR
                      4467                       6497
        T22-90282_MIMIC023                      VU248
                      4082                       5124
                     VU266                      VU314
                      6839                       4133
                     VU494                VUMC11_pons
                      6264                       5824
           VUMC11_thalamus                     VUMC17
                      6511                       5126
            VUMC17_healthy
                      4863

In [ ]:
rm(dmg)
gc()

       used       (Mb)    gc trigger  (Mb)     max used    (Mb)
Ncells    8161740   435.9    15954808    852.1    15954808    852.1
Vcells 9459656835 72171.5 19456747068 148443.2 16213886992 123702.2

In [ ]:
#check cell name nomenclature to add to numbat pipeline
head(colnames(ruiz[[1]]))

[1] "BT042_PD_CCGTTCATCTATGTGG-1" "BT042_PD_CTACCTGGTATGAAAC-1"
[3] "BT042_PD_TTGCATTTCCTGTAGA-1" "BT042_PD_GTGCTGGGTAACGCGA-1"
[5] "BT042_PD_CTTCTAAAGACGCATG-1" "BT042_PD_CCTCACACAAAGCTAA-1"

In [ ]:
length(ruiz)

[1] 51

In [ ]:
for(i in 1:30) {  # run on the first half of ruiz
    cat(' ############################################\n',
        '### Numbat for dataset number ', names(ruiz[i]), '###\n',
        '############################################\n')
    
    old <- Sys.time() # get start time
    
    file_path <- paste0('/projects/0/einf2548/cruiz/cellranger_output/numbat_pileup_output_cellbender/',
                        names(ruiz[i]),'/',names(ruiz[i]),'_allele_counts.tsv.gz')
    
    if (file.exists(file_path)) {  # check if file exists
        df_allele = fread(file_path)
        df_allele$cell <- paste0(names(ruiz[i]),'_',df_allele$cell)
          
        # run
        out = run_numbat(
            as.matrix(GetAssayData(ruiz[[i]], slot = 'counts', assay = 'RNA')), # gene x cell integer UMI count matrix 
            ref_internal, # reference expression profile, a gene x cell type normalized expression level matrix
            df_allele, # allele dataframe generated by pileup_and_phase script and MUST BE A DATATABLE!
            min_cells = 20,
            t = 1e-3,
            max_iter = 2,
            init_k = 3,
            ncores = 40,
            ncores_nni = 40,
            multi_allelic = TRUE,
            plot = TRUE,
            genome = "hg38",
            out_dir = paste0('/projects/0/einf2548/cruiz/dmg/notebooks/iCNV/numbat/dmg_atlas_segregated_ref/Ruiz2023/',names(ruiz[i]))
        )
      
        cat(' ############################################\n',
        '### Done with dataset', names(ruiz[i]), '###\n',
        '############################################\n')
        
        # print elapsed time
        new <- Sys.time() - old # calculate difference
        print(new) # print in nice format
    } else {
        cat(' ############################################\n',
        '### Skipping dataset', names(ruiz[i]), 'because the file does not exist ###\n',
        '############################################\n')
    }
}

 ############################################
 ### Numbat for dataset number  BT042_PD ###
 ############################################
 ############################################
 ### Skipping dataset BT042_PD because the file does not exist ###
 ############################################
 ############################################
 ### Numbat for dataset number  BT042_pons_1 ###
 ############################################
 ############################################
 ### Skipping dataset BT042_pons_1 because the file does not exist ###
 ############################################
 ############################################
 ### Numbat for dataset number  BT042_pons_2 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 165.9
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
553 cells

Mem used: 76.3Gb

Approximating initial clusters using smoothed expression ..

Mem used: 76.3Gb

number of genes left: 12364

running hclust...

Iteration 1

Mem used: 28Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.57).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 27.7Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 27.7Gb

Using 3 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 27.7Gb

Iter 2 -334.076265796198, 0.017s

Iter 3 -334.076265796198, 0.01s

Found 475 normal cells..

Iteration 2

Mem used: 27.7Gb

Running HMMs on 2 cell groups..

Running HMMs on 2 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 27.6Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 27.6Gb

Using 3 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 27.6Gb

Iter 2 -313.412518792004, 0.01s

Iter 3 -305.02133141675, 0.01s

Iter 4 -305.02133141675, 0.01s

Found 476 normal cells..

Running HMMs on 2 cell groups..

All done!

 ############################################
 ### Done with dataset BT042_pons_2 ###
 ############################################
Time difference of 4.964552 mins
 ############################################
 ### Numbat for dataset number  BT072_region_1 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 433.2
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
1444 cells

Mem used: 27.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 27.7Gb

number of genes left: 12167

running hclust...

Iteration 1

Mem used: 29.4Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.84).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 28.5Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 28.5Gb

Using 8 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 28.5Gb

Iter 2 -4148.53853823187, 0.13s

Iter 3 -4096.62255293519, 0.06s

Iter 4 -4062.79784537361, 0.059s

Iter 5 -4049.28019749113, 0.06s

Iter 6 -4041.52597861625, 0.06s

Iter 7 -4036.6709634121, 0.059s

Iter 8 -4036.25387291285, 0.059s

Iter 9 -4030.77964442458, 0.06s

Iter 10 -4029.7125269131, 0.06s

Iter 11 -4029.3504545089, 0.06s

Iter 12 -4029.3504545089, 0.059s

Found 182 normal cells..

Iteration 2

Mem used: 28.5Gb

Running HMMs on 4 cell groups..

Running HMMs on 4 cell groups..

Testing for multi-allelic CNVs ..

1 multi-allelic CNVs found: 6b

Evaluating CNV per cell ..

Mem used: 28.5Gb

All cells succeeded

Expanding allelic states..

Building phylogeny ..

Mem used: 28.6Gb

Using 9 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 28.6Gb

Iter 2 -4753.4973712947, 0.18s

Iter 3 -4730.4715204476, 0.066s

Iter 4 -4710.38377886698, 0.065s

Iter 5 -4695.39392166068, 0.064s

Iter 6 -4690.17208949768, 0.064s

Iter 7 -4674.61924350835, 0.065s

Iter 8 -4634.44080380694, 0.066s

Iter 9 -4632.22756832212, 0.065s

Iter 10 -4628.82707788207, 0.065s

Iter 11 -4628.82707788207, 0.065s

Found 185 normal cells..

Running HMMs on 4 cell groups..

All done!

 ############################################
 ### Done with dataset BT072_region_1 ###
 ############################################
Time difference of 11.28271 mins
 ############################################
 ### Numbat for dataset number  BT072_region_2 ###
 ############################################

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.0 GiB”
Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 2105.7
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
7019 cells

Mem used: 29.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.7Gb

number of genes left: 12049

running hclust...

Iteration 1

Mem used: 37.7Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.87).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 32.4Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 32.6Gb

Using 10 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 32.9Gb

Iter 2 -20376.83054894, 1.8s

Iter 3 -20294.1672709175, 1.7s

Iter 4 -20240.3326770495, 1.7s

Iter 5 -20190.8878209655, 1.7s

Iter 6 -20121.8903057959, 1.7s

Iter 7 -20083.8452341797, 1.7s

Iter 8 -20055.0299136099, 1.7s

Iter 9 -20041.9997665765, 1.7s

Iter 10 -20029.2644795301, 1.7s

Iter 11 -20018.2663374785, 1.7s

Iter 12 -20016.5315715571, 1.7s

Iter 13 -19987.1854531865, 1.7s

Iter 14 -19922.7806153828, 1.7s

Iter 15 -19922.1404011476, 1.7s

Iter 16 -19895.3118086617, 1.7s

Iter 17 -19894.6935485021, 1.7s

Iter 18 -19893.5823980768, 1.7s

Iter 19 -19893.5823980768, 1.7s

Found 482 normal cells..

Iteration 2

Mem used: 32.9Gb

Running HMMs on 5 cell groups..

Running HMMs on 5 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 33.7Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 33.9Gb

Using 10 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 33.9Gb

Iter 2 -21747.1692004999, 1.7s

Iter 3 -21664.6927983304, 1.7s

Iter 4 -21600.211139824, 1.7s

Iter 5 -21575.4547378588, 1.7s

Iter 6 -21558.1299795376, 1.7s

Iter 7 -21538.3001875491, 1.7s

Iter 8 -21521.0511267343, 1.7s

Iter 9 -21503.9984425618, 1.7s

Iter 10 -21492.472990815, 1.7s

Iter 11 -21483.0915586586, 1.7s

Iter 12 -21474.2108078742, 1.7s

Iter 13 -21465.7756358609, 1.7s

Iter 14 -21462.1809134325, 1.7s

Iter 15 -21460.187151365, 1.7s

Iter 16 -21457.8732431935, 1.7s

Iter 17 -21457.8732431935, 1.7s

Found 491 normal cells..

Running HMMs on 4 cell groups..

All done!

 ############################################
 ### Done with dataset BT072_region_2 ###
 ############################################
Time difference of 1.038058 hours
 ############################################
 ### Numbat for dataset number  BT789AAQ ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1623.9
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
5413 cells

Mem used: 30.4Gb

Approximating initial clusters using smoothed expression ..

Mem used: 30.4Gb

number of genes left: 11947

running hclust...

Iteration 1

Mem used: 35.3Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.9).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31.6Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31.8Gb

Using 14 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 32Gb

Iter 2 -24117.6884054939, 1.3s

Iter 3 -23808.4346679648, 1.2s

Iter 4 -23524.131766824, 1.2s

Iter 5 -23378.0769630913, 1.2s

Iter 6 -23258.7459625386, 1.2s

Iter 7 -23223.2834047636, 1.2s

Iter 8 -23207.8967968059, 1.2s

Iter 9 -23195.312456166, 1.2s

Iter 10 -23175.1961796216, 1.2s

Iter 11 -23164.0746837112, 1.2s

Iter 12 -23158.8800787136, 1.2s

Iter 13 -23153.8899007461, 1.2s

Iter 14 -22952.2038935581, 1.2s

Iter 15 -22950.2384514396, 1.2s

Iter 16 -22948.5787304552, 1.2s

Iter 17 -22948.3537343758, 1.2s

Iter 18 -22940.7187631009, 1.2s

Iter 19 -22939.4940143158, 1.2s

Iter 20 -22927.2206850612, 1.2s

Iter 21 -22925.5609640768, 1.2s

Iter 22 -22925.5609640768, 1.2s

Found 124 normal cells..

Iteration 2

Mem used: 32Gb

Running HMMs on 7 cell groups..

Running HMMs on 7 cell groups..

Testing for multi-allelic CNVs ..

2 multi-allelic CNVs found: 11b,14b

Evaluating CNV per cell ..

Mem used: 32.8Gb

All cells succeeded

Expanding allelic states..

Building phylogeny ..

Mem used: 32.9Gb

Using 16 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 32.9Gb

Iter 2 -25148.1430846249, 1.5s

Iter 3 -24841.5488083804, 1.4s

Iter 4 -24827.4473344394, 1.4s

Iter 5 -24815.0092569715, 1.4s

Iter 6 -24807.9975164487, 1.4s

Iter 7 -24802.4334997816, 1.4s

Iter 8 -24797.052917445, 1.4s

Iter 9 -24792.0418850519, 1.4s

Iter 10 -24787.4317749592, 1.4s

Iter 11 -24783.2533557217, 1.4s

Iter 12 -24775.9102185604, 1.4s

Iter 13 -24770.7504532262, 1.4s

Iter 14 -24768.7225931749, 1.4s

Iter 15 -24763.7342679828, 1.4s

Iter 16 -24760.2624666491, 1.4s

Iter 17 -24758.0480033262, 1.4s

Iter 18 -24756.8767411667, 1.4s

Iter 19 -24752.20349167, 1.4s

Iter 20 -24751.3148949316, 1.3s

Iter 21 -24751.1373218124, 1.4s

Iter 22 -24750.7293739869, 1.4s

Iter 23 -24750.7293739869, 1.4s

Found 127 normal cells..

Running HMMs on 8 cell groups..

All done!

 ############################################
 ### Done with dataset BT789AAQ ###
 ############################################
Time difference of 43.66694 mins
 ############################################
 ### Numbat for dataset number  GNG_region_10 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1724.7
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
5749 cells

Mem used: 30.9Gb

Approximating initial clusters using smoothed expression ..

Mem used: 30.9Gb

number of genes left: 12368

running hclust...

Iteration 1

Mem used: 36Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.8).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31.9Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 32.2Gb

Using 16 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 32.4Gb

Iter 2 -40500.0831902227, 1.8s

Iter 3 -40362.394991428, 1.7s

Iter 4 -40262.5810576354, 1.7s

Iter 5 -40208.8681680696, 1.7s

Iter 6 -40080.8053673956, 1.7s

Iter 7 -39889.347936042, 1.7s

Iter 8 -39834.1382527342, 1.7s

Iter 9 -39790.6211071144, 1.7s

Iter 10 -39762.2525295659, 1.7s

Iter 11 -39736.7770056001, 1.7s

Iter 12 -39717.8033570316, 1.7s

Iter 13 -39700.8459230468, 1.7s

Iter 14 -39686.3778865975, 1.7s

Iter 15 -39674.4680842808, 1.7s

Iter 16 -39660.7428474954, 1.7s

Iter 17 -39652.7065192024, 1.7s

Iter 18 -39645.9577628223, 1.7s

Iter 19 -39635.9078370497, 1.7s

Iter 20 -39631.855634771, 1.7s

Iter 21 -39631.756552281, 1.7s

Iter 22 -39631.756552281, 1.7s

Found 5045 normal cells..

Iteration 2

Mem used: 32.4Gb

Running HMMs on 8 cell groups..

Running HMMs on 8 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 33Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 33.1Gb

Using 14 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 33.1Gb

Iter 2 -32586.6812547075, 1.5s

Iter 3 -32515.8058365731, 1.5s

Iter 4 -32358.4756317297, 1.5s

Iter 5 -32333.0856627722, 1.5s

Iter 6 -32312.2608354894, 1.5s

Iter 7 -32297.617674283, 1.5s

Iter 8 -32283.1985382188, 1.5s

Iter 9 -32224.4729450892, 1.5s

Iter 10 -32210.593104688, 1.5s

Iter 11 -32202.82759272, 1.5s

Iter 12 -32195.2884975093, 1.5s

Iter 13 -32188.4728831505, 1.5s

Iter 14 -32182.2779447481, 1.5s

Iter 15 -32176.3135836192, 1.5s

Iter 16 -32167.8243630763, 1.5s

Iter 17 -32166.4392318563, 1.5s

Iter 18 -32165.4089709724, 1.5s

Iter 19 -32165.4089709724, 1.5s

Found 5064 normal cells..

Running HMMs on 8 cell groups..

All done!

 ############################################
 ### Done with dataset GNG_region_10 ###
 ############################################
Time difference of 49.19742 mins
 ############################################
 ### Numbat for dataset number  GNG_region_11 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1937.1
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
6457 cells

Mem used: 30.8Gb

Approximating initial clusters using smoothed expression ..

Mem used: 30.8Gb

number of genes left: 12293

running hclust...

Iteration 1

Mem used: 37Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.83).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 32.1Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 32.7Gb

Using 8 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 32.9Gb

Iter 2 -33222.2639075553, 1.3s

Iter 3 -33016.7666000439, 1.3s

Iter 4 -32905.432119133, 1.3s

Iter 5 -32844.4763219358, 1.3s

Iter 6 -32813.3216308079, 1.3s

Iter 7 -32749.3334853599, 1.3s

Iter 8 -32749.3334853599, 1.3s

Found 3102 normal cells..

Iteration 2

Mem used: 32.9Gb

Running HMMs on 6 cell groups..

Running HMMs on 6 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 34.2Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 34.5Gb

Using 13 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 34.5Gb

Iter 2 -72731.0608395529, 2s

Iter 3 -72428.0784709954, 1.9s

Iter 4 -72225.7023019792, 1.9s

Iter 5 -71908.7294763823, 1.9s

Iter 6 -71744.0704245635, 1.9s

Iter 7 -71527.2020892096, 1.9s

Iter 8 -71131.0150666911, 1.9s

Iter 9 -71043.3192288164, 1.9s

Iter 10 -70959.0421672067, 1.9s

Iter 11 -70932.759203404, 1.9s

Iter 12 -70876.9017640154, 1.9s

Iter 13 -70856.6318558109, 1.9s

Iter 14 -70840.1954602212, 1.9s

Iter 15 -70802.4674438716, 1.9s

Iter 16 -70789.6246928146, 1.9s

Iter 17 -70787.8868507988, 1.9s

Iter 18 -70787.8868507988, 1.9s

Found 2957 normal cells..

Running HMMs on 8 cell groups..

All done!

 ############################################
 ### Done with dataset GNG_region_11 ###
 ############################################
Time difference of 1.020617 hours
 ############################################
 ### Numbat for dataset number  GNG_region_12 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1712.4
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
5708 cells

Mem used: 31.3Gb

Approximating initial clusters using smoothed expression ..

Mem used: 31.3Gb

number of genes left: 12623

running hclust...

Iteration 1

Mem used: 36.3Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.77).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 32.7Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 33.3Gb

Using 26 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 33.5Gb

Iter 2 -81434.6854596202, 3s

Iter 3 -81376.4907544532, 2.9s

Iter 4 -81318.5652067495, 2.9s

Iter 5 -81267.3847633933, 2.9s

Iter 6 -81233.6903097587, 2.9s

Iter 7 -81209.9271164306, 2.9s

Iter 8 -81188.1180489245, 2.9s

Iter 9 -81169.427172654, 2.9s

Iter 10 -81153.4457616765, 2.9s

Iter 11 -81139.8320828447, 2.9s

Iter 12 -81127.4807613114, 3s

Iter 13 -81116.2483036926, 3s

Iter 14 -81108.463989105, 3s

Iter 15 -81101.687394537, 2.9s

Iter 16 -81040.0375047577, 2.9s

Iter 17 -80941.5399405376, 2.9s

Iter 18 -80895.5195192016, 3s

Iter 19 -80853.2953955763, 3s

Iter 20 -80848.4109344661, 3s

Iter 21 -80844.7099024932, 3s

Iter 22 -80841.5546293744, 2.9s

Iter 23 -80839.0598442207, 3s

Iter 24 -80836.9807059328, 3s

Iter 25 -80819.4609467467, 3s

Iter 26 -80777.3717750123, 3s

Iter 27 -80776.1679442676, 2.9s

Iter 28 -80771.7086159328, 3s

Iter 29 -80770.783321003, 2.9s

Iter 30 -80770.0162340725, 2.9s

Iter 31 -80769.3887544487, 2.9s

Iter 32 -80768.8066225481, 3s

Iter 33 -80768.0863810988, 2.9s

Iter 34 -80767.0557560498, 2.9s

Iter 35 -80767.0557560498, 2.9s

Found 4020 normal cells..

Iteration 2

Mem used: 33.5Gb

Running HMMs on 12 cell groups..

Running HMMs on 12 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 35.1Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 35.4Gb

Using 28 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 35.4Gb

Iter 2 -88567.8549339072, 3.4s

Iter 3 -88487.790187466, 3.3s

Iter 4 -88410.9821444929, 3.3s

Iter 5 -88357.1503032707, 3.3s

Iter 6 -88315.174219155, 3.3s

Iter 7 -88257.9758050397, 3.3s

Iter 8 -88225.8452599108, 3.3s

Iter 9 -88195.5384309345, 3.3s

Iter 10 -88169.4451606079, 3.3s

Iter 11 -88143.3932986119, 3.3s

Iter 12 -88092.5658170449, 3.3s

Iter 13 -87899.0708602146, 3.3s

Iter 14 -87801.3146693202, 3.3s

Iter 15 -87735.0017289704, 3.3s

Iter 16 -87707.2955180061, 3.3s

Iter 17 -87685.14588147, 3.3s

Iter 18 -87605.4033895432, 3.3s

Iter 19 -87583.7517542682, 3.3s

Iter 20 -87528.2225458755, 3.3s

Iter 21 -87498.3980644061, 3.3s

Iter 22 -87477.6276232923, 3.2s

Iter 23 -87428.8648635126, 3.1s

Iter 24 -87152.7983086696, 3.2s

Iter 25 -87109.7292674399, 3.2s

Iter 26 -87071.7592859391, 3.2s

Iter 27 -87051.8719972421, 3.2s

Iter 28 -87032.8788732472, 3.1s

Iter 29 -87017.7850437126, 3.2s

Iter 30 -87003.5122923808, 3.2s

Iter 31 -86989.5892776687, 3.2s

Iter 32 -86980.5149442053, 3.2s

Iter 33 -86972.1229122695, 3.2s

Iter 34 -86963.7683080371, 3.2s

Iter 35 -86957.5991273295, 3.2s

Iter 36 -86951.4892634388, 3.2s

Iter 37 -86945.397236294, 3.2s

Iter 38 -86933.0213077502, 3.2s

Iter 39 -86903.8958478152, 3.2s

Iter 40 -86898.6657450945, 3.2s

Iter 41 -86894.3746069435, 3.1s

Iter 42 -86890.4259197521, 3.1s

Iter 43 -86886.6086906975, 3.1s

Iter 44 -86883.9283965815, 3s

Iter 45 -86883.3018745125, 3s

Iter 46 -86883.0795332211, 3.1s

Iter 47 -86849.3809673857, 3.1s

Iter 48 -86848.2312863737, 3.1s

Iter 49 -86845.9932154527, 3.1s

Iter 50 -86845.4361096931, 3.1s

Iter 51 -86845.2953698664, 3s

Iter 52 -86843.4675995665, 3s

Iter 53 -86836.8949949138, 3s

Iter 54 -86836.8949949138, 3s

Found 4039 normal cells..

Running HMMs on 13 cell groups..

All done!

 ############################################
 ### Done with dataset GNG_region_12 ###
 ############################################
Time difference of 1.001382 hours
 ############################################
 ### Numbat for dataset number  GNG_region_6 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 517.2
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
1724 cells

Mem used: 30.4Gb

Approximating initial clusters using smoothed expression ..

Mem used: 30.4Gb

number of genes left: 11800

running hclust...

Iteration 1

Mem used: 29.6Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.83).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 28.2Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 28.2Gb

No CNV remains after filtering by entropy in single cells. Consider increasing max_entropy.

 ############################################
 ### Done with dataset GNG_region_6 ###
 ############################################
Time difference of 6.903531 mins
 ############################################
 ### Numbat for dataset number  T19-90627_466AAL ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 616.8
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
2056 cells

Mem used: 28Gb

Approximating initial clusters using smoothed expression ..

Mem used: 28Gb

number of genes left: 12782

running hclust...

Iteration 1

Mem used: 30.4Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.75).

No CNV remains after filtering by LLR in pseudobulks. Consider reducing min_LLR.

 ############################################
 ### Done with dataset T19-90627_466AAL ###
 ############################################
Time difference of 3.159231 mins
 ############################################
 ### Numbat for dataset number  T19-90673_577AAL_section_1 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 111.6
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
372 cells

Mem used: 28.2Gb

Approximating initial clusters using smoothed expression ..

Mem used: 28.2Gb

number of genes left: 11838

running hclust...

Iteration 1

Mem used: 27.8Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.84).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 27.6Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 27.6Gb

Using 4 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 27.6Gb

Iter 2 -535.775532652676, 0.006s

Iter 3 -535.15183738977, 0.004s

Iter 4 -535.15183738977, 0.004s

Found 129 normal cells..

Iteration 2

Mem used: 27.6Gb

Running HMMs on 4 cell groups..

Running HMMs on 4 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 27.6Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 27.6Gb

Using 3 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 27.6Gb

Iter 2 -264.95917238122, 0.007s

Iter 3 -263.733042708529, 0.007s

Iter 4 -263.026813519005, 0.004s

Iter 5 -263.026813519005, 0.004s

Found 95 normal cells..

Running HMMs on 4 cell groups..

All done!

 ############################################
 ### Done with dataset T19-90673_577AAL_section_1 ###
 ############################################
Time difference of 5.673164 mins
 ############################################
 ### Numbat for dataset number  T19-90673_577AAL_section_2 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1475.1
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
4917 cells

Mem used: 28.8Gb

Approximating initial clusters using smoothed expression ..

Mem used: 28.8Gb

number of genes left: 12249

running hclust...

Iteration 1

Mem used: 34.7Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.81).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31.6Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31.8Gb

Using 11 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 31.9Gb

Iter 2 -39922.744788619, 0.91s

Iter 3 -39837.0313467258, 0.87s

Iter 4 -39799.2486424251, 0.87s

Iter 5 -39776.8788948626, 0.87s

Iter 6 -39765.0179931645, 0.87s

Iter 7 -39757.509080992, 0.88s

Iter 8 -28612.0130948116, 0.87s

Iter 9 -26543.3702397113, 0.87s

Iter 10 -26531.8147537395, 0.87s

Iter 11 -26520.8111968532, 0.87s

Iter 12 -26507.8292455215, 0.87s

Iter 13 -26496.3014081311, 0.87s

Iter 14 -26486.2642566792, 0.87s

Iter 15 -26477.4601994431, 0.87s

Iter 16 -26316.8336083054, 0.87s

Iter 17 -26310.3277055939, 0.87s

Iter 18 -26301.7510728371, 0.87s

Iter 19 -26300.9231357329, 0.87s

Iter 20 -26299.2930364487, 0.87s

Iter 21 -26298.6622602294, 0.87s

Iter 22 -26274.6625051002, 0.87s

Iter 23 -26274.6625051002, 0.88s

Found 1084 normal cells..

Iteration 2

Mem used: 32Gb

Running HMMs on 7 cell groups..

Running HMMs on 7 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 33.1Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 33.2Gb

Using 13 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 33.2Gb

Iter 2 -54030.9085439864, 1.1s

Iter 3 -53864.9205326451, 1s

Iter 4 -53803.1209996595, 1s

Iter 5 -53714.8311813886, 1s

Iter 6 -53603.9718439942, 1s

Iter 7 -53572.9232457759, 1s

Iter 8 -53499.6324037644, 1s

Iter 9 -53452.1523943402, 1s

Iter 10 -53426.0841263384, 1s

Iter 11 -44797.4460768381, 1s

Iter 12 -44777.3258848156, 1s

Iter 13 -44761.6732231629, 1s

Iter 14 -44427.5437512638, 1s

Iter 15 -44046.9678245151, 1s

Iter 16 -43842.7752136799, 1s

Iter 17 -43838.5350044252, 1s

Iter 18 -43834.3900634875, 1s

Iter 19 -43831.3477895522, 1s

Iter 20 -43829.686633424, 1s

Iter 21 -43828.4628843846, 1s

Iter 22 -43824.0284536807, 1s

Iter 23 -43816.9825467797, 1s

Iter 24 -43812.5846911303, 1s

Iter 25 -43811.1274802025, 1s

Iter 26 -43810.3499637035, 1s

Iter 27 -43810.3499637035, 1s

Found 1062 normal cells..

Running HMMs on 8 cell groups..

All done!

 ############################################
 ### Done with dataset T19-90673_577AAL_section_2 ###
 ############################################
Time difference of 41.9075 mins
 ############################################
 ### Numbat for dataset number  T19-91014_635AAM_core ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 882.3
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
2941 cells

Mem used: 30.2Gb

Approximating initial clusters using smoothed expression ..

Mem used: 30.2Gb

number of genes left: 12633

running hclust...

Iteration 1

Mem used: 31.7Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.68).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 29.6Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 29.6Gb

Using 8 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 29.7Gb

Iter 2 -4384.77372087254, 0.29s

Iter 3 -4340.58024766612, 0.25s

Iter 4 -4223.30084421779, 0.25s

Iter 5 -4181.59358644738, 0.25s

Iter 6 -4147.70007987719, 0.25s

Iter 7 -4112.76123045229, 0.25s

Iter 8 -4111.70450413099, 0.25s

Iter 9 -4096.37316612903, 0.25s

Iter 10 -4096.22605707675, 0.25s

Iter 11 -4096.22605707675, 0.25s

Found 2309 normal cells..

Iteration 2

Mem used: 29.7Gb

Running HMMs on 2 cell groups..

Running HMMs on 2 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 29.3Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 29.3Gb

Using 9 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 29.3Gb

Iter 2 -6522.59102382919, 0.32s

Iter 3 -6452.87463175877, 0.27s

Iter 4 -6392.2984918284, 0.27s

Iter 5 -6346.98685820073, 0.27s

Iter 6 -6318.27379042256, 0.27s

Iter 7 -6310.86866198202, 0.27s

Iter 8 -6299.92212622872, 0.27s

Iter 9 -6292.53263051783, 0.27s

Iter 10 -6286.43127207712, 0.27s

Iter 11 -6277.44598397792, 0.27s

Iter 12 -6273.54264663677, 0.27s

Iter 13 -6272.87647207101, 0.27s

Iter 14 -6252.229969436, 0.27s

Iter 15 -6249.66720295039, 0.28s

Iter 16 -6244.49576094533, 0.27s

Iter 17 -6244.37619209649, 0.27s

Iter 18 -6244.37619209649, 0.27s

Found 2307 normal cells..

Running HMMs on 2 cell groups..

All done!

 ############################################
 ### Done with dataset T19-91014_635AAM_core ###
 ############################################
Time difference of 20.06717 mins
 ############################################
 ### Numbat for dataset number  T19-91014_635AAM_edge ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 726.3
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
2421 cells

Mem used: 28.4Gb

Approximating initial clusters using smoothed expression ..

Mem used: 28.4Gb

number of genes left: 12605

running hclust...

Iteration 1

Mem used: 31Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.55).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 29.4Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 29.5Gb

Using 19 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 29.5Gb

Iter 2 -12838.7285129838, 0.38s

Iter 3 -12825.8722640532, 0.33s

Iter 4 -12725.831224698, 0.32s

Iter 5 -12703.856207668, 0.31s

Iter 6 -12693.1040406437, 0.31s

Iter 7 -12645.787181209, 0.31s

Iter 8 -12638.3185113575, 0.31s

Iter 9 -12631.9811858772, 0.31s

Iter 10 -12628.917853085, 0.31s

Iter 11 -12623.8839541026, 0.31s

Iter 12 -12619.0156445938, 0.31s

Iter 13 -12613.2748637375, 0.31s

Iter 14 -12610.279128442, 0.31s

Iter 15 -12598.9167594862, 0.31s

Iter 16 -12598.0697467821, 0.31s

Iter 17 -12597.2424253566, 0.31s

Iter 18 -12597.2424253566, 0.31s

Found 2004 normal cells..

Iteration 2

Mem used: 29.6Gb

Running HMMs on 7 cell groups..

Running HMMs on 7 cell groups..

Testing for multi-allelic CNVs ..

1 multi-allelic CNVs found: 1e

Evaluating CNV per cell ..

Mem used: 29.7Gb

All cells succeeded

Expanding allelic states..

Building phylogeny ..

Mem used: 29.8Gb

Using 25 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 29.8Gb

Iter 2 -17928.0204516145, 0.44s

Iter 3 -17898.4945672337, 0.39s

Iter 4 -17880.7794364753, 0.39s

Iter 5 -17865.8085877434, 0.39s

Iter 6 -17851.5208119482, 0.39s

Iter 7 -17841.4171049703, 0.4s

Iter 8 -17835.9091401075, 0.39s

Iter 9 -17806.5609200082, 0.39s

Iter 10 -17800.1090526761, 0.39s

Iter 11 -17795.4768689659, 0.39s

Iter 12 -17793.7834005657, 0.39s

Iter 13 -17793.7515341501, 0.39s

Iter 14 -17779.5194847391, 0.4s

Iter 15 -17779.5194847391, 0.4s

Found 2001 normal cells..

Running HMMs on 8 cell groups..

Warning message in melt.data.table(., measure.vars = c("logFC", "pHF")):
“'measure.vars' [logFC, pHF, ...] are not all of the same type. By order of hierarchy, the molten data value column will be of type 'double'. All measure variables not of type 'double' will be coerced too. Check DETAILS in ?melt.data.table for more on coercion.”
All done!

 ############################################
 ### Done with dataset T19-91014_635AAM_edge ###
 ############################################
Time difference of 19.39137 mins
 ############################################
 ### Numbat for dataset number  T20-01237_291AAN ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1070.4
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
3568 cells

Mem used: 29Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29Gb

number of genes left: 12543

running hclust...

Iteration 1

Mem used: 32.6Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.71).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 29.5Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 29.6Gb

Using 12 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 29.7Gb

Iter 2 -7496.19956161814, 0.6s

Iter 3 -7487.49043154909, 0.49s

Iter 4 -7424.68715496273, 0.49s

Iter 5 -7400.90807625432, 0.5s

Iter 6 -7390.13956346482, 0.49s

Iter 7 -7382.3756342436, 0.49s

Iter 8 -7361.8147931295, 0.49s

Iter 9 -7354.27974475481, 0.49s

Iter 10 -7348.16644224622, 0.49s

Iter 11 -7344.56428440901, 0.49s

Iter 12 -7342.22303449739, 0.49s

Iter 13 -7340.46792174802, 0.49s

Iter 14 -7339.50177961257, 0.49s

Iter 15 -7323.56260152714, 0.5s

Iter 16 -7308.61758950657, 0.49s

Iter 17 -7297.89979600656, 0.49s

Iter 18 -7291.01516493409, 0.49s

Iter 19 -7291.01516493409, 0.49s

Found 2568 normal cells..

Iteration 2

Mem used: 29.7Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 29.6Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 29.6Gb

Using 12 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 29.6Gb

Iter 2 -6732.01167218619, 0.53s

Iter 3 -6706.68945179228, 0.49s

Iter 4 -6704.57944261744, 0.49s

Iter 5 -6703.5197925668, 0.49s

Iter 6 -6702.54975539967, 0.48s

Iter 7 -6701.97355857961, 0.49s

Iter 8 -6701.60089479532, 0.49s

Iter 9 -6701.50878863902, 0.49s

Iter 10 -6701.41782899595, 0.49s

Iter 11 -6701.41782899595, 0.49s

Found 2568 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset T20-01237_291AAN ###
 ############################################
Time difference of 23.39356 mins
 ############################################
 ### Numbat for dataset number  T20-90005_998AAH ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1283.1
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
4277 cells

Mem used: 29.1Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.1Gb

number of genes left: 12401

running hclust...

Iteration 1

Mem used: 33.9Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.81).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31.4Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31.5Gb

Using 13 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 31.6Gb

Iter 2 -18796.0887358612, 0.79s

Iter 3 -18751.6883579189, 0.75s

Iter 4 -18710.1272171802, 0.75s

Iter 5 -18676.2210634916, 0.75s

Iter 6 -18565.4630201378, 0.75s

Iter 7 -18535.3480238803, 0.75s

Iter 8 -18418.8655856743, 0.75s

Iter 9 -18215.5436850787, 0.75s

Iter 10 -18066.4259477585, 0.75s

Iter 11 -18024.737918636, 0.75s

Iter 12 -17994.7232142717, 0.75s

Iter 13 -17949.5273600627, 0.75s

Iter 14 -17921.6956133827, 0.75s

Iter 15 -17905.1104309202, 0.75s

Iter 16 -17892.2056583741, 0.75s

Iter 17 -17880.8934741928, 0.75s

Iter 18 -17874.9577205049, 0.75s

Iter 19 -17869.4653866771, 0.75s

Iter 20 -17865.57922913, 0.76s

Iter 21 -17853.5058641121, 0.75s

Iter 22 -17850.4001780924, 0.75s

Iter 23 -17849.1333251934, 0.75s

Iter 24 -17848.3925898748, 0.75s

Iter 25 -17848.3925898748, 0.75s

Found 874 normal cells..

Iteration 2

Mem used: 31.6Gb

Running HMMs on 4 cell groups..

Running HMMs on 4 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31.8Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31.8Gb

Using 14 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 31.8Gb

Iter 2 -19843.9482618294, 0.84s

Iter 3 -19767.1150215325, 0.8s

Iter 4 -19595.9324449612, 0.8s

Iter 5 -19444.2002920081, 0.8s

Iter 6 -19387.5740780811, 0.8s

Iter 7 -19207.3228732589, 0.8s

Iter 8 -19185.6674424372, 0.8s

Iter 9 -19155.5409296676, 0.8s

Iter 10 -19112.7189008944, 0.8s

Iter 11 -18833.2525672977, 0.8s

Iter 12 -18805.8250560826, 0.8s

Iter 13 -18662.9719124676, 0.8s

Iter 14 -18180.1540711092, 0.8s

Iter 15 -18148.060469786, 0.79s

Iter 16 -18134.8480642218, 0.79s

Iter 17 -18122.6011661544, 0.8s

Iter 18 -18113.2671846992, 0.8s

Iter 19 -18087.5643054691, 0.8s

Iter 20 -18064.9949577069, 0.8s

Iter 21 -18014.5031850914, 0.8s

Iter 22 -17990.409781933, 0.8s

Iter 23 -17982.7451477535, 0.8s

Iter 24 -17977.6705024507, 0.79s

Iter 25 -17886.0646480235, 0.8s

Iter 26 -17869.550336504, 0.8s

Iter 27 -17801.0019379448, 0.8s

Iter 28 -17798.9337034782, 0.8s

Iter 29 -17798.4644421786, 0.8s

Iter 30 -17798.4644421786, 0.8s

Found 873 normal cells..

Running HMMs on 4 cell groups..

All done!

 ############################################
 ### Done with dataset T20-90005_998AAH ###
 ############################################
Time difference of 35.94902 mins
 ############################################
 ### Numbat for dataset number  T20-90151_212AAK ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 328.2
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
1094 cells

Mem used: 29Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29Gb

number of genes left: 12690

running hclust...

Iteration 1

Mem used: 28.9Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.75).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 28.1Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 28.1Gb

Using 10 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 28.1Gb

Iter 2 -2270.33148720801, 0.069s

Iter 3 -2261.36132804894, 0.057s

Iter 4 -2255.77536101765, 0.043s

Iter 5 -2249.90152664848, 0.042s

Iter 6 -2249.72681432539, 0.044s

Iter 7 -2248.57429011611, 0.043s

Iter 8 -2248.57429011611, 0.042s

Found 333 normal cells..

Iteration 2

Mem used: 28.1Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 28.1Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 28.1Gb

Using 11 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 28.1Gb

Iter 2 -2528.30486278101, 0.086s

Iter 3 -2463.19480635222, 0.049s

Iter 4 -2440.11164468853, 0.043s

Iter 5 -2422.66991325158, 0.044s

Iter 6 -2413.61218220631, 0.045s

Iter 7 -2413.45577507461, 0.043s

Iter 8 -2413.45577507461, 0.043s

Found 328 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset T20-90151_212AAK ###
 ############################################
Time difference of 9.586767 mins
 ############################################
 ### Numbat for dataset number  T20-90239_175AAA ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 215.4
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
718 cells

Mem used: 27.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 27.7Gb

number of genes left: 11842

running hclust...

Iteration 1

Mem used: 28.3Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.74).

No CNV remains after filtering by LLR in pseudobulks. Consider reducing min_LLR.

 ############################################
 ### Done with dataset T20-90239_175AAA ###
 ############################################
Time difference of 1.411002 mins
 ############################################
 ### Numbat for dataset number  T20-90296_472AAL_autopsy ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1770.6
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
5902 cells

Mem used: 29.2Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.2Gb

number of genes left: 12318

running hclust...

Iteration 1

Mem used: 36.2Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.82).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31.9Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 32.1Gb

Using 8 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 32.3Gb

Iter 2 -13515.2845740409, 1.1s

Iter 3 -13493.5565456444, 1s

Iter 4 -13488.6029861331, 1s

Iter 5 -13487.0756168937, 1s

Iter 6 -13487.0756168937, 1s

Found 1184 normal cells..

Iteration 2

Mem used: 32.3Gb

Running HMMs on 6 cell groups..

Running HMMs on 6 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 33.2Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 33.2Gb

Using 8 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 33.2Gb

Iter 2 -11835.6496769801, 1s

Iter 3 -11611.6683989169, 1s

Iter 4 -11544.0872754198, 0.99s

Iter 5 -11508.9755252654, 1s

Iter 6 -11493.7915094369, 1s

Iter 7 -11484.8708534377, 1s

Iter 8 -11389.616359379, 1s

Iter 9 -11389.3987091406, 1s

Iter 10 -11366.3728582935, 0.99s

Iter 11 -11366.3728582935, 0.99s

Found 1185 normal cells..

Running HMMs on 6 cell groups..

All done!

 ############################################
 ### Done with dataset T20-90296_472AAL_autopsy ###
 ############################################
Time difference of 48.20026 mins
 ############################################
 ### Numbat for dataset number  T20-90296_472AAL_diagnosis ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 736.5
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
2455 cells

Mem used: 29.6Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.6Gb

number of genes left: 11778

running hclust...

Iteration 1

Mem used: 30.7Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.96).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 28.4Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 28.4Gb

Using 5 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 28.5Gb

Iter 2 -2145.45463592352, 0.17s

Iter 3 -2141.83392248251, 0.13s

Iter 4 -2141.7408380545, 0.13s

Iter 5 -2140.73278153206, 0.12s

Iter 6 -2140.73278153206, 0.13s

Found 128 normal cells..

Iteration 2

Mem used: 28.5Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 28.5Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 28.5Gb

Using 5 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 28.5Gb

Iter 2 -2274.52006166478, 0.17s

Iter 3 -2019.3938223175, 0.13s

Iter 4 -2012.15938074033, 0.13s

Iter 5 -1972.15887376617, 0.13s

Iter 6 -1970.82159797187, 0.13s

Iter 7 -1970.44923150665, 0.13s

Iter 8 -1970.44923150665, 0.13s

Found 128 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset T20-90296_472AAL_diagnosis ###
 ############################################
Time difference of 17.27979 mins
 ############################################
 ### Numbat for dataset number  T20-90296_472AAL_relapse ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 660.3
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
2201 cells

Mem used: 28Gb

Approximating initial clusters using smoothed expression ..

Mem used: 28Gb

number of genes left: 12160

running hclust...

Iteration 1

Mem used: 30.5Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.72).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 28.8Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 28.8Gb

Using 4 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 28.9Gb

Iter 2 -986.476257586587, 0.14s

Iter 3 -984.225090666984, 0.097s

Iter 4 -984.225090666984, 0.097s

Found 965 normal cells..

Iteration 2

Mem used: 28.9Gb

Running HMMs on 2 cell groups..

Running HMMs on 2 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 28.7Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 28.7Gb

Using 4 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 28.7Gb

Iter 2 -1050.06293581142, 0.13s

Iter 3 -1019.3688094649, 0.097s

Iter 4 -969.950174099809, 0.097s

Iter 5 -963.227687533144, 0.096s

Iter 6 -962.686549310461, 0.097s

Iter 7 -962.315375862735, 0.096s

Iter 8 -962.315375862735, 0.096s

Found 965 normal cells..

Running HMMs on 2 cell groups..

All done!

 ############################################
 ### Done with dataset T20-90296_472AAL_relapse ###
 ############################################
Time difference of 15.42003 mins
 ############################################
 ### Numbat for dataset number  T20-90372_190AAO ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1118.4
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
3728 cells

Mem used: 28.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 28.7Gb

number of genes left: 12413

running hclust...

Iteration 1

Mem used: 33Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.95).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 30.5Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 30.8Gb

Using 23 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 30.9Gb

Iter 2 -97322.5193366318, 1s

Iter 3 -96778.2979470886, 0.95s

Iter 4 -96294.3466423348, 0.96s

Iter 5 -95727.1675726739, 0.95s

Iter 6 -95357.4281530992, 0.96s

Iter 7 -94734.4656648241, 0.95s

Iter 8 -94358.1212857041, 0.96s

Iter 9 -93259.6607856837, 0.95s

Iter 10 -92976.1779227303, 0.95s

Iter 11 -92814.630227651, 0.96s

Iter 12 -92661.7401754153, 0.96s

Iter 13 -92563.6105628863, 0.95s

Iter 14 -92475.7506130114, 0.96s

Iter 15 -92423.7473388137, 0.95s

Iter 16 -92340.6548055922, 0.95s

Iter 17 -92293.8175352396, 0.95s

Iter 18 -92260.3900153415, 0.95s

Iter 19 -92233.5142628842, 0.95s

Iter 20 -92210.7840130495, 0.95s

Iter 21 -92181.1723192218, 0.95s

Iter 22 -92102.0745805384, 0.95s

Iter 23 -92077.4826615544, 0.95s

Iter 24 -92054.9140746821, 0.95s

Iter 25 -91950.5280340876, 0.96s

Iter 26 -91929.9986742602, 0.96s

Iter 27 -91899.5900989646, 0.95s

Iter 28 -91883.9180485028, 0.96s

Iter 29 -91854.2002783394, 0.95s

Iter 30 -91845.8622686518, 0.95s

Iter 31 -91838.9210050509, 0.95s

Iter 32 -91834.698386129, 0.96s

Iter 33 -91830.5359407452, 0.96s

Iter 34 -91824.8444478852, 0.95s

Iter 35 -91820.8075710964, 0.96s

Iter 36 -91817.8740618506, 0.96s

Iter 37 -91817.8740618506, 0.95s

Found 309 normal cells..

Iteration 2

Mem used: 30.9Gb

Running HMMs on 11 cell groups..

Running HMMs on 11 cell groups..

Testing for multi-allelic CNVs ..

1 multi-allelic CNVs found: 3a

Evaluating CNV per cell ..

Mem used: 33Gb

less than 5% genes are in neutral region - including LOH in baseline

All cells succeeded

Expanding allelic states..

Building phylogeny ..

Mem used: 33.1Gb

Using 20 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 33.1Gb

Iter 2 -66628.0985920336, 0.83s

Iter 3 -66434.5543923788, 0.77s

Iter 4 -66312.4577188205, 0.78s

Iter 5 -66228.1994625464, 0.78s

Iter 6 -66174.8274072005, 0.77s

Iter 7 -66127.9925233181, 0.78s

Iter 8 -66084.2424274674, 0.78s

Iter 9 -66044.1451560206, 0.78s

Iter 10 -66014.5835996393, 0.78s

Iter 11 -65848.8519357923, 0.78s

Iter 12 -65829.0369690434, 0.78s

Iter 13 -65815.9964573599, 0.78s

Iter 14 -65809.2147794813, 0.79s

Iter 15 -65803.6609523733, 0.78s

Iter 16 -65800.6024032487, 0.78s

Iter 17 -65797.605798947, 0.77s

Iter 18 -65781.7076214849, 0.78s

Iter 19 -65764.3018233914, 0.78s

Iter 20 -65742.9759757596, 0.78s

Iter 21 -65716.6451481614, 0.78s

Iter 22 -65705.7443896687, 0.78s

Iter 23 -65690.9806614126, 0.78s

Iter 24 -65685.1593857703, 0.78s

Iter 25 -65679.9785038859, 0.78s

Iter 26 -65658.4915862752, 0.78s

Iter 27 -65652.9914983833, 0.78s

Iter 28 -65648.2531295461, 0.78s

Iter 29 -65645.3823069561, 0.78s

Iter 30 -65643.0884042818, 0.78s

Iter 31 -65643.0884042818, 0.78s

Found 354 normal cells..

Running HMMs on 4 cell groups..

All done!

 ############################################
 ### Done with dataset T20-90372_190AAO ###
 ############################################
Time difference of 38.07032 mins
 ############################################
 ### Numbat for dataset number  T20-93210_698AAO_region_1 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1311.6
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
4372 cells

Mem used: 29.6Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.6Gb

number of genes left: 12507

running hclust...

Iteration 1

Mem used: 34Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.81).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31.3Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31.4Gb

Using 1 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 31.4Gb

Iter 2 -137.82988486324, 0.25s

Iter 3 -137.82988486324, 0.21s

Found 271 normal cells..

Iteration 2

Mem used: 31.5Gb

Running HMMs on 2 cell groups..

Running HMMs on 2 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 30.4Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 30.4Gb

Using 1 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 30.4Gb

Iter 2 -138.382503575995, 0.25s

Iter 3 -138.382503575995, 0.21s

Found 273 normal cells..

Running HMMs on 2 cell groups..

All done!

 ############################################
 ### Done with dataset T20-93210_698AAO_region_1 ###
 ############################################
Time difference of 49.98379 mins
 ############################################
 ### Numbat for dataset number  T20-93210_698AAO_region_2 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 828
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
2760 cells

Mem used: 28.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 28.7Gb

number of genes left: 12339

running hclust...

Iteration 1

Mem used: 31.4Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.88).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 29.7Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 29.7Gb

Using 4 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 29.8Gb

Iter 2 -1215.4618887001, 0.19s

Iter 3 -1149.34605772035, 0.14s

Iter 4 -1145.5310893258, 0.14s

Iter 5 -1139.71622907897, 0.14s

Iter 6 -1139.71622907897, 0.14s

Found 423 normal cells..

Iteration 2

Mem used: 29.8Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 29.4Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 29.4Gb

Using 3 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 29.4Gb

Iter 2 -904.55805633541, 0.17s

Iter 3 -904.55805633541, 0.13s

Found 407 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset T20-93210_698AAO_region_2 ###
 ############################################
Time difference of 21.01572 mins
 ############################################
 ### Numbat for dataset number  T20-93369_977AAO ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1866.9
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
6223 cells

Mem used: 29.2Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.2Gb

number of genes left: 12438

running hclust...

Iteration 1

Mem used: 36.3Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.83).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 30.8Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 30.9Gb

Using 6 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 31.1Gb

Iter 2 -12829.271191013, 1s

Iter 3 -12711.8918390738, 0.98s

Iter 4 -12598.9127488173, 0.98s

Iter 5 -12475.8736696176, 0.98s

Iter 6 -12408.1288119866, 0.98s

Iter 7 -12408.1288119866, 0.98s

Found 1743 normal cells..

Iteration 2

Mem used: 31.1Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31Gb

Using 8 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 31Gb

Iter 2 -21042.9554531666, 1.2s

Iter 3 -20879.8151703193, 1.2s

Iter 4 -20799.9283225747, 1.2s

Iter 5 -20751.390915678, 1.2s

Iter 6 -20708.1326548281, 1.2s

Iter 7 -20670.5542914929, 1.2s

Iter 8 -20518.3449396461, 1.2s

Iter 9 -20494.2937212752, 1.2s

Iter 10 -20475.54135108, 1.2s

Iter 11 -20463.9492505256, 1.2s

Iter 12 -20437.2413714246, 1.2s

Iter 13 -20427.3150758518, 1.2s

Iter 14 -20418.020951922, 1.2s

Iter 15 -20382.2463283482, 1.2s

Iter 16 -20228.5578906456, 1.2s

Iter 17 -20030.1465859922, 1.2s

Iter 18 -20012.9476262777, 1.2s

Iter 19 -19986.3192671089, 1.2s

Iter 20 -19976.3929715361, 1.2s

Iter 21 -19968.9977024999, 1.2s

Iter 22 -19958.6840421488, 1.2s

Iter 23 -19957.765336524, 1.2s

Iter 24 -19957.7606529609, 1.2s

Iter 25 -19957.5031336285, 1.2s

Iter 26 -19957.5031336285, 1.2s

Found 1728 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset T20-93369_977AAO ###
 ############################################
Time difference of 49.85768 mins
 ############################################
 ### Numbat for dataset number  T20-93623_348AAP ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 902.4
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
3008 cells

Mem used: 28.8Gb

Approximating initial clusters using smoothed expression ..

Mem used: 28.8Gb

number of genes left: 12008

running hclust...

Iteration 1

Mem used: 31.6Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.92).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 29.6Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 29.7Gb

Using 11 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 29.8Gb

Iter 2 -18044.206433589, 0.38s

Iter 3 -17344.3569174874, 0.33s

Iter 4 -17243.9307055453, 0.33s

Iter 5 -17102.8591648445, 0.34s

Iter 6 -17060.0750115126, 0.34s

Iter 7 -17025.8667765659, 0.33s

Iter 8 -16991.7591608862, 0.33s

Iter 9 -16980.1699141974, 0.33s

Iter 10 -16934.8376338752, 0.33s

Iter 11 -16929.038871937, 0.34s

Iter 12 -16928.3824651253, 0.33s

Iter 13 -16928.3824651253, 0.33s

Found 86 normal cells..

Iteration 2

Mem used: 29.8Gb

Running HMMs on 6 cell groups..

Running HMMs on 6 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 30.2Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 30.3Gb

Using 11 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 30.3Gb

Iter 2 -17265.9324736527, 0.38s

Iter 3 -17258.8039761083, 0.34s

Iter 4 -17254.5054351365, 0.34s

Iter 5 -17253.2893056539, 0.34s

Iter 6 -17252.430348517, 0.34s

Iter 7 -17251.6274875688, 0.34s

Iter 8 -17250.9128317727, 0.34s

Iter 9 -17250.2668229588, 0.34s

Iter 10 -17249.8377937304, 0.34s

Iter 11 -17249.4334719778, 0.34s

Iter 12 -17249.0679935975, 0.34s

Iter 13 -17248.4807318347, 0.34s

Iter 14 -17248.142707688, 0.34s

Iter 15 -17247.3553061208, 0.34s

Iter 16 -17247.2624779627, 0.34s

Iter 17 -17247.0014174645, 0.34s

Iter 18 -17246.9736990517, 0.34s

Iter 19 -17246.7117812529, 0.34s

Iter 20 -17246.6900376188, 0.34s

Iter 21 -17168.6243983664, 0.34s

Iter 22 -17168.0216561721, 0.34s

Iter 23 -17167.8239536161, 0.34s

Iter 24 -17167.0064581786, 0.34s

Iter 25 -17167.001683165, 0.34s

Iter 26 -17166.8693918459, 0.34s

Iter 27 -17166.8693918459, 0.34s

Found 96 normal cells..

Running HMMs on 6 cell groups..

All done!

 ############################################
 ### Done with dataset T20-93623_348AAP ###
 ############################################
Time difference of 24.24054 mins
 ############################################
 ### Numbat for dataset number  T21-90437_071AAQ ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1154.4
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
3848 cells

Mem used: 29.3Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.3Gb

number of genes left: 12502

running hclust...

Iteration 1

Mem used: 33.2Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.78).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 30.8Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 30.9Gb

Using 6 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 31Gb

Iter 2 -7055.30448599663, 0.41s

Iter 3 -6818.05485043558, 0.37s

Iter 4 -6737.24118510958, 0.37s

Iter 5 -6727.92373650595, 0.37s

Iter 6 -6707.92294826578, 0.37s

Iter 7 -6707.92294826578, 0.37s

Found 900 normal cells..

Iteration 2

Mem used: 31Gb

Running HMMs on 4 cell groups..

Running HMMs on 4 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31.3Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31.4Gb

Using 6 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 31.4Gb

Iter 2 -7205.63631063429, 0.41s

Iter 3 -6957.58738996876, 0.36s

Iter 4 -6945.82808126239, 0.37s

Iter 5 -6852.74883379681, 0.37s

Iter 6 -6852.74883379681, 0.36s

Found 928 normal cells..

Running HMMs on 4 cell groups..

All done!

 ############################################
 ### Done with dataset T21-90437_071AAQ ###
 ############################################
Time difference of 30.70001 mins
 ############################################
 ### Numbat for dataset number  T21-90517_099AAQ ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1185.3
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
3951 cells

Mem used: 29.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.7Gb

number of genes left: 12533

running hclust...

Iteration 1

Mem used: 33.3Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.74).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 30.7Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 30.7Gb

Using 5 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 30.8Gb

Iter 2 -4163.9662917263, 0.41s

Iter 3 -4065.57292667768, 0.35s

Iter 4 -4039.72781434491, 0.35s

Iter 5 -4021.00214056045, 0.35s

Iter 6 -4021.00214056045, 0.35s

Found 1263 normal cells..

Iteration 2

Mem used: 30.8Gb

Running HMMs on 4 cell groups..

Running HMMs on 4 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31Gb

Using 5 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 31Gb

Iter 2 -5282.448511122, 0.39s

Iter 3 -4898.60405743327, 0.36s

Iter 4 -4698.89179460182, 0.35s

Iter 5 -4333.27242930259, 0.35s

Iter 6 -4057.34969703608, 0.35s

Iter 7 -4057.34969703608, 0.35s

Found 1267 normal cells..

Running HMMs on 4 cell groups..

All done!

 ############################################
 ### Done with dataset T21-90517_099AAQ ###
 ############################################
Time difference of 29.72981 mins
 ############################################
 ### Numbat for dataset number  T21-90581_212AAQ_region_1 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 276.6
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
922 cells

Mem used: 28.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 28.7Gb

number of genes left: 12523

running hclust...

Iteration 1

Mem used: 28.7Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.78).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 28.3Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 28.3Gb

Using 3 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 28.3Gb

Iter 2 -287.729153453875, 0.029s

Iter 3 -280.112702645823, 0.025s

Iter 4 -280.112702645823, 0.022s

Found 185 normal cells..

Iteration 2

Mem used: 28.3Gb

Running HMMs on 2 cell groups..

Running HMMs on 2 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 28.1Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 28.1Gb

Using 3 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 28.1Gb

Iter 2 -310.294907946094, 0.024s

Iter 3 -309.345578311298, 0.021s

Iter 4 -308.790367645879, 0.021s

Iter 5 -308.330516073463, 0.022s

Iter 6 -308.135111941857, 0.018s

Iter 7 -307.978859733897, 0.014s

Iter 8 -307.880354042204, 0.014s

Iter 9 -307.808263467758, 0.014s

Iter 10 -307.808263467758, 0.013s

Found 187 normal cells..

Running HMMs on 2 cell groups..

All done!

 ############################################
 ### Done with dataset T21-90581_212AAQ_region_1 ###
 ############################################
Time difference of 8.9675 mins

### Samples that did not detect CNVs with default settings

In [ ]:
which(names(ruiz) == 'GNG_region_6')
which(names(ruiz) == 'T19-90627_466AAL')
which(names(ruiz) == 'T20-90239_175AAA')

[1] 10

[1] 11

[1] 19

In [ ]:
for(i in c(10, 11)) {  # run on the first half of ruiz
    cat(' ############################################\n',
        '### Numbat for dataset number ', names(ruiz[i]), '###\n',
        '############################################\n')
    
    old <- Sys.time() # get start time
    
    file_path <- paste0('/projects/0/einf2548/cruiz/cellranger_output/numbat_pileup_output_cellbender/',
                        names(ruiz[i]),'/',names(ruiz[i]),'_allele_counts.tsv.gz')
    
    if (file.exists(file_path)) {  # check if file exists
        df_allele = fread(file_path)
        df_allele$cell <- paste0(names(ruiz[i]),'_',df_allele$cell)
          
        # run
        out = run_numbat(
            as.matrix(GetAssayData(ruiz[[i]], slot = 'counts', assay = 'RNA')), # gene x cell integer UMI count matrix 
            ref_internal, # reference expression profile, a gene x cell type normalized expression level matrix
            df_allele, # allele dataframe generated by pileup_and_phase script and MUST BE A DATATABLE!
            min_cells = 20,
            t = 1e-3,
            max_iter = 2,
            init_k = 5, # changed this parameter 
            max_entropy = 0.8, # changed this parameter
            ncores = 40,
            ncores_nni = 40,
            multi_allelic = TRUE,
            plot = TRUE,
            genome = "hg38",
            out_dir = paste0('/projects/0/einf2548/cruiz/dmg/notebooks/iCNV/numbat/dmg_atlas_segregated_ref/Ruiz2023/',names(ruiz[i]))
        )
      
        cat(' ############################################\n',
        '### Done with dataset', names(ruiz[i]), '###\n',
        '############################################\n')
        
        # print elapsed time
        new <- Sys.time() - old # calculate difference
        print(new) # print in nice format
    } else {
        cat(' ############################################\n',
        '### Skipping dataset', names(ruiz[i]), 'because the file does not exist ###\n',
        '############################################\n')
    }
}

 ############################################
 ### Numbat for dataset number  GNG_region_6 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 5
max_cost = 517.2
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.8
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
1724 cells

Mem used: 76.5Gb

Approximating initial clusters using smoothed expression ..

Mem used: 76.5Gb

number of genes left: 11800

running hclust...

Iteration 1

Mem used: 29.6Gb

Running HMMs on 9 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 28.3Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 28.3Gb

Using 2 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 28.3Gb

Iter 2 -962.822240438805, 0.11s

Iter 3 -962.822240438805, 0.083s

Found 1130 normal cells..

Iteration 2

Mem used: 28.3Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 28.1Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 28.1Gb

Using 3 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 28.1Gb

Iter 2 -1374.48117099576, 0.12s

Iter 3 -1368.59915527454, 0.084s

Iter 4 -1368.59915527454, 0.07s

Found 1127 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset GNG_region_6 ###
 ############################################
Time difference of 14.30189 mins
 ############################################
 ### Numbat for dataset number  T19-90627_466AAL ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 5
max_cost = 616.8
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.8
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
2056 cells

Mem used: 28Gb

Approximating initial clusters using smoothed expression ..

Mem used: 28Gb

number of genes left: 12782

running hclust...

Iteration 1

Mem used: 30.4Gb

Running HMMs on 9 cell groups..

Expression noise level: medium (0.75).

Running HMMs on 5 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 29.3Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 29.3Gb

No CNV remains after filtering by entropy in single cells. Consider increasing max_entropy.

 ############################################
 ### Done with dataset T19-90627_466AAL ###
 ############################################
Time difference of 9.855829 mins

In [ ]:
for(i in c(11)) {  # run on the first half of ruiz
    cat(' ############################################\n',
        '### Numbat for dataset number ', names(ruiz[i]), '###\n',
        '############################################\n')
    
    old <- Sys.time() # get start time
    
    file_path <- paste0('/projects/0/einf2548/cruiz/cellranger_output/numbat_pileup_output_cellbender/',
                        names(ruiz[i]),'/',names(ruiz[i]),'_allele_counts.tsv.gz')
    
    if (file.exists(file_path)) {  # check if file exists
        df_allele = fread(file_path)
        df_allele$cell <- paste0(names(ruiz[i]),'_',df_allele$cell)
          
        # run
        out = run_numbat(
            as.matrix(GetAssayData(ruiz[[i]], slot = 'counts', assay = 'RNA')), # gene x cell integer UMI count matrix 
            ref_internal, # reference expression profile, a gene x cell type normalized expression level matrix
            df_allele, # allele dataframe generated by pileup_and_phase script and MUST BE A DATATABLE!
            min_cells = 20,
            t = 1e-3,
            max_iter = 2,
            init_k = 10, # changed this parameter 
            max_entropy = 1, # changed this parameter
            ncores = 32,
            ncores_nni = 32,
            multi_allelic = TRUE,
            plot = TRUE,
            genome = "hg38",
            out_dir = paste0('/projects/0/einf2548/cruiz/dmg/notebooks/iCNV/numbat/dmg_atlas_segregated_ref/Ruiz2023/',names(ruiz[i]))
        )
      
        cat(' ############################################\n',
        '### Done with dataset', names(ruiz[i]), '###\n',
        '############################################\n')
        
        # print elapsed time
        new <- Sys.time() - old # calculate difference
        print(new) # print in nice format
    } else {
        cat(' ############################################\n',
        '### Skipping dataset', names(ruiz[i]), 'because the file does not exist ###\n',
        '############################################\n')
    }
}

 ############################################
 ### Numbat for dataset number  T19-90627_466AAL ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 10
max_cost = 616.8
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 1
skip_nj = FALSE
diploid_chroms =
ncores = 32
ncores_nni = 32
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
2056 cells

Mem used: 76.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 76.7Gb

number of genes left: 12782

running hclust...

Iteration 1

Mem used: 30.4Gb

Running HMMs on 18 cell groups..

Expression noise level: medium (0.75).

Running HMMs on 9 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 29.9Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 29.9Gb

Using 2 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 29.9Gb

Iter 2 -1161.93693767708, 0.16s

Iter 3 -1159.52048091939, 0.081s

Iter 4 -1158.63387655533, 0.077s

Iter 5 -1157.77977870501, 0.076s

Iter 6 -1157.05807950258, 0.077s

Iter 7 -1156.27925214579, 0.076s

Iter 8 -1155.54486158387, 0.076s

Iter 9 -1154.86054165496, 0.078s

Iter 10 -1154.20998208199, 0.076s

Iter 11 -1152.84728940763, 0.077s

Iter 12 -1152.2279038043, 0.076s

Iter 13 -1149.60989501751, 0.077s

Iter 14 -1148.24605599449, 0.076s

Iter 15 -1147.64784700228, 0.076s

Iter 16 -1147.14057729287, 0.077s

Iter 17 -1146.68376488882, 0.076s

Iter 18 -1146.24567665839, 0.077s

Iter 19 -1145.81526544024, 0.077s

Iter 20 -1145.29934523924, 0.078s

Iter 21 -1144.94278830743, 0.077s

Iter 22 -1144.59310249597, 0.076s

Iter 23 -1144.37367812051, 0.081s

Iter 24 -1143.92992490679, 0.079s

Iter 25 -1143.71204605466, 0.078s

Iter 26 -1143.50108288808, 0.076s

Iter 27 -1143.27877769242, 0.079s

Iter 28 -1143.06850625934, 0.08s

Iter 29 -1142.45587196618, 0.08s

Iter 30 -1142.24855464922, 0.078s

Iter 31 -1141.83592278784, 0.078s

Iter 32 -1141.46612416853, 0.077s

Iter 33 -1141.26085079548, 0.078s

Iter 34 -1141.06007241742, 0.079s

Iter 35 -1140.85692331227, 0.078s

Iter 36 -1140.65485935567, 0.077s

Iter 37 -1140.45390503414, 0.077s

Iter 38 -1140.25554297188, 0.076s

Iter 39 -1139.47426287668, 0.077s

Iter 40 -1139.28394435938, 0.076s

Iter 41 -1138.73634393052, 0.076s

Iter 42 -1138.5475595913, 0.077s

Iter 43 -1138.3624831486, 0.077s

Iter 44 -1138.17841115988, 0.077s

Iter 45 -1137.99449853527, 0.076s

Iter 46 -1137.81117383092, 0.077s

Iter 47 -1137.62990613485, 0.077s

Iter 48 -1137.44951177265, 0.077s

Iter 49 -1137.27026003298, 0.079s

Iter 50 -1137.09245502962, 0.077s

Iter 51 -1136.91654352891, 0.077s

Iter 52 -1136.74237620868, 0.079s

Iter 53 -1136.57056248846, 0.076s

Iter 54 -1136.40581930599, 0.078s

Iter 55 -1135.76099102027, 0.077s

Iter 56 -1135.59780529268, 0.077s

Iter 57 -1134.15345667411, 0.077s

Iter 58 -1133.97542746361, 0.077s

Iter 59 -1133.45147835968, 0.078s

Iter 60 -1133.28998667593, 0.077s

Iter 61 -1133.1293588858, 0.077s

Iter 62 -1132.96931267083, 0.078s

Iter 63 -1131.45281919219, 0.077s

Iter 64 -1131.29657822275, 0.077s

Iter 65 -1131.12263871338, 0.076s

Iter 66 -1130.96792412801, 0.077s

Iter 67 -1130.81544965456, 0.077s

Iter 68 -1130.66364717862, 0.077s

Iter 69 -1130.38925823339, 0.076s

Iter 70 -1130.25154595503, 0.078s

Iter 71 -1129.9930963559, 0.077s

Iter 72 -1129.72733810747, 0.077s

Iter 73 -1129.59846868838, 0.077s

Iter 74 -1129.47027313532, 0.078s

Iter 75 -1129.34306573338, 0.078s

Iter 76 -1128.85903617879, 0.077s

Iter 77 -1128.73925204505, 0.077s

Iter 78 -1128.62021648355, 0.076s

Iter 79 -1128.5016803328, 0.077s

Iter 80 -1128.34736276692, 0.079s

Iter 81 -1127.50609734391, 0.078s

Iter 82 -1127.30633194457, 0.078s

Iter 83 -1127.18935836451, 0.079s

Iter 84 -1127.07404952403, 0.077s

Iter 85 -1126.96103111264, 0.077s

Iter 86 -1126.85042081562, 0.077s

Iter 87 -1126.63426596981, 0.083s

Iter 88 -1126.5269227463, 0.08s

Iter 89 -1126.31644426265, 0.08s

Iter 90 -1126.21522985665, 0.078s

Iter 91 -1126.01537105679, 0.078s

Iter 92 -1125.91799677399, 0.078s

Iter 93 -1125.55394527114, 0.077s

Iter 94 -1125.47230628191, 0.077s

Iter 95 -1125.12028772188, 0.077s

Iter 96 -1125.03853958017, 0.076s

Iter 97 -1124.95784173973, 0.078s

Iter 98 -1124.87943495475, 0.078s

Iter 99 -1124.8018430243, 0.077s

Iter 100 -1124.73294712451, 0.078s

Iter 101 -1124.60007049839, 0.079s

Found 1706 normal cells..

Iteration 2

Mem used: 30Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 28.9Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 28.9Gb

Using 2 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 28.9Gb

Iter 2 -1150.01149580672, 0.14s

Iter 3 -1150.01149580672, 0.097s

Found 1698 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset T19-90627_466AAL ###
 ############################################
Time difference of 19.19236 mins

In [ ]:
for(i in 19) {  # run on the first half of ruiz
    cat(' ############################################\n',
        '### Numbat for dataset number ', names(ruiz[i]), '###\n',
        '############################################\n')
    
    old <- Sys.time() # get start time
    
    file_path <- paste0('/projects/0/einf2548/cruiz/cellranger_output/numbat_pileup_output_cellbender/',
                        names(ruiz[i]),'/',names(ruiz[i]),'_allele_counts.tsv.gz')
    
    if (file.exists(file_path)) {  # check if file exists
        df_allele = fread(file_path)
        df_allele$cell <- paste0(names(ruiz[i]),'_',df_allele$cell)
          
        # run
        out = run_numbat(
            as.matrix(GetAssayData(ruiz[[i]], slot = 'counts', assay = 'RNA')), # gene x cell integer UMI count matrix 
            ref_internal, # reference expression profile, a gene x cell type normalized expression level matrix
            df_allele, # allele dataframe generated by pileup_and_phase script and MUST BE A DATATABLE!
            min_cells = 20,
            t = 1e-3,
            max_iter = 2,
            init_k = 5, # changed this parameter 
            min_LLR = 3, # changed this parameter
            ncores = 40,
            ncores_nni = 40,
            multi_allelic = TRUE,
            plot = TRUE,
            genome = "hg38",
            out_dir = paste0('/projects/0/einf2548/cruiz/dmg/notebooks/iCNV/numbat/dmg_atlas_segregated_ref/Ruiz2023/',names(ruiz[i]))
        )
      
        cat(' ############################################\n',
        '### Done with dataset', names(ruiz[i]), '###\n',
        '############################################\n')
        
        # print elapsed time
        new <- Sys.time() - old # calculate difference
        print(new) # print in nice format
    } else {
        cat(' ############################################\n',
        '### Skipping dataset', names(ruiz[i]), 'because the file does not exist ###\n',
        '############################################\n')
    }
}

 ############################################
 ### Numbat for dataset number  T20-90239_175AAA ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 5
max_cost = 215.4
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 3
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
718 cells

Mem used: 28Gb

Approximating initial clusters using smoothed expression ..

Mem used: 28Gb

number of genes left: 11842

running hclust...

Iteration 1

Mem used: 28.3Gb

Running HMMs on 9 cell groups..

Expression noise level: medium (0.73).

Running HMMs on 5 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 27.9Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 27.9Gb

Using 3 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 27.9Gb

Iter 2 -435.313339444181, 0.018s

Iter 3 -434.595936588534, 0.018s

Iter 4 -433.980657500682, 0.02s

Iter 5 -433.418554262935, 0.025s

Iter 6 -432.898078515652, 0.019s

Iter 7 -432.416000567463, 0.013s

Iter 8 -431.940786645851, 0.011s

Iter 9 -431.304624561386, 0.011s

Iter 10 -431.024715569095, 0.011s

Iter 11 -430.475392900023, 0.011s

Iter 12 -430.214261468004, 0.011s

Iter 13 -429.958635434904, 0.01s

Iter 14 -429.755995536476, 0.011s

Iter 15 -429.664855570809, 0.011s

Iter 16 -429.642194758178, 0.011s

Iter 17 -429.642194758178, 0.01s

Found 480 normal cells..

Iteration 2

Mem used: 27.9Gb

Running HMMs on 4 cell groups..

Running HMMs on 4 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 27.8Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 27.8Gb

Using 3 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 27.8Gb

Iter 2 -164.608764768129, 0.017s

Iter 3 -164.353305531774, 0.018s

Iter 4 -164.257308560351, 0.017s

Iter 5 -164.257308560351, 0.02s

Found 509 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset T20-90239_175AAA ###
 ############################################
Time difference of 6.987257 mins