In [1]:
library(numbat)
library(dplyr)
library(Seurat)
library(data.table)
library(future)
plan("multicore", workers = 12)
options(future.globals.maxSize = 10000 * 1024^10,
        future.rng.onMisuse = 'ignore')
sessionInfo()

Loading required package: Matrix


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: SeuratObject

Loading required package: sp


Attaching package: ‘SeuratObject’


The following objects are masked from ‘package:base’:

    intersect, saveRDS


Loading Seurat v5 beta version
To maintain compatibility with previous workflows, new Seurat objects will use the previous object structure by default
To use new Seurat v5 assays: Please run: options(Seurat.object.assay.version = 'v5')


Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last

R version 4.2.3 (2023-03-15)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Rocky Linux 8.7 (Green Obsidian)

Matrix products: default
BLAS/LAPACK: /gpfs/home3/cruiz2/miniconda3/envs/r_python/lib/libopenblasp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] future_1.32.0           data.table_1.14.8       Seurat_4.9.9.9040
[4] SeuratObject_4.9.9.9081 sp_1.6-0                dplyr_1.1.1
[7] numbat_1.2.3            Matrix_1.5-3

loaded via a namespace (and not attached):
  [1] uuid_1.1-0             spam_2.9-1             parallelDist_0.2.6
  [4] fastmatch_1.1-3        plyr_1.8.8             igraph_1.4.1
  [7] repr_1.1.6             lazyeval_0.2.2         splines_4.2.3
 [10] RcppHNSW_0.4.1         listenv_0.9.0          scattermore_0.8
 [13] ggplot2_3.4.1          digest_0.6.31          yulab.utils_0.0.6
 [16] htmltools_0.5.5        viridis_0.6.2          fansi_1.0.4
 [19] magrittr_2.0.3         tensor_1.5             cluster_2.1.4
 [22] ROCR_1.0-11            globals_0.16.2         graphlayouts_0.8.4
 [25] RcppParallel_5.1.7     matrixStats_0.63.0     spatstat.sparse_3.0-1
 [28] colorspace_2.1-0       ggrepel_0.9.3          crayon_1.5.2
 [31] jsonlite_1.8.4         progressr_0.13.0       spatstat.data_3.0-1
 [34] survival_3.5-5         zoo_1.8-11             phangorn_2.11.1
 [37] ape_5.7-1              glue_1.6.2             polyclip_1.10-4
 [40] gtable_0.3.3           leiden_0.4.3           future.apply_1.10.0
 [43] abind_1.4-5            scales_1.2.1           spatstat.random_3.1-4
 [46] miniUI_0.1.1.1         Rcpp_1.0.10            viridisLite_0.4.1
 [49] xtable_1.8-4           gridGraphics_0.5-1     tidytree_0.4.2
 [52] reticulate_1.28        dotCall64_1.0-2        htmlwidgets_1.6.2
 [55] httr_1.4.5             RColorBrewer_1.1-3     ellipsis_0.3.2
 [58] ica_1.0-3              pkgconfig_2.0.3        farver_2.1.1
 [61] uwot_0.1.14            deldir_1.0-6           utf8_1.2.3
 [64] ggplotify_0.1.0        tidyselect_1.2.0       rlang_1.1.0
 [67] reshape2_1.4.4         later_1.3.0            munsell_0.5.0
 [70] tools_4.2.3            cli_3.6.1              generics_0.1.3
 [73] ggridges_0.5.4         evaluate_0.20          stringr_1.5.0
 [76] fastmap_1.1.1          goftest_1.2-3          ggtree_3.6.2
 [79] RhpcBLASctl_0.23-42    fitdistrplus_1.1-8     tidygraph_1.2.3
 [82] purrr_1.0.1            RANN_2.6.1             ggraph_2.1.0
 [85] pbapply_1.7-0          nlme_3.1-162           mime_0.12
 [88] aplot_0.1.10           compiler_4.2.3         plotly_4.10.1
 [91] png_0.1-8              spatstat.utils_3.0-2   treeio_1.22.0
 [94] tibble_3.2.1           tweenr_2.0.2           stringi_1.7.12
 [97] RSpectra_0.16-1        logger_0.2.2           lattice_0.20-45
[100] IRdisplay_1.1          vctrs_0.6.1            pillar_1.9.0
[103] lifecycle_1.0.3        spatstat.geom_3.1-0    lmtest_0.9-40
[106] RcppAnnoy_0.0.20       cowplot_1.1.1          irlba_2.3.5.1
[109] httpuv_1.6.9           patchwork_1.1.2        R6_2.5.1
[112] scistreer_1.1.0        promises_1.2.0.1       KernSmooth_2.23-20
[115] gridExtra_2.3          parallelly_1.35.0      codetools_0.2-19
[118] fastDummies_1.6.3      MASS_7.3-58.3          withr_2.5.0
[121] sctransform_0.3.5      parallel_4.2.3         quadprog_1.5-8
[124] grid_4.2.3             ggfun_0.0.9            IRkernel_1.3.2
[127] tidyr_1.3.0            Rtsne_0.16             pbdZMQ_0.3-9
[130] spatstat.explore_3.1-0 ggforce_0.4.1          shiny_1.7.4
[133] base64enc_0.1-3

In [2]:
dmg <- readRDS('/projects/0/einf2548/cruiz/dmg/data/merged_dmg_atlas_qc_filtered.rds')
dmg

An object of class Seurat
38576 features across 409561 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

In [4]:
dmg$numbat_id <- recode(dmg$predicted.annotation_level_3,
                         `AC-like` = 'Malignant',
                                       `MES-like` = "Malignant",    
                                       `OPC-like` = "Malignant", 
                                       `NPC-like` = "Malignant",    
                                       `Astrocyte` = "Glial_Neuronal", 
                                       # `Oligodendrocyte` = "Glial_Neuronal",    
                                       `OPC` = "Glial_Neuronal", 
                                       `Neuron` = "Glial_Neuronal",
                                        `Mono` = "Myeloid",
                                       `TAM-BDM` = "Myeloid",    
                                       `TAM-MG` = "Myeloid", 
                                       `DC` = "Myeloid",    
                                       `Mast` = "Myeloid",
                                       `CD4/CD8` = "Lymphoid",    
                                       `NK` = "Lymphoid", 
                                       `B cell` = "Lymphoid",    
                                       `Plasma B` = "Lymphoid",
                                       `Endothelial` = "Vascular",    
                                       `Mural cell` = "Vascular"
                         )
Idents(dmg) <- dmg$numbat_id
table(dmg@active.ident)

      Malignant  Glial_Neuronal        Vascular         Myeloid Oligodendrocyte
         231886           78710            7188           60905           25955
       Lymphoid
           4917

In [5]:
`%nin%` <- function(x, y) !(x %in% y)
dmg <- subset(dmg, Study %nin% c('Filbin2018', 'Liu2022'))
dmg
gc()

An object of class Seurat
38576 features across 397794 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

       used        (Mb)    gc trigger  (Mb)     max used    (Mb)
Ncells     8382606   447.7    16414178    876.7    16414178   876.7
Vcells 12653726388 96540.3 16213889217 123702.2 12897181288 98397.7

In [8]:
dmg <- subset(dmg, Study == 'Ruiz2023')
dmg

An object of class Seurat
38576 features across 205805 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

In [9]:
ref_internal = aggregate_counts(GetAssayData(subset(dmg, 
                                                   idents = c('Malignant', 'Glial_Neuronal'),
                                                   invert = TRUE),
                                             slot = 'counts'
                                            ), 
                               as.data.frame(dmg@active.ident) %>% 
                                `colnames<-`('group') %>% 
                                tibble::rownames_to_column('cell') %>%
                                filter(!group %in% c('Malignant', 'Glial_Neuronal'))
                               )
ref_internal

Warning message:
“The `slot` argument of `GetAssayData()` is deprecated as of SeuratObject 5.0.0.
ℹ Please use the `layer` argument instead.”

cell_dict
       Vascular         Myeloid Oligodendrocyte        Lymphoid
           5538           35409           18407            3682

         Vascular     Myeloid      Oligodendrocyte Lymphoid
A1BG     6.210648e-06 6.937543e-06 1.800258e-05    1.096939e-05
A1CF     3.382036e-07 2.559213e-07 7.373789e-08    4.387757e-07
A2M      8.043712e-04 4.919084e-04 2.396482e-05    1.562041e-04
A2ML1    2.920850e-06 2.427794e-06 1.590632e-06    6.581635e-07
A3GALT2  1.199086e-06 3.057222e-06 7.479129e-07    8.775513e-07
A4GALT   3.609555e-05 3.596732e-07 4.318934e-07    3.290817e-07
A4GNT    3.074578e-08 1.245023e-07 5.266992e-08    1.096939e-07
AAAS     1.159116e-05 8.237900e-06 1.669637e-05    7.897962e-06
AACS     1.641825e-05 1.660722e-05 3.225506e-05    2.884950e-05
AADAC    2.767121e-07 2.628381e-07 6.320391e-08    1.096939e-07
AADACL2  1.045357e-06 8.991830e-08 2.106797e-08    0.000000e+00
AADACL3  3.074578e-08 4.150075e-08 2.106797e-08    0.000000e+00
AADACL4  3.074578e-08 5.533434e-08 5.266992e-08    1.096939e-07
AADAT    4.796342e-06 1.175855e-07 1.791831e-05    2.193878e-07
AAGAB    4.925475e-05 4.912306e-05 3.524671e-05    7.579849e-05
AAK1     3.297485e-04 4.878898e-04 2.878095e-04    8.741508e-04
AAMDC    6.960846e-05 4.810629e-05 1.008208e-04    3.850256e-05
AAMP     1.349740e-05 1.439384e-05 1.284093e-05    1.305358e-05
AANAT    4.611868e-07 8.514571e-06 1.790777e-07    9.872452e-07
AAR2     1.159116e-05 1.054811e-05 1.530588e-05    1.360205e-05
AARD     3.689494e-07 1.867534e-07 4.740293e-07    2.193878e-07
AARS     3.422006e-05 3.902454e-05 4.220968e-05    3.455358e-05
AARS2    8.270616e-06 1.196605e-05 8.490392e-06    8.665819e-06
AARSD1   1.506543e-05 1.668330e-05 1.699132e-05    1.338266e-05
AASDH    4.525779e-05 4.533266e-05 6.254027e-05    3.016583e-05
AASDHPPT 3.913938e-05 2.019703e-05 5.121623e-05    2.906889e-05
AASS     1.404160e-04 9.828762e-06 1.616651e-04    1.974490e-06
AATF     5.558838e-05 8.751126e-05 7.860459e-05    1.205536e-04
AATK     1.423530e-05 1.991345e-05 4.278799e-04    9.872452e-07
ABAT     1.807852e-05 7.107004e-05 3.580501e-05    3.927042e-05
⋮        ⋮            ⋮            ⋮               ⋮
ZSCAN26  2.484259e-05 2.096480e-05 5.279633e-05    1.096939e-05
ZSCAN29  8.824040e-06 1.166171e-05 1.298840e-05    9.872452e-06
ZSCAN30  4.940848e-05 3.658291e-05 1.024746e-04    1.217602e-05
ZSCAN31  2.139907e-05 3.444563e-06 8.371358e-05    4.387757e-06
ZSCAN32  1.165265e-05 1.153721e-05 1.702292e-05    1.294388e-05
ZSCAN4   1.229831e-07 2.766717e-08 1.053398e-08    0.000000e+00
ZSCAN5A  3.741762e-05 4.520124e-05 3.706909e-05    1.513776e-05
ZSCAN5B  3.074578e-08 4.841755e-08 6.320391e-08    0.000000e+00
ZSCAN5C  0.000000e+00 0.000000e+00 3.160195e-08    0.000000e+00
ZSCAN9   1.629527e-05 1.968519e-05 1.382059e-05    5.484696e-06
ZSWIM1   1.875493e-06 1.909035e-06 1.653836e-06    1.426021e-06
ZSWIM2   6.149157e-08 4.841755e-08 3.160195e-08    0.000000e+00
ZSWIM3   7.532717e-06 6.695455e-06 8.069032e-06    6.801023e-06
ZSWIM4   2.133757e-05 1.303815e-05 3.434079e-06    6.033165e-06
ZSWIM5   1.403238e-04 2.040454e-06 1.178016e-04    3.422450e-05
ZSWIM6   4.586656e-04 1.085514e-03 6.856044e-04    1.795689e-04
ZSWIM7   4.491959e-05 5.924924e-05 5.157439e-05    2.961736e-05
ZSWIM8   4.116861e-05 6.397341e-05 4.260997e-05    3.192093e-05
ZSWIM9   1.048431e-05 1.191072e-05 1.621180e-05    1.798980e-05
ZUP1     3.240606e-05 5.639952e-05 3.594196e-05    4.508420e-05
ZW10     1.786330e-05 1.910418e-05 2.486020e-05    1.426021e-05
ZWILCH   8.762549e-06 1.141271e-05 4.729759e-06    1.184694e-05
ZWINT    1.414306e-06 2.379377e-06 6.320391e-07    1.206633e-06
ZXDA     2.767121e-06 9.683509e-07 2.981118e-06    2.852042e-06
ZXDB     3.720240e-06 1.625446e-06 2.391215e-06    4.278063e-06
ZXDC     7.142246e-05 9.953956e-05 9.336271e-05    9.532401e-05
ZYG11A   1.322069e-06 6.847624e-07 6.741750e-07    1.426021e-06
ZYG11B   6.478137e-05 7.353242e-05 7.007207e-05    3.192093e-05
ZYX      3.126846e-05 3.907988e-05 3.233933e-06    2.490052e-05
ZZEF1    9.002366e-05 1.364614e-04 1.014949e-04    1.486353e-04

### Process Ruiz2023

In [ ]:
ruiz <- SplitObject(dmg, split.by = 'SampleID')
ruiz
gc()

In [ ]:
table(dmg$SampleID)

In [ ]:
rm(dmg)
gc()

In [ ]:
#check cell name nomenclature to add to numbat pipeline
head(colnames(ruiz[[1]]))

In [15]:
length(ruiz)

[1] 51

In [16]:
for(i in 31:length(ruiz)) {  # run on the first half of ruiz
    cat(' ############################################\n',
        '### Numbat for dataset number ', names(ruiz[i]), '###\n',
        '############################################\n')
    
    old <- Sys.time() # get start time
    
    file_path <- paste0('/projects/0/einf2548/cruiz/cellranger_output/numbat_pileup_output_cellbender/',
                        names(ruiz[i]),'/',names(ruiz[i]),'_allele_counts.tsv.gz')
    
    if (file.exists(file_path)) {  # check if file exists
        df_allele = fread(file_path)
        df_allele$cell <- paste0(names(ruiz[i]),'_',df_allele$cell)
          
        # run
        out = run_numbat(
            as.matrix(GetAssayData(ruiz[[i]], slot = 'counts', assay = 'RNA')), # gene x cell integer UMI count matrix 
            ref_internal, # reference expression profile, a gene x cell type normalized expression level matrix
            df_allele, # allele dataframe generated by pileup_and_phase script and MUST BE A DATATABLE!
            min_cells = 20,
            t = 1e-3,
            max_iter = 2,
            init_k = 3,
            ncores = 40,
            ncores_nni = 40,
            multi_allelic = TRUE,
            plot = TRUE,
            genome = "hg38",
            out_dir = paste0('/projects/0/einf2548/cruiz/dmg/notebooks/iCNV/numbat/dmg_atlas_segregated_ref/Ruiz2023/',names(ruiz[i]))
        )
      
        cat(' ############################################\n',
        '### Done with dataset', names(ruiz[i]), '###\n',
        '############################################\n')
        
        # print elapsed time
        new <- Sys.time() - old # calculate difference
        print(new) # print in nice format
    } else {
        cat(' ############################################\n',
        '### Skipping dataset', names(ruiz[i]), 'because the file does not exist ###\n',
        '############################################\n')
    }
}

 ############################################
 ### Numbat for dataset number  T21-90581_212AAQ_region_2 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 273.9
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
913 cells

Mem used: 76.4Gb

Approximating initial clusters using smoothed expression ..

Mem used: 76.4Gb

number of genes left: 12505

running hclust...

Iteration 1

Mem used: 28.7Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.77).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

1 multi-allelic CNVs found: 15a

Evaluating CNV per cell ..

Mem used: 28.2Gb

All cells succeeded

Expanding allelic states..

Building phylogeny ..

Mem used: 28.2Gb

Using 5 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 28.2Gb

Iter 2 -837.775780137649, 0.043s

Iter 3 -829.098145238691, 0.039s

Iter 4 -829.098145238691, 0.026s

Found 210 normal cells..

Iteration 2

Mem used: 28.3Gb

Running HMMs on 4 cell groups..

Running HMMs on 4 cell groups..

Testing for multi-allelic CNVs ..

1 multi-allelic CNVs found: 15a

Evaluating CNV per cell ..

Mem used: 28.4Gb

All cells succeeded

Expanding allelic states..

Building phylogeny ..

Mem used: 28.4Gb

Using 6 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 28.4Gb

Iter 2 -996.546881103451, 0.037s

Iter 3 -993.7772785553, 0.048s

Iter 4 -992.514231243115, 0.03s

Iter 5 -977.725747727097, 0.024s

Iter 6 -976.821322750295, 0.023s

Iter 7 -976.631232265211, 0.023s

Iter 8 -976.39013280379, 0.022s

Iter 9 -976.233090718226, 0.021s

Iter 10 -976.232056266053, 0.023s

Iter 11 -976.232056266053, 0.022s

Found 211 normal cells..

Running HMMs on 4 cell groups..

All done!

 ############################################
 ### Done with dataset T21-90581_212AAQ_region_2 ###
 ############################################
Time difference of 8.842005 mins
 ############################################
 ### Numbat for dataset number  T21-90610_232AAQ ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1744.8
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
5816 cells

Mem used: 29.4Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.4Gb

number of genes left: 12592

running hclust...

Iteration 1

Mem used: 36.2Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.86).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

2 multi-allelic CNVs found: 14a,15c

Evaluating CNV per cell ..

Mem used: 31.8Gb

All cells succeeded

Expanding allelic states..

Building phylogeny ..

Mem used: 31.9Gb

Using 5 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 32.1Gb

Iter 2 -5265.3983276455, 0.89s

Iter 3 -5263.16832468376, 0.75s

Iter 4 -5247.87156818699, 0.74s

Iter 5 -5242.79099475042, 0.74s

Iter 6 -5242.79099475042, 0.74s

Found 571 normal cells..

Iteration 2

Mem used: 32.1Gb

Running HMMs on 6 cell groups..

Running HMMs on 6 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 33Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 32.9Gb

Using 5 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 32.9Gb

Iter 2 -19428.0614681778, 1s

Iter 3 -19423.9978965212, 0.9s

Iter 4 -19412.2839190722, 0.85s

Iter 5 -19404.3246546541, 0.84s

Iter 6 -19400.3364575353, 0.8s

Iter 7 -19396.4354454385, 0.79s

Iter 8 -19388.751956331, 0.8s

Iter 9 -19377.555289629, 0.79s

Iter 10 -19373.7243049954, 0.78s

Iter 11 -19370.0081309818, 0.78s

Iter 12 -19366.0199851909, 0.79s

Iter 13 -19362.3742962566, 0.79s

Iter 14 -19293.6368087374, 0.78s

Iter 15 -19290.2722689209, 0.78s

Iter 16 -19286.7751637698, 0.78s

Iter 17 -19283.2865958045, 0.78s

Iter 18 -19279.804599623, 0.78s

Iter 19 -19276.3678532899, 0.78s

Iter 20 -19272.9568898254, 0.78s

Iter 21 -19269.5735533173, 0.78s

Iter 22 -19266.2628973423, 0.78s

Iter 23 -19262.9164850971, 0.78s

Iter 24 -19259.6465641258, 0.78s

Iter 25 -19256.3933636225, 0.78s

Iter 26 -19249.8084206298, 0.78s

Iter 27 -19246.5318196247, 0.78s

Iter 28 -19243.2598398692, 0.78s

Iter 29 -19240.0159236117, 0.78s

Iter 30 -19236.7915429222, 0.78s

Iter 31 -19233.5709892185, 0.78s

Iter 32 -19230.4099611057, 0.78s

Iter 33 -19227.2603656661, 0.78s

Iter 34 -19224.1324577659, 0.78s

Iter 35 -19221.0130474443, 0.78s

Iter 36 -19217.6607649689, 0.78s

Iter 37 -19214.4627086686, 0.78s

Iter 38 -19211.384645103, 0.79s

Iter 39 -19199.3391849788, 0.79s

Iter 40 -19193.5392175789, 0.79s

Iter 41 -19167.6085950312, 0.79s

Iter 42 -19161.6859635063, 0.79s

Iter 43 -19158.6231210436, 0.79s

Iter 44 -19155.5136528618, 0.79s

Iter 45 -19124.2505954471, 0.79s

Iter 46 -19121.0143574185, 0.78s

Iter 47 -19116.3713597725, 0.78s

Iter 48 -19109.8020702555, 0.8s

Iter 49 -19106.0275421461, 0.79s

Iter 50 -19066.4961152972, 0.79s

Iter 51 -19063.0994358102, 0.79s

Iter 52 -19059.6405800213, 0.79s

Iter 53 -19051.3032780014, 0.79s

Iter 54 -18741.6264613856, 0.79s

Iter 55 -18736.5610219538, 0.78s

Iter 56 -18733.6408086871, 0.78s

Iter 57 -18730.7904241754, 0.78s

Iter 58 -18725.1264634218, 0.77s

Iter 59 -18722.4293993202, 0.78s

Iter 60 -18693.7747726336, 0.78s

Iter 61 -18691.1009061985, 0.78s

Iter 62 -18688.4732692727, 0.77s

Iter 63 -18685.9814166485, 0.78s

Iter 64 -18683.4921627639, 0.78s

Iter 65 -18676.7605117249, 0.78s

Iter 66 -18674.505238977, 0.78s

Iter 67 -18667.3344159029, 0.78s

Iter 68 -18662.8606090099, 0.78s

Iter 69 -18660.5601884396, 0.78s

Iter 70 -18658.326391668, 0.78s

Iter 71 -18653.8830174456, 0.78s

Iter 72 -18640.7275258795, 0.78s

Iter 73 -18630.1038723993, 0.78s

Iter 74 -18628.0127467736, 0.78s

Iter 75 -18625.9129923493, 0.78s

Iter 76 -18623.8287192898, 0.78s

Iter 77 -18621.807838712, 0.78s

Iter 78 -18617.7677887448, 0.78s

Iter 79 -18502.3677340865, 0.78s

Iter 80 -18500.4199170929, 0.78s

Iter 81 -18498.5844110053, 0.78s

Iter 82 -18493.3792695978, 0.77s

Iter 83 -18490.2246360435, 0.78s

Iter 84 -18488.4057555432, 0.78s

Iter 85 -18485.8992551023, 0.78s

Iter 86 -18478.4169147935, 0.78s

Iter 87 -18476.4212298111, 0.78s

Iter 88 -18474.9845905085, 0.78s

Iter 89 -18473.3145732173, 0.78s

Iter 90 -18469.4316345964, 0.78s

Iter 91 -18468.3223767293, 0.78s

Iter 92 -18467.4352094776, 0.78s

Iter 93 -18466.0509749938, 0.78s

Iter 94 -18465.2001037466, 0.78s

Iter 95 -18463.2403090807, 0.79s

Iter 96 -18462.4371955406, 0.78s

Iter 97 -18461.6384414539, 0.78s

Iter 98 -18460.0500372803, 0.79s

Iter 99 -18459.1781923483, 0.77s

Iter 100 -18458.0573462279, 0.77s

Iter 101 -18457.2820627619, 0.78s

Found 588 normal cells..

Running HMMs on 5 cell groups..

All done!

 ############################################
 ### Done with dataset T21-90610_232AAQ ###
 ############################################
Time difference of 48.63547 mins
 ############################################
 ### Numbat for dataset number  T21-90717_MIMIC002 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1152.3
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
3841 cells

Mem used: 30.2Gb

Approximating initial clusters using smoothed expression ..

Mem used: 30.2Gb

number of genes left: 12497

running hclust...

Iteration 1

Mem used: 33.2Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.71).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 30.8Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 30.9Gb

Using 5 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 30.9Gb

Iter 2 -2231.19445362278, 0.38s

Iter 3 -2078.94824407489, 0.33s

Iter 4 -2044.99889543737, 0.33s

Iter 5 -2044.99889543737, 0.33s

Found 1429 normal cells..

Iteration 2

Mem used: 30.9Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 30.9Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 30.9Gb

Using 5 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 30.9Gb

Iter 2 -2351.00149102152, 0.35s

Iter 3 -2322.62055669755, 0.33s

Iter 4 -2304.05203208528, 0.33s

Iter 5 -1981.70430571293, 0.33s

Iter 6 -1951.85093525856, 0.33s

Iter 7 -1951.85093525856, 0.33s

Found 1427 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset T21-90717_MIMIC002 ###
 ############################################
Time difference of 30.47009 mins
 ############################################
 ### Numbat for dataset number  T21-90789_MIMIC005 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 2073.3
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
6911 cells

Mem used: 30.4Gb

Approximating initial clusters using smoothed expression ..

Mem used: 30.4Gb

number of genes left: 12481

running hclust...

Iteration 1

Mem used: 37.8Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.76).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

1 multi-allelic CNVs found: 8a

Evaluating CNV per cell ..

Mem used: 32.5Gb

All cells succeeded

Expanding allelic states..

Building phylogeny ..

Mem used: 33.2Gb

Using 14 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 33.4Gb

Iter 2 -27789.195150651, 2.6s

Iter 3 -27768.7649981294, 2.5s

Iter 4 -27756.3356286609, 2.5s

Iter 5 -27746.7978973827, 2.4s

Iter 6 -27737.8636098826, 2.5s

Iter 7 -27732.7279600078, 2.5s

Iter 8 -27672.3714015222, 2.5s

Iter 9 -27668.1893981806, 2.5s

Iter 10 -27666.6562107596, 2.5s

Iter 11 -27635.5163887789, 2.5s

Iter 12 -27634.763291996, 2.5s

Iter 13 -27626.3394173473, 2.5s

Iter 14 -27625.7273465996, 2.5s

Iter 15 -27622.2773276206, 2.5s

Iter 16 -27620.4497910282, 2.5s

Iter 17 -27620.4497910282, 2.5s

Found 1818 normal cells..

Iteration 2

Mem used: 33.7Gb

Running HMMs on 6 cell groups..

Running HMMs on 6 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 34.5Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 34.5Gb

Using 18 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 34.6Gb

Iter 2 -35508.553925192, 3.2s

Iter 3 -35479.3702884706, 3.1s

Iter 4 -35461.8998304336, 3.1s

Iter 5 -35445.3639216561, 3.1s

Iter 6 -35425.1470880148, 3.1s

Iter 7 -35410.481404348, 3.1s

Iter 8 -35392.6884759233, 3.1s

Iter 9 -35321.5258233264, 3.1s

Iter 10 -35312.949500847, 3.2s

Iter 11 -35306.4151881896, 3.1s

Iter 12 -35304.3164597557, 3.1s

Iter 13 -35303.6292945702, 3.1s

Iter 14 -35302.6597254547, 3.1s

Iter 15 -35297.3834980308, 3.2s

Iter 16 -35296.7205578087, 3.2s

Iter 17 -35296.6000218288, 3.1s

Iter 18 -35293.2545278581, 3.1s

Iter 19 -35293.2025867701, 3.1s

Iter 20 -35292.3233340093, 3.2s

Iter 21 -35290.6553948829, 3.2s

Iter 22 -35290.6553948829, 3.1s

Found 1840 normal cells..

Running HMMs on 7 cell groups..

All done!

 ############################################
 ### Done with dataset T21-90789_MIMIC005 ###
 ############################################
Time difference of 1.201966 hours
 ############################################
 ### Numbat for dataset number  T21-90813_MIMIC006 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 535.5
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
1785 cells

Mem used: 29.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.7Gb

number of genes left: 12405

running hclust...

Iteration 1

Mem used: 29.9Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.53).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 28.6Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 28.7Gb

No CNV remains after filtering by entropy in single cells. Consider increasing max_entropy.

 ############################################
 ### Done with dataset T21-90813_MIMIC006 ###
 ############################################
Time difference of 7.064278 mins
 ############################################
 ### Numbat for dataset number  T21-90868_448AAQ ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1951.8
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
6506 cells

Mem used: 29.6Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.6Gb

number of genes left: 12618

running hclust...

Iteration 1

Mem used: 37.4Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.74).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 32.7Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 33Gb

Using 13 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 33.2Gb

Iter 2 -41196.9597891566, 2s

Iter 3 -41155.7802697046, 1.9s

Iter 4 -41136.881592003, 2s

Iter 5 -41071.4987381065, 2s

Iter 6 -41054.5881350028, 2s

Iter 7 -41009.8463717128, 2s

Iter 8 -40997.5391134548, 2s

Iter 9 -40877.8425400887, 2s

Iter 10 -40866.6031645253, 2s

Iter 11 -40861.3973772704, 2s

Iter 12 -40833.5272987971, 2s

Iter 13 -40832.0775889952, 2s

Iter 14 -40825.9549104416, 2s

Iter 15 -40825.4998511549, 2s

Iter 16 -40825.12068279, 2s

Iter 17 -40824.7705135605, 2s

Iter 18 -40824.5532608088, 2s

Iter 19 -40824.4388817526, 2s

Iter 20 -40824.2147329383, 2s

Iter 21 -40823.991186255, 2s

Iter 22 -40822.2962594888, 2s

Iter 23 -40822.1440915797, 2s

Iter 24 -40822.1440915797, 1.9s

Found 3629 normal cells..

Iteration 2

Mem used: 33.3Gb

Running HMMs on 6 cell groups..

Running HMMs on 6 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 34.1Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 34.3Gb

Using 13 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 34.3Gb

Iter 2 -37254.6176402477, 2.5s

Iter 3 -37103.102100282, 2.2s

Iter 4 -36987.7458367418, 2.2s

Iter 5 -36894.6375289761, 2.2s

Iter 6 -36886.5748604169, 2.2s

Iter 7 -36882.3213976878, 2.2s

Iter 8 -36871.8416209519, 2.1s

Iter 9 -36870.5157100396, 2.1s

Iter 10 -36869.5110767442, 2.1s

Iter 11 -36868.5409202587, 2.1s

Iter 12 -36867.7558814044, 2.1s

Iter 13 -36867.0487169751, 2.1s

Iter 14 -36854.3892487433, 2.1s

Iter 15 -36852.116837752, 2s

Iter 16 -36851.5364575621, 2s

Iter 17 -36851.1587097347, 2s

Iter 18 -36850.9416642865, 2s

Iter 19 -36850.9416642865, 2s

Found 3628 normal cells..

Running HMMs on 6 cell groups..

All done!

 ############################################
 ### Done with dataset T21-90868_448AAQ ###
 ############################################
Time difference of 1.021121 hours
 ############################################
 ### Numbat for dataset number  T21-91022_MIMIC008 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1831.8
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
6106 cells

Mem used: 31.2Gb

Approximating initial clusters using smoothed expression ..

Mem used: 31.2Gb

number of genes left: 12348

running hclust...

Iteration 1

Mem used: 36.6Gb

Running HMMs on 5 cell groups..

Expression noise level: low (0.47).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 32.4Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 32.4Gb

No CNV remains after filtering by entropy in single cells. Consider increasing max_entropy.

 ############################################
 ### Done with dataset T21-91022_MIMIC008 ###
 ############################################
Time difference of 22.78753 mins
 ############################################
 ### Numbat for dataset number  T21-91074_MIMIC010 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1466.7
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
4889 cells

Mem used: 29.9Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.9Gb

number of genes left: 12568

running hclust...

Iteration 1

Mem used: 34.8Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.79).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31.1Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31.2Gb

Using 9 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 31.3Gb

Iter 2 -8372.63562463358, 1s

Iter 3 -8358.31184831901, 0.93s

Iter 4 -8348.88891189807, 0.86s

Iter 5 -8335.85500263614, 0.84s

Iter 6 -8326.13395299351, 0.84s

Iter 7 -8321.74408161158, 0.83s

Iter 8 -8306.62499921671, 0.83s

Iter 9 -8300.25345544419, 0.83s

Iter 10 -8300.25345544419, 0.82s

Found 1304 normal cells..

Iteration 2

Mem used: 31.3Gb

Running HMMs on 4 cell groups..

Running HMMs on 4 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31.9Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 32Gb

Using 9 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 32Gb

Iter 2 -7615.53651465258, 0.85s

Iter 3 -7592.51066380547, 0.8s

Iter 4 -7582.05838258146, 0.79s

Iter 5 -7571.30340043209, 0.8s

Iter 6 -7563.5698829316, 0.8s

Iter 7 -7552.66729690803, 0.79s

Iter 8 -7542.45753244678, 0.8s

Iter 9 -7536.42382803365, 0.79s

Iter 10 -7532.09370692832, 0.8s

Iter 11 -7529.85798922095, 0.8s

Iter 12 -7528.2279028069, 0.8s

Iter 13 -7516.56363292247, 0.79s

Iter 14 -7512.28916262881, 0.8s

Iter 15 -7511.05436010603, 0.8s

Iter 16 -7510.8931814134, 0.8s

Iter 17 -7500.89850469664, 0.8s

Iter 18 -7500.15918963477, 0.8s

Iter 19 -7500.15918963477, 0.8s

Found 1303 normal cells..

Running HMMs on 4 cell groups..

All done!

 ############################################
 ### Done with dataset T21-91074_MIMIC010 ###
 ############################################
Time difference of 40.98372 mins
 ############################################
 ### Numbat for dataset number  T21-91160_MIMIC013 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1974.3
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
6581 cells

Mem used: 30.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 30.7Gb

number of genes left: 12083

running hclust...

Iteration 1

Mem used: 37.2Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.84).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 32.4Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 32.5Gb

Using 5 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 32.7Gb

Iter 2 -5696.62469185612, 1.2s

Iter 3 -5596.98256359708, 1s

Iter 4 -5583.1215348437, 1s

Iter 5 -5572.9568843595, 1s

Iter 6 -5570.8014855178, 1s

Iter 7 -5568.21700117416, 1s

Iter 8 -5568.21688038382, 1s

Iter 9 -5568.21688038382, 1s

Found 1016 normal cells..

Iteration 2

Mem used: 32.7Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 33.2Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 33.2Gb

Using 5 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 33.2Gb

Iter 2 -6061.35965460103, 1.2s

Iter 3 -6058.56559658795, 1.1s

Iter 4 -6058.10789720162, 1.1s

Iter 5 -6058.10789720162, 1.1s

Found 1011 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset T21-91160_MIMIC013 ###
 ############################################
Time difference of 58.79589 mins
 ############################################
 ### Numbat for dataset number  T22-90003_MIMIC014 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 2011.5
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
6705 cells

Mem used: 30.8Gb

Approximating initial clusters using smoothed expression ..

Mem used: 30.8Gb

number of genes left: 12589

running hclust...

Iteration 1

Mem used: 37.6Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.63).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 32.7Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 33.2Gb

Using 22 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 33.5Gb

Iter 2 -81283.7603278133, 3.7s

Iter 3 -80967.607496169, 3.7s

Iter 4 -80689.3710964061, 3.7s

Iter 5 -80430.8759262588, 3.7s

Iter 6 -80266.5349543405, 3.7s

Iter 7 -80133.163075191, 3.7s

Iter 8 -80050.7555815955, 3.7s

Iter 9 -79988.1095648067, 3.7s

Iter 10 -79930.3000317143, 3.7s

Iter 11 -79894.2312169766, 3.7s

Iter 12 -79868.3393510881, 3.7s

Iter 13 -79846.1944222971, 3.7s

Iter 14 -79824.1159267375, 3.7s

Iter 15 -79805.0273496496, 3.7s

Iter 16 -79786.755757181, 3.7s

Iter 17 -79769.0344756542, 3.8s

Iter 18 -79756.5876134828, 3.7s

Iter 19 -79744.5693654541, 3.7s

Iter 20 -79733.4844086513, 3.8s

Iter 21 -79725.5227268661, 3.7s

Iter 22 -79699.3389527961, 3.7s

Iter 23 -79694.7372007052, 3.7s

Iter 24 -79692.9732993442, 3.7s

Iter 25 -79687.2847692189, 3.7s

Iter 26 -79686.6090283086, 3.7s

Iter 27 -79685.0655024832, 3.7s

Iter 28 -79684.5911403147, 3.7s

Iter 29 -79681.7877805355, 3.7s

Iter 30 -79680.8497221227, 3.7s

Iter 31 -79680.4783021681, 3.7s

Iter 32 -79680.4192539583, 3.7s

Iter 33 -79680.4192539583, 3.5s

Found 2887 normal cells..

Iteration 2

Mem used: 33.5Gb

Running HMMs on 9 cell groups..

Running HMMs on 9 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 34.6Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 34.8Gb

Using 24 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 34.8Gb

Iter 2 -89525.0261698078, 4s

Iter 3 -89188.3867879792, 3.9s

Iter 4 -88998.7378217329, 3.9s

Iter 5 -88584.7059472163, 3.9s

Iter 6 -88442.3998271761, 3.9s

Iter 7 -88319.5295021158, 3.9s

Iter 8 -88228.5707618439, 3.8s

Iter 9 -88145.246706789, 3.8s

Iter 10 -88094.0433280896, 3.8s

Iter 11 -88050.8225025232, 3.9s

Iter 12 -87992.544065541, 3.8s

Iter 13 -87928.8302851012, 3.8s

Iter 14 -87861.3870629377, 3.8s

Iter 15 -87826.7948015175, 3.8s

Iter 16 -87801.6191520161, 3.8s

Iter 17 -87577.1763293423, 3.8s

Iter 18 -87554.9688839708, 3.8s

Iter 19 -87540.4973427108, 3.8s

Iter 20 -87528.3953502404, 3.8s

Iter 21 -87517.6346707917, 3.8s

Iter 22 -87509.4616405718, 3.8s

Iter 23 -87497.0216465096, 3.8s

Iter 24 -87485.9924278283, 3.8s

Iter 25 -87463.8810024474, 3.9s

Iter 26 -87441.0544362768, 3.9s

Iter 27 -87175.1073070015, 3.9s

Iter 28 -87147.757257574, 3.9s

Iter 29 -87119.51064965, 3.8s

Iter 30 -87114.1772332698, 3.9s

Iter 31 -87073.0415655141, 3.9s

Iter 32 -87070.145530112, 3.9s

Iter 33 -87063.0470260804, 3.9s

Iter 34 -87061.2993200902, 3.9s

Iter 35 -87036.1443121261, 3.9s

Iter 36 -87009.5023795012, 3.9s

Iter 37 -86964.3366148305, 3.8s

Iter 38 -86962.0734652883, 3.9s

Iter 39 -86960.4723932122, 3.9s

Iter 40 -86959.9696130409, 3.9s

Iter 41 -86959.9696130409, 3.8s

Found 2918 normal cells..

Running HMMs on 9 cell groups..

All done!

 ############################################
 ### Done with dataset T22-90003_MIMIC014 ###
 ############################################
Time difference of 1.194511 hours
 ############################################
 ### Numbat for dataset number  T22-90066_MIMIC015 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1340.1
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
4467 cells

Mem used: 30.8Gb

Approximating initial clusters using smoothed expression ..

Mem used: 30.8Gb

number of genes left: 12318

running hclust...

Iteration 1

Mem used: 34Gb

Running HMMs on 5 cell groups..

Expression noise level: low (0.42).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 30.9Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31Gb

Using 20 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 31.2Gb

Iter 2 -18008.5167240347, 1.4s

Iter 3 -17969.061701298, 1.3s

Iter 4 -17949.2734342621, 1.3s

Iter 5 -17934.4210160484, 1.3s

Iter 6 -17923.2620416486, 1.3s

Iter 7 -17913.6338851206, 1.3s

Iter 8 -17905.2545915024, 1.2s

Iter 9 -17896.9786903602, 1.2s

Iter 10 -17889.8785420369, 1.2s

Iter 11 -17883.146969326, 1.2s

Iter 12 -17878.5826920297, 1.2s

Iter 13 -17877.0760416742, 1.2s

Iter 14 -17877.0760416742, 1.2s

Found 4112 normal cells..

Iteration 2

Mem used: 31.2Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 30.6Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 30.7Gb

Using 19 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 30.7Gb

Iter 2 -17570.1342011032, 1.1s

Iter 3 -17465.2653275685, 1s

Iter 4 -17392.2806162505, 1s

Iter 5 -17360.9737655731, 1s

Iter 6 -17343.5468462962, 1s

Iter 7 -17328.3050509663, 1s

Iter 8 -17313.8692359792, 1s

Iter 9 -17301.5906400891, 1s

Iter 10 -17291.8399797945, 1s

Iter 11 -17283.1846712432, 1.1s

Iter 12 -17244.6576117499, 1.1s

Iter 13 -17233.4435771001, 1.1s

Iter 14 -17224.5983653786, 1s

Iter 15 -17217.5378205192, 1.1s

Iter 16 -17188.8850428511, 1.1s

Iter 17 -17178.8758589045, 1s

Iter 18 -17173.3128248848, 1.1s

Iter 19 -17170.8076084565, 1.1s

Iter 20 -17161.1799699292, 1s

Iter 21 -17159.6233834416, 1.1s

Iter 22 -17154.6281956499, 1.1s

Iter 23 -17153.2218377238, 1.1s

Iter 24 -17151.889421875, 1s

Iter 25 -17150.7206509026, 1s

Iter 26 -17149.9598062982, 1s

Iter 27 -17149.7706694282, 1s

Iter 28 -17149.7706694282, 1s

Found 4113 normal cells..

Running HMMs on 2 cell groups..

All done!

 ############################################
 ### Done with dataset T22-90066_MIMIC015 ###
 ############################################
Time difference of 36.91174 mins
 ############################################
 ### Numbat for dataset number  T22-90221_148AAR ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1949.1
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
6497 cells

Mem used: 29.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.7Gb

number of genes left: 12698

running hclust...

Iteration 1

Mem used: 37.2Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.7).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 32Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 32.1Gb

Using 3 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 32.3Gb

Iter 2 -2965.06414229747, 0.83s

Iter 3 -2956.74901910263, 0.76s

Iter 4 -2956.74901910263, 0.76s

Found 2791 normal cells..

Iteration 2

Mem used: 32.3Gb

Running HMMs on 2 cell groups..

Running HMMs on 2 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31.7Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31.8Gb

Using 3 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 31.8Gb

Iter 2 -2797.23503106856, 0.82s

Iter 3 -2797.23503106856, 0.76s

Found 2799 normal cells..

Running HMMs on 2 cell groups..

All done!

 ############################################
 ### Done with dataset T22-90221_148AAR ###
 ############################################
Time difference of 53.66639 mins
 ############################################
 ### Numbat for dataset number  T22-90282_MIMIC023 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1224.6
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
4082 cells

Mem used: 29.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.7Gb

number of genes left: 12451

running hclust...

Iteration 1

Mem used: 33.8Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.83).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31.8Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31.9Gb

Using 1 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 32Gb

Iter 2 -230.102210258177, 0.22s

Iter 3 -230.102210258177, 0.18s

Found 721 normal cells..

Iteration 2

Mem used: 32Gb

Running HMMs on 2 cell groups..

Running HMMs on 2 cell groups..

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31.2Gb

Using 1 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 31.2Gb

Iter 2 -187.008856728571, 0.28s

Iter 3 -187.008856728571, 0.21s

Found 710 normal cells..

Running HMMs on 2 cell groups..

All done!

 ############################################
 ### Done with dataset T22-90282_MIMIC023 ###
 ############################################
Time difference of 48.35309 mins
 ############################################
 ### Numbat for dataset number  VU248 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1537.2
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
5124 cells

Mem used: 29.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.7Gb

number of genes left: 12505

running hclust...

Iteration 1

Mem used: 35Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.63).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31.1Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31.2Gb

Using 3 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 31.3Gb

Iter 2 -3481.43412282117, 0.53s

Iter 3 -3481.43412282117, 0.48s

Found 2836 normal cells..

Iteration 2

Mem used: 31.3Gb

Running HMMs on 2 cell groups..

Running HMMs on 2 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 30.8Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 30.8Gb

Using 3 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 30.8Gb

Iter 2 -2683.8494370281, 0.51s

Iter 3 -2633.63471963457, 0.47s

Iter 4 -2629.13047998732, 0.47s

Iter 5 -2629.13047998732, 0.48s

Found 2912 normal cells..

Running HMMs on 2 cell groups..

All done!

 ############################################
 ### Done with dataset VU248 ###
 ############################################
Time difference of 38.50075 mins
 ############################################
 ### Numbat for dataset number  VU266 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 2051.7
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
6839 cells

Mem used: 30.1Gb

Approximating initial clusters using smoothed expression ..

Mem used: 30Gb

number of genes left: 12592

running hclust...

Iteration 1

Mem used: 37.8Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.53).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 32.5Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 32.7Gb

Using 11 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 33Gb

Iter 2 -16821.2082744683, 2.4s

Iter 3 -16809.3434485472, 2.1s

Iter 4 -16797.6583871917, 2s

Iter 5 -16782.7111374417, 1.9s

Iter 6 -16749.556367605, 1.9s

Iter 7 -16740.4344963192, 1.9s

Iter 8 -16735.7206435961, 1.9s

Iter 9 -16725.0130923216, 1.9s

Iter 10 -16700.1474340228, 1.9s

Iter 11 -16695.3435640135, 1.9s

Iter 12 -16695.014887674, 1.9s

Iter 13 -16695.014887674, 1.9s

Found 3580 normal cells..

Iteration 2

Mem used: 33Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 32.8Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 32.9Gb

Using 12 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 32.9Gb

Iter 2 -18215.6131712164, 2.4s

Iter 3 -18206.5930773842, 2.2s

Iter 4 -18199.0080076944, 2.1s

Iter 5 -18191.2631188598, 2s

Iter 6 -18183.8730881474, 2s

Iter 7 -18176.7862679724, 2s

Iter 8 -18171.7306789612, 2s

Iter 9 -18167.7916797857, 2s

Iter 10 -18165.1649459916, 2s

Iter 11 -18161.7720920662, 2s

Iter 12 -18157.7845805758, 2s

Iter 13 -18154.8914015522, 2s

Iter 14 -18154.1436417927, 2s

Iter 15 -18154.1436417927, 2s

Found 3599 normal cells..

Running HMMs on 4 cell groups..

All done!

 ############################################
 ### Done with dataset VU266 ###
 ############################################
Time difference of 1.027304 hours
 ############################################
 ### Numbat for dataset number  VU314 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1239.9
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
4133 cells

Mem used: 30Gb

Approximating initial clusters using smoothed expression ..

Mem used: 30Gb

number of genes left: 12488

running hclust...

Iteration 1

Mem used: 33.5Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.69).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 30.7Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 30.7Gb

No CNV remains after filtering by entropy in single cells. Consider increasing max_entropy.

 ############################################
 ### Done with dataset VU314 ###
 ############################################
Time difference of 15.87962 mins
 ############################################
 ### Numbat for dataset number  VU494 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1879.2
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
6264 cells

Mem used: 29.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.7Gb

number of genes left: 12356

running hclust...

Iteration 1

Mem used: 36.5Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.56).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31.1Gb

Using 5 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 31.3Gb

Iter 2 -11764.3960210036, 0.9s

Iter 3 -11160.6514867355, 0.82s

Iter 4 -11160.6514867355, 0.82s

Found 5298 normal cells..

Iteration 2

Mem used: 31.3Gb

Running HMMs on 4 cell groups..

Running HMMs on 4 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31.1Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31.1Gb

Using 7 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 31.1Gb

Iter 2 -17728.9559562126, 1s

Iter 3 -17264.3832211261, 0.98s

Iter 4 -17048.7335394639, 0.97s

Iter 5 -16936.3657410634, 0.96s

Iter 6 -16849.4211802806, 0.96s

Iter 7 -16849.4211802806, 0.96s

Found 5316 normal cells..

Running HMMs on 4 cell groups..

All done!

 ############################################
 ### Done with dataset VU494 ###
 ############################################
Time difference of 47.52697 mins
 ############################################
 ### Numbat for dataset number  VUMC11_pons ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1747.2
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
5824 cells

Mem used: 29.4Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.4Gb

number of genes left: 12622

running hclust...

Iteration 1

Mem used: 35.9Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.75).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31.2Gb

Using 11 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 31.4Gb

Iter 2 -21675.0845035304, 1.5s

Iter 3 -21640.0356674751, 1.4s

Iter 4 -21619.2816078951, 1.3s

Iter 5 -21605.0110266993, 1.3s

Iter 6 -21593.8230344433, 1.3s

Iter 7 -21513.9719796493, 1.3s

Iter 8 -21491.9247718679, 1.3s

Iter 9 -21486.2174077618, 1.3s

Iter 10 -21481.7365609113, 1.3s

Iter 11 -21477.1371615362, 1.3s

Iter 12 -21475.3426918806, 1.3s

Iter 13 -21474.8624356046, 1.3s

Iter 14 -21474.3451817643, 1.3s

Iter 15 -21474.3451817643, 1.3s

Found 1385 normal cells..

Iteration 2

Mem used: 31.4Gb

Running HMMs on 5 cell groups..

Running HMMs on 5 cell groups..

Testing for multi-allelic CNVs ..

2 multi-allelic CNVs found: 11c,3a

Evaluating CNV per cell ..

Mem used: 31.6Gb

All cells succeeded

Expanding allelic states..

Building phylogeny ..

Mem used: 31.7Gb

Using 13 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 31.7Gb

Iter 2 -22231.9635082353, 1.5s

Iter 3 -22174.9137201716, 1.4s

Iter 4 -22021.5626034774, 1.5s

Iter 5 -21965.8878532312, 1.4s

Iter 6 -21731.0848470237, 1.4s

Iter 7 -21699.5704726446, 1.4s

Iter 8 -21669.6075589858, 1.4s

Iter 9 -21646.7843793984, 1.4s

Iter 10 -21625.802440007, 1.5s

Iter 11 -21530.7411889509, 1.4s

Iter 12 -21487.3681563732, 1.4s

Iter 13 -21367.4901324874, 1.4s

Iter 14 -21348.0259232939, 1.4s

Iter 15 -21315.9078833071, 1.4s

Iter 16 -21306.3131186774, 1.4s

Iter 17 -21276.2055963593, 1.4s

Iter 18 -21260.5112920148, 1.5s

Iter 19 -21213.724695415, 1.4s

Iter 20 -21183.4869148657, 1.4s

Iter 21 -21165.4597344541, 1.4s

Iter 22 -21159.4347879277, 1.5s

Iter 23 -21158.0138277985, 1.4s

Iter 24 -21158.0138277985, 1.4s

Found 1402 normal cells..

Running HMMs on 7 cell groups..

All done!

 ############################################
 ### Done with dataset VUMC11_pons ###
 ############################################
Time difference of 51.44512 mins
 ############################################
 ### Numbat for dataset number  VUMC11_thalamus ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1953.3
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
6511 cells

Mem used: 30.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 30.7Gb

number of genes left: 12519

running hclust...

Iteration 1

Mem used: 37.4Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.85).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 33Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 33.2Gb

Using 7 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 33.4Gb

Iter 2 -8168.84124706816, 1.2s

Iter 3 -8024.11796575547, 1.2s

Iter 4 -7551.6193663596, 1.1s

Iter 5 -7471.73968011088, 1.1s

Iter 6 -7453.10743454508, 1.1s

Iter 7 -7390.53974519001, 1.1s

Iter 8 -7341.45502218401, 1.1s

Iter 9 -7244.6654179422, 1.1s

Iter 10 -7243.75284599914, 1.1s

Iter 11 -7239.02121730085, 1.1s

Iter 12 -7194.73160998811, 1.1s

Iter 13 -7194.73160998811, 1.1s

Found 4291 normal cells..

Iteration 2

Mem used: 33.4Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 32.5Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 32.6Gb

Using 7 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 32.6Gb

Iter 2 -8238.41735564539, 1.2s

Iter 3 -8137.06870713713, 1.1s

Iter 4 -8096.11069340467, 1.1s

Iter 5 -8063.9057231826, 1.1s

Iter 6 -8058.52325732006, 1.1s

Iter 7 -8052.35439652539, 1.1s

Iter 8 -8048.87130302044, 1.1s

Iter 9 -8046.02113146771, 1.1s

Iter 10 -8045.12956808449, 1.1s

Iter 11 -8045.12956808449, 1.1s

Found 4301 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset VUMC11_thalamus ###
 ############################################
Time difference of 57.72861 mins
 ############################################
 ### Numbat for dataset number  VUMC17_healthy ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1458.9
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
4863 cells

Mem used: 30.2Gb

Approximating initial clusters using smoothed expression ..

Mem used: 30.2Gb

number of genes left: 12818

running hclust...

Iteration 1

Mem used: 35.1Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.65).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 32.1Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 32.3Gb

Using 12 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 32.5Gb

Iter 2 -14783.360727162, 1s

Iter 3 -14776.1318954075, 0.99s

Iter 4 -14771.5299258544, 0.99s

Iter 5 -14769.4024375243, 1s

Iter 6 -14767.3438378462, 0.99s

Iter 7 -14765.4631136132, 0.99s

Iter 8 -14765.1061664888, 0.99s

Iter 9 -14764.9424941095, 0.99s

Iter 10 -14764.8161864344, 0.99s

Iter 11 -14764.1436737709, 1s

Iter 12 -14763.8414450992, 0.99s

Iter 13 -14762.9115993448, 0.99s

Iter 14 -14762.8997375269, 1s

Iter 15 -14762.8997375269, 0.99s

Found 2169 normal cells..

Iteration 2

Mem used: 32.5Gb

Running HMMs on 2 cell groups..

Running HMMs on 2 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31.8Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31.9Gb

Using 12 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 31.9Gb

Iter 2 -14482.2112248505, 1.4s

Iter 3 -14440.6567795008, 1.2s

Iter 4 -14427.324989737, 1.1s

Iter 5 -14410.8296986067, 1.1s

Iter 6 -14402.1850774233, 1s

Iter 7 -14401.1444736466, 1s

Iter 8 -14400.4679952452, 1s

Iter 9 -14398.2346975008, 1s

Iter 10 -14397.7445668144, 1s

Iter 11 -14397.2584287493, 1s

Iter 12 -14397.0112965548, 0.99s

Iter 13 -14397.0112965548, 0.99s

Found 2169 normal cells..

Running HMMs on 2 cell groups..

All done!

 ############################################
 ### Done with dataset VUMC17_healthy ###
 ############################################
Time difference of 42.14408 mins
 ############################################
 ### Numbat for dataset number  VUMC17 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1537.8
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
5126 cells

Mem used: 29.6Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.6Gb

number of genes left: 12345

running hclust...

Iteration 1

Mem used: 34.7Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.82).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 30.3Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 30.4Gb

Using 4 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 30.6Gb

Iter 2 -3715.51462127556, 0.63s

Iter 3 -3674.19576694696, 0.52s

Iter 4 -3598.39799525744, 0.52s

Iter 5 -3569.94692978089, 0.52s

Iter 6 -3554.33401113519, 0.52s

Iter 7 -3554.33401113519, 0.51s

Found 703 normal cells..

Iteration 2

Mem used: 30.6Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 30.2Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 30.3Gb

Using 4 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 30.3Gb

Iter 2 -3489.17398613886, 0.6s

Iter 3 -3416.27619842508, 0.53s

Iter 4 -3343.48414371643, 0.51s

Iter 5 -3334.41619933036, 0.51s

Iter 6 -3334.11537171522, 0.51s

Iter 7 -3332.90904104855, 0.51s

Iter 8 -3330.87432687425, 0.52s

Iter 9 -3329.44503441391, 0.51s

Iter 10 -3329.44503441391, 0.51s

Found 863 normal cells..

Running HMMs on 2 cell groups..

All done!

 ############################################
 ### Done with dataset VUMC17 ###
 ############################################
Time difference of 40.37678 mins

### Samples that did not detect CNVs with default settings

In [14]:
which(names(ruiz) == 'T21-90813_MIMIC006')
which(names(ruiz) == 'T21-91022_MIMIC008')
which(names(ruiz) == 'VU314')

[1] 35

[1] 37

[1] 46

In [14]:
for(i in c(35, 37, 46)) {  # run on the first half of ruiz
    cat(' ############################################\n',
        '### Numbat for dataset number ', names(ruiz[i]), '###\n',
        '############################################\n')
    
    old <- Sys.time() # get start time
    
    file_path <- paste0('/projects/0/einf2548/cruiz/cellranger_output/numbat_pileup_output_cellbender/',
                        names(ruiz[i]),'/',names(ruiz[i]),'_allele_counts.tsv.gz')
    
    if (file.exists(file_path)) {  # check if file exists
        df_allele = fread(file_path)
        df_allele$cell <- paste0(names(ruiz[i]),'_',df_allele$cell)
          
        # run
        out = run_numbat(
            as.matrix(GetAssayData(ruiz[[i]], slot = 'counts', assay = 'RNA')), # gene x cell integer UMI count matrix 
            ref_internal, # reference expression profile, a gene x cell type normalized expression level matrix
            df_allele, # allele dataframe generated by pileup_and_phase script and MUST BE A DATATABLE!
            min_cells = 20,
            t = 1e-3,
            max_iter = 2,
            init_k = 5, # changed this parameter 
            max_entropy = 0.8, # changed this parameter
            ncores = 32,
            ncores_nni = 32,
            multi_allelic = TRUE,
            plot = TRUE,
            genome = "hg38",
            out_dir = paste0('/projects/0/einf2548/cruiz/dmg/notebooks/iCNV/numbat/dmg_atlas_segregated_ref/Ruiz2023/',names(ruiz[i]))
        )
      
        cat(' ############################################\n',
        '### Done with dataset', names(ruiz[i]), '###\n',
        '############################################\n')
        
        # print elapsed time
        new <- Sys.time() - old # calculate difference
        print(new) # print in nice format
    } else {
        cat(' ############################################\n',
        '### Skipping dataset', names(ruiz[i]), 'because the file does not exist ###\n',
        '############################################\n')
    }
}

Iteration 1

Mem used: 29.9Gb

Running HMMs on 9 cell groups..

Expression noise level: medium (0.53).

Running HMMs on 5 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 28.9Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 28.9Gb

No CNV remains after filtering by entropy in single cells. Consider increasing max_entropy.

 ############################################
 ### Done with dataset T21-90813_MIMIC006 ###
 ############################################
Time difference of 7.47044 mins
 ############################################
 ### Numbat for dataset number  T21-91022_MIMIC008 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 5
max_cost = 1831.8
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.8
skip_nj = FALSE
diploid_chroms =
ncores = 32
ncores_nni = 32
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
6106 cells

Mem used: 29.5Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29.5Gb

number of genes left: 12348

running hclust...

Iteration 1

Mem used: 36.6Gb

Running HMMs on 9 cell groups..

Expression noise level: low (0.47).

Running HMMs on 5 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 33Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 33.1Gb

Using 11 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 33.3Gb

Iter 2 -17676.9958088297, 2s

Iter 3 -17652.4245015134, 1.9s

Iter 4 -17638.3947540933, 1.9s

Iter 5 -17628.4576819652, 1.9s

Iter 6 -17622.7243463971, 1.9s

Iter 7 -17619.8920466091, 1.8s

Iter 8 -17618.0603073363, 1.9s

Iter 9 -17617.4187771237, 1.9s

Iter 10 -17617.159810888, 1.9s

Iter 11 -17616.9089752236, 1.9s

Iter 12 -17616.9089752236, 1.9s

Found 5617 normal cells..

Iteration 2

Mem used: 33.3Gb

Running HMMs on 5 cell groups..

Running HMMs on 5 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 32.5Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 32.6Gb

Using 12 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 32.6Gb

Iter 2 -21142.3820754331, 2.2s

Iter 3 -21106.0585665089, 2.1s

Iter 4 -21092.061061832, 2.1s

Iter 5 -21085.60178049, 2.1s

Iter 6 -21085.60178049, 2.1s

Found 5650 normal cells..

Running HMMs on 6 cell groups..

All done!

 ############################################
 ### Done with dataset T21-91022_MIMIC008 ###
 ############################################
Time difference of 53.75608 mins
 ############################################
 ### Numbat for dataset number  VU314 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 5
max_cost = 1239.9
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.8
skip_nj = FALSE
diploid_chroms =
ncores = 32
ncores_nni = 32
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
4133 cells

Mem used: 30Gb

Approximating initial clusters using smoothed expression ..

Mem used: 30Gb

number of genes left: 12488

running hclust...

Iteration 1

Mem used: 33.5Gb

Running HMMs on 9 cell groups..

Expression noise level: medium (0.69).

Running HMMs on 5 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 31.4Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 31.5Gb

No CNV remains after filtering by entropy in single cells. Consider increasing max_entropy.

 ############################################
 ### Done with dataset VU314 ###
 ############################################
Time difference of 17.43709 mins

In [15]:
for(i in c(35, 46)) {  # run on the first half of ruiz
    cat(' ############################################\n',
        '### Numbat for dataset number ', names(ruiz[i]), '###\n',
        '############################################\n')
    
    old <- Sys.time() # get start time
    
    file_path <- paste0('/projects/0/einf2548/cruiz/cellranger_output/numbat_pileup_output_cellbender/',
                        names(ruiz[i]),'/',names(ruiz[i]),'_allele_counts.tsv.gz')
    
    if (file.exists(file_path)) {  # check if file exists
        df_allele = fread(file_path)
        df_allele$cell <- paste0(names(ruiz[i]),'_',df_allele$cell)
          
        # run
        out = run_numbat(
            as.matrix(GetAssayData(ruiz[[i]], slot = 'counts', assay = 'RNA')), # gene x cell integer UMI count matrix 
            ref_internal, # reference expression profile, a gene x cell type normalized expression level matrix
            df_allele, # allele dataframe generated by pileup_and_phase script and MUST BE A DATATABLE!
            min_cells = 20,
            t = 1e-3,
            max_iter = 2,
            init_k = 10, # changed this parameter 
            max_entropy = 1, # changed this parameter
            ncores = 32,
            ncores_nni = 32,
            multi_allelic = TRUE,
            plot = TRUE,
            genome = "hg38",
            out_dir = paste0('/projects/0/einf2548/cruiz/dmg/notebooks/iCNV/numbat/dmg_atlas_segregated_ref/Ruiz2023/',names(ruiz[i]))
        )
      
        cat(' ############################################\n',
        '### Done with dataset', names(ruiz[i]), '###\n',
        '############################################\n')
        
        # print elapsed time
        new <- Sys.time() - old # calculate difference
        print(new) # print in nice format
    } else {
        cat(' ############################################\n',
        '### Skipping dataset', names(ruiz[i]), 'because the file does not exist ###\n',
        '############################################\n')
    }
}

 ############################################
 ### Numbat for dataset number  T21-90813_MIMIC006 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 10
max_cost = 535.5
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 1
skip_nj = FALSE
diploid_chroms =
ncores = 32
ncores_nni = 32
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
1785 cells

Mem used: 29Gb

Approximating initial clusters using smoothed expression ..

Mem used: 29Gb

number of genes left: 12405

running hclust...

Iteration 1

Mem used: 29.9Gb

Running HMMs on 18 cell groups..

Expression noise level: low (0.48).

Running HMMs on 9 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 29.4Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 29.4Gb

Using 2 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 29.5Gb

Iter 2 -1859.17810332883, 0.11s

Iter 3 -1859.07690657709, 0.089s

Iter 4 -1859.0221761469, 0.075s

Iter 5 -1858.97901489792, 0.07s

Iter 6 -1858.87860931392, 0.062s

Iter 7 -1858.70413021874, 0.061s

Iter 8 -1858.66447772449, 0.06s

Iter 9 -1858.63459157024, 0.061s

Iter 10 -1858.6181274127, 0.059s

Iter 11 -1858.6181274127, 0.058s

Found 1656 normal cells..

Iteration 2

Mem used: 29.5Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 28.5Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 28.5Gb

Using 2 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 28.5Gb

Iter 2 -1304.19595944698, 0.11s

Iter 3 -1304.19595944698, 0.084s

Found 1206 normal cells..

Running HMMs on 2 cell groups..

All done!

 ############################################
 ### Done with dataset T21-90813_MIMIC006 ###
 ############################################
Time difference of 15.88219 mins
 ############################################
 ### Numbat for dataset number  VU314 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 10
max_cost = 1239.9
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 1
skip_nj = FALSE
diploid_chroms =
ncores = 32
ncores_nni = 32
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
4133 cells

Mem used: 28.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 28.7Gb

number of genes left: 12488

running hclust...

Iteration 1

Mem used: 33.5Gb

Running HMMs on 19 cell groups..

Expression noise level: medium (0.65).

Running HMMs on 10 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 32.4Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 32.4Gb

Using 2 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 32.5Gb

Iter 2 -3126.05920919892, 0.46s

Iter 3 -3119.68855463027, 0.34s

Iter 4 -3085.50501657217, 0.33s

Iter 5 -3085.50501657217, 0.33s

Found 1452 normal cells..

Iteration 2

Mem used: 32.5Gb

Running HMMs on 2 cell groups..

Running HMMs on 2 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 30.2Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 30.2Gb

Using 3 CNVs to construct phylogeny

All done!

 ############################################
 ### Done with dataset VU314 ###
 ############################################
Time difference of 36.56692 mins