In [1]:
library(numbat)
library(dplyr)
library(Seurat)
library(data.table)
library(future)
plan("multicore", workers = 12)
options(future.globals.maxSize = 10000 * 1024^10,
        future.rng.onMisuse = 'ignore')
sessionInfo()

Loading required package: Matrix


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: SeuratObject

Loading required package: sp


Attaching package: ‘SeuratObject’


The following objects are masked from ‘package:base’:

    intersect, saveRDS


Loading Seurat v5 beta version
To maintain compatibility with previous workflows, new Seurat objects will use the previous object structure by default
To use new Seurat v5 assays: Please run: options(Seurat.object.assay.version = 'v5')


Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last

R version 4.2.3 (2023-03-15)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Rocky Linux 8.7 (Green Obsidian)

Matrix products: default
BLAS/LAPACK: /gpfs/home3/cruiz2/miniconda3/envs/r_python/lib/libopenblasp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] future_1.32.0           data.table_1.14.8       Seurat_4.9.9.9040
[4] SeuratObject_4.9.9.9081 sp_1.6-0                dplyr_1.1.1
[7] numbat_1.2.3            Matrix_1.5-3

loaded via a namespace (and not attached):
  [1] uuid_1.1-0             spam_2.9-1             parallelDist_0.2.6
  [4] fastmatch_1.1-3        plyr_1.8.8             igraph_1.4.1
  [7] repr_1.1.6             lazyeval_0.2.2         splines_4.2.3
 [10] RcppHNSW_0.4.1         listenv_0.9.0          scattermore_0.8
 [13] ggplot2_3.4.1          digest_0.6.31          yulab.utils_0.0.6
 [16] htmltools_0.5.5        viridis_0.6.2          fansi_1.0.4
 [19] magrittr_2.0.3         tensor_1.5             cluster_2.1.4
 [22] ROCR_1.0-11            globals_0.16.2         graphlayouts_0.8.4
 [25] RcppParallel_5.1.7     matrixStats_0.63.0     spatstat.sparse_3.0-1
 [28] colorspace_2.1-0       ggrepel_0.9.3          crayon_1.5.2
 [31] jsonlite_1.8.4         progressr_0.13.0       spatstat.data_3.0-1
 [34] survival_3.5-5         zoo_1.8-11             phangorn_2.11.1
 [37] ape_5.7-1              glue_1.6.2             polyclip_1.10-4
 [40] gtable_0.3.3           leiden_0.4.3           future.apply_1.10.0
 [43] abind_1.4-5            scales_1.2.1           spatstat.random_3.1-4
 [46] miniUI_0.1.1.1         Rcpp_1.0.10            viridisLite_0.4.1
 [49] xtable_1.8-4           gridGraphics_0.5-1     tidytree_0.4.2
 [52] reticulate_1.28        dotCall64_1.0-2        htmlwidgets_1.6.2
 [55] httr_1.4.5             RColorBrewer_1.1-3     ellipsis_0.3.2
 [58] ica_1.0-3              pkgconfig_2.0.3        farver_2.1.1
 [61] uwot_0.1.14            deldir_1.0-6           utf8_1.2.3
 [64] ggplotify_0.1.0        tidyselect_1.2.0       rlang_1.1.0
 [67] reshape2_1.4.4         later_1.3.0            munsell_0.5.0
 [70] tools_4.2.3            cli_3.6.1              generics_0.1.3
 [73] ggridges_0.5.4         evaluate_0.20          stringr_1.5.0
 [76] fastmap_1.1.1          goftest_1.2-3          ggtree_3.6.2
 [79] RhpcBLASctl_0.23-42    fitdistrplus_1.1-8     tidygraph_1.2.3
 [82] purrr_1.0.1            RANN_2.6.1             ggraph_2.1.0
 [85] pbapply_1.7-0          nlme_3.1-162           mime_0.12
 [88] aplot_0.1.10           compiler_4.2.3         plotly_4.10.1
 [91] png_0.1-8              spatstat.utils_3.0-2   treeio_1.22.0
 [94] tibble_3.2.1           tweenr_2.0.2           stringi_1.7.12
 [97] RSpectra_0.16-1        logger_0.2.2           lattice_0.20-45
[100] IRdisplay_1.1          vctrs_0.6.1            pillar_1.9.0
[103] lifecycle_1.0.3        spatstat.geom_3.1-0    lmtest_0.9-40
[106] RcppAnnoy_0.0.20       cowplot_1.1.1          irlba_2.3.5.1
[109] httpuv_1.6.9           patchwork_1.1.2        R6_2.5.1
[112] scistreer_1.1.0        promises_1.2.0.1       KernSmooth_2.23-20
[115] gridExtra_2.3          parallelly_1.35.0      codetools_0.2-19
[118] fastDummies_1.6.3      MASS_7.3-58.3          withr_2.5.0
[121] sctransform_0.3.5      parallel_4.2.3         quadprog_1.5-8
[124] grid_4.2.3             ggfun_0.0.9            IRkernel_1.3.2
[127] tidyr_1.3.0            Rtsne_0.16             pbdZMQ_0.3-9
[130] spatstat.explore_3.1-0 ggforce_0.4.1          shiny_1.7.4
[133] base64enc_0.1-3

In [2]:
dmg <- readRDS('/projects/0/einf2548/cruiz/dmg/data/merged_dmg_atlas_qc_filtered.rds')
dmg

An object of class Seurat
38576 features across 409561 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

In [4]:
dmg$numbat_id <- recode(dmg$predicted.annotation_level_3,
                         `AC-like` = 'Malignant',
                                       `MES-like` = "Malignant",    
                                       `OPC-like` = "Malignant", 
                                       `NPC-like` = "Malignant",    
                                       `Astrocyte` = "Glial_Neuronal", 
                                       # `Oligodendrocyte` = "Glial_Neuronal",    
                                       `OPC` = "Glial_Neuronal", 
                                       `Neuron` = "Glial_Neuronal",
                                        `Mono` = "Myeloid",
                                       `TAM-BDM` = "Myeloid",    
                                       `TAM-MG` = "Myeloid", 
                                       `DC` = "Myeloid",    
                                       `Mast` = "Myeloid",
                                       `CD4/CD8` = "Lymphoid",    
                                       `NK` = "Lymphoid", 
                                       `B cell` = "Lymphoid",    
                                       `Plasma B` = "Lymphoid",
                                       `Endothelial` = "Vascular",    
                                       `Mural cell` = "Vascular"
                         )
Idents(dmg) <- dmg$numbat_id
table(dmg@active.ident)

      Malignant  Glial_Neuronal        Vascular         Myeloid Oligodendrocyte
         231886           78710            7188           60905           25955
       Lymphoid
           4917

In [5]:
`%nin%` <- function(x, y) !(x %in% y)
dmg <- subset(dmg, Study %nin% c('Filbin2018', 'Liu2022'))
dmg
gc()

An object of class Seurat
38576 features across 397794 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

       used        (Mb)    gc trigger  (Mb)     max used    (Mb)
Ncells     8382601   447.7    16414148    876.7    16414148   876.7
Vcells 12653726388 96540.3 16213889217 123702.2 12897181282 98397.7

In [8]:
dmg <- subset(dmg, Batch_for_correction == '10Xv3_cell_rna')
dmg

An object of class Seurat
38576 features across 57305 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

In [9]:
ref_internal = aggregate_counts(GetAssayData(subset(dmg, 
                                                   idents = c('Malignant', 'Glial_Neuronal'),
                                                   invert = TRUE),
                                             slot = 'counts'
                                            ), 
                               as.data.frame(dmg@active.ident) %>% 
                                `colnames<-`('group') %>% 
                                tibble::rownames_to_column('cell') %>%
                                filter(!group %in% c('Malignant', 'Glial_Neuronal'))
                               )
ref_internal

Warning message:
“The `slot` argument of `GetAssayData()` is deprecated as of SeuratObject 5.0.0.
ℹ Please use the `layer` argument instead.”

cell_dict
       Vascular         Myeloid Oligodendrocyte        Lymphoid
            494            9876             274             385

         Vascular     Myeloid      Oligodendrocyte Lymphoid
A1BG     2.026477e-05 3.359908e-06 2.672274e-05    1.608720e-05
A1CF     0.000000e+00 2.181759e-08 0.000000e+00    0.000000e+00
A2M      9.342580e-04 7.911493e-04 1.027798e-05    5.692393e-05
A2ML1    5.196095e-07 3.490814e-07 0.000000e+00    0.000000e+00
A3GALT2  1.039219e-06 1.614501e-06 2.055596e-06    0.000000e+00
A4GALT   2.182360e-05 6.545276e-08 0.000000e+00    0.000000e+00
A4GNT    0.000000e+00 1.527231e-07 0.000000e+00    0.000000e+00
AAAS     9.872581e-06 6.719816e-06 3.288953e-05    3.712430e-06
AACS     1.299024e-05 5.432579e-06 1.233357e-05    1.113729e-05
AADAC    0.000000e+00 6.545276e-08 0.000000e+00    0.000000e+00
AADACL2  0.000000e+00 0.000000e+00 0.000000e+00    0.000000e+00
AADACL3  0.000000e+00 2.181759e-08 0.000000e+00    0.000000e+00
AADACL4  0.000000e+00 0.000000e+00 0.000000e+00    0.000000e+00
AADAT    4.676486e-06 2.181759e-08 2.055596e-06    0.000000e+00
AAGAB    4.052954e-05 1.967946e-05 4.111191e-05    4.083673e-05
AAK1     1.361377e-04 1.387380e-04 2.322823e-04    2.858571e-04
AAMDC    7.378456e-05 2.930102e-05 7.605704e-05    3.341187e-05
AAMP     5.715705e-05 4.260974e-05 3.083393e-05    3.959926e-05
AANAT    5.196095e-07 2.945374e-06 0.000000e+00    2.474953e-06
AAR2     1.818633e-05 1.001427e-05 2.055596e-05    2.474953e-06
AARD     0.000000e+00 4.363517e-08 0.000000e+00    0.000000e+00
AARS     3.585306e-05 3.837713e-05 1.233357e-05    1.979963e-05
AARS2    6.235315e-06 4.188976e-06 1.027798e-05    7.424860e-06
AARSD1   2.805892e-05 1.210876e-05 2.261155e-05    2.474953e-05
AASDH    2.130399e-05 2.321391e-05 3.700072e-05    2.227458e-05
AASDHPPT 4.000993e-05 2.177395e-05 2.466715e-05    3.093692e-05
AASS     5.663744e-05 1.721407e-05 8.839061e-05    1.237477e-06
AATF     3.845111e-05 5.048589e-05 4.727870e-05    8.662337e-05
AATK     3.637267e-06 7.199803e-06 1.027798e-03    0.000000e+00
ABAT     4.676486e-06 1.223967e-05 2.877834e-05    2.969944e-05
⋮        ⋮            ⋮            ⋮               ⋮
ZSCAN26  8.313753e-06 9.643373e-06 3.905632e-05    6.187384e-06
ZSCAN29  6.235315e-06 5.825295e-06 2.466715e-05    1.237477e-06
ZSCAN30  1.870594e-05 1.555594e-05 6.166787e-05    2.474953e-06
ZSCAN31  2.078438e-06 1.723589e-06 2.631162e-04    0.000000e+00
ZSCAN32  5.715705e-06 8.203412e-06 4.111191e-06    9.899814e-06
ZSCAN4   0.000000e+00 0.000000e+00 0.000000e+00    0.000000e+00
ZSCAN5A  1.610790e-05 1.553412e-05 1.438917e-05    3.712430e-06
ZSCAN5B  0.000000e+00 4.363517e-08 2.055596e-06    0.000000e+00
ZSCAN5C  0.000000e+00 0.000000e+00 0.000000e+00    0.000000e+00
ZSCAN9   1.091180e-05 1.339600e-05 1.850036e-05    3.712430e-06
ZSWIM1   5.196095e-07 1.810860e-06 2.055596e-06    2.474953e-06
ZSWIM2   0.000000e+00 2.181759e-08 2.055596e-06    0.000000e+00
ZSWIM3   7.274534e-06 5.650755e-06 8.222383e-06    3.712430e-06
ZSWIM4   1.922555e-05 6.676181e-06 2.055596e-06    1.237477e-06
ZSWIM5   7.586299e-05 1.745407e-07 6.372346e-05    7.424860e-06
ZSWIM6   2.951382e-04 6.544621e-04 8.489610e-04    2.771948e-04
ZSWIM7   3.273540e-05 5.393307e-05 2.672274e-05    1.979963e-05
ZSWIM8   4.416681e-05 2.672654e-05 2.055596e-05    1.732467e-05
ZSWIM9   9.872581e-06 4.603510e-06 8.222383e-06    8.662337e-06
ZUP1     2.286282e-05 3.224639e-05 1.233357e-05    9.899814e-06
ZW10     1.454907e-05 1.069062e-05 2.261155e-05    0.000000e+00
ZWILCH   8.833362e-06 7.963419e-06 2.055596e-06    9.899814e-06
ZWINT    1.299024e-05 9.403379e-06 0.000000e+00    6.187384e-06
ZXDA     1.039219e-06 6.108924e-07 8.222383e-06    2.474953e-06
ZXDB     3.637267e-06 1.527231e-06 2.055596e-06    3.712430e-06
ZXDC     4.364720e-05 6.074016e-05 1.068910e-04    2.846196e-05
ZYG11A   0.000000e+00 1.745407e-07 0.000000e+00    0.000000e+00
ZYG11B   4.832369e-05 3.628264e-05 8.633502e-05    6.187384e-06
ZYX      7.898065e-05 6.132923e-05 2.055596e-06    2.846196e-05
ZZEF1    5.663744e-05 5.201312e-05 8.016823e-05    6.682374e-05

### Process Jessa2022

In [10]:
jessa <- SplitObject(dmg, split.by = 'SampleID')
jessa
gc()

$`P-6117_S-8370_RNA_only`
An object of class Seurat
38576 features across 12688 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-6240_S-8628_RNA_only`
An object of class Seurat
38576 features across 6680 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-6328_S-8672_RNA_only`
An object of class Seurat
38576 features across 13392 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-6337_S-8821_RNA_only`
An object of class Seurat
38576 features across 12318 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-6519_S-9084_RNA_only`
An object of class Seurat
38576 features across 12227 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

       used       (Mb)    gc trigger  (Mb)     max used    (Mb)
Ncells    8138678   434.7    16414148    876.7    16414148    876.7
Vcells 7784315822 59389.7 16213889217 123702.2 14401538685 109875.1

In [11]:
table(dmg$SampleID)

P-6117_S-8370_RNA_only P-6240_S-8628_RNA_only P-6328_S-8672_RNA_only
                 12688                   6680                  13392
P-6337_S-8821_RNA_only P-6519_S-9084_RNA_only
                 12318                  12227

In [12]:
rm(dmg)
gc()

       used       (Mb)    gc trigger  (Mb)     max used    (Mb)
Ncells    8135632   434.5    16414148    876.7    16414148    876.7
Vcells 6971516305 53188.5 16213889217 123702.2 14401538685 109875.1

In [13]:
#check cell name nomenclature to add to numbat pipeline
head(colnames(jessa[[1]]))

[1] "rna_P-6117_S-8370_TGGCCAGCAGCGTAAG-1"
[2] "rna_P-6117_S-8370_CAAGAAACAACTGCTA-1"
[3] "rna_P-6117_S-8370_GCTGCAGCACCATCCT-1"
[4] "rna_P-6117_S-8370_GCGAGAACACTCGACG-1"
[5] "rna_P-6117_S-8370_GCAGCCACAGTGACAG-1"
[6] "rna_P-6117_S-8370_GACCAATTCCCTAATT-1"

In [14]:
length(jessa)

[1] 5

In [15]:
names(jessa) <- gsub('_RNA_only', '', names(jessa))
jessa

$`P-6117_S-8370`
An object of class Seurat
38576 features across 12688 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-6240_S-8628`
An object of class Seurat
38576 features across 6680 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-6328_S-8672`
An object of class Seurat
38576 features across 13392 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-6337_S-8821`
An object of class Seurat
38576 features across 12318 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-6519_S-9084`
An object of class Seurat
38576 features across 12227 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

In [16]:
for(i in 1:length(jessa)) {
    cat(' ############################################\n',
        '### Numbat for dataset number ', names(jessa[i]), '###\n',
        '############################################\n')
    
    old <- Sys.time() # get start time
    
    file_path <- paste0('/projects/0/einf2548/cruiz/dmg/public_data/Jessa2022/EGAD00001008351_sc_sn_RNA/numbat_pileup_output_cellbender/',
                        names(jessa[i]),'/',names(jessa[i]),'_allele_counts.tsv.gz')
    
    if (file.exists(file_path)) {  # check if file exists
        df_allele = fread(file_path)
        df_allele$cell <- paste0('rna_', names(jessa[i]),'_',df_allele$cell)
          
        # run
        out = run_numbat(
            as.matrix(GetAssayData(jessa[[i]], slot = 'counts', assay = 'RNA')), # gene x cell integer UMI count matrix 
            ref_internal, # reference expression profile, a gene x cell type normalized expression level matrix
            df_allele, # allele dataframe generated by pileup_and_phase script and MUST BE A DATATABLE!
            min_cells = 20,
            t = 1e-3,
            max_iter = 2,
            init_k = 3,
            ncores = 40,
            ncores_nni = 40,
            multi_allelic = TRUE,
            plot = TRUE,
            genome = "hg38",
            out_dir = paste0('/projects/0/einf2548/cruiz/dmg/notebooks/iCNV/numbat/dmg_atlas_segregated_ref/Jessa2022/sc/',names(jessa[i]))
        )
      
        cat(' ############################################\n',
        '### Done with dataset', names(jessa[i]), '###\n',
        '############################################\n')
        
        # print elapsed time
        new <- Sys.time() - old # calculate difference
        print(new) # print in nice format
    } else {
        cat(' ############################################\n',
        '### Skipping dataset', names(jessa[i]), 'because the file does not exist ###\n',
        '############################################\n')
    }
}

 ############################################
 ### Numbat for dataset number  P-6117_S-8370 ###
 ############################################

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.8 GiB”
Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 3806.4
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
12688 cells

Mem used: 58.7Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.4 GiB”
Approximating initial clusters using smoothed expression ..

Mem used: 58.7Gb

number of genes left: 11591

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.1 GiB”
running hclust...

Iteration 1

Mem used: 23Gb

Running HMMs on 5 cell groups..

Expression noise level: high (1). Consider using a custom expression reference profile.

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 11.9Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.7 GiB”
All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 12.2Gb

Using 17 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 13Gb

Iter 2 -46050.1988236504, 11s

Iter 3 -45838.2562848947, 11s

Iter 4 -45772.2283427949, 12s

Iter 5 -45430.7725921028, 12s

Iter 6 -45042.106103894, 11s

Iter 7 -45012.5247083857, 11s

Iter 8 -44963.4537543693, 11s

Iter 9 -44945.1327382772, 11s

Iter 10 -44893.8845193242, 11s

Iter 11 -44862.91504611, 11s

Iter 12 -44846.3060856503, 11s

Iter 13 -44827.5508468954, 11s

Iter 14 -44813.8399745833, 11s

Iter 15 -44803.9925187932, 11s

Iter 16 -44791.5634690265, 11s

Iter 17 -44786.9200241546, 10s

Iter 18 -44782.9662961371, 10s

Iter 19 -44779.4187592575, 10s

Iter 20 -44777.8718212451, 10s

Iter 21 -44777.4847948452, 10s

Iter 22 -44761.1109895715, 10s

Iter 23 -44760.8488251686, 10s

Iter 24 -44759.102327865, 10s

Iter 25 -44755.4100439308, 10s

Iter 26 -44755.2270206947, 10s

Iter 27 -44755.2270206947, 10s

Found 196 normal cells..

Iteration 2

Mem used: 13.1Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 13Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.7 GiB”
All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 13.1Gb

Using 17 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 13.1Gb

Iter 2 -43656.7971758545, 10s

Iter 3 -43555.3334726662, 10s

Iter 4 -42857.9067489341, 10s

Iter 5 -42778.3692610849, 10s

Iter 6 -42707.4992438498, 10s

Iter 7 -42635.6229608882, 10s

Iter 8 -42548.8075462298, 9.9s

Iter 9 -42486.2850189845, 10s

Iter 10 -42446.8508016951, 10s

Iter 11 -42420.8046190329, 10s

Iter 12 -42400.574649191, 10s

Iter 13 -42381.94091193, 10s

Iter 14 -42371.0596614263, 10s

Iter 15 -41809.7037938876, 10s

Iter 16 -41798.3571663371, 10s

Iter 17 -41330.8398596995, 10s

Iter 18 -41103.9672205774, 9.8s

Iter 19 -40649.426125139, 9.9s

Iter 20 -40506.4358922212, 9.9s

Iter 21 -40497.3450242002, 10s

Iter 22 -40489.2010079561, 10s

Iter 23 -40481.2940469088, 10s

Iter 24 -40475.7401819618, 10s

Iter 25 -40473.4373781034, 9.8s

Iter 26 -40471.8514893309, 10s

Iter 27 -40471.53611585, 9.9s

Iter 28 -40471.53611585, 10s

Found 196 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset P-6117_S-8370 ###
 ############################################
Time difference of 3.138038 hours
 ############################################
 ### Numbat for dataset number  P-6240_S-8628 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 2004
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
6680 cells

Mem used: 9.07Gb

Approximating initial clusters using smoothed expression ..

Mem used: 9.05Gb

number of genes left: 12048

running hclust...

Iteration 1

Mem used: 16.7Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.9).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 9.76Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 9.77Gb

Using 1 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 9.95Gb

Iter 2 -754.678969062763, 0.56s

Iter 3 -754.678969062763, 0.52s

Found 3825 normal cells..

Iteration 2

Mem used: 9.97Gb

Running HMMs on 2 cell groups..

Running HMMs on 2 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 9.84Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 9.84Gb

Using 1 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 9.84Gb

Iter 2 -896.9088507127, 0.58s

Iter 3 -896.9088507127, 0.52s

Found 3599 normal cells..

Running HMMs on 2 cell groups..

All done!

 ############################################
 ### Done with dataset P-6240_S-8628 ###
 ############################################
Time difference of 1.688322 hours
 ############################################
 ### Numbat for dataset number  P-6328_S-8672 ###
 ############################################

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.9 GiB”
Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 4017.6
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
13392 cells

Mem used: 10.4Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.4 GiB”
Approximating initial clusters using smoothed expression ..

Mem used: 10.4Gb

number of genes left: 11157

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.1 GiB”
running hclust...

Iteration 1

Mem used: 23.3Gb

Running HMMs on 5 cell groups..

Expression noise level: high (1.1). Consider using a custom expression reference profile.

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 13.8Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.8 GiB”
All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 14Gb

Using 1 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 14.7Gb

Iter 2 -43.7852321295941, 2s

Iter 3 -43.7852321295941, 2s

Found 496 normal cells..

Iteration 2

Mem used: 14.8Gb

Running HMMs on 2 cell groups..

Running HMMs on 2 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 13.8Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.8 GiB”
All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 13.9Gb

Using 1 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 13.9Gb

Iter 2 -44.0064878909907, 2.1s

Iter 3 -44.0064878909907, 2s

Found 496 normal cells..

Running HMMs on 2 cell groups..

All done!

 ############################################
 ### Done with dataset P-6328_S-8672 ###
 ############################################
Time difference of 9.51719 hours
 ############################################
 ### Numbat for dataset number  P-6337_S-8821 ###
 ############################################

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.8 GiB”
Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 3695.4
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
12318 cells

Mem used: 10.7Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.3 GiB”
Approximating initial clusters using smoothed expression ..

Mem used: 10.7Gb

number of genes left: 12174

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.1 GiB”
running hclust...

Iteration 1

Mem used: 23.6Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.8).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 13Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.7 GiB”
All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 13.4Gb

Using 9 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 14Gb

Iter 2 -25050.4126964654, 5.5s

Iter 3 -24981.8388535961, 5.5s

Iter 4 -24492.0087263111, 5.4s

Iter 5 -24439.7289353928, 5.5s

Iter 6 -24415.2425262353, 5.5s

Iter 7 -24302.9153356875, 5.5s

Iter 8 -24184.3409292712, 5.5s

Iter 9 -24128.6086459855, 5.5s

Iter 10 -24094.543784312, 5.5s

Iter 11 -24070.4625797427, 5.5s

Iter 12 -24047.9050893684, 5.5s

Iter 13 -24032.5997653953, 5.6s

Iter 14 -24022.4537565183, 5.5s

Iter 15 -24019.5975669604, 5.5s

Iter 16 -24019.309334176, 5.5s

Iter 17 -24019.309334176, 5.4s

Found 3980 normal cells..

Iteration 2

Mem used: 14.1Gb

Running HMMs on 2 cell groups..

Running HMMs on 2 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 13.4Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.7 GiB”
All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 13.6Gb

Using 11 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 13.6Gb

Iter 2 -33997.1603550709, 6.7s

Iter 3 -33273.8137552146, 6.7s

Iter 4 -33232.8264935997, 6.7s

Iter 5 -33206.2385362684, 6.7s

Iter 6 -33186.2054458457, 6.8s

Iter 7 -33126.7756846001, 6.7s

Iter 8 -33121.1466569424, 6.7s

Iter 9 -33116.2990690104, 6.7s

Iter 10 -33111.7977534946, 6.6s

Iter 11 -33107.6711052167, 6.7s

Iter 12 -33103.9991685455, 6.6s

Iter 13 -33100.5417096545, 6.7s

Iter 14 -33037.8944422754, 6.7s

Iter 15 -33036.9732680644, 6.7s

Iter 16 -33036.4070927701, 6.7s

Iter 17 -33035.2169526908, 6.7s

Iter 18 -33034.84463238, 6.7s

Iter 19 -33034.5158640242, 6.7s

Iter 20 -33034.5158640242, 6.6s

Found 3978 normal cells..

Running HMMs on 2 cell groups..

All done!

 ############################################
 ### Done with dataset P-6337_S-8821 ###
 ############################################
Time difference of 2.572544 hours
 ############################################
 ### Numbat for dataset number  P-6519_S-9084 ###
 ############################################

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.8 GiB”
Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 3668.1
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
12227 cells

Mem used: 10.9Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.3 GiB”
Approximating initial clusters using smoothed expression ..

Mem used: 10.9Gb

number of genes left: 11917

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.1 GiB”
running hclust...

Iteration 1

Mem used: 23.5Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.69).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 13.2Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.6 GiB”
All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 13.3Gb

Using 3 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 14Gb

Iter 2 -12837.4375955683, 2.7s

Iter 3 -12837.4375955683, 2.7s

Found 6691 normal cells..

Iteration 2

Mem used: 14Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 13.8Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.6 GiB”
All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 13.8Gb

Using 3 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 13.8Gb

Iter 2 -14801.004979725, 2.7s

Iter 3 -14801.004979725, 2.7s

Found 6800 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset P-6519_S-9084 ###
 ############################################
Time difference of 2.302198 hours