In [ ]:
library(numbat)
library(dplyr)
library(Seurat)
library(data.table)
library(future)
plan("multicore", workers = 12)
options(future.globals.maxSize = 10000 * 1024^10,
        future.rng.onMisuse = 'ignore')
sessionInfo()

Loading required package: Matrix


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: SeuratObject

Loading required package: sp


Attaching package: ‘SeuratObject’


The following objects are masked from ‘package:base’:

    intersect, saveRDS


Loading Seurat v5 beta version
To maintain compatibility with previous workflows, new Seurat objects will use the previous object structure by default
To use new Seurat v5 assays: Please run: options(Seurat.object.assay.version = 'v5')


Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last

R version 4.2.3 (2023-03-15)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Rocky Linux 8.7 (Green Obsidian)

Matrix products: default
BLAS/LAPACK: /gpfs/home3/cruiz2/miniconda3/envs/r_python/lib/libopenblasp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] future_1.32.0           data.table_1.14.8       Seurat_4.9.9.9040
[4] SeuratObject_4.9.9.9081 sp_1.6-0                dplyr_1.1.1
[7] numbat_1.2.3            Matrix_1.5-3

loaded via a namespace (and not attached):
  [1] uuid_1.1-0             spam_2.9-1             parallelDist_0.2.6
  [4] fastmatch_1.1-3        plyr_1.8.8             igraph_1.4.1
  [7] repr_1.1.6             lazyeval_0.2.2         splines_4.2.3
 [10] RcppHNSW_0.4.1         listenv_0.9.0          scattermore_0.8
 [13] ggplot2_3.4.1          digest_0.6.31          yulab.utils_0.0.6
 [16] htmltools_0.5.5        viridis_0.6.2          fansi_1.0.4
 [19] magrittr_2.0.3         tensor_1.5             cluster_2.1.4
 [22] ROCR_1.0-11            globals_0.16.2         graphlayouts_0.8.4
 [25] RcppParallel_5.1.7     matrixStats_0.63.0     spatstat.sparse_3.0-1
 [28] colorspace_2.1-0       ggrepel_0.9.3          crayon_1.5.2
 [31] jsonlite_1.8.4         progressr_0.13.0       spatstat.data_3.0-1
 [34] survival_3.5-5         zoo_1.8-11             phangorn_2.11.1
 [37] ape_5.7-1              glue_1.6.2             polyclip_1.10-4
 [40] gtable_0.3.3           leiden_0.4.3           future.apply_1.10.0
 [43] abind_1.4-5            scales_1.2.1           spatstat.random_3.1-4
 [46] miniUI_0.1.1.1         Rcpp_1.0.10            viridisLite_0.4.1
 [49] xtable_1.8-4           gridGraphics_0.5-1     tidytree_0.4.2
 [52] reticulate_1.28        dotCall64_1.0-2        htmlwidgets_1.6.2
 [55] httr_1.4.5             RColorBrewer_1.1-3     ellipsis_0.3.2
 [58] ica_1.0-3              pkgconfig_2.0.3        farver_2.1.1
 [61] uwot_0.1.14            deldir_1.0-6           utf8_1.2.3
 [64] ggplotify_0.1.0        tidyselect_1.2.0       rlang_1.1.0
 [67] reshape2_1.4.4         later_1.3.0            munsell_0.5.0
 [70] tools_4.2.3            cli_3.6.1              generics_0.1.3
 [73] ggridges_0.5.4         evaluate_0.20          stringr_1.5.0
 [76] fastmap_1.1.1          goftest_1.2-3          ggtree_3.6.2
 [79] RhpcBLASctl_0.23-42    fitdistrplus_1.1-8     tidygraph_1.2.3
 [82] purrr_1.0.1            RANN_2.6.1             ggraph_2.1.0
 [85] pbapply_1.7-0          nlme_3.1-162           mime_0.12
 [88] aplot_0.1.10           compiler_4.2.3         plotly_4.10.1
 [91] png_0.1-8              spatstat.utils_3.0-2   treeio_1.22.0
 [94] tibble_3.2.1           tweenr_2.0.2           stringi_1.7.12
 [97] RSpectra_0.16-1        logger_0.2.2           lattice_0.20-45
[100] IRdisplay_1.1          vctrs_0.6.1            pillar_1.9.0
[103] lifecycle_1.0.3        spatstat.geom_3.1-0    lmtest_0.9-40
[106] RcppAnnoy_0.0.20       cowplot_1.1.1          irlba_2.3.5.1
[109] httpuv_1.6.9           patchwork_1.1.2        R6_2.5.1
[112] scistreer_1.1.0        promises_1.2.0.1       KernSmooth_2.23-20
[115] gridExtra_2.3          parallelly_1.35.0      codetools_0.2-19
[118] fastDummies_1.6.3      MASS_7.3-58.3          withr_2.5.0
[121] sctransform_0.3.5      parallel_4.2.3         quadprog_1.5-8
[124] grid_4.2.3             ggfun_0.0.9            IRkernel_1.3.2
[127] tidyr_1.3.0            Rtsne_0.16             pbdZMQ_0.3-9
[130] spatstat.explore_3.1-0 ggforce_0.4.1          shiny_1.7.4
[133] base64enc_0.1-3

In [ ]:
dmg <- readRDS('/projects/0/einf2548/cruiz/dmg/data/merged_dmg_atlas_qc_filtered.rds')
dmg

An object of class Seurat
38576 features across 409561 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

In [ ]:
dmg$numbat_id <- recode(dmg$predicted.annotation_level_3,
                         `AC-like` = 'Malignant',
                                       `MES-like` = "Malignant",    
                                       `OPC-like` = "Malignant", 
                                       `NPC-like` = "Malignant",    
                                       `Astrocyte` = "Glial_Neuronal", 
                                       # `Oligodendrocyte` = "Glial_Neuronal",    
                                       `OPC` = "Glial_Neuronal", 
                                       `Neuron` = "Glial_Neuronal",
                                        `Mono` = "Myeloid",
                                       `TAM-BDM` = "Myeloid",    
                                       `TAM-MG` = "Myeloid", 
                                       `DC` = "Myeloid",    
                                       `Mast` = "Myeloid",
                                       `CD4/CD8` = "Lymphoid",    
                                       `NK` = "Lymphoid", 
                                       `B cell` = "Lymphoid",    
                                       `Plasma B` = "Lymphoid",
                                       `Endothelial` = "Vascular",    
                                       `Mural cell` = "Vascular"
                         )
Idents(dmg) <- dmg$numbat_id
table(dmg@active.ident)

      Malignant  Glial_Neuronal        Vascular         Myeloid Oligodendrocyte
         231886           78710            7188           60905           25955
       Lymphoid
           4917

In [ ]:
`%nin%` <- function(x, y) !(x %in% y)
dmg <- subset(dmg, Study %nin% c('Filbin2018', 'Liu2022'))
dmg
gc()

An object of class Seurat
38576 features across 397794 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

       used        (Mb)    gc trigger  (Mb)     max used    (Mb)
Ncells     8382606   447.7    16414262    876.7    16414262   876.7
Vcells 12653726388 96540.3 16213889217 123702.2 12897181277 98397.7

In [ ]:
dmg <- subset(dmg, Batch_for_correction == '10Xv1_nuclei_multiome')
dmg

An object of class Seurat
38576 features across 80155 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

In [ ]:
ref_internal = aggregate_counts(GetAssayData(subset(dmg, 
                                                   idents = c('Malignant', 'Glial_Neuronal'),
                                                   invert = TRUE),
                                             slot = 'counts'
                                            ), 
                               as.data.frame(dmg@active.ident) %>% 
                                `colnames<-`('group') %>% 
                                tibble::rownames_to_column('cell') %>%
                                filter(!group %in% c('Malignant', 'Glial_Neuronal'))
                               )
ref_internal

Warning message:
“The `slot` argument of `GetAssayData()` is deprecated as of SeuratObject 5.0.0.
ℹ Please use the `layer` argument instead.”

cell_dict
       Vascular         Myeloid Oligodendrocyte        Lymphoid
            670            7673            6164             570

         Vascular     Myeloid      Oligodendrocyte Lymphoid
A1BG     6.903810e-06 1.908153e-05 2.231141e-05    1.850247e-05
A1CF     0.000000e+00 3.381536e-07 3.203988e-07    0.000000e+00
A2M      1.250926e-03 2.718272e-04 6.495358e-06    4.995666e-05
A2ML1    1.558925e-06 1.352614e-06 5.825433e-07    2.775370e-06
A3GALT2  2.227036e-07 9.178455e-07 3.786532e-07    0.000000e+00
A4GALT   3.251472e-05 9.661532e-07 2.038902e-07    0.000000e+00
A4GNT    2.227036e-07 0.000000e+00 5.825433e-08    0.000000e+00
AAAS     1.046707e-05 7.391072e-06 1.339850e-05    4.625616e-06
AACS     2.449739e-05 1.463722e-05 1.963171e-05    2.220296e-05
AADAC    1.336221e-06 0.000000e+00 0.000000e+00    0.000000e+00
AADACL2  0.000000e+00 9.661532e-08 2.912717e-08    0.000000e+00
AADACL3  0.000000e+00 2.415383e-07 2.912717e-08    0.000000e+00
AADACL4  0.000000e+00 1.449230e-07 1.165087e-07    0.000000e+00
AADAT    3.117850e-06 0.000000e+00 1.284508e-05    0.000000e+00
AAGAB    4.454071e-05 3.574767e-05 1.421406e-05    7.493499e-05
AAK1     3.169072e-04 3.974754e-04 2.505519e-04    7.872799e-04
AAMDC    5.211263e-05 3.328398e-05 6.122530e-05    1.942759e-05
AAMP     1.135788e-05 1.140061e-05 1.750543e-05    1.202660e-05
AANAT    2.227036e-07 1.111076e-06 3.203988e-07    9.251233e-07
AAR2     9.798957e-06 9.516609e-06 1.599081e-05    7.400986e-06
AARD     2.227036e-07 1.932306e-07 2.621445e-07    0.000000e+00
AARS     4.253638e-05 3.623074e-05 8.796404e-05    3.700493e-05
AARS2    6.458403e-06 1.028953e-05 5.155508e-06    3.700493e-06
AARSD1   1.202599e-05 1.164215e-05 8.796404e-06    9.251233e-06
AASDH    2.650172e-05 3.251105e-05 4.232177e-05    2.220296e-05
AASDHPPT 4.142286e-05 3.159321e-05 8.103178e-05    3.885518e-05
AASS     9.286738e-05 8.019071e-06 8.621641e-05    0.000000e+00
AATF     5.055371e-05 7.936948e-05 1.100424e-04    1.017636e-04
AATK     1.358492e-05 2.149691e-05 2.630474e-04    2.775370e-06
ABAT     2.449739e-05 7.753379e-05 3.503998e-05    4.070543e-05
⋮        ⋮            ⋮            ⋮               ⋮
ZSCAN26  1.558925e-05 8.888609e-06 1.823361e-05    5.550740e-06
ZSCAN29  7.571921e-06 1.111076e-05 1.051491e-05    1.017636e-05
ZSCAN30  4.342719e-05 2.526491e-05 4.337035e-05    1.665222e-05
ZSCAN31  2.338387e-05 4.347689e-07 6.486620e-05    2.775370e-06
ZSCAN32  8.908142e-06 7.777533e-06 9.844982e-06    1.387685e-05
ZSCAN4   0.000000e+00 4.830766e-08 5.825433e-08    0.000000e+00
ZSCAN5A  2.895146e-05 3.077198e-05 1.928218e-05    1.110148e-05
ZSCAN5B  2.227036e-07 4.830766e-08 5.825433e-08    0.000000e+00
ZSCAN5C  0.000000e+00 4.830766e-08 0.000000e+00    0.000000e+00
ZSCAN9   8.462735e-06 1.405753e-05 6.844884e-06    7.400986e-06
ZSWIM1   2.449739e-06 2.898460e-06 2.301046e-06    9.251233e-07
ZSWIM2   0.000000e+00 4.830766e-08 0.000000e+00    0.000000e+00
ZSWIM3   8.685439e-06 6.376611e-06 4.747728e-06    4.625616e-06
ZSWIM4   2.961957e-05 9.130148e-06 3.466133e-06    3.700493e-06
ZSWIM5   1.529973e-04 3.381536e-06 1.231205e-04    1.480197e-05
ZSWIM6   5.834833e-04 1.266482e-03 6.630508e-04    3.163922e-04
ZSWIM7   2.338387e-05 4.057843e-05 4.974920e-05    2.867882e-05
ZSWIM8   4.030934e-05 5.043320e-05 3.643808e-05    2.867882e-05
ZSWIM9   1.514384e-05 1.019292e-05 1.307810e-05    1.665222e-05
ZUP1     3.251472e-05 3.676213e-05 2.758343e-05    4.255567e-05
ZW10     1.068977e-05 1.178707e-05 1.473835e-05    1.757734e-05
ZWILCH   6.235700e-06 6.231688e-06 1.805884e-06    1.110148e-05
ZWINT    1.113518e-06 1.642460e-06 2.330173e-07    3.700493e-06
ZXDA     3.117850e-06 1.400922e-06 3.262243e-06    1.850247e-06
ZXDB     3.563257e-06 3.671382e-06 5.330271e-06    4.625616e-06
ZXDC     9.420361e-05 1.184504e-04 1.197418e-04    8.973696e-05
ZYG11A   2.004332e-06 5.796919e-07 3.786532e-07    0.000000e+00
ZYG11B   7.326947e-05 9.265409e-05 6.209912e-05    4.255567e-05
ZYX      3.563257e-05 5.212396e-05 6.262341e-06    3.145419e-05
ZZEF1    8.485006e-05 1.258898e-04 6.635168e-05    1.137902e-04

### Process Jessa2022

In [ ]:
jessa <- SplitObject(dmg, split.by = 'SampleID')
jessa
gc()

$`P-1694_S-1694_Multiome`
An object of class Seurat
38576 features across 5868 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-1701_S-1701_Multiome`
An object of class Seurat
38576 features across 10566 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-1709_S-1709_Multiome`
An object of class Seurat
38576 features across 19292 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-1764_S-1766_Multiome`
An object of class Seurat
38576 features across 6799 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-1779_S-1781_Multiome`
An object of class Seurat
38576 features across 5173 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-1780_S-1780_Multiome`
An object of class Seurat
38576 features across 7868 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-6253_S-8498_Multiome`
An object of class Seurat
38576 features across 3336 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-6337_S-8821_Multiome`
An object of class Seurat
38576 features across 7020 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-6640_S-9581_Multiome`
An object of class Seurat
38576 features across 4657 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-6774_S-10146_Multiome`
An object of class Seurat
38576 features across 9576 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

       used       (Mb)    gc trigger  (Mb)     max used    (Mb)
Ncells    8139363   434.7    16414262    876.7    16414262    876.7
Vcells 8554342137 65264.5 16213889217 123702.2 15238403904 116259.8

In [ ]:
table(dmg$SampleID)

 P-1694_S-1694_Multiome  P-1701_S-1701_Multiome  P-1709_S-1709_Multiome
                   5868                   10566                   19292
 P-1764_S-1766_Multiome  P-1779_S-1781_Multiome  P-1780_S-1780_Multiome
                   6799                    5173                    7868
 P-6253_S-8498_Multiome  P-6337_S-8821_Multiome  P-6640_S-9581_Multiome
                   3336                    7020                    4657
P-6774_S-10146_Multiome
                   9576

In [ ]:
rm(dmg)
gc()

       used       (Mb)    gc trigger  (Mb)     max used    (Mb)
Ncells    8138369   434.7    16414262    876.7    16414262    876.7
Vcells 7357113046 56130.4 16213889217 123702.2 15238403904 116259.8

In [ ]:
#check cell name nomenclature to add to numbat pipeline
head(colnames(jessa[[1]]))

[1] "multiome_P-1694_S-1694_GTTTGTAAGGCTGGCT-1"
[2] "multiome_P-1694_S-1694_GCTCTGGCAAATATCC-1"
[3] "multiome_P-1694_S-1694_CATAACGGTTGACTTC-1"
[4] "multiome_P-1694_S-1694_CACAGGCTCTTGACCC-1"
[5] "multiome_P-1694_S-1694_CCCTCACCAGTATGTT-1"
[6] "multiome_P-1694_S-1694_GCTGTGATCCGCAACA-1"

In [ ]:
length(jessa)

[1] 10

In [ ]:
names(jessa) <- gsub('_Multiome', '', names(jessa))
jessa

$`P-1694_S-1694`
An object of class Seurat
38576 features across 5868 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-1701_S-1701`
An object of class Seurat
38576 features across 10566 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-1709_S-1709`
An object of class Seurat
38576 features across 19292 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-1764_S-1766`
An object of class Seurat
38576 features across 6799 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-1779_S-1781`
An object of class Seurat
38576 features across 5173 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-1780_S-1780`
An object of class Seurat
38576 features across 7868 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-6253_S-8498`
An object of class Seurat
38576 features across 3336 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-6337_S-8821`
An object of class Seurat
38576 features across 7020 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-6640_S-9581`
An object of class Seurat
38576 features across 4657 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

$`P-6774_S-10146`
An object of class Seurat
38576 features across 9576 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

In [ ]:
for(i in 1:length(jessa)) {
    cat(' ############################################\n',
        '### Numbat for dataset number ', names(jessa[i]), '###\n',
        '############################################\n')
    
    old <- Sys.time() # get start time
    
    file_path <- paste0('/projects/0/einf2548/cruiz/dmg/public_data/Jessa2022/EGAD00001008349_multiome/numbat_pileup_output_cellbender/',
                        names(jessa[i]),'/',names(jessa[i]),'_allele_counts.tsv.gz')
    
    if (file.exists(file_path)) {  # check if file exists
        df_allele = fread(file_path)
        df_allele$cell <- paste0('multiome_', names(jessa[i]),'_',df_allele$cell)
          
        # run
        out = run_numbat(
            as.matrix(GetAssayData(jessa[[i]], slot = 'counts', assay = 'RNA')), # gene x cell integer UMI count matrix 
            ref_internal, # reference expression profile, a gene x cell type normalized expression level matrix
            df_allele, # allele dataframe generated by pileup_and_phase script and MUST BE A DATATABLE!
            min_cells = 20,
            t = 1e-3,
            max_iter = 2,
            init_k = 3,
            ncores = 40,
            ncores_nni = 40,
            multi_allelic = TRUE,
            plot = TRUE,
            genome = "hg38",
            out_dir = paste0('/projects/0/einf2548/cruiz/dmg/notebooks/iCNV/numbat/dmg_atlas_segregated_ref/Jessa2022/multiome/',names(jessa[i]))
        )
      
        cat(' ############################################\n',
        '### Done with dataset', names(jessa[i]), '###\n',
        '############################################\n')
        
        # print elapsed time
        new <- Sys.time() - old # calculate difference
        print(new) # print in nice format
    } else {
        cat(' ############################################\n',
        '### Skipping dataset', names(jessa[i]), 'because the file does not exist ###\n',
        '############################################\n')
    }
}

 ############################################
 ### Numbat for dataset number  P-1694_S-1694 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1760.4
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
5868 cells

Mem used: 61Gb

Approximating initial clusters using smoothed expression ..

Mem used: 61Gb

number of genes left: 12085

running hclust...

Iteration 1

Mem used: 19.2Gb

Running HMMs on 5 cell groups..

Expression noise level: low (0.45).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 14.8Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 15Gb

Using 12 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 15.2Gb

Iter 2 -12213.9496032187, 1.5s

Iter 3 -12146.604992731, 1.4s

Iter 4 -12111.1515910238, 1.4s

Iter 5 -12087.7364977483, 1.4s

Iter 6 -12066.3532382314, 1.4s

Iter 7 -12055.0824786675, 1.4s

Iter 8 -12047.2596374481, 1.4s

Iter 9 -12029.3449075864, 1.4s

Iter 10 -12015.9923954203, 1.4s

Iter 11 -12010.4220024041, 1.4s

Iter 12 -12004.8718123112, 1.4s

Iter 13 -12003.7858067745, 1.4s

Iter 14 -11978.9265135702, 1.4s

Iter 15 -11960.9782225905, 1.4s

Iter 16 -11909.3038395579, 1.4s

Iter 17 -11895.7259557843, 1.4s

Iter 18 -11882.5381661162, 1.4s

Iter 19 -11862.4676798275, 1.4s

Iter 20 -11861.4224676751, 1.4s

Iter 21 -11860.5281060614, 1.4s

Iter 22 -11860.5281060614, 1.4s

Found 4780 normal cells..

Iteration 2

Mem used: 15.2Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 15Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 15.1Gb

Using 13 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 15.1Gb

Iter 2 -14299.4944264334, 2.2s

Iter 3 -14259.6331957855, 2s

Iter 4 -14214.8393471408, 1.9s

Iter 5 -14056.9495552403, 1.9s

Iter 6 -14027.2611776574, 1.8s

Iter 7 -14009.1174133947, 1.8s

Iter 8 -13986.571609686, 1.5s

Iter 9 -13980.2278100348, 1.5s

Iter 10 -13967.4437849039, 1.5s

Iter 11 -13962.3343578293, 1.5s

Iter 12 -13961.3543944275, 1.5s

Iter 13 -13960.6735399553, 1.5s

Iter 14 -13960.0210140623, 1.5s

Iter 15 -13960.0210140623, 1.5s

Found 4371 normal cells..

Running HMMs on 5 cell groups..

All done!

 ############################################
 ### Done with dataset P-1694_S-1694 ###
 ############################################
Time difference of 48.11133 mins
 ############################################
 ### Numbat for dataset number  P-1701_S-1701 ###
 ############################################

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.5 GiB”
Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 3169.8
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
10566 cells

Mem used: 14.8Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.1 GiB”
Approximating initial clusters using smoothed expression ..

Mem used: 14.8Gb

number of genes left: 12231

running hclust...

Iteration 1

Mem used: 26Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.79).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 17.6Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.4 GiB”
All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 18Gb

Using 11 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 18.6Gb

Iter 2 -35403.40583317, 5.3s

Iter 3 -35063.2125528723, 5.3s

Iter 4 -34874.0976170315, 5.3s

Iter 5 -34733.3046886055, 5.2s

Iter 6 -34652.2570273534, 5.2s

Iter 7 -34607.418986069, 5.3s

Iter 8 -34583.7138881233, 5.3s

Iter 9 -34551.7498184117, 5.3s

Iter 10 -34530.1852617604, 5.3s

Iter 11 -34452.3258295981, 5.3s

Iter 12 -34150.2599038341, 5.3s

Iter 13 -33916.759631525, 5.3s

Iter 14 -33881.0049874126, 5.3s

Iter 15 -33876.8125693523, 5.3s

Iter 16 -33867.9807690804, 5.3s

Iter 17 -33865.0320876141, 5.3s

Iter 18 -33860.8324991424, 5.3s

Iter 19 -33857.5683447834, 5.3s

Iter 20 -33856.185449657, 5.3s

Iter 21 -33855.4501417686, 5.3s

Iter 22 -33847.6991220949, 5.3s

Iter 23 -33847.6991220949, 5.3s

Found 3623 normal cells..

Iteration 2

Mem used: 18.6Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 18.6Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.4 GiB”
All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 18.7Gb

Using 10 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 18.7Gb

Iter 2 -31459.961582771, 4.9s

Iter 3 -30225.8895630908, 4.8s

Iter 4 -29963.2572002648, 4.8s

Iter 5 -29756.0891634372, 4.8s

Iter 6 -29597.537334605, 4.8s

Iter 7 -28999.164069829, 4.8s

Iter 8 -28904.4476584659, 4.8s

Iter 9 -28845.6790112287, 4.8s

Iter 10 -28356.4916966962, 4.8s

Iter 11 -27743.3604053849, 4.8s

Iter 12 -27679.1852636695, 4.8s

Iter 13 -27645.135234267, 4.8s

Iter 14 -27621.1401433334, 4.8s

Iter 15 -27606.3228627184, 4.7s

Iter 16 -27568.2651531896, 4.6s

Iter 17 -27555.8587807403, 4.7s

Iter 18 -27555.8587807403, 4.7s

Found 3613 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset P-1701_S-1701 ###
 ############################################
Time difference of 2.110663 hours
 ############################################
 ### Numbat for dataset number  P-1709_S-1709 ###
 ############################################

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 2.8 GiB”
Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 5787.6
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
19292 cells

Mem used: 16.2Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 2.0 GiB”
Approximating initial clusters using smoothed expression ..

Mem used: 16.2Gb

number of genes left: 11679

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.7 GiB”
running hclust...

Iteration 1

Mem used: 31.8Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.83).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 18.8Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 2.6 GiB”
All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 19.8Gb

Using 12 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 21.5Gb

Iter 2 -93630.6137546039, 30s

Iter 3 -92788.0466701121, 29s

Iter 4 -92480.5689780593, 29s

Iter 5 -92361.1263919142, 28s

Iter 6 -92242.2583461129, 24s

Iter 7 -92175.753434988, 24s

Iter 8 -92115.0552465527, 24s

Iter 9 -92067.9735323879, 24s

Iter 10 -92049.2575567406, 24s

Iter 11 -92022.1773106077, 24s

Iter 12 -92008.1955026921, 24s

Iter 13 -92000.7902948153, 24s

Iter 14 -91994.5945052091, 24s

Iter 15 -91989.9494876415, 22s

Iter 16 -91938.7872824729, 21s

Iter 17 -91900.2734574516, 21s

Iter 18 -91850.1679319172, 21s

Iter 19 -91813.888755304, 21s

Iter 20 -91811.2398383317, 21s

Iter 21 -91770.1337360392, 21s

Iter 22 -91743.4594912402, 21s

Iter 23 -91740.1780683005, 21s

Iter 24 -91730.4120691909, 21s

Iter 25 -91728.0140416042, 21s

Iter 26 -91727.4567069757, 21s

Iter 27 -91727.4567069757, 21s

Found 434 normal cells..

Iteration 2

Mem used: 21.6Gb

Running HMMs on 5 cell groups..

Running HMMs on 5 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 21.8Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 2.6 GiB”
All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 22.2Gb

Using 11 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 22.2Gb

Iter 2 -64784.8357721753, 23s

Iter 3 -64414.7344067675, 20s

Iter 4 -64198.7543301481, 20s

Iter 5 -64076.465922039, 20s

Iter 6 -63928.6846738052, 20s

Iter 7 -63840.3629428061, 20s

Iter 8 -63756.733650841, 19s

Iter 9 -63695.7917762404, 19s

Iter 10 -63677.5568640221, 20s

Iter 11 -63665.0636788796, 20s

Iter 12 -63654.9895629003, 19s

Iter 13 -63521.5146498109, 20s

Iter 14 -63272.9653457903, 19s

Iter 15 -63162.5658031018, 20s

Iter 16 -63157.1068986188, 20s

Iter 17 -63152.3306480105, 19s

Iter 18 -63148.8023450656, 20s

Iter 19 -63145.5520521714, 19s

Iter 20 -63143.5359450549, 20s

Iter 21 -63019.9545496165, 19s

Iter 22 -63019.9545496165, 20s

Found 465 normal cells..

Running HMMs on 5 cell groups..

All done!

 ############################################
 ### Done with dataset P-1709_S-1709 ###
 ############################################
Time difference of 6.768094 hours
 ############################################
 ### Numbat for dataset number  P-1764_S-1766 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 2039.7
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
6799 cells

Mem used: 13.8Gb

Approximating initial clusters using smoothed expression ..

Mem used: 13.7Gb

number of genes left: 12374

running hclust...

Iteration 1

Mem used: 20.6Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.74).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 15.4Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 15.8Gb

Using 12 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 16Gb

Iter 2 -28887.6928298572, 2.2s

Iter 3 -28820.2603070362, 2.1s

Iter 4 -28795.4509494709, 2.1s

Iter 5 -28776.3381563593, 2.1s

Iter 6 -28308.9281178379, 2.1s

Iter 7 -28273.9339600989, 2.1s

Iter 8 -28258.1155193446, 2.1s

Iter 9 -28208.3676870096, 2.1s

Iter 10 -28180.7374078336, 2.1s

Iter 11 -28172.9111813966, 2.1s

Iter 12 -28165.8156641537, 2.1s

Iter 13 -28160.0663000165, 2.1s

Iter 14 -28156.0751815637, 2.1s

Iter 15 -28152.1494121342, 2.1s

Iter 16 -28144.8170957235, 2.1s

Iter 17 -28135.8083579996, 2.1s

Iter 18 -28132.9167642012, 2.1s

Iter 19 -27947.9002847009, 2s

Iter 20 -27918.8933913853, 2.1s

Iter 21 -27904.4240032344, 2.1s

Iter 22 -27891.5322171377, 2.1s

Iter 23 -27873.468990384, 2.1s

Iter 24 -27873.1812690479, 2.1s

Iter 25 -27873.1812690479, 2.1s

Found 3085 normal cells..

Iteration 2

Mem used: 16Gb

Running HMMs on 4 cell groups..

Running HMMs on 4 cell groups..

Testing for multi-allelic CNVs ..

1 multi-allelic CNVs found: 14b

Evaluating CNV per cell ..

Mem used: 16.1Gb

All cells succeeded

Expanding allelic states..

Building phylogeny ..

Mem used: 16.2Gb

Using 14 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 16.2Gb

Iter 2 -36496.4354734056, 2.6s

Iter 3 -36451.4905531721, 2.5s

Iter 4 -36348.8544865106, 2.4s

Iter 5 -34629.2247701572, 2.4s

Iter 6 -34502.8695267644, 2.4s

Iter 7 -34469.2918378175, 2.4s

Iter 8 -34458.4185934388, 2.4s

Iter 9 -34451.6395969799, 2.5s

Iter 10 -34446.1061203285, 2.4s

Iter 11 -34442.2853613824, 2.4s

Iter 12 -34434.4246670641, 2.4s

Iter 13 -34422.5645161563, 2.4s

Iter 14 -34418.901540075, 2.4s

Iter 15 -34405.0043716045, 2.4s

Iter 16 -34405.0043716045, 2.4s

Found 3135 normal cells..

Running HMMs on 6 cell groups..

All done!

 ############################################
 ### Done with dataset P-1764_S-1766 ###
 ############################################
Time difference of 1.042115 hours
 ############################################
 ### Numbat for dataset number  P-1779_S-1781 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1551.9
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
5173 cells

Mem used: 13.7Gb

Approximating initial clusters using smoothed expression ..

Mem used: 13.7Gb

number of genes left: 12596

running hclust...

Iteration 1

Mem used: 18.1Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.88).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 14Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 14.1Gb

Using 5 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 14.2Gb

Iter 2 -8339.80556897262, 0.93s

Iter 3 -7937.8437729768, 0.81s

Iter 4 -7894.12982085163, 0.8s

Iter 5 -7782.33410592883, 0.77s

Iter 6 -7661.8690494778, 0.74s

Iter 7 -7661.8690494778, 0.69s

Found 3668 normal cells..

Iteration 2

Mem used: 14.2Gb

Running HMMs on 2 cell groups..

Running HMMs on 2 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 13.6Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 13.7Gb

Using 6 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 13.7Gb

Iter 2 -10756.0878787178, 0.93s

Iter 3 -10681.2062393973, 0.74s

Iter 4 -10499.3358759768, 0.74s

Iter 5 -10336.3918578129, 0.73s

Iter 6 -10294.7590878454, 0.73s

Iter 7 -10294.7590878454, 0.73s

Found 3658 normal cells..

Running HMMs on 2 cell groups..

All done!

 ############################################
 ### Done with dataset P-1779_S-1781 ###
 ############################################
Time difference of 39.95414 mins
 ############################################
 ### Numbat for dataset number  P-1780_S-1780 ###
 ############################################

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.1 GiB”
Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 2360.4
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
7868 cells

Mem used: 13.3Gb

Approximating initial clusters using smoothed expression ..

Mem used: 13.3Gb

number of genes left: 12394

running hclust...

Iteration 1

Mem used: 22.3Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.86).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 16.2Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.1 GiB”
All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 16.4Gb

Using 10 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 16.7Gb

Iter 2 -32120.0065360785, 4.8s

Iter 3 -31844.9457517141, 4.2s

Iter 4 -31707.882889085, 4.2s

Iter 5 -31613.4819730226, 3.9s

Iter 6 -31549.8339936434, 3.7s

Iter 7 -31502.1220692868, 3.7s

Iter 8 -31470.7494663863, 3.7s

Iter 9 -31416.1038049129, 3.2s

Iter 10 -31401.4049793983, 3s

Iter 11 -31386.24272194, 3s

Iter 12 -31380.3237547601, 3.3s

Iter 13 -31375.5202576689, 3.3s

Iter 14 -31367.5290292501, 3.3s

Iter 15 -31361.6100620702, 3.3s

Iter 16 -31358.1405183077, 3s

Iter 17 -31358.1405183077, 2.7s

Found 1151 normal cells..

Iteration 2

Mem used: 16.8Gb

Running HMMs on 4 cell groups..

Running HMMs on 4 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 17.1Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.1 GiB”
All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 17.2Gb

Using 11 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 17.2Gb

Iter 2 -42452.0071174962, 3.6s

Iter 3 -42327.2042502646, 3.2s

Iter 4 -42273.4182562376, 3.4s

Iter 5 -42240.3555385934, 3.6s

Iter 6 -42213.7283644734, 3.4s

Iter 7 -42108.6844138141, 3.3s

Iter 8 -42089.1282540949, 3.3s

Iter 9 -42045.2793961092, 3.2s

Iter 10 -42028.5514378319, 3.3s

Iter 11 -42018.615224741, 3.2s

Iter 12 -42011.6366102517, 3.3s

Iter 13 -41983.1183895187, 3.2s

Iter 14 -41976.008242962, 3.2s

Iter 15 -41975.5183379265, 3.3s

Iter 16 -41970.3037256086, 3.2s

Iter 17 -41970.3037256086, 3.2s

Found 1151 normal cells..

Running HMMs on 4 cell groups..

All done!

 ############################################
 ### Done with dataset P-1780_S-1780 ###
 ############################################
Time difference of 1.314717 hours
 ############################################
 ### Numbat for dataset number  P-6253_S-8498 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1000.8
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
3336 cells

Mem used: 13Gb

Approximating initial clusters using smoothed expression ..

Mem used: 13Gb

number of genes left: 12404

running hclust...

Iteration 1

Mem used: 15.4Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.77).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 13.6Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 13.6Gb

Using 4 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 13.7Gb

Iter 2 -3232.00883703686, 0.3s

Iter 3 -3142.41759673255, 0.24s

Iter 4 -3142.41759673255, 0.24s

Found 2313 normal cells..

Iteration 2

Mem used: 13.7Gb

Running HMMs on 3 cell groups..

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 13.2Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 13.3Gb

Using 5 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 13.3Gb

Iter 2 -4078.87141185979, 0.31s

Iter 3 -3955.02312001214, 0.26s

Iter 4 -3792.91830045727, 0.26s

Iter 5 -3767.61926553832, 0.26s

Iter 6 -3756.04279555425, 0.26s

Iter 7 -3744.89202033714, 0.26s

Iter 8 -3744.16493900013, 0.26s

Iter 9 -3742.85873274104, 0.26s

Iter 10 -3742.63275915908, 0.26s

Iter 11 -3742.19409832766, 0.26s

Iter 12 -3741.49693908988, 0.26s

Iter 13 -3741.49693908988, 0.26s

Found 2304 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset P-6253_S-8498 ###
 ############################################
Time difference of 26.02846 mins
 ############################################
 ### Numbat for dataset number  P-6337_S-8821 ###
 ############################################

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.0 GiB”
Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 2106
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
7020 cells

Mem used: 13.2Gb

Approximating initial clusters using smoothed expression ..

Mem used: 13.2Gb

number of genes left: 12066

running hclust...

Iteration 1

Mem used: 20.7Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.96).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 15.6Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 15.9Gb

Using 9 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 16.1Gb

Iter 2 -32335.0971418541, 2.1s

Iter 3 -30540.423543783, 1.8s

Iter 4 -30341.5944086407, 1.8s

Iter 5 -30147.9222750661, 1.8s

Iter 6 -29892.8856211411, 1.9s

Iter 7 -29723.9283291696, 1.8s

Iter 8 -29591.9352312215, 1.8s

Iter 9 -29540.7552490902, 1.8s

Iter 10 -29527.6096956005, 1.8s

Iter 11 -29521.9823368081, 1.8s

Iter 12 -29507.9560041551, 1.8s

Iter 13 -29506.473395616, 1.8s

Iter 14 -29506.473395616, 1.8s

Found 484 normal cells..

Iteration 2

Mem used: 16.2Gb

Running HMMs on 4 cell groups..

Running HMMs on 4 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 16Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 16.1Gb

Using 9 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 16.1Gb

Iter 2 -31037.2750739653, 2.7s

Iter 3 -30478.9439410026, 2.2s

Iter 4 -29883.0941373497, 1.9s

Iter 5 -29617.2530976749, 1.7s

Iter 6 -29560.5758993533, 1.7s

Iter 7 -29500.5738302234, 1.6s

Iter 8 -29471.3153871396, 1.7s

Iter 9 -29443.2563859865, 1.7s

Iter 10 -29419.2562528695, 1.7s

Iter 11 -29401.2345394767, 1.7s

Iter 12 -29391.5395381082, 1.7s

Iter 13 -29382.7472465738, 1.6s

Iter 14 -29355.7248122871, 1.7s

Iter 15 -29311.0000489138, 1.7s

Iter 16 -29304.5784068818, 1.7s

Iter 17 -29236.4294163441, 1.7s

Iter 18 -29231.9251558466, 1.7s

Iter 19 -29227.2438274238, 1.7s

Iter 20 -29225.1406619537, 1.7s

Iter 21 -29217.402288476, 1.7s

Iter 22 -29202.9238885636, 1.7s

Iter 23 -29202.9238885636, 1.7s

Found 505 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset P-6337_S-8821 ###
 ############################################
Time difference of 1.048631 hours
 ############################################
 ### Numbat for dataset number  P-6640_S-9581 ###
 ############################################

Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 1397.1
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
4657 cells

Mem used: 12.9Gb

Approximating initial clusters using smoothed expression ..

Mem used: 12.9Gb

number of genes left: 12027

running hclust...

Iteration 1

Mem used: 17.4Gb

Running HMMs on 5 cell groups..

Expression noise level: high (1). Consider using a custom expression reference profile.

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 14.7Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 14.9Gb

Using 12 CNVs to construct phylogeny

Using NJ tree as seed..

Mem used: 15Gb

Iter 2 -36050.1950270177, 0.95s

Iter 3 -36021.2869259945, 0.87s

Iter 4 -35957.8205899868, 0.86s

Iter 5 -34797.640442512, 0.86s

Iter 6 -34790.1622644005, 0.85s

Iter 7 -34384.2595062122, 0.86s

Iter 8 -34365.6443938575, 0.85s

Iter 9 -34343.3876236936, 0.86s

Iter 10 -34235.2617983666, 0.86s

Iter 11 -34148.5899003701, 0.85s

Iter 12 -34143.905734287, 0.86s

Iter 13 -34139.5065905556, 0.86s

Iter 14 -34040.6718311883, 0.86s

Iter 15 -33710.6807411253, 0.86s

Iter 16 -33705.6895134017, 0.86s

Iter 17 -33701.5835509157, 0.86s

Iter 18 -33697.6283890718, 0.85s

Iter 19 -33694.7716645115, 0.85s

Iter 20 -33692.0864419762, 0.85s

Iter 21 -33689.2302499071, 0.86s

Iter 22 -33686.7374407354, 0.85s

Iter 23 -33680.8826407203, 0.85s

Iter 24 -33664.178509716, 0.86s

Iter 25 -33560.4769870301, 0.86s

Iter 26 -33390.9027252432, 0.85s

Iter 27 -33388.8060939894, 0.86s

Iter 28 -33386.9129307435, 0.86s

Iter 29 -33128.7180381916, 0.86s

Iter 30 -33127.5436677387, 0.86s

Iter 31 -33120.2405546705, 0.86s

Iter 32 -33117.694559076, 0.85s

Iter 33 -33116.4607343182, 0.86s

Iter 34 -33115.4338584595, 0.85s

Iter 35 -32451.1478062592, 0.86s

Iter 36 -32448.1427886186, 0.86s

Iter 37 -32439.964716057, 0.85s

Iter 38 -32438.1441081006, 0.85s

Iter 39 -32421.1811075, 0.85s

Iter 40 -32418.9343481486, 0.85s

Iter 41 -32417.9717444933, 0.87s

Iter 42 -32417.05928083, 0.85s

Iter 43 -32416.3848166307, 0.85s

Iter 44 -32415.8198788236, 0.85s

Iter 45 -32415.2811413194, 0.86s

Iter 46 -32414.8181731547, 0.85s

Iter 47 -32355.6849748108, 0.85s

Iter 48 -32176.9169775823, 0.85s

Iter 49 -31942.6252095467, 0.85s

Iter 50 -31931.7295647723, 0.85s

Iter 51 -31893.1436422753, 0.85s

Iter 52 -31892.0914682874, 0.85s

Iter 53 -31891.6824883367, 0.85s

Iter 54 -31891.3515649676, 0.85s

Iter 55 -31885.8531724814, 0.85s

Iter 56 -31883.6197554808, 0.85s

Iter 57 -31883.2906209595, 0.86s

Iter 58 -31882.9845285083, 0.85s

Iter 59 -31882.7432906146, 0.85s

Iter 60 -31882.5152572442, 0.85s

Iter 61 -31880.7299416722, 0.85s

Iter 62 -31879.96433772, 0.85s

Iter 63 -31879.3305430288, 0.86s

Iter 64 -31879.117555587, 0.85s

Iter 65 -31874.0492257372, 0.86s

Iter 66 -31873.8054000183, 0.86s

Iter 67 -31851.7614991885, 0.85s

Iter 68 -31851.6106712233, 0.85s

Iter 69 -31851.2601609039, 0.85s

Iter 70 -31851.2601609039, 0.85s

Found 61 normal cells..

Iteration 2

Mem used: 15Gb

Running HMMs on 5 cell groups..

Running HMMs on 5 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 15.5Gb

All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 15.6Gb

Using 11 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 15.6Gb

Iter 2 -38281.0757309418, 0.96s

Iter 3 -38090.7540821402, 0.9s

Iter 4 -30221.5218709366, 0.86s

Iter 5 -29438.2187421699, 0.83s

Iter 6 -28647.13039173, 0.81s

Iter 7 -28496.2107688559, 0.81s

Iter 8 -28253.4110364828, 0.81s

Iter 9 -28103.9137695904, 0.8s

Iter 10 -24442.2359369133, 0.79s

Iter 11 -23298.8436235695, 0.79s

Iter 12 -22829.439979698, 0.79s

Iter 13 -22806.6683939204, 0.79s

Iter 14 -22790.8087367241, 0.79s

Iter 15 -22776.2098321284, 0.79s

Iter 16 -22775.9025182708, 0.79s

Iter 17 -22775.9025182708, 0.8s

Found 70 normal cells..

Running HMMs on 5 cell groups..

All done!

 ############################################
 ### Done with dataset P-6640_S-9581 ###
 ############################################
Time difference of 39.21305 mins
 ############################################
 ### Numbat for dataset number  P-6774_S-10146 ###
 ############################################

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.4 GiB”
Numbat version: 1.2.3
Running under parameters:
t = 0.001
alpha = 1e-04
gamma = 20
min_cells = 20
init_k = 3
max_cost = 2872.8
n_cut = 0
max_iter = 2
max_nni = 100
min_depth = 0
use_loh = auto
multi_allelic = TRUE
min_LLR = 5
min_overlap = 0.45
max_entropy = 0.5
skip_nj = FALSE
diploid_chroms =
ncores = 40
ncores_nni = 40
common_diploid = TRUE
tau = 0.3
check_convergence = FALSE
plot = TRUE
genome = hg38
Input metrics:
9576 cells

Mem used: 14.5Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.0 GiB”
Approximating initial clusters using smoothed expression ..

Mem used: 14.5Gb

number of genes left: 11315

running hclust...

Iteration 1

Mem used: 23.7Gb

Running HMMs on 5 cell groups..

Expression noise level: medium (0.96).

Running HMMs on 3 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 16.2Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.3 GiB”
All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 16.8Gb

Using 15 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 17.3Gb

Iter 2 -37448.2594816291, 6.6s

Iter 3 -37230.0190831083, 6.3s

Iter 4 -36438.3887458009, 6.3s

Iter 5 -36192.5953012546, 6.2s

Iter 6 -35982.8429047542, 6.2s

Iter 7 -35797.6326032972, 6.3s

Iter 8 -35650.7659217133, 6.2s

Iter 9 -35508.9201445335, 6.2s

Iter 10 -35451.464454432, 6.2s

Iter 11 -35415.49710612, 6.2s

Iter 12 -35396.447751149, 6.2s

Iter 13 -35376.6145813637, 6.3s

Iter 14 -35344.3992243682, 6.3s

Iter 15 -35333.5578070051, 6.3s

Iter 16 -35325.0242202844, 6.3s

Iter 17 -35316.6284451863, 6.3s

Iter 18 -35312.3768751705, 6.3s

Iter 19 -35308.8439235819, 6.3s

Iter 20 -35305.5349365576, 6.3s

Iter 21 -35301.5844799269, 6.3s

Iter 22 -35298.6793544363, 6.3s

Iter 23 -35297.5145926979, 6.4s

Iter 24 -35295.8662986764, 6.3s

Iter 25 -35295.7561268366, 6.3s

Iter 26 -35294.8705791443, 6.3s

Iter 27 -35294.7970040518, 6.4s

Iter 28 -35294.7970040518, 6.1s

Found 417 normal cells..

Iteration 2

Mem used: 17.3Gb

Running HMMs on 4 cell groups..

Running HMMs on 4 cell groups..

Testing for multi-allelic CNVs ..

0 multi-allelic CNVs found:

Evaluating CNV per cell ..

Mem used: 17.7Gb

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.3 GiB”
All cells succeeded

Expanding allelic states..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

No multi-allelic CNVs, skipping ..

Building phylogeny ..

Mem used: 17.9Gb

Using 12 CNVs to construct phylogeny

Using UPGMA tree as seed..

Mem used: 17.9Gb

Iter 2 -24376.6025532724, 4.9s

Iter 3 -24315.9961618062, 4.3s

Iter 4 -24296.2214123209, 4.3s

Iter 5 -24279.9129225804, 4.3s

Iter 6 -24269.1757463103, 4.3s

Iter 7 -24253.2462195317, 4.3s

Iter 8 -24244.2467341105, 4.3s

Iter 9 -24238.6308883785, 4.3s

Iter 10 -24233.6712259306, 4.2s

Iter 11 -24221.5557473639, 4.2s

Iter 12 -24216.7866351374, 4.1s

Iter 13 -24213.6693029735, 4.2s

Iter 14 -24205.2113674244, 4.1s

Iter 15 -24198.9074531339, 4.1s

Iter 16 -24194.561799537, 4.1s

Iter 17 -24191.4875147907, 4.1s

Iter 18 -24190.3660744963, 4.1s

Iter 19 -24170.4555706241, 4.1s

Iter 20 -24169.8547858509, 4.1s

Iter 21 -24169.6869570974, 4.1s

Iter 22 -24169.6869570974, 4.1s

Found 409 normal cells..

Running HMMs on 3 cell groups..

All done!

 ############################################
 ### Done with dataset P-6774_S-10146 ###
 ############################################
Time difference of 1.922954 hours