`conda activate r_python`

In [13]:
library(tidyverse)
library(Seurat)
library(stringr)
library(tibble)
library(data.table)
library(Matrix)
library(dplyr)
library(future)
library(HGNChelper)
library(BiocParallel)
library(scDblFinder)
library(DoubletFinder)
library(KernSmooth)
library(cluster)
library(parallel)
library(dittoSeq)
library(scCustomize)
library(patchwork)
source("scripts/helper_functions_v1.R")
set.seed(1)
plan("multiprocess", workers = 24)
options(future.globals.maxSize = 1000 * 1024^6)

── Attaching core tidyverse packages ──────────────
✔ dplyr     1.1.0     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.1     ✔ tibble    3.1.8
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1
── Conflicts ───────────── tidyverse_conflicts() ──
✖ lubridate::%within%() masks IRanges::%within%()
✖ dplyr::collapse()     masks IRanges::collapse()
✖ dplyr::combine()      masks Biobase::combine(), BiocGenerics::combine()
✖ dplyr::desc()         masks IRanges::desc()
✖ tidyr::expand()       masks S4Vectors::expand()
✖ dplyr::filter()       masks stats::filter()
✖ dplyr::first()        masks S4Vectors::first()
✖ dplyr::lag()          masks stats::lag()
✖ ggplot2::Position()   masks BiocGenerics::Position(), base::Position()
✖ purrr::reduce()       masks GenomicRanges::reduce(), IRanges::reduce()
✖ dplyr::rename()       masks S4Vectors::rename()
✖ lubridate::second()   masks S4Vectors::second()
✖ lubridate::second<-() masks S4Vectors::second<-()
✖ dplyr::select()       masks biomaRt::select(), AnnotationDbi::select()
✖ dplyr::slice()        masks IRanges::slice()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Attaching SeuratObject


Attaching package: ‘data.table’


The following objects are masked from ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


The following objects are masked from ‘package:dplyr’:

    between, first, last


The following object is masked from ‘package:purrr’:

    transpose


The following object is masked from ‘package:GenomicRanges’:

    shift


The following object is masked from ‘package:IRanges’:

    shift


The following objects are masked from ‘package:S4Vectors’:

    first, second



Attaching package: ‘Matrix’


The following objects are masked from ‘package:tidyr’:

    expand, pack, unpack


The following object is masked from ‘package:S4Vectors’:

    expand


Loading required package: SingleCellExperiment

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘matrixStats’


The following object is masked from ‘package:dplyr’:

    count


The following objects are masked from ‘package:Biobase’:

    anyMissing, rowMedians



Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


The following object is masked from ‘package:Biobase’:

    rowMedians



Attaching package: ‘SummarizedExperiment’


The following object is masked from ‘package:SeuratObject’:

    Assays


The following object is masked from ‘package:Seurat’:

    Assays


KernSmooth 2.23 loaded
Copyright M. P. Wand 1997-2009

scCustomize v1.1.1
If you find the scCustomize useful please cite.
See
'samuel-marsh.github.io/scCustomize/articles/FAQ.html'
for citation info.

In [2]:
meta_cohort <- readxl::read_excel('../data/dmg_atlas_metadata.xlsx',
                                  sheet = "Metadata")
meta_cohort

    Study     Institute Preservation_method ID
1   Ruiz2023  PMC       Cryo                T18-90532
2   Ruiz2023  PMC       Cryo                T19-90171
3   Ruiz2023  PMC       Cryo                T19-91014
4   Ruiz2023  PMC       Cryo                T20-01237
5   Ruiz2023  PMC       NA                  T20-90151
6   Ruiz2023  PMC       Cryo                T20-90239
7   Ruiz2023  PMC       Cryo                T20-90296
8   Ruiz2023  PMC       Cryo                T20-93623
9   Ruiz2023  PMC       Cryo/Snap-frozen    T20-93210
10  Ruiz2023  PMC       Snap-frozen         T20-90372
11  Ruiz2023  PMC       Snap-frozen         T19-90627
12  Ruiz2023  PMC       Snap-frozen         T20-90005
13  Ruiz2023  PMC       Snap-frozen         T19-90673
14  Ruiz2023  PMC       Snap-frozen         T20-93369
15  Ruiz2023  PMC       Snap-frozen         T21-90517
16  Ruiz2023  PMC       Snap-frozen         T21-90581
17  Ruiz2023  PMC       Cryo                T21-90437
18  Ruiz2023  PMC       Snap-frozen         T21-90610
19  Ruiz2023  PMC       Snap-frozen         T21-90868
20  Ruiz2023  PMC       Snap-frozen         T21-91115
21  Ruiz2023  PMC       Snap-frozen         T21-90717
22  Ruiz2023  PMC       Snap-frozen         T21-90789
23  Ruiz2023  PMC       Snap-frozen         T21-90813
24  Ruiz2023  PMC       Snap-frozen         T21-91022
25  Ruiz2023  PMC       Snap-frozen         T21-91074
26  Ruiz2023  PMC       Snap-frozen         T21-91160
27  Ruiz2023  PMC       Snap-frozen         T22-90003
28  Ruiz2023  PMC       Snap-frozen         T22-90066
29  Ruiz2023  PMC       Snap-frozen         T22-90282
30  Ruiz2023  PMC       Snap-frozen         T22-90221
⋮   ⋮         ⋮         ⋮                   ⋮
71  Liu2022   N/A       Snap-frozen         SUDIPG45
72  Liu2022   N/A       Snap-frozen         SUDIPG31
73  Jessa2022 N/A       N/A                 P-6337_S-8821
74  Jessa2022 N/A       N/A                 P-6519_S-9084
75  Jessa2022 N/A       N/A                 P-6640_S-9581
76  Jessa2022 N/A       N/A                 P-6117_S-8370
77  Jessa2022 N/A       N/A                 P-6240_S-8628
78  Jessa2022 N/A       N/A                 P-6251_S-8496
79  Jessa2022 N/A       N/A                 P-1741_S-2756
80  Jessa2022 N/A       N/A                 P-6255_S-8500
81  Jessa2022 N/A       N/A                 P-6253_S-8498
82  Jessa2022 N/A       N/A                 P-1713_S-1713
83  Jessa2022 N/A       N/A                 P-6254_S-8499
84  Jessa2022 N/A       N/A                 P-1780_S-1780
85  Jessa2022 N/A       N/A                 P-2687_S-2688
86  Jessa2022 N/A       N/A                 P-1569_S-1569
87  Jessa2022 N/A       N/A                 P-1764_S-1766
88  Jessa2022 N/A       N/A                 P-1775_S-1775
89  Jessa2022 N/A       N/A                 P-4198_S-4459
90  Jessa2022 N/A       N/A                 P-3407_S-3447
91  Jessa2022 N/A       N/A                 P-6774_S-10146
92  Jessa2022 N/A       N/A                 P-1694_S-1694
93  Jessa2022 N/A       N/A                 P-1709_S-1709
94  Jessa2022 N/A       N/A                 P-1701_S-1701
95  Jessa2022 N/A       N/A                 P-1779_S-1781
96  Jessa2022 N/A       N/A                 P-4504_S-4916
97  Jessa2022 N/A       N/A                 P-6328_S-8672
98  Jessa2022 N/A       N/A                 P-5099_S-6218
99  Jessa2022 N/A       N/A                 P-5613_S-7162
100 Jessa2022 N/A       N/A                 P-3387_S-3411
    Diagnosis                           Tumor_type             Tumor_subtype
1   DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
2   DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
3   DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
4   DMG Spinal                          DMG H3 K27-altered     H3.3 K27-mutant
5   DMG Thalamus                        DMG H3 K27-altered     H3.3 K27-mutant
6   DMG Spinal                          DMG H3 K27-altered     H3.3 K27-mutant
7   DMG Pons                            DMG H3 K27-altered     H3.2 K27-mutant
8   DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
9   DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
10  DMG Cortex                          DMG H3 K27-altered     H3.3 K27-mutant
11  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
12  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
13  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
14  DMG Thalamus                        DMG H3 K27-altered     H3.3 K27-mutant
15  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
16  DMG Thalamus                        DMG H3 K27-altered     H3.1 K27-mutant
17  DMG Thalamus                        DMG H3 K27-altered     H3.3 K27-mutant
18  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
19  DMG Cortex                          DMG H3 K27-altered     H3.3 K27-mutant
20  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
21  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
22  ped HGG Pons, IDH & H3 wildtype     DpHGG H3-wt and IDH-wt H3-wt
23  DMG Thalamus                        DMG H3 K27-altered     H3.3 K27-mutant
24  DMG Pons & Cerebellum               DMG H3 K27-altered     H3.3 K27-mutant
25  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
26  DMG Thalamus                        DpHGG H3-wt and IDH-wt H3-wt
27  ped HGG Thalamus, IDH & H3 wildtype DpHGG H3-wt and IDH-wt H3-wt
28  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
29  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
30  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
⋮   ⋮                                   ⋮                      ⋮
71  DMG pons                            DMG H3 K27-altered     H3.3 K27-mutant
72  DMG pons                            DMG H3 K27-altered     H3.3 K27-mutant
73  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
74  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
75  DMG Thalamus                        DMG H3 K27-altered     H3.3 K27-mutant
76  DMG Thalamus                        DMG H3 K27-altered     H3.3 K27-mutant
77  ped HGG Pons, IDH & H3 wildtype     DpHGG H3-wt and IDH-wt H3-wt
78  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
79  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
80  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
81  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
82  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
83  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
84  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
85  DMG Pons                            DMG H3 K27-altered     H3.2 K27-mutant
86  DMG Cortex                          DMG H3 K27-altered     H3.3 K27-mutant
87  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
88  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
89  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
90  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
91  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
92  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
93  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
94  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
95  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
96  DMG Thalamus                        DMG H3 K27-altered     H3.3 K27-mutant
97  DMG Thalamus                        DMG H3 K27-altered     H3.3 K27-mutant
98  ped HGG Pons, IDH & H3 wildtype     DpHGG H3-wt and IDH-wt H3-wt
99  ped HGG Pons, IDH & H3 wildtype     DpHGG H3-wt and IDH-wt H3-wt
100 ped HGG Pons, IDH & H3 wildtype     DpHGG H3-wt and IDH-wt H3-wt
    Location            Source    Clinical_status    ⋯ PPM1D ACVR1 TSHR BRAF
1   Pons                Autopsy   Recurrence         ⋯ WT    WT    WT   WT
2   Pons                Autopsy   Recurrence         ⋯ WT    WT    WT   WT
3   Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
4   Spinal              Biopsy    Primary            ⋯ WT    WT    WT   WT
5   Thalamus            Biopsy    Recurrence         ⋯ WT    WT    WT   WT
6   Spinal              Biopsy    Recurrence         ⋯ WT    WT    WT   WT
7   Pons                Biopsy    Primary/Recurrence ⋯ WT    M     WT   WT
8   Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
9   Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
10  Cortex              Biopsy    Primary            ⋯ WT    WT    WT   WT
11  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
12  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
13  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
14  Thalamus            Debulking Primary            ⋯ WT    WT    WT   WT
15  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
16  Thalamus            Debulking Primary            ⋯ WT    WT    WT   WT
17  Thalamus            Biopsy    Primary            ⋯ WT    WT    WT   WT
18  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
19  Cortex              Debulking Primary            ⋯ WT    WT    WT   WT
20  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
21  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
22  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
23  Thalamus            Biopsy    Primary            ⋯ WT    WT    WT   WT
24  Pons and cerebellum Biopsy    Primary            ⋯ WT    WT    WT   WT
25  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
26  Thalamus            Biopsy    Primary            ⋯ WT    WT    WT   WT
27  Thalamus            Biopsy    Primary            ⋯ WT    WT    WT   WT
28  Pons                Biopsy    Primary            ⋯ M     WT    WT   WT
29  Pons                Biopsy    Primary            ⋯ M     WT    WT   WT
30  Pons                Biopsy    Primary            ⋯ WT    WT    M    WT
⋮   ⋮                   ⋮         ⋮                  ⋱ ⋮     ⋮     ⋮    ⋮
71  Pons                N/A       Recurrence         ⋯ WT    WT    WT   WT
72  Pons                N/A       Recurrence         ⋯ WT    WT    WT   WT
73  Pons                N/A       N/A                ⋯ N/A   WT    N/A  N/A
74  Pons                N/A       N/A                ⋯ N/A   WT    N/A  N/A
75  Thalamus            N/A       N/A                ⋯ N/A   WT    N/A  N/A
76  Thalamus            N/A       N/A                ⋯ N/A   WT    N/A  M
77  Cortex              N/A       N/A                ⋯ N/A   WT    N/A  N/A
78  Pons                N/A       N/A                ⋯ N/A   M     N/A  N/A
79  Pons                N/A       N/A                ⋯ N/A   M     N/A  N/A
80  Pons                N/A       N/A                ⋯ N/A   WT    N/A  N/A
81  Pons                N/A       N/A                ⋯ N/A   M     N/A  N/A
82  Pons                N/A       N/A                ⋯ N/A   M     N/A  N/A
83  Pons                N/A       N/A                ⋯ N/A   M     N/A  N/A
84  Pons                N/A       N/A                ⋯ N/A   N/A   N/A  N/A
85  Pons                N/A       N/A                ⋯ N/A   M     N/A  N/A
86  Cortex              N/A       N/A                ⋯ N/A   WT    N/A  N/A
87  Pons                N/A       N/A                ⋯ N/A   WT    N/A  N/A
88  Pons                N/A       N/A                ⋯ N/A   WT    N/A  N/A
89  Pons                N/A       N/A                ⋯ N/A   WT    N/A  N/A
90  Pons                N/A       N/A                ⋯ N/A   WT    N/A  N/A
91  Pons                N/A       N/A                ⋯ N/A   WT    N/A  N/A
92  Pons                N/A       N/A                ⋯ N/A   N/A   N/A  N/A
93  Pons                N/A       N/A                ⋯ N/A   WT    N/A  M
94  Pons                N/A       N/A                ⋯ N/A   M     N/A  N/A
95  Pons                N/A       N/A                ⋯ N/A   N/A   N/A  N/A
96  Thalamus            N/A       N/A                ⋯ N/A   WT    N/A  N/A
97  Thalamus            N/A       N/A                ⋯ N/A   WT    N/A  N/A
98  Cortex              N/A       N/A                ⋯ N/A   WT    N/A  N/A
99  Cortex              N/A       N/A                ⋯ N/A   WT    N/A  N/A
100 Cortex              N/A       N/A                ⋯ N/A   WT    N/A  N/A
    GNAQ LMNA KIT ARID1A KRAS Other
1   WT   WT   WT  WT     WT   N/A
2   WT   WT   WT  WT     WT   N/A
3   WT   WT   WT  WT     WT   N/A
4   WT   WT   WT  WT     WT   N/A
5   WT   WT   WT  WT     WT   N/A
6   WT   WT   WT  WT     WT   N/A
7   WT   WT   WT  WT     WT   FGFR3 overexpression; TP53 inactivation
8   WT   WT   WT  WT     WT   RGMA-ERAS fusion
9   WT   WT   WT  WT     WT   N/A
10  WT   WT   WT  WT     WT   N/A
11  WT   WT   WT  WT     WT   N/A
12  WT   WT   WT  WT     WT   N/A
13  WT   WT   WT  WT     WT   CHIC2-PDGFRA fusion
14  WT   WT   WT  WT     WT   N/A
15  WT   WT   WT  WT     WT   N/A
16  WT   WT   WT  WT     WT   N/A
17  WT   WT   WT  WT     WT   N/A
18  WT   WT   WT  WT     WT   N/A
19  WT   WT   WT  WT     WT   N/A
20  WT   WT   WT  WT     WT   N/A
21  WT   WT   WT  WT     WT   N/A
22  WT   WT   WT  WT     WT   EGFR-MYC amplification
23  WT   WT   WT  WT     WT   N/A
24  WT   WT   WT  WT     WT   N/A
25  WT   WT   WT  WT     WT   N/A
26  WT   WT   WT  WT     WT   N/A
27  WT   WT   WT  WT     WT   N/A
28  WT   WT   WT  WT     WT   N/A
29  WT   WT   WT  WT     WT   N/A
30  WT   WT   WT  WT     WT   N/A
⋮   ⋮    ⋮    ⋮   ⋮      ⋮    ⋮
71  WT   WT   WT  WT     WT   N/A
72  WT   WT   WT  WT     WT   N/A
73  N/A  N/A  N/A N/A    N/A  N/A
74  N/A  N/A  N/A N/A    N/A  N/A
75  N/A  N/A  N/A N/A    N/A  N/A
76  N/A  N/A  N/A N/A    N/A  N/A
77  N/A  N/A  N/A N/A    N/A  N/A
78  N/A  N/A  N/A N/A    N/A  N/A
79  N/A  N/A  N/A N/A    N/A  N/A
80  N/A  N/A  N/A N/A    N/A  N/A
81  N/A  N/A  N/A N/A    N/A  N/A
82  N/A  N/A  N/A N/A    N/A  N/A
83  N/A  N/A  N/A N/A    N/A  N/A
84  N/A  N/A  N/A N/A    N/A  N/A
85  N/A  N/A  N/A N/A    N/A  N/A
86  N/A  N/A  N/A N/A    N/A  N/A
87  N/A  N/A  N/A N/A    N/A  N/A
88  N/A  N/A  N/A N/A    N/A  N/A
89  N/A  N/A  N/A N/A    N/A  N/A
90  N/A  N/A  N/A N/A    N/A  N/A
91  N/A  N/A  N/A N/A    N/A  N/A
92  N/A  N/A  N/A N/A    N/A  N/A
93  N/A  N/A  N/A N/A    N/A  N/A
94  N/A  N/A  N/A N/A    N/A  N/A
95  N/A  N/A  N/A N/A    N/A  N/A
96  N/A  N/A  N/A N/A    N/A  N/A
97  N/A  N/A  N/A N/A    N/A  N/A
98  N/A  N/A  N/A N/A    N/A  PDGFRA-FIP1L1 fusion
99  N/A  N/A  N/A N/A    N/A  N/A
100 N/A  N/A  N/A N/A    N/A  N/A

### Filbin2018

DOI: 10.1126/science.aao4750

##### Read TPM normalized matrices

In [3]:
counts <- as.matrix(fread(paste0('/hpc/pmc_stunnenberg/cruiz/scRNA/',
             'markers-and-databases/dmg/Filbin2018/',
             'K27Mproject.RSEM.vh20170621.txt'),
                             blank.lines.skip=FALSE) %>% column_to_rownames('Gene'))

gene.names <- checkGeneSymbols(rownames(counts), unmapped.as.na=FALSE)
gene.names
rownames(counts) <- make.unique(gene.names$Suggested.Symbol)

counts

Maps last updated on: Thu Oct 24 12:31:05 2019

Warning message in checkGeneSymbols(rownames(counts), unmapped.as.na = FALSE):
“Human gene symbols should be all upper-case except for the 'orf' in open reading frames. The case of some letters was corrected.”
Warning message in checkGeneSymbols(rownames(counts), unmapped.as.na = FALSE):
“x contains non-approved gene symbols”

      x          Approved Suggested.Symbol
1     A1BG        TRUE    A1BG
2     A1BG-AS1    TRUE    A1BG-AS1
3     A1CF        TRUE    A1CF
4     A2M         TRUE    A2M
5     A2M-AS1     TRUE    A2M-AS1
6     A2ML1       TRUE    A2ML1
7     A2MP1       TRUE    A2MP1
8     A4GALT      TRUE    A4GALT
9     A4GNT       TRUE    A4GNT
10    AA06       FALSE    AA06
11    AAAS        TRUE    AAAS
12    AACS        TRUE    AACS
13    AACSP1      TRUE    AACSP1
14    AADAC       TRUE    AADAC
15    AADACL2     TRUE    AADACL2
16    AADACL3     TRUE    AADACL3
17    AADACL4     TRUE    AADACL4
18    AADAT       TRUE    AADAT
19    AAED1      FALSE    PRXL2C
20    AAGAB       TRUE    AAGAB
21    AAK1        TRUE    AAK1
22    AAMDC       TRUE    AAMDC
23    AAMP        TRUE    AAMP
24    AANAT       TRUE    AANAT
25    AAR2        TRUE    AAR2
26    AARD        TRUE    AARD
27    AARS       FALSE    AARS1
28    AARS2       TRUE    AARS2
29    AARSD1      TRUE    AARSD1
30    AASDH       TRUE    AASDH
⋮     ⋮          ⋮        ⋮
23657 ZSCAN26     TRUE    ZSCAN26
23658 ZSCAN29     TRUE    ZSCAN29
23659 ZSCAN30     TRUE    ZSCAN30
23660 ZSCAN31     TRUE    ZSCAN31
23661 ZSCAN32     TRUE    ZSCAN32
23662 ZSCAN4      TRUE    ZSCAN4
23663 ZSCAN5A     TRUE    ZSCAN5A
23664 ZSCAN5B     TRUE    ZSCAN5B
23665 ZSCAN9      TRUE    ZSCAN9
23666 ZSWIM1      TRUE    ZSWIM1
23667 ZSWIM2      TRUE    ZSWIM2
23668 ZSWIM3      TRUE    ZSWIM3
23669 ZSWIM4      TRUE    ZSWIM4
23670 ZSWIM5      TRUE    ZSWIM5
23671 ZSWIM6      TRUE    ZSWIM6
23672 ZSWIM7      TRUE    ZSWIM7
23673 ZSWIM8      TRUE    ZSWIM8
23674 ZSWIM8-AS1  TRUE    ZSWIM8-AS1
23675 ZUFSP      FALSE    ZUP1
23676 ZW10        TRUE    ZW10
23677 ZWILCH      TRUE    ZWILCH
23678 ZWINT       TRUE    ZWINT
23679 ZXDA        TRUE    ZXDA
23680 ZXDB        TRUE    ZXDB
23681 ZXDC        TRUE    ZXDC
23682 ZYG11A      TRUE    ZYG11A
23683 ZYG11B      TRUE    ZYG11B
23684 ZYX         TRUE    ZYX
23685 ZZEF1       TRUE    ZZEF1
23686 ZZZ3        TRUE    ZZZ3

           MUV1-P04-B12 MUV1-P04-C08 MUV1-P04-D09 MUV1-P04-D10 MUV1-P04-E03
A1BG         0.00         0.00         0.00         0.00         0.00
A1BG-AS1     0.00         0.00         0.00         0.00         0.00
A1CF         0.00         0.00         0.00         0.00         0.00
A2M          0.00         0.00         0.00         0.00       348.48
A2M-AS1      0.00         0.00         0.00         0.00         0.00
A2ML1        0.00         0.92         0.00         0.00         1.25
A2MP1        0.00         0.00         0.00         0.00         0.00
A4GALT       0.00         0.00         0.00         0.00         0.00
A4GNT        0.00         0.00         0.00         0.00         0.00
AA06         0.00         0.00         0.00         0.00         0.00
AAAS         0.00         0.00         0.00       454.66        55.59
AACS         0.00         0.00       599.81         0.00         0.00
AACSP1       0.00         0.00         0.00         0.00         0.00
AADAC        0.00         0.00         0.00         0.00         0.00
AADACL2      0.00         0.00         0.00         0.00         0.00
AADACL3      0.00         0.00         0.00         0.00         0.00
AADACL4      0.00         0.00         0.00         0.00         0.00
AADAT        0.00         0.00         0.00         0.00         0.00
PRXL2C       0.00         0.00         0.00         0.00         0.00
AAGAB        0.00         0.00         0.00         0.00         0.00
AAK1        17.78         0.23         4.64         6.31         1.10
AAMDC        0.00         0.00         0.00         0.00         0.00
AAMP         0.00         0.00         0.00         0.00       420.89
AANAT        0.00         0.00         0.00         0.00         0.00
AAR2         0.00         0.00       777.52         0.00         0.00
AARD         3.69         0.00        14.81         8.80         2.80
AARS1        0.00         0.00       285.45       391.38       488.38
AARS2      176.15         4.98         6.46         5.22         4.94
AARSD1     105.33         0.00         0.00         0.00         0.00
AASDH        1.68       157.80         0.00         9.14         0.00
⋮          ⋮            ⋮            ⋮            ⋮            ⋮
ZSCAN26     0.00          0.00          7.68       55.18         0.00
ZSCAN29     0.00          2.12          7.06        3.01         0.00
ZSCAN30     0.00          0.00          0.00        0.00         0.00
ZSCAN31     0.00          0.00          0.00        0.00         0.00
ZSCAN32     0.00          0.00          0.00        0.00         0.00
ZSCAN4      0.00          0.00          0.00        0.00         2.15
ZSCAN5A     0.00          0.00          0.00        0.00         0.00
ZSCAN5B     0.00          0.00          0.00        0.00         0.00
ZSCAN9      0.00          0.00          0.00        0.00         0.00
ZSWIM1      4.35          0.00         26.48        3.93        55.28
ZSWIM2      0.00          0.00          0.00        0.00         0.00
ZSWIM3      0.00          0.00          0.00        0.00         0.00
ZSWIM4      0.00          0.00          0.00        0.00         0.00
ZSWIM5      0.00          0.00          0.00        0.00        83.93
ZSWIM6      0.00          0.00        329.06        0.00         0.00
ZSWIM7     13.08          0.00          6.83        5.84         0.00
ZSWIM8      0.00          0.00         50.84        0.00        24.51
ZSWIM8-AS1  0.00          0.00         32.90        0.00         0.00
ZUP1        0.00          0.00       1717.18        0.00         0.00
ZW10        0.00          0.00          0.00        7.39         0.00
ZWILCH      0.00          0.00          0.00        0.00         0.00
ZWINT       0.00        608.62          0.00        0.00         0.00
ZXDA        0.00          0.00          0.00        0.00         0.00
ZXDB        0.00         75.78          0.00        0.00         0.00
ZXDC       14.42          0.62          7.91       28.95         3.90
ZYG11A      0.00          0.93         11.51        2.69         6.24
ZYG11B     40.65          1.77        124.90        1.43       120.83
ZYX        63.27        556.98          0.00        0.00         6.27
ZZEF1       0.00          0.00        283.93      173.14        38.58
ZZZ3        0.00          0.00          0.00        3.75         5.48
           MUV1-P04-E07 MUV1-P04-E08 MUV1-P04-E10 MUV1-P04-E11 MUV1-P04-F05 ⋯
A1BG         0.00         0.00         0.00         0.00        0.00        ⋯
A1BG-AS1     0.00         0.00         0.00         0.00        0.00        ⋯
A1CF         0.00         0.53         0.34         0.00        0.00        ⋯
A2M        362.08         0.00         0.00         0.00       27.17        ⋯
A2M-AS1      1.19         0.00         0.00         0.00        0.00        ⋯
A2ML1        0.33         0.00         0.85         4.19        0.00        ⋯
A2MP1        0.00         0.00         0.00         0.00        0.00        ⋯
A4GALT      29.25         0.00         0.00         0.00        0.00        ⋯
A4GNT        0.00         0.00         0.00         0.00        0.00        ⋯
AA06         0.00         0.00         0.00         0.00        0.00        ⋯
AAAS         0.00       198.42       361.59         0.00        0.00        ⋯
AACS         0.00         0.00         0.00         0.00       27.36        ⋯
AACSP1       0.00         0.00         0.00         0.00        0.00        ⋯
AADAC        0.00         0.00         0.00         0.00        0.00        ⋯
AADACL2      0.00         0.00         0.00         0.00        0.00        ⋯
AADACL3      0.00         0.00         0.00         0.00        0.00        ⋯
AADACL4      0.00         0.00         0.00         0.00        0.00        ⋯
AADAT        0.00         0.00         0.00         0.00        0.00        ⋯
PRXL2C       0.00         0.00         0.00         0.00        0.00        ⋯
AAGAB        1.18         0.00         0.00         0.00        0.00        ⋯
AAK1         1.16        28.43         2.08        54.99        5.13        ⋯
AAMDC        0.00       442.61         0.00         0.00        0.00        ⋯
AAMP       292.52         0.00       487.77       603.65        0.00        ⋯
AANAT        0.00         0.00         0.00         0.00        0.00        ⋯
AAR2         0.00         0.00         0.00         0.00        0.00        ⋯
AARD         4.50         0.00         1.87        57.08       10.42        ⋯
AARS1        0.00         0.00       294.85       540.20        0.00        ⋯
AARS2        0.83         2.52         3.37        12.97       16.42        ⋯
AARSD1      26.55         0.00         0.00         0.00        0.00        ⋯
AASDH        0.00        57.31       101.77         0.00        0.00        ⋯
⋮          ⋮            ⋮            ⋮            ⋮            ⋮            ⋱
ZSCAN26     22.72       482.89         0.00       379.93         0.00       ⋯
ZSCAN29      1.68         3.08         1.31        16.38       223.32       ⋯
ZSCAN30      0.00         0.00         0.00         0.00         0.00       ⋯
ZSCAN31      0.00         0.00         0.00         0.00         0.00       ⋯
ZSCAN32      0.00         0.00         0.00         0.00         0.00       ⋯
ZSCAN4       0.51         0.00         0.00         0.00         0.00       ⋯
ZSCAN5A      0.00         0.00         0.00         0.00         0.00       ⋯
ZSCAN5B      0.00         0.00         0.00         0.00         0.00       ⋯
ZSCAN9       0.00         0.00         0.00         0.00         0.00       ⋯
ZSWIM1       4.86        14.21         1.16        69.58        16.01       ⋯
ZSWIM2       0.00         0.00         0.00         0.00         0.00       ⋯
ZSWIM3       0.00       401.23         0.00         0.00         0.00       ⋯
ZSWIM4       1.11        40.02         0.00         0.00         0.00       ⋯
ZSWIM5       0.00         0.00         0.00         0.00         0.00       ⋯
ZSWIM6       0.22       238.19        12.15        47.28       916.71       ⋯
ZSWIM7       0.49         2.73         0.00        13.53         4.62       ⋯
ZSWIM8      19.98         2.49         0.00         0.00         0.00       ⋯
ZSWIM8-AS1   6.55         0.00         0.00         0.00         0.00       ⋯
ZUP1         0.00         0.00         0.00        19.54         0.00       ⋯
ZW10         0.00         0.00         0.00         0.00       426.48       ⋯
ZWILCH     123.19         0.00         0.00        97.92         0.00       ⋯
ZWINT      136.19         0.00         0.00         0.00         0.00       ⋯
ZXDA         0.00         0.00         0.00         2.33         0.00       ⋯
ZXDB         0.00         0.00         0.00         0.00         0.00       ⋯
ZXDC         1.69         2.18       153.69        56.93         4.43       ⋯
ZYG11A      33.41         3.04         3.04        21.36        10.89       ⋯
ZYG11B      22.66       143.31         2.43        23.37        72.72       ⋯
ZYX         33.87         0.00         0.00         2.67         0.00       ⋯
ZZEF1        5.43         0.00         0.00        43.78         0.00       ⋯
ZZZ3         0.00       267.43         0.00         0.00         0.00       ⋯
           Oligo-P22-G05 Oligo-P22-G07 Oligo-P22-G11 Oligo-P22-G12
A1BG         0.00        132.26          0.00          0.00
A1BG-AS1     0.00          0.00          0.00          0.00
A1CF         0.00          0.65          0.00          0.00
A2M          0.00          0.00          0.00          0.00
A2M-AS1      0.00          0.00          0.00          0.00
A2ML1        0.00          0.00          0.00          0.00
A2MP1        0.00          0.00          0.00          0.00
A4GALT       0.00          0.00          0.00          0.00
A4GNT        0.00          0.00          0.00          0.00
AA06         0.00          0.00          0.00          0.00
AAAS       388.43          0.00          0.00          0.00
AACS         1.55        142.53        378.65          0.00
AACSP1       0.00          0.00          0.00          0.00
AADAC        0.00          0.00          0.00          0.00
AADACL2      0.00          0.00          0.00          0.00
AADACL3      0.00          0.00          0.00          0.00
AADACL4      0.00          0.00          0.00          0.00
AADAT        9.85          0.00          0.00          0.00
PRXL2C       0.00          0.00          0.00          0.00
AAGAB        0.00          0.00          0.00          0.00
AAK1        35.30         44.35          4.35          2.65
AAMDC        0.00          0.00          0.00        209.41
AAMP         0.00          0.00        250.46        314.53
AANAT        0.00          0.00          0.00          0.00
AAR2       470.68          0.00          0.00          0.00
AARD         5.85          0.00          3.18          0.00
AARS1        4.62          0.00          0.00        304.86
AARS2        3.25          0.00          2.16          3.28
AARSD1       0.00          0.00          0.00          0.00
AASDH        0.00          0.00          0.00          0.00
⋮          ⋮             ⋮             ⋮             ⋮
ZSCAN26      0.00          0.00         56.17          0.00
ZSCAN29      5.14          3.23          1.04          3.02
ZSCAN30      0.00         49.84          0.00          0.00
ZSCAN31      0.00          0.00          0.00          0.00
ZSCAN32      0.00          0.00        354.73          0.00
ZSCAN4       0.00          0.00          0.00          0.00
ZSCAN5A      0.00          0.00          0.00          0.00
ZSCAN5B      0.00          0.00          0.00          0.00
ZSCAN9       0.00          0.00          0.00          0.00
ZSWIM1     105.71        138.23          4.12          4.82
ZSWIM2       0.00          0.00          0.00          0.00
ZSWIM3       0.00          0.00          0.00          0.00
ZSWIM4       0.00          0.00          0.00          0.00
ZSWIM5       0.00          0.00          0.00          0.00
ZSWIM6      62.46          0.00         74.66          1.41
ZSWIM7       2.78          9.87          0.00        129.34
ZSWIM8       0.00          1.01          0.00          0.00
ZSWIM8-AS1   0.00          0.00          0.00          0.00
ZUP1        84.48          0.00          0.00          0.00
ZW10         0.00          0.00          0.00          0.00
ZWILCH       0.00          0.00          0.00          0.00
ZWINT        0.00          0.00          0.00          0.00
ZXDA         0.00          0.00          0.00          0.00
ZXDB         0.00        204.23          0.00          0.00
ZXDC         2.21         10.29         19.05         24.79
ZYG11A       1.40          0.00          1.35          7.97
ZYG11B       1.66          3.71          5.40          3.10
ZYX         11.25        309.60         49.03          0.00
ZZEF1       12.11          0.00          0.00         67.26
ZZZ3         0.00          0.00         23.30          0.00
           Oligo-P22-H02 Oligo-P22-H03 Oligo-P22-H05 Oligo-P22-H06
A1BG         0.00          0.00          0.00          0.00
A1BG-AS1     0.00          0.00          0.00          0.00
A1CF         0.00          0.00          0.00          0.00
A2M          0.00          0.00          0.00          0.00
A2M-AS1      0.00          0.00          0.00          0.00
A2ML1        0.00          0.00          5.88          0.00
A2MP1        0.00          0.00          0.00          0.00
A4GALT       0.00          0.00          0.00          0.00
A4GNT        0.00          0.00          0.00          0.00
AA06         0.00          0.00          0.00          0.00
AAAS         0.00          0.00          0.00        193.91
AACS         0.00          0.00          0.00          0.00
AACSP1       0.00          0.00          0.00          0.00
AADAC        0.00          0.00          0.00          0.00
AADACL2      0.00          0.00          0.00          0.00
AADACL3      0.00          0.00          0.00          0.00
AADACL4      0.00          0.00          0.00          0.00
AADAT        0.00          0.00          0.00          0.00
PRXL2C       0.00          0.00          0.00          0.00
AAGAB        0.00         70.98          0.00          0.00
AAK1         2.35          9.43          0.00          0.00
AAMDC      233.60          0.00        432.00          0.00
AAMP         0.00         10.06          0.00         62.59
AANAT        0.00          0.00          0.00          0.00
AAR2         0.00        107.95          0.00        134.21
AARD         0.00          0.00          0.00          0.00
AARS1      217.61         19.96          0.00        198.36
AARS2        2.09        150.64          4.65          0.00
AARSD1       0.00        150.17          0.00          0.00
AASDH        0.00          0.00          0.00          0.00
⋮          ⋮             ⋮             ⋮             ⋮
ZSCAN26     92.67          0.00        0.00           23.07
ZSCAN29      2.46          0.94        3.96            9.29
ZSCAN30      0.00        150.43        0.00            0.00
ZSCAN31      0.00          0.00        0.00            0.00
ZSCAN32      0.00          0.00        0.00            0.00
ZSCAN4       0.00          0.00        0.00            0.00
ZSCAN5A      0.00          0.00        0.00            0.00
ZSCAN5B      0.00          0.00        0.00            0.00
ZSCAN9     145.14        115.37        0.00            0.00
ZSWIM1     103.99         10.23        0.00            0.00
ZSWIM2       0.00          0.00        0.00            0.00
ZSWIM3      16.36          0.00        0.00            0.00
ZSWIM4       4.40          0.00        0.00            0.00
ZSWIM5       0.00          0.00        0.00            0.00
ZSWIM6       8.30          4.02        0.00            0.00
ZSWIM7       2.07          3.77        0.00            0.00
ZSWIM8       0.00         93.50        0.00            0.00
ZSWIM8-AS1   0.00          0.00        0.00            0.00
ZUP1         0.00          0.00        0.00            0.00
ZW10         0.00          0.00        0.00            0.00
ZWILCH       0.00          0.00        0.00            0.00
ZWINT        0.00          0.00        0.00            0.00
ZXDA        26.34          0.00        0.00            0.00
ZXDB         0.00          0.00        0.00            0.00
ZXDC         4.55         34.27        0.00            0.00
ZYG11A       1.11          4.42        0.00            0.00
ZYG11B       1.80          1.40        0.00            8.40
ZYX         18.41        157.44        9.75            0.00
ZZEF1        8.64          6.56        1.94            0.00
ZZZ3         5.30          0.00        0.00          140.10
           Oligo-P22-H08 Oligo-P22-H09
A1BG          0.00         0.00
A1BG-AS1      0.00         0.00
A1CF          0.00         0.00
A2M           0.00         0.00
A2M-AS1    1098.07         0.00
A2ML1         0.00         0.00
A2MP1         0.00         0.00
A4GALT        0.00         0.00
A4GNT         0.00         0.00
AA06          0.00         0.00
AAAS          0.00         0.00
AACS          0.00         0.00
AACSP1        0.00         0.00
AADAC         0.00         0.00
AADACL2       0.00         0.00
AADACL3       0.00         0.00
AADACL4       0.00         0.00
AADAT         0.00         0.00
PRXL2C        0.00         0.00
AAGAB         0.00       131.85
AAK1          3.95         1.57
AAMDC         0.00         0.00
AAMP          0.00         0.00
AANAT         0.00         0.00
AAR2        991.10         0.00
AARD         25.84         0.00
AARS1        13.70         0.00
AARS2       310.07         7.04
AARSD1        0.00         0.00
AASDH         0.00         0.00
⋮          ⋮             ⋮
ZSCAN26      0.00         0.00
ZSCAN29     16.19        17.97
ZSCAN30     99.60         0.00
ZSCAN31      0.00         0.00
ZSCAN32      0.00         0.00
ZSCAN4       0.00         0.00
ZSCAN5A      0.00         0.00
ZSCAN5B      0.00         0.00
ZSCAN9       0.00         0.00
ZSWIM1      22.73         0.00
ZSWIM2       0.00         0.00
ZSWIM3       0.00         0.00
ZSWIM4       0.00         0.00
ZSWIM5       0.00         0.00
ZSWIM6       0.00         0.00
ZSWIM7       0.00         0.00
ZSWIM8       0.00         0.00
ZSWIM8-AS1   0.00         0.00
ZUP1         0.00         0.00
ZW10         0.00         0.00
ZWILCH       0.00         0.00
ZWINT        0.00         0.00
ZXDA         0.00         0.00
ZXDB         0.00         5.95
ZXDC        68.34         0.00
ZYG11A       0.00        16.26
ZYG11B       2.79         0.00
ZYX          0.00         0.00
ZZEF1        0.00         0.00
ZZZ3       443.58         0.00

In [4]:
Filbin2018 <- CreateSeuratObject(counts, min.features = 0, min.cells = 0, 
                                  project = 'Filbin2018')
Filbin2018$ID <- gsub("-.*","\\1",colnames(Filbin2018)) # https://datascience.stackexchange.com/questions/8922/removing-strings-after-a-certain-character-in-a-given-text
Filbin2018@meta.data

Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”

              orig.ident nCount_RNA nFeature_RNA ID
MUV1-P04-B12  Filbin2018 1000000.3  4811         MUV1
MUV1-P04-C08  Filbin2018 1000000.3  2617         MUV1
MUV1-P04-D09  Filbin2018 1000000.0  4628         MUV1
MUV1-P04-D10  Filbin2018 1000000.1  4882         MUV1
MUV1-P04-E03  Filbin2018 1000000.4  5927         MUV1
MUV1-P04-E07  Filbin2018 1000000.3  7844         MUV1
MUV1-P04-E08  Filbin2018 1000000.4  5814         MUV1
MUV1-P04-E10  Filbin2018  999999.8  5833         MUV1
MUV1-P04-E11  Filbin2018 1000000.4  5992         MUV1
MUV1-P04-F05  Filbin2018  999999.9  4513         MUV1
MUV1-P04-F08  Filbin2018  999999.9  4382         MUV1
MUV1-P04-F09  Filbin2018 1000000.1  6873         MUV1
MUV1-P04-F10  Filbin2018  999999.9  5752         MUV1
MUV1-P04-G08  Filbin2018  999999.8  7046         MUV1
MUV1-P04-G09  Filbin2018 1000000.0  5858         MUV1
MUV1-P04-H08  Filbin2018  999999.8  4281         MUV1
MUV1-P04-H10  Filbin2018 1000000.1  5964         MUV1
MUV1-P04-H11  Filbin2018 1000000.1  6169         MUV1
MUV1-P05-A01  Filbin2018 1000000.3  3481         MUV1
MUV1-P05-A09  Filbin2018 1000000.0  7290         MUV1
MUV1-P05-B02  Filbin2018 1000000.6  4719         MUV1
MUV1-P05-B08  Filbin2018  999999.8  5069         MUV1
MUV1-P05-B10  Filbin2018  999999.5  4683         MUV1
MUV1-P05-B11  Filbin2018  999999.7  4582         MUV1
MUV1-P05-B12  Filbin2018  999999.9  3151         MUV1
MUV1-P05-C02  Filbin2018 1000000.1  5084         MUV1
MUV1-P05-C04  Filbin2018  999999.9  4874         MUV1
MUV1-P05-C05  Filbin2018 1000000.0  3431         MUV1
MUV1-P05-C06  Filbin2018  999999.8  4514         MUV1
MUV1-P05-C09  Filbin2018  999999.9  4758         MUV1
⋮             ⋮          ⋮          ⋮            ⋮
Oligo-P22-E05 Filbin2018 1000000.2  4070         Oligo
Oligo-P22-E06 Filbin2018 1000000.3  6080         Oligo
Oligo-P22-E07 Filbin2018 1000000.2  3788         Oligo
Oligo-P22-E08 Filbin2018  999999.9  3651         Oligo
Oligo-P22-E09 Filbin2018 1000000.1  4529         Oligo
Oligo-P22-E11 Filbin2018  999999.8  4418         Oligo
Oligo-P22-E12 Filbin2018  999999.5  5392         Oligo
Oligo-P22-F01 Filbin2018 1000000.0  5446         Oligo
Oligo-P22-F03 Filbin2018 1000000.0  4337         Oligo
Oligo-P22-F04 Filbin2018  999999.9  4482         Oligo
Oligo-P22-F05 Filbin2018 1000000.1  4823         Oligo
Oligo-P22-F07 Filbin2018 1000000.0  5082         Oligo
Oligo-P22-F08 Filbin2018  999999.7  4535         Oligo
Oligo-P22-F09 Filbin2018  999999.7  4875         Oligo
Oligo-P22-F10 Filbin2018  999999.6  5029         Oligo
Oligo-P22-F12 Filbin2018 1000000.0  5665         Oligo
Oligo-P22-G01 Filbin2018 1000000.0  4106         Oligo
Oligo-P22-G02 Filbin2018  999999.7  5281         Oligo
Oligo-P22-G03 Filbin2018 1000000.0  5253         Oligo
Oligo-P22-G04 Filbin2018  999999.8  5432         Oligo
Oligo-P22-G05 Filbin2018 1000000.2  4639         Oligo
Oligo-P22-G07 Filbin2018 1000000.0  4192         Oligo
Oligo-P22-G11 Filbin2018  999999.6  4807         Oligo
Oligo-P22-G12 Filbin2018 1000000.2  5259         Oligo
Oligo-P22-H02 Filbin2018  999999.9  6062         Oligo
Oligo-P22-H03 Filbin2018 1000000.1  5547         Oligo
Oligo-P22-H05 Filbin2018 1000000.1  2991         Oligo
Oligo-P22-H06 Filbin2018 1000000.0  2977         Oligo
Oligo-P22-H08 Filbin2018  999999.8  2885         Oligo
Oligo-P22-H09 Filbin2018  999999.9  3006         Oligo

In [5]:
table(Filbin2018$ID)

      BCH1126        BCH836        BCH869 BCH869_DGC100  BCH869_DGC75
          299           527           492            89           165
    BCH869_GF     BCH869_GS    BCH869_PDX     BCH869_SF        MGH101
           68           290           167            84            92
       MGH104         MGH66          MUV1         MUV10          MUV5
           65           442           146           286           708
        Oligo
          138

In [6]:
# There are three sample from this study that were also included later in Liu2022
# Checking the barcodes there was 444 matches between both datsets that couls also be due to the method the use (plate-based)
# and the Liu2022 methods do not mention they integrated cells from the previous study
# All cells will be kept

Filbin2018 <- subset(Filbin2018, subset = ID %in% (meta_cohort %>% 
                     filter(Study %in% c('Filbin2018', 'Liu2022')) %>% pull(ID)))
Filbin2018

An object of class Seurat
23686 features across 2458 samples within 1 assay
Active assay: RNA (23686 features, 0 variable features)

In [7]:
Filbin2018_meta <- as.data.frame(fread(paste0('/hpc/pmc_stunnenberg/cruiz/scRNA/',
             'markers-and-databases/dmg/Filbin2018/',
             'PortalK27M_Metadata.vh20180223.txt'))) 
Filbin2018_meta <- Filbin2018_meta[-1,]
Filbin2018_meta <- Filbin2018_meta %>% filter(NAME %in% colnames(Filbin2018)) %>% 
                      column_to_rownames('NAME')

Filbin2018_meta

                Sample  GenesExpressed HousekeepingGeneExpression
BCH1126-P01-A01 BCH1126 4064           6.371650316
BCH1126-P01-A02 BCH1126 5162           6.363841855
BCH1126-P01-A04 BCH1126 3583           4.623983418
BCH1126-P01-A07 BCH1126 4743           6.131107408
BCH1126-P01-A08 BCH1126 4015           5.803742692
BCH1126-P01-A09 BCH1126 5742           6.430943464
BCH1126-P01-B01 BCH1126 3044           4.32654854
BCH1126-P01-B03 BCH1126 4889           6.075816313
BCH1126-P01-B04 BCH1126 5565           6.054379026
BCH1126-P01-B05 BCH1126 5253           5.809870501
BCH1126-P01-B06 BCH1126 4340           4.789038484
BCH1126-P01-B08 BCH1126 5103           5.954073453
BCH1126-P01-B10 BCH1126 5160           6.298778136
BCH1126-P01-B11 BCH1126 4056           5.854249581
BCH1126-P01-C01 BCH1126 4446           6.530699568
BCH1126-P01-C02 BCH1126 4825           6.135115566
BCH1126-P01-C03 BCH1126 4658           5.951449516
BCH1126-P01-C04 BCH1126 5637           6.211421691
BCH1126-P01-C05 BCH1126 3236           6.397132027
BCH1126-P01-C07 BCH1126 5171           6.429517293
BCH1126-P01-C09 BCH1126 3878           6.119530793
BCH1126-P01-C10 BCH1126 4045           6.108783568
BCH1126-P01-C11 BCH1126 4803           5.940849033
BCH1126-P01-C12 BCH1126 4175           5.794099865
BCH1126-P01-D01 BCH1126 5709           6.469156759
BCH1126-P01-D02 BCH1126 3409           5.607263658
BCH1126-P01-D03 BCH1126 4859           4.519115274
BCH1126-P01-D05 BCH1126 5817           6.193240317
BCH1126-P01-D07 BCH1126 4393           5.924341084
BCH1126-P01-D08 BCH1126 5178           6.25262164
⋮               ⋮       ⋮              ⋮
MUV5-P12-E10    MUV5    3932           5.88842503
MUV5-P12-E11    MUV5    7685           5.988697742
MUV5-P12-E12    MUV5    3659           5.422728663
MUV5-P12-F01    MUV5    5334           6.121396349
MUV5-P12-F02    MUV5    4080           6.207287517
MUV5-P12-F03    MUV5    7186           5.163963143
MUV5-P12-F04    MUV5    5310           6.221171612
MUV5-P12-F05    MUV5    5375           6.065740467
MUV5-P12-F06    MUV5    7649           5.374840341
MUV5-P12-F07    MUV5    5021           6.014867144
MUV5-P12-F08    MUV5    4303           5.048590845
MUV5-P12-F10    MUV5    4237           3.810864151
MUV5-P12-F11    MUV5    5388           5.944558341
MUV5-P12-G01    MUV5    5422           6.220717121
MUV5-P12-G02    MUV5    5942           6.15287585
MUV5-P12-G03    MUV5    4379           5.987875771
MUV5-P12-G04    MUV5    3736           5.931869126
MUV5-P12-G05    MUV5    4874           6.253884228
MUV5-P12-G06    MUV5    3398           5.988969361
MUV5-P12-G09    MUV5    3236           4.669631542
MUV5-P12-G10    MUV5    3125           5.682540165
MUV5-P12-G11    MUV5    6346           6.160488705
MUV5-P12-G12    MUV5    4663           6.614482367
MUV5-P12-H01    MUV5    4780           4.221099074
MUV5-P12-H02    MUV5    4824           5.657906767
MUV5-P12-H04    MUV5    4240           6.05529572
MUV5-P12-H06    MUV5    3590           6.258232835
MUV5-P12-H07    MUV5    4461           6.181141635
MUV5-P12-H09    MUV5    4561           6.122249488
MUV5-P12-H10    MUV5    5253           6.204441889
                Type            Cellcycle    OPC-variable OC-like
BCH1126-P01-A01 Malignant       -0.44186567  -1.018729626 -0.511928109
BCH1126-P01-A02 Malignant       -0.490522093 -0.938585898 -0.018924871
BCH1126-P01-A04 Malignant       0.319448462  -0.870724574 0.327553519
BCH1126-P01-A07 Malignant       -0.747714419 -0.444016923 -0.461922304
BCH1126-P01-A08 Malignant       -0.219426632 -0.074824661 0.304706623
BCH1126-P01-A09 Malignant       -0.577234556 -1.3868627   0.329421293
BCH1126-P01-B01 Immune cell     NA           NA           NA
BCH1126-P01-B03 Malignant       -0.46423596  -0.118795718 0.257534493
BCH1126-P01-B04 Malignant       -0.629568899 -0.893449316 0.894925577
BCH1126-P01-B05 Malignant       -0.482456989 0.491212127  1.839374009
BCH1126-P01-B06 Immune cell     NA           NA           NA
BCH1126-P01-B08 Malignant       0.659743418  -1.329680647 0.670249948
BCH1126-P01-B10 Malignant       -0.561964761 -0.457817453 0.166938089
BCH1126-P01-B11 Malignant       -0.334987396 -0.202954807 -0.523591532
BCH1126-P01-C01 Malignant       -0.377260563 -1.357491491 -0.193621779
BCH1126-P01-C02 Malignant       -0.706243311 -0.695943719 -0.701559903
BCH1126-P01-C03 Malignant       -0.095498082 -0.130833422 -0.023298067
BCH1126-P01-C04 Malignant       -0.250410396 -1.436804329 -0.517682443
BCH1126-P01-C05 Immune cell     NA           NA           NA
BCH1126-P01-C07 Malignant       -0.387920654 -1.353792339 -0.458487538
BCH1126-P01-C09 Malignant       -0.398336116 0.072193642  1.81866027
BCH1126-P01-C10 Malignant       -0.097550867 -1.314809085 -0.630153594
BCH1126-P01-C11 Malignant       2.621467738  -1.160414578 0.000991033
BCH1126-P01-C12 Malignant       -0.605798532 -1.050110867 1.513755728
BCH1126-P01-D01 Malignant       -0.290459623 -1.843195863 -0.156377701
BCH1126-P01-D02 Malignant       -0.655253049 -0.815808724 -0.14715129
BCH1126-P01-D03 Oligodendrocyte NA           NA           NA
BCH1126-P01-D05 Malignant       -0.271524155 -0.759807199 1.597930044
BCH1126-P01-D07 Malignant       -0.097954287 -1.217046674 -0.300155067
BCH1126-P01-D08 Malignant       -0.792721747 -1.463381737 -0.246346712
⋮               ⋮               ⋮            ⋮            ⋮
MUV5-P12-E10    Malignant       -0.354853286 -1.207872834 -0.042515452
MUV5-P12-E11    Malignant       -0.772706375 -1.046623124 0.110634506
MUV5-P12-E12    Malignant       -0.261472976 -0.331442415 -0.421498492
MUV5-P12-F01    Malignant       -0.389280721 -0.934182313 0.250533876
MUV5-P12-F02    Malignant       -0.703211186 -1.173879201 -0.933541781
MUV5-P12-F03    Malignant       -0.678816257 -0.114782767 0.630953648
MUV5-P12-F04    Malignant       -0.558410444 -0.513838552 0.286336428
MUV5-P12-F05    Malignant       -0.641601041 -0.922949542 -0.404948563
MUV5-P12-F06    Malignant       -0.985585124 -0.85643571  -0.22411224
MUV5-P12-F07    Malignant       -0.59920971  0.220211334  -0.060717431
MUV5-P12-F08    Malignant       -0.525586038 -0.490316123 4.284309582
MUV5-P12-F10    Malignant       -0.165532621 1.701514549  0.679687759
MUV5-P12-F11    Malignant       0.051485195  -0.939656049 0.033577788
MUV5-P12-G01    Malignant       -0.951996826 -0.721256858 -0.628250273
MUV5-P12-G02    Malignant       0.077478299  -0.925393092 -0.21226524
MUV5-P12-G03    Malignant       -0.658057636 -1.250196409 -1.011474862
MUV5-P12-G04    Malignant       -0.130138938 -0.081203947 -0.208061561
MUV5-P12-G05    Malignant       -0.290332141 -0.870409626 0.033115012
MUV5-P12-G06    Malignant       0.208161987  -0.506692242 -0.020298395
MUV5-P12-G09    Malignant       -0.139229413 0.029698594  -0.297008264
MUV5-P12-G10    Malignant       0.15944514   -0.802306692 -0.176570974
MUV5-P12-G11    Malignant       -0.646665263 -0.914202921 -0.173168465
MUV5-P12-G12    Malignant       0.107449369  -1.578535919 -0.217335003
MUV5-P12-H01    Oligodendrocyte NA           NA           NA
MUV5-P12-H02    Malignant       -0.709416641 -0.739089273 3.787294456
MUV5-P12-H04    Malignant       -0.459781758 -0.893816737 0.161463092
MUV5-P12-H06    Malignant       -0.296587838 -0.590851398 -0.445266217
MUV5-P12-H07    Malignant       -0.618423238 -1.511359746 -0.183541032
MUV5-P12-H09    Malignant       0.411884443  -1.380330605 -0.010459438
MUV5-P12-H10    Malignant       -0.616152151 -0.573399339 -0.281722248
                AC-like      OPC-like
BCH1126-P01-A01 -0.523686956 0.83940171
BCH1126-P01-A02 -1.02391073  0.400311983
BCH1126-P01-A04 0.303905206  -0.314469209
BCH1126-P01-A07 -0.421771418 1.11865115
BCH1126-P01-A08 0.184920455  1.718093353
BCH1126-P01-A09 -0.88265844  -0.013435158
BCH1126-P01-B01 NA           NA
BCH1126-P01-B03 -0.387274608 1.493154986
BCH1126-P01-B04 -1.70173949  0.228877493
BCH1126-P01-B05 -1.005291514 0.526729719
BCH1126-P01-B06 NA           NA
BCH1126-P01-B08 -1.059536128 -1.078659584
BCH1126-P01-B10 -0.390890341 -0.130400865
BCH1126-P01-B11 2.18407916   0.813369308
BCH1126-P01-C01 -0.536278339 0.890504904
BCH1126-P01-C02 -0.771469681 0.655226395
BCH1126-P01-C03 -0.393487178 0.693253422
BCH1126-P01-C04 -0.966753056 0.078740894
BCH1126-P01-C05 NA           NA
BCH1126-P01-C07 -0.294274303 -0.070769195
BCH1126-P01-C09 -0.906534474 0.329417759
BCH1126-P01-C10 -0.551107116 1.660842378
BCH1126-P01-C11 -0.431880856 0.36588457
BCH1126-P01-C12 -1.271220838 -1.678303335
BCH1126-P01-D01 0.028187938  -1.98057314
BCH1126-P01-D02 0.242345012  0.607046512
BCH1126-P01-D03 NA           NA
BCH1126-P01-D05 -1.080340924 -1.506462209
BCH1126-P01-D07 -0.321623551 1.739897837
BCH1126-P01-D08 -0.636541064 1.268789662
⋮               ⋮            ⋮
MUV5-P12-E10    -1.426180136 0.619854895
MUV5-P12-E11    -1.230350277 -0.090029352
MUV5-P12-E12    5.471105443  -1.674261198
MUV5-P12-F01    -0.840633465 0.209580219
MUV5-P12-F02    -0.883296409 -0.405083296
MUV5-P12-F03    4.925832789  -1.062988237
MUV5-P12-F04    -0.990418015 -0.129536927
MUV5-P12-F05    -0.820050214 -0.09079522
MUV5-P12-F06    4.704313029  -1.386056346
MUV5-P12-F07    -0.953384729 0.978696591
MUV5-P12-F08    -1.460102252 -2.978247712
MUV5-P12-F10    0.058043116  -0.053386185
MUV5-P12-F11    -1.180006176 0.419024046
MUV5-P12-G01    -0.999996639 -0.085449403
MUV5-P12-G02    -0.916419001 -0.638869298
MUV5-P12-G03    -1.246006571 0.842489039
MUV5-P12-G04    0.226297912  1.377725651
MUV5-P12-G05    -1.299543557 0.784820486
MUV5-P12-G06    -0.902016003 0.979863503
MUV5-P12-G09    5.332284299  -2.135334085
MUV5-P12-G10    -0.616421339 1.519289806
MUV5-P12-G11    -1.060872292 1.084405713
MUV5-P12-G12    2.286681512  -1.884043599
MUV5-P12-H01    NA           NA
MUV5-P12-H02    -1.282522252 -3.095500619
MUV5-P12-H04    -1.00288137  0.383959428
MUV5-P12-H06    -0.952807699 0.385016555
MUV5-P12-H07    -1.178111563 -0.261441271
MUV5-P12-H09    -0.272497972 -0.713374612
MUV5-P12-H10    -1.47177582  0.03217689

In [8]:
table(Filbin2018_meta$Type)

         Filter     Immune cell       Malignant Oligodendrocyte
              9              96            2259              94

##### Check final metadata

In [10]:
# Metadata of MUV samples was more complete in Liu2022 and we kept those. Survivael info was not present in Liu2022
# Added survival from Filbin2018 MUV samples to Liu2022

Filbin2018 <- AddMetaData(Filbin2018, Filbin2018_meta %>% select(Type))
Filbin2018$Original_annotation <- Filbin2018$Type
Filbin2018$SampleID <- Filbin2018$ID
Filbin2018$Data <- 'RNA_only'
Filbin2018$Batch_for_correction <- 'SmartSeq2_cell_rna'

Filbin2018$Type <- NULL
Filbin2018$orig.ident <- NULL

Filbin2018@meta.data

                nCount_RNA nFeature_RNA ID      Original_annotation SampleID
MUV1-P04-B12    1000000.3  4811         MUV1    Malignant           MUV1
MUV1-P04-C08    1000000.3  2617         MUV1    Malignant           MUV1
MUV1-P04-D09    1000000.0  4628         MUV1    Malignant           MUV1
MUV1-P04-D10    1000000.1  4882         MUV1    Malignant           MUV1
MUV1-P04-E03    1000000.4  5927         MUV1    Malignant           MUV1
MUV1-P04-E07    1000000.3  7844         MUV1    Malignant           MUV1
MUV1-P04-E08    1000000.4  5814         MUV1    Malignant           MUV1
MUV1-P04-E10     999999.8  5833         MUV1    Malignant           MUV1
MUV1-P04-E11    1000000.4  5992         MUV1    Malignant           MUV1
MUV1-P04-F05     999999.9  4513         MUV1    Malignant           MUV1
MUV1-P04-F08     999999.9  4382         MUV1    Malignant           MUV1
MUV1-P04-F09    1000000.1  6873         MUV1    Malignant           MUV1
MUV1-P04-F10     999999.9  5752         MUV1    Malignant           MUV1
MUV1-P04-G08     999999.8  7046         MUV1    Malignant           MUV1
MUV1-P04-G09    1000000.0  5858         MUV1    Malignant           MUV1
MUV1-P04-H08     999999.8  4281         MUV1    Malignant           MUV1
MUV1-P04-H10    1000000.1  5964         MUV1    Malignant           MUV1
MUV1-P04-H11    1000000.1  6169         MUV1    Malignant           MUV1
MUV1-P05-A01    1000000.3  3481         MUV1    Malignant           MUV1
MUV1-P05-A09    1000000.0  7290         MUV1    Malignant           MUV1
MUV1-P05-B02    1000000.6  4719         MUV1    Malignant           MUV1
MUV1-P05-B08     999999.8  5069         MUV1    Malignant           MUV1
MUV1-P05-B10     999999.5  4683         MUV1    Malignant           MUV1
MUV1-P05-B11     999999.7  4582         MUV1    Malignant           MUV1
MUV1-P05-B12     999999.9  3151         MUV1    Immune cell         MUV1
MUV1-P05-C02    1000000.1  5084         MUV1    Malignant           MUV1
MUV1-P05-C04     999999.9  4874         MUV1    Malignant           MUV1
MUV1-P05-C05    1000000.0  3431         MUV1    Malignant           MUV1
MUV1-P05-C06     999999.8  4514         MUV1    Malignant           MUV1
MUV1-P05-C09     999999.9  4758         MUV1    Malignant           MUV1
⋮               ⋮          ⋮            ⋮       ⋮                   ⋮
BCH1126-P04-E12  999999.8  6208         BCH1126 Malignant           BCH1126
BCH1126-P04-F01 1000000.0  5482         BCH1126 Malignant           BCH1126
BCH1126-P04-F02 1000000.1  6085         BCH1126 Malignant           BCH1126
BCH1126-P04-F03 1000000.0  5705         BCH1126 Malignant           BCH1126
BCH1126-P04-F04 1000000.0  6912         BCH1126 Malignant           BCH1126
BCH1126-P04-F06  999999.9  4716         BCH1126 Oligodendrocyte     BCH1126
BCH1126-P04-F07  999999.7  4912         BCH1126 Malignant           BCH1126
BCH1126-P04-F10 1000000.0  3115         BCH1126 Immune cell         BCH1126
BCH1126-P04-F11 1000000.1  5214         BCH1126 Malignant           BCH1126
BCH1126-P04-G01 1000000.0  5721         BCH1126 Malignant           BCH1126
BCH1126-P04-G02  999999.7  4598         BCH1126 Malignant           BCH1126
BCH1126-P04-G03 1000000.1  6127         BCH1126 Malignant           BCH1126
BCH1126-P04-G04  999999.8  3014         BCH1126 Immune cell         BCH1126
BCH1126-P04-G06  999999.9  4290         BCH1126 Immune cell         BCH1126
BCH1126-P04-G07  999999.9  4286         BCH1126 Immune cell         BCH1126
BCH1126-P04-G08 1000000.3  5939         BCH1126 Malignant           BCH1126
BCH1126-P04-G09  999999.8  6565         BCH1126 Malignant           BCH1126
BCH1126-P04-G10 1000000.2  5104         BCH1126 Malignant           BCH1126
BCH1126-P04-G11  999999.7  6312         BCH1126 Malignant           BCH1126
BCH1126-P04-H01  999999.9  3787         BCH1126 Malignant           BCH1126
BCH1126-P04-H02 1000000.3  3520         BCH1126 Immune cell         BCH1126
BCH1126-P04-H04 1000000.1  4381         BCH1126 Malignant           BCH1126
BCH1126-P04-H05 1000000.0  3033         BCH1126 Malignant           BCH1126
BCH1126-P04-H06  999999.8  6674         BCH1126 Malignant           BCH1126
BCH1126-P04-H07  999999.9  3418         BCH1126 Malignant           BCH1126
BCH1126-P04-H08 1000000.1  4333         BCH1126 Oligodendrocyte     BCH1126
BCH1126-P04-H09 1000000.0  3869         BCH1126 Malignant           BCH1126
BCH1126-P04-H10  999999.8  5011         BCH1126 Malignant           BCH1126
BCH1126-P04-H11 1000000.4  4866         BCH1126 Malignant           BCH1126
BCH1126-P04-H12 1000000.3  4564         BCH1126 Malignant           BCH1126
                Data     Batch_for_correction
MUV1-P04-B12    RNA_only SmartSeq2_cell_rna
MUV1-P04-C08    RNA_only SmartSeq2_cell_rna
MUV1-P04-D09    RNA_only SmartSeq2_cell_rna
MUV1-P04-D10    RNA_only SmartSeq2_cell_rna
MUV1-P04-E03    RNA_only SmartSeq2_cell_rna
MUV1-P04-E07    RNA_only SmartSeq2_cell_rna
MUV1-P04-E08    RNA_only SmartSeq2_cell_rna
MUV1-P04-E10    RNA_only SmartSeq2_cell_rna
MUV1-P04-E11    RNA_only SmartSeq2_cell_rna
MUV1-P04-F05    RNA_only SmartSeq2_cell_rna
MUV1-P04-F08    RNA_only SmartSeq2_cell_rna
MUV1-P04-F09    RNA_only SmartSeq2_cell_rna
MUV1-P04-F10    RNA_only SmartSeq2_cell_rna
MUV1-P04-G08    RNA_only SmartSeq2_cell_rna
MUV1-P04-G09    RNA_only SmartSeq2_cell_rna
MUV1-P04-H08    RNA_only SmartSeq2_cell_rna
MUV1-P04-H10    RNA_only SmartSeq2_cell_rna
MUV1-P04-H11    RNA_only SmartSeq2_cell_rna
MUV1-P05-A01    RNA_only SmartSeq2_cell_rna
MUV1-P05-A09    RNA_only SmartSeq2_cell_rna
MUV1-P05-B02    RNA_only SmartSeq2_cell_rna
MUV1-P05-B08    RNA_only SmartSeq2_cell_rna
MUV1-P05-B10    RNA_only SmartSeq2_cell_rna
MUV1-P05-B11    RNA_only SmartSeq2_cell_rna
MUV1-P05-B12    RNA_only SmartSeq2_cell_rna
MUV1-P05-C02    RNA_only SmartSeq2_cell_rna
MUV1-P05-C04    RNA_only SmartSeq2_cell_rna
MUV1-P05-C05    RNA_only SmartSeq2_cell_rna
MUV1-P05-C06    RNA_only SmartSeq2_cell_rna
MUV1-P05-C09    RNA_only SmartSeq2_cell_rna
⋮               ⋮        ⋮
BCH1126-P04-E12 RNA_only SmartSeq2_cell_rna
BCH1126-P04-F01 RNA_only SmartSeq2_cell_rna
BCH1126-P04-F02 RNA_only SmartSeq2_cell_rna
BCH1126-P04-F03 RNA_only SmartSeq2_cell_rna
BCH1126-P04-F04 RNA_only SmartSeq2_cell_rna
BCH1126-P04-F06 RNA_only SmartSeq2_cell_rna
BCH1126-P04-F07 RNA_only SmartSeq2_cell_rna
BCH1126-P04-F10 RNA_only SmartSeq2_cell_rna
BCH1126-P04-F11 RNA_only SmartSeq2_cell_rna
BCH1126-P04-G01 RNA_only SmartSeq2_cell_rna
BCH1126-P04-G02 RNA_only SmartSeq2_cell_rna
BCH1126-P04-G03 RNA_only SmartSeq2_cell_rna
BCH1126-P04-G04 RNA_only SmartSeq2_cell_rna
BCH1126-P04-G06 RNA_only SmartSeq2_cell_rna
BCH1126-P04-G07 RNA_only SmartSeq2_cell_rna
BCH1126-P04-G08 RNA_only SmartSeq2_cell_rna
BCH1126-P04-G09 RNA_only SmartSeq2_cell_rna
BCH1126-P04-G10 RNA_only SmartSeq2_cell_rna
BCH1126-P04-G11 RNA_only SmartSeq2_cell_rna
BCH1126-P04-H01 RNA_only SmartSeq2_cell_rna
BCH1126-P04-H02 RNA_only SmartSeq2_cell_rna
BCH1126-P04-H04 RNA_only SmartSeq2_cell_rna
BCH1126-P04-H05 RNA_only SmartSeq2_cell_rna
BCH1126-P04-H06 RNA_only SmartSeq2_cell_rna
BCH1126-P04-H07 RNA_only SmartSeq2_cell_rna
BCH1126-P04-H08 RNA_only SmartSeq2_cell_rna
BCH1126-P04-H09 RNA_only SmartSeq2_cell_rna
BCH1126-P04-H10 RNA_only SmartSeq2_cell_rna
BCH1126-P04-H11 RNA_only SmartSeq2_cell_rna
BCH1126-P04-H12 RNA_only SmartSeq2_cell_rna

In [11]:
saveRDS(Filbin2018, '../data/Filbin2018_no_filtered.rds')

### Liu2022

DOI:10.1038/s41588-022-01236-3

In [4]:
path.dir <- '/hpc/pmc_stunnenberg/cruiz/scRNA/markers-and-databases/dmg/Liu2022/'

In [5]:
sc_mtx <- fread(paste0(path.dir, 'GSE184357_counts_fresh_preFilter.txt.gz')) %>%
            column_to_rownames('V1')
gene.names <- checkGeneSymbols(rownames(sc_mtx), unmapped.as.na=FALSE)
gene.names
rownames(sc_mtx) <- make.unique(gene.names$Suggested.Symbol)
sc_mtx

Warning message in fread(paste0(path.dir, "GSE184357_counts_fresh_preFilter.txt.gz")):
“Detected 8251 column names but the data has 8252 columns (i.e. invalid file). Added 1 extra default column name for the first column which is guessed to be row names or an index. Use setnames() afterwards if this guess is not correct, or fix the file write command that created the file to create a valid file.”
Maps last updated on: Thu Oct 24 12:31:05 2019

Warning message in checkGeneSymbols(rownames(sc_mtx), unmapped.as.na = FALSE):
“Human gene symbols should be all upper-case except for the 'orf' in open reading frames. The case of some letters was corrected.”
Warning message in checkGeneSymbols(rownames(sc_mtx), unmapped.as.na = FALSE):
“x contains non-approved gene symbols”

      x            Approved Suggested.Symbol
1     5S_rRNA      FALSE    5S_rRNA
2     7SK          FALSE    RN7SK
3     A1BG          TRUE    A1BG
4     A1BG-AS1      TRUE    A1BG-AS1
5     A1CF          TRUE    A1CF
6     A2M           TRUE    A2M
7     A2M-AS1       TRUE    A2M-AS1
8     A2ML1         TRUE    A2ML1
9     A2ML1-AS1     TRUE    A2ML1-AS1
10    A2ML1-AS2     TRUE    A2ML1-AS2
11    A3GALT2       TRUE    A3GALT2
12    A4GALT        TRUE    A4GALT
13    A4GNT         TRUE    A4GNT
14    AAAS          TRUE    AAAS
15    AACS          TRUE    AACS
16    AADAC         TRUE    AADAC
17    AADACL2       TRUE    AADACL2
18    AADACL3       TRUE    AADACL3
19    AADACL4       TRUE    AADACL4
20    AADAT         TRUE    AADAT
21    AAED1        FALSE    PRXL2C
22    AAGAB         TRUE    AAGAB
23    AAK1          TRUE    AAK1
24    AAMDC         TRUE    AAMDC
25    AAMP          TRUE    AAMP
26    AANAT         TRUE    AANAT
27    AAR2          TRUE    AAR2
28    AARD          TRUE    AARD
29    AARS         FALSE    AARS1
30    AARS2         TRUE    AARS2
⋮     ⋮            ⋮        ⋮
32588 ZSWIM1        TRUE    ZSWIM1
32589 ZSWIM2        TRUE    ZSWIM2
32590 ZSWIM3        TRUE    ZSWIM3
32591 ZSWIM4        TRUE    ZSWIM4
32592 ZSWIM5        TRUE    ZSWIM5
32593 ZSWIM6        TRUE    ZSWIM6
32594 ZSWIM7        TRUE    ZSWIM7
32595 ZSWIM8        TRUE    ZSWIM8
32596 ZSWIM8-AS1    TRUE    ZSWIM8-AS1
32597 ZUFSP        FALSE    ZUP1
32598 ZW10          TRUE    ZW10
32599 ZWILCH        TRUE    ZWILCH
32600 ZWINT         TRUE    ZWINT
32601 ZXDA          TRUE    ZXDA
32602 ZXDB          TRUE    ZXDB
32603 ZXDC          TRUE    ZXDC
32604 ZYG11A        TRUE    ZYG11A
32605 ZYG11B        TRUE    ZYG11B
32606 ZYX           TRUE    ZYX
32607 ZZEF1         TRUE    ZZEF1
32608 ZZZ3          TRUE    ZZZ3
32609 hsa-mir-1199 FALSE    MIR1199
32610 hsa-mir-1253 FALSE    MIR1253
32611 hsa-mir-125a FALSE    MIR125A
32612 hsa-mir-150  FALSE    MIR150
32613 hsa-mir-335  FALSE    MIR335
32614 hsa-mir-490  FALSE    MIR490
32615 hsa-mir-7515 FALSE    MIR7515
32616 hsa-mir-8072 FALSE    MIR8072
32617 snoU13       FALSE    snoU13

           BT1126.P1.A01 BT1126.P1.A02 BT1126.P1.A03 BT1126.P1.A04
5S_rRNA      0.00          0.00          0.00          0.00
RN7SK        5.68          0.00          0.00          0.00
A1BG         0.00         73.49          0.00          0.00
A1BG-AS1     0.00          0.00          0.00          0.68
A1CF         0.00          0.00          0.00          0.00
A2M          0.00          0.00          0.00          0.00
A2M-AS1      0.00          0.00          0.00          0.00
A2ML1        0.00          0.00          0.00          0.00
A2ML1-AS1    0.00          0.00          0.00          0.00
A2ML1-AS2    0.00          0.00          0.00          0.00
A3GALT2      0.00          0.00          0.00          0.00
A4GALT       0.00          0.00          0.00          0.00
A4GNT        0.00          0.00          0.00          0.00
AAAS       249.40          0.00          0.00          0.00
AACS         0.31         80.95          0.00          0.84
AADAC        0.00          0.00          0.00          0.00
AADACL2      0.00          0.00          0.00          0.00
AADACL3      0.00          0.00          0.00          0.00
AADACL4      0.00          0.00          0.00          0.00
AADAT        0.00          0.00          0.00          0.00
PRXL2C       0.36          0.00          0.00          0.00
AAGAB        0.00          0.00          0.00          0.00
AAK1         1.36          0.00        195.32          0.00
AAMDC        0.00        105.74          0.00          0.00
AAMP         8.58        210.41          0.00          0.00
AANAT        0.00          0.00          0.00          0.00
AAR2         0.00          0.00          0.00        169.83
AARD         0.00          0.00          0.00          0.00
AARS1        0.00          0.00          0.00          0.00
AARS2        0.23          2.33          0.00          2.78
⋮          ⋮             ⋮             ⋮             ⋮
ZSWIM1     0.00           2.81         0              1.31
ZSWIM2     0.00           0.00         0              0.00
ZSWIM3     0.00           0.00         0              0.00
ZSWIM4     0.00           0.00         0              0.00
ZSWIM5     0.00           0.00         0              0.00
ZSWIM6     0.00          22.63         0              0.00
ZSWIM7     1.04          86.18         0              8.26
ZSWIM8     0.00           5.55         0             46.87
ZSWIM8-AS1 0.00           0.00         0              0.00
ZUP1       0.00           0.00         0              0.00
ZW10       0.00           0.00         0              0.00
ZWILCH     0.00           0.00         0              0.00
ZWINT      0.00           0.00         0              0.00
ZXDA       0.00           0.00         0              0.00
ZXDB       0.00           0.00         0              0.00
ZXDC       0.00           0.00         0              0.00
ZYG11A     0.00           0.00         0              0.00
ZYG11B     0.32          19.63         0              0.00
ZYX        0.00          37.49         0              0.00
ZZEF1      0.00          61.96         0              1.86
ZZZ3       0.00          84.62         0              0.00
MIR1199    0.00           0.00         0              0.00
MIR1253    0.00           0.00         0              0.00
MIR125A    0.00           0.00         0              0.00
MIR150     0.00           0.00         0              0.00
MIR335     0.69           0.00         0              1.24
MIR490     2.12           0.00         0              5.43
MIR7515    0.00           0.00         0              0.00
MIR8072    0.00           0.00         0              0.00
snoU13     0.00           0.00         0              0.00
           BT1126.P1.A05 BT1126.P1.A06 BT1126.P1.A07 BT1126.P1.A08
5S_rRNA       0.00       0               0.00        0.00
RN7SK         0.00       0               0.00        0.00
A1BG          1.41       0               1.04        0.00
A1BG-AS1      0.00       0               0.00        0.00
A1CF          0.00       0               0.00        0.00
A2M        2437.14       0               0.00        0.00
A2M-AS1       1.44       0               0.00        0.00
A2ML1         1.04       0               0.00        0.00
A2ML1-AS1     0.00       0               0.00        0.00
A2ML1-AS2     0.00       0               0.00        0.00
A3GALT2       0.00       0               0.00        0.00
A4GALT        0.00       0               0.00        0.00
A4GNT         0.00       0               0.00        0.00
AAAS          0.00       0             262.65        0.00
AACS          7.31       0               0.00        1.19
AADAC         0.00       0               0.00        0.00
AADACL2       0.00       0               0.00        0.00
AADACL3       0.00       0               0.00        0.00
AADACL4       0.00       0               0.00        0.00
AADAT         0.00       0               0.00        0.00
PRXL2C       97.85       0               0.80        1.08
AAGAB         0.00       0               0.00        0.00
AAK1          0.00       0               1.41        1.17
AAMDC        57.80       0               0.00        0.00
AAMP          0.00       0               0.00        0.00
AANAT         0.00       0               0.00        0.00
AAR2       1074.64       0               0.00        0.00
AARD          1.33       0               0.00        0.00
AARS1         0.00       0               0.00        0.00
AARS2         4.25       0              68.38        0.00
⋮          ⋮             ⋮             ⋮             ⋮
ZSWIM1       4.38        0             0.78           1.95
ZSWIM2       0.00        0             0.00           0.00
ZSWIM3       0.00        0             0.00           0.00
ZSWIM4       0.00        0             0.00           0.00
ZSWIM5       0.00        0             0.00           0.00
ZSWIM6     335.58        0             0.00           0.00
ZSWIM7      12.54        0             3.75           2.46
ZSWIM8       6.28        0             0.00           7.58
ZSWIM8-AS1   0.00        0             0.00           0.00
ZUP1         0.00        0             0.00           0.00
ZW10         0.00        0             0.00           0.00
ZWILCH       0.00        0             0.00          20.90
ZWINT        0.00        0             0.00           0.00
ZXDA         0.00        0             0.00           0.00
ZXDB         0.00        0             0.00           0.00
ZXDC         0.00        0             0.00           0.00
ZYG11A       0.75        0             0.00           0.68
ZYG11B       1.05        0             0.51          38.22
ZYX          0.00        0             8.67           0.00
ZZEF1        5.40        0             0.48           0.00
ZZZ3         0.00        0             0.44          30.87
MIR1199      0.00        0             0.00           0.00
MIR1253      0.00        0             0.00           0.00
MIR125A      0.00        0             0.00           0.67
MIR150       0.00        0             0.00           0.00
MIR335       1.15        0             0.00          24.95
MIR490      14.74        0             0.00           0.00
MIR7515      0.00        0             0.00           0.00
MIR8072      0.00        0             0.00           0.00
snoU13       0.00        0             0.00           0.00
           BT1126.P1.A09 BT1126.P1.A10 ⋯ MUV87.P2.H03 MUV87.P2.H04 MUV87.P2.H05
5S_rRNA      0.00           0.00       ⋯   0.00         0.00         0.00
RN7SK       12.91           0.00       ⋯   0.00         0.00         0.00
A1BG        56.86           0.00       ⋯  19.90         4.20        54.59
A1BG-AS1     0.00           0.00       ⋯   0.00         0.00         0.00
A1CF         0.00           0.00       ⋯   0.00         0.00         0.00
A2M         55.30           0.00       ⋯   0.00         0.00         0.00
A2M-AS1    117.03           0.00       ⋯   0.00        36.83         0.00
A2ML1        0.00           0.00       ⋯   0.00         0.00         0.00
A2ML1-AS1    0.00           0.00       ⋯   0.00         0.00         0.00
A2ML1-AS2    0.00           0.00       ⋯   0.00         0.00         0.00
A3GALT2      0.00           0.00       ⋯   0.00         0.00         0.00
A4GALT       0.00           0.00       ⋯   0.00         0.00         0.00
A4GNT        0.00           0.00       ⋯   0.00         0.00         0.00
AAAS         0.00           0.00       ⋯ 159.79       137.63         0.00
AACS         2.03           0.00       ⋯   0.00         3.92        72.74
AADAC        0.00           0.00       ⋯   0.00         0.00         0.00
AADACL2      0.00           0.00       ⋯   0.00         0.00         0.00
AADACL3      0.00           0.00       ⋯   0.00         0.00         0.00
AADACL4      0.00           0.00       ⋯   0.00         0.00         0.00
AADAT        0.00           0.00       ⋯   0.00         0.00        15.82
PRXL2C       0.00           0.00       ⋯   0.00         7.03         0.00
AAGAB        0.00           0.00       ⋯   0.00         0.00         0.00
AAK1         0.00           0.00       ⋯  95.94        24.58         0.00
AAMDC      186.09         171.77       ⋯   0.00        13.12         0.00
AAMP       416.90        1105.14       ⋯   0.00         0.00       212.53
AANAT        0.00           0.00       ⋯   0.00         0.00         0.00
AAR2         0.00           0.00       ⋯ 155.30       131.24       106.08
AARD         0.00         207.72       ⋯   0.00         0.00         0.00
AARS1        0.00           0.00       ⋯  93.88         0.00         0.00
AARS2        0.00           0.00       ⋯  59.09         2.22         0.00
⋮          ⋮             ⋮             ⋱ ⋮            ⋮            ⋮
ZSWIM1       0.71          0.00        ⋯  0.00          0.00       80.08
ZSWIM2       0.00          0.00        ⋯  0.00          0.00        0.00
ZSWIM3       0.00          0.00        ⋯  0.00          0.00        0.00
ZSWIM4       0.00          0.00        ⋯  0.00          0.00        0.00
ZSWIM5       0.00         27.52        ⋯  0.00          0.00        0.00
ZSWIM6       0.00          0.00        ⋯  0.00          0.00        0.00
ZSWIM7     117.19          0.00        ⋯  0.00          0.00        0.00
ZSWIM8       0.00          0.00        ⋯  0.00          0.00        0.00
ZSWIM8-AS1   0.00          0.00        ⋯  0.00          0.00        0.00
ZUP1         0.00          0.00        ⋯  0.00          0.00       25.61
ZW10         0.00          0.00        ⋯  0.00         37.85        0.00
ZWILCH       0.00          0.00        ⋯  0.00          0.00        0.00
ZWINT        0.00          0.00        ⋯  0.00        171.52        0.00
ZXDA         0.00          0.00        ⋯  0.00          0.00        0.00
ZXDB         0.00          0.00        ⋯  0.00          0.00        0.00
ZXDC         0.00        255.32        ⋯  0.00          0.00        0.00
ZYG11A       0.00          0.00        ⋯  0.00          2.17        0.00
ZYG11B       0.23          0.00        ⋯  0.00         11.33        0.00
ZYX          0.00        303.17        ⋯ 40.77         48.34        4.26
ZZEF1        0.00          0.00        ⋯  0.00          0.00       31.37
ZZZ3         0.81         18.64        ⋯  0.00         81.31        0.00
MIR1199      0.00          0.00        ⋯  0.00          0.00        0.00
MIR1253      0.00          0.00        ⋯  0.00          0.00        0.00
MIR125A      0.00          0.00        ⋯  0.00          0.00        2.10
MIR150       0.00          0.00        ⋯  0.00          0.00        0.00
MIR335       0.00          0.00        ⋯  0.00          0.00        0.00
MIR490      10.48          0.00        ⋯  0.00          0.00        0.00
MIR7515      0.00          0.00        ⋯  0.00          0.00        0.00
MIR8072      0.00          0.00        ⋯  0.00          0.00        0.00
snoU13       0.00          0.00        ⋯  0.00          0.00        0.00
           MUV87.P2.H06 MUV87.P2.H07 MUV87.P2.H08 MUV87.P2.H09 MUV87.P2.H10
5S_rRNA      0.00         0.00         0.00         0.00         0.00
RN7SK        0.00         0.00         0.00         0.00         0.00
A1BG         0.00         0.00         2.23        32.96         0.00
A1BG-AS1    32.64         0.00         0.00         0.00         0.00
A1CF         0.00         0.00         0.00         0.00         0.00
A2M         34.57         0.00       137.88        11.89       173.49
A2M-AS1     94.17         0.00         0.00         0.00         0.00
A2ML1        0.00         1.96         0.92         0.00         0.00
A2ML1-AS1    0.00         0.00         0.00         0.00         0.00
A2ML1-AS2    0.00         0.00         0.00         0.00         0.00
A3GALT2      0.00         0.00         0.00         0.00         0.00
A4GALT       0.00         0.00         0.00         0.00         0.00
A4GNT        0.00         0.00         0.00         0.00         0.00
AAAS         0.00       247.26       213.81        44.79       100.14
AACS         3.34         7.53         0.00         0.00        48.52
AADAC        0.00         0.00         0.00         0.00         0.00
AADACL2      0.00         0.00         0.00         0.00         0.00
AADACL3      0.00         0.00         0.00         0.00         0.00
AADACL4      0.00         0.00         0.00         0.00         0.00
AADAT        8.20        58.82         0.00         0.00         0.00
PRXL2C      50.54        18.81         0.00         6.28         0.00
AAGAB        0.00       135.36         0.00         0.00       124.45
AAK1         8.39       471.76         0.00        11.94        10.54
AAMDC      208.26         0.00         0.00       103.15        15.77
AAMP         0.00         0.00         2.99        70.94       144.30
AANAT        0.00         0.00         0.00         0.00         0.00
AAR2         0.00         0.00         0.00         0.00        39.40
AARD         0.00         0.00         0.00         0.00         0.00
AARS1      114.20         0.00        76.11        37.79        21.41
AARS2        2.14         0.00         0.00         1.33        26.18
⋮          ⋮            ⋮            ⋮            ⋮            ⋮
ZSWIM1       0.00         2.42        26.32         0.00         2.32
ZSWIM2       0.00         0.00         0.00         0.00         0.00
ZSWIM3       0.00         4.84         0.00        41.40         0.00
ZSWIM4       0.00         0.00         0.00         3.51         0.00
ZSWIM5       1.39         0.00         0.00        12.95         0.00
ZSWIM6       0.00         0.00         0.00         0.00         0.00
ZSWIM7     130.83         0.00       173.69       253.52        89.12
ZSWIM8      36.30         0.00        68.21         6.24       160.50
ZSWIM8-AS1   0.00         0.00         0.00         0.00         0.00
ZUP1         0.00         0.00         0.00         0.00         0.00
ZW10         0.00         0.00         0.00         0.00         0.00
ZWILCH       0.00         0.00         0.00        59.55         0.00
ZWINT        0.00         0.00         0.00         0.00         0.00
ZXDA         0.00         0.00         0.00        17.45         0.00
ZXDB         0.00         0.00         0.00         0.00         0.00
ZXDC         0.00         0.00         0.00         0.00        12.93
ZYG11A       0.00         4.99         0.00         0.00         0.00
ZYG11B      28.35         0.79        10.76         1.23         0.00
ZYX          0.00         0.00         0.00         0.00         0.00
ZZEF1        0.00        32.78         0.00        56.56         0.00
ZZZ3         0.00       212.24         0.00        21.98        17.80
MIR1199      0.00         0.00         0.00         0.00        25.18
MIR1253      0.00         0.00         0.00         0.00         0.00
MIR125A      0.00         0.00         0.00         0.00         0.00
MIR150       0.00         0.00         0.00         0.00         0.00
MIR335      45.58         0.00         0.00         0.00         0.00
MIR490       0.00         0.00         0.00         0.00        26.67
MIR7515      0.00         0.00         0.00         0.00         0.00
MIR8072      0.00         0.00         0.00         0.00         0.00
snoU13       0.00         0.00         0.00         0.00         0.00
           MUV87.P2.H11 MUV87.P2.H12
5S_rRNA      0.00       0
RN7SK        0.00       0
A1BG         0.00       0
A1BG-AS1     0.00       0
A1CF         0.00       0
A2M          0.00       0
A2M-AS1      0.00       0
A2ML1        0.00       0
A2ML1-AS1    0.00       0
A2ML1-AS2    0.00       0
A3GALT2      0.00       0
A4GALT       0.00       0
A4GNT        0.00       0
AAAS       149.69       0
AACS        17.84       0
AADAC        0.00       0
AADACL2      0.00       0
AADACL3      0.00       0
AADACL4      0.00       0
AADAT        0.00       0
PRXL2C      19.17       0
AAGAB        0.00       0
AAK1        35.39       0
AAMDC       14.97       0
AAMP       333.94       0
AANAT        8.63       0
AAR2         0.00       0
AARD         0.00       0
AARS1      161.97       0
AARS2        0.00       0
⋮          ⋮            ⋮
ZSWIM1       8.62       0
ZSWIM2       0.00       0
ZSWIM3       0.00       0
ZSWIM4       2.72       0
ZSWIM5       0.00       0
ZSWIM6      18.15       0
ZSWIM7     223.75       0
ZSWIM8       0.00       0
ZSWIM8-AS1   0.00       0
ZUP1         0.00       0
ZW10         0.00       0
ZWILCH       0.00       0
ZWINT        0.00       0
ZXDA         0.00       0
ZXDB        46.28       0
ZXDC         0.00       0
ZYG11A       0.00       0
ZYG11B       0.00       0
ZYX          0.00       0
ZZEF1        0.00       0
ZZZ3         0.00       0
MIR1199      0.00       0
MIR1253      0.00       0
MIR125A      0.00       0
MIR150       0.00       0
MIR335       0.00       0
MIR490       0.00       0
MIR7515      0.00       0
MIR8072      1.41       0
snoU13       0.00       0

In [6]:
sn_mtx <- fread(paste0(path.dir, 'GSE184357_counts_frozen_preFilter.txt.gz')) %>%
            column_to_rownames('V1')
gene.names <- checkGeneSymbols(rownames(sn_mtx), unmapped.as.na=FALSE)
gene.names
rownames(sn_mtx) <- make.unique(gene.names$Suggested.Symbol)
sn_mtx

Warning message in fread(paste0(path.dir, "GSE184357_counts_frozen_preFilter.txt.gz")):
“Detected 10176 column names but the data has 10177 columns (i.e. invalid file). Added 1 extra default column name for the first column which is guessed to be row names or an index. Use setnames() afterwards if this guess is not correct, or fix the file write command that created the file to create a valid file.”
Maps last updated on: Thu Oct 24 12:31:05 2019

Warning message in checkGeneSymbols(rownames(sn_mtx), unmapped.as.na = FALSE):
“Human gene symbols should be all upper-case except for the 'orf' in open reading frames. The case of some letters was corrected.”
Warning message in checkGeneSymbols(rownames(sn_mtx), unmapped.as.na = FALSE):
“x contains non-approved gene symbols”

      x            Approved Suggested.Symbol
1     5S_rRNA      FALSE    5S_rRNA
2     7SK          FALSE    RN7SK
3     A1BG          TRUE    A1BG
4     A1BG-AS1      TRUE    A1BG-AS1
5     A1CF          TRUE    A1CF
6     A2M           TRUE    A2M
7     A2M-AS1       TRUE    A2M-AS1
8     A2ML1         TRUE    A2ML1
9     A2ML1-AS1     TRUE    A2ML1-AS1
10    A2ML1-AS2     TRUE    A2ML1-AS2
11    A3GALT2       TRUE    A3GALT2
12    A4GALT        TRUE    A4GALT
13    A4GNT         TRUE    A4GNT
14    AAAS          TRUE    AAAS
15    AACS          TRUE    AACS
16    AADAC         TRUE    AADAC
17    AADACL2       TRUE    AADACL2
18    AADACL3       TRUE    AADACL3
19    AADACL4       TRUE    AADACL4
20    AADAT         TRUE    AADAT
21    AAED1        FALSE    PRXL2C
22    AAGAB         TRUE    AAGAB
23    AAK1          TRUE    AAK1
24    AAMDC         TRUE    AAMDC
25    AAMP          TRUE    AAMP
26    AANAT         TRUE    AANAT
27    AAR2          TRUE    AAR2
28    AARD          TRUE    AARD
29    AARS         FALSE    AARS1
30    AARS2         TRUE    AARS2
⋮     ⋮            ⋮        ⋮
32588 ZSWIM1        TRUE    ZSWIM1
32589 ZSWIM2        TRUE    ZSWIM2
32590 ZSWIM3        TRUE    ZSWIM3
32591 ZSWIM4        TRUE    ZSWIM4
32592 ZSWIM5        TRUE    ZSWIM5
32593 ZSWIM6        TRUE    ZSWIM6
32594 ZSWIM7        TRUE    ZSWIM7
32595 ZSWIM8        TRUE    ZSWIM8
32596 ZSWIM8-AS1    TRUE    ZSWIM8-AS1
32597 ZUFSP        FALSE    ZUP1
32598 ZW10          TRUE    ZW10
32599 ZWILCH        TRUE    ZWILCH
32600 ZWINT         TRUE    ZWINT
32601 ZXDA          TRUE    ZXDA
32602 ZXDB          TRUE    ZXDB
32603 ZXDC          TRUE    ZXDC
32604 ZYG11A        TRUE    ZYG11A
32605 ZYG11B        TRUE    ZYG11B
32606 ZYX           TRUE    ZYX
32607 ZZEF1         TRUE    ZZEF1
32608 ZZZ3          TRUE    ZZZ3
32609 hsa-mir-1199 FALSE    MIR1199
32610 hsa-mir-1253 FALSE    MIR1253
32611 hsa-mir-125a FALSE    MIR125A
32612 hsa-mir-150  FALSE    MIR150
32613 hsa-mir-335  FALSE    MIR335
32614 hsa-mir-490  FALSE    MIR490
32615 hsa-mir-7515 FALSE    MIR7515
32616 hsa-mir-8072 FALSE    MIR8072
32617 snoU13       FALSE    snoU13

           MUV82.P1.A01 MUV82.P1.A02 MUV82.P1.A03 MUV82.P1.A04 MUV82.P1.A05
5S_rRNA      0.00         0.00         0.00        0.00           0.00
RN7SK        0.00         0.00         0.00        0.00           0.00
A1BG         0.00         0.00         0.00        0.00           0.00
A1BG-AS1    24.28         0.00         0.00        0.00           0.00
A1CF         0.00         0.00         0.00        0.00           0.00
A2M         67.47       237.88       111.46        0.00        2715.89
A2M-AS1      0.00         0.00         0.00        0.00           0.00
A2ML1        0.00         0.00         0.00        0.00           0.00
A2ML1-AS1    1.16         0.00         0.00        0.00           0.00
A2ML1-AS2    0.00         0.00         0.00        0.00           0.00
A3GALT2      0.00         0.00         0.00        0.00           0.00
A4GALT       0.00         0.00         0.00        0.00           0.00
A4GNT        0.00         0.00         0.00        0.00           0.00
AAAS         0.00         0.00        81.25        0.00          40.63
AACS        70.68         0.00         1.68       47.44           0.00
AADAC        0.00         0.00         0.00        0.00           0.00
AADACL2      0.00         0.00         0.00        0.00           0.00
AADACL3      0.00         0.00         0.00        0.00           0.00
AADACL4      0.00         0.00         0.00        0.00           0.00
AADAT       10.96         0.00        30.27        0.00           0.00
PRXL2C      18.04         0.00        12.33        0.00           0.00
AAGAB        0.39         0.00         0.00        0.00         466.59
AAK1       177.13       897.12       110.96        0.00          45.97
AAMDC        0.47         0.00         0.15        0.00           0.00
AAMP         3.53         0.00         0.00        0.00           0.00
AANAT        0.00        22.92         0.00        0.00          30.03
AAR2         0.61         0.00         6.26        0.00           0.00
AARD         0.00         0.00         0.00        0.00           0.00
AARS1        0.57         0.00         4.52        0.00           0.00
AARS2        5.72         0.00         0.00        0.00           3.31
⋮          ⋮            ⋮            ⋮            ⋮            ⋮
ZSWIM1      0.00           0.00         0.00      0              0.00
ZSWIM2      0.00           0.00         0.00      0              0.00
ZSWIM3      1.97           0.00         0.00      0              0.00
ZSWIM4      0.57           0.00         0.79      0              0.00
ZSWIM5      0.39           0.06         8.47      0              0.05
ZSWIM6     12.47           4.99        15.29      0             14.47
ZSWIM7      0.00           0.00        56.78      0              0.00
ZSWIM8      6.60           0.00       101.32      0              0.00
ZSWIM8-AS1  0.00           0.00        79.92      0              0.00
ZUP1       31.36           0.00       135.39      0              0.02
ZW10        0.00           0.42         0.36      0              0.00
ZWILCH      0.47           0.00         0.00      0              0.00
ZWINT       0.00           0.00         0.00      0              0.00
ZXDA        0.00           0.00         0.00      0              0.00
ZXDB        0.00           0.00         0.00      0              0.00
ZXDC       31.38           0.00         0.00      0              0.00
ZYG11A      0.00           0.00         0.28      0              0.00
ZYG11B      0.83           0.58         0.00      0              3.08
ZYX         0.00           0.00         0.00      0              0.00
ZZEF1      77.83        1544.87        39.53      0            642.78
ZZZ3       20.74         241.68         7.40      0              0.00
MIR1199     0.00           0.00         0.00      0              0.00
MIR1253     0.00           0.00         0.00      0              0.00
MIR125A     0.00           0.00         0.00      0              0.00
MIR150      0.00           0.00         0.00      0              0.00
MIR335      0.00           0.00         0.00      0              0.00
MIR490      0.13           0.04         0.15      0              0.00
MIR7515     0.00           0.00         0.00      0              0.00
MIR8072     0.00           0.00         0.00      0              0.00
snoU13      0.00        2918.57      2340.49      0              0.00
           MUV82.P1.A06 MUV82.P1.A07 MUV82.P1.A08 MUV82.P1.A09 MUV82.P1.A10 ⋯
5S_rRNA      0.00         0.00         0.00          0.00       0.00        ⋯
RN7SK        0.00         0.00         0.00          0.40       0.00        ⋯
A1BG         0.00         0.00         0.00       1290.30       0.00        ⋯
A1BG-AS1     0.00         0.00         0.00          0.00       0.00        ⋯
A1CF         0.00         0.00         0.00          0.71       0.00        ⋯
A2M          0.00         0.00        62.45         81.05       0.29        ⋯
A2M-AS1      0.00         0.00         0.00          0.00       0.00        ⋯
A2ML1        0.00         0.00         0.00          0.00       0.00        ⋯
A2ML1-AS1    0.00         0.00         0.00          0.00       0.00        ⋯
A2ML1-AS2    0.00         0.00         0.00          0.00       0.00        ⋯
A3GALT2      0.00         0.00         0.00          0.00       0.00        ⋯
A4GALT       0.00         0.34         0.00          0.00       0.00        ⋯
A4GNT        0.00         0.00         0.00          0.00       0.00        ⋯
AAAS         0.00         0.00       464.83          0.00       0.00        ⋯
AACS         0.00         0.00         0.08          0.00       8.81        ⋯
AADAC        0.00         0.00         0.00          0.00       0.00        ⋯
AADACL2      0.00         0.00         0.00          0.00       0.00        ⋯
AADACL3      0.00         0.00         0.00          0.00       0.00        ⋯
AADACL4      0.00         0.00         0.00          0.00       0.00        ⋯
AADAT        0.00         0.00         0.00          0.00       0.00        ⋯
PRXL2C       0.00         0.00         0.00        667.29       0.00        ⋯
AAGAB       20.01         0.00         0.00          0.00       0.00        ⋯
AAK1       605.74       346.98       363.64         51.27       0.00        ⋯
AAMDC        0.13         0.00         0.00          0.00      28.54        ⋯
AAMP         0.00        89.17         0.00          0.00       0.00        ⋯
AANAT        0.00         0.00         0.00          0.00       0.00        ⋯
AAR2         0.00         0.00         0.00          0.00       0.00        ⋯
AARD         0.00         0.00         0.00          0.00       0.00        ⋯
AARS1        0.00         0.00         0.00         11.51       0.00        ⋯
AARS2        0.00         0.00         0.00          0.00       0.00        ⋯
⋮          ⋮            ⋮            ⋮            ⋮            ⋮            ⋱
ZSWIM1       0.00          0.00        0.00       0.00            0.00      ⋯
ZSWIM2       0.00          0.00        0.00       0.00            0.00      ⋯
ZSWIM3       0.00          0.00        0.00       0.00            0.00      ⋯
ZSWIM4       0.00          0.00        0.00       0.00            0.00      ⋯
ZSWIM5       4.54          0.04        0.00       1.03           69.60      ⋯
ZSWIM6     105.96          0.00       22.70       0.67            0.10      ⋯
ZSWIM7       0.00          0.00        0.00       0.00            0.00      ⋯
ZSWIM8       0.00          0.00        0.00       0.00            0.00      ⋯
ZSWIM8-AS1   0.00          0.00        0.00       0.00            0.00      ⋯
ZUP1         0.46          1.92      486.28       0.00            0.00      ⋯
ZW10         0.00          0.00        0.14       0.00            0.00      ⋯
ZWILCH       0.00          0.00        0.00       0.00            0.00      ⋯
ZWINT        0.00          0.00        0.00       0.00            0.00      ⋯
ZXDA         0.00          0.00        0.00       0.00            0.00      ⋯
ZXDB         0.00          0.00        0.00       0.00            0.00      ⋯
ZXDC         0.00          0.00        0.00       0.00           34.95      ⋯
ZYG11A       0.00          0.00        0.00       0.00            0.00      ⋯
ZYG11B       0.00          0.00        0.12       0.00            0.00      ⋯
ZYX          0.00          0.00        0.00       0.00            0.00      ⋯
ZZEF1        0.00          0.50        0.00       0.00            0.00      ⋯
ZZZ3         0.99         79.44        0.00       0.00           21.04      ⋯
MIR1199      0.00          0.00        0.00       0.00            0.00      ⋯
MIR1253      0.00          0.00        0.00       0.00            0.00      ⋯
MIR125A      0.00          0.00        0.00       0.00            0.00      ⋯
MIR150       0.00          0.00        0.00       0.00            0.00      ⋯
MIR335       0.00          0.00        0.00       0.00            0.00      ⋯
MIR490       0.03          0.01        0.00       0.06            0.01      ⋯
MIR7515      0.00          0.00        0.00       0.00            0.00      ⋯
MIR8072      0.00          0.00        0.00       0.00            0.00      ⋯
snoU13       0.00       3816.32        0.00       0.00         7341.07      ⋯
           S1D2E3H7.P2.H03 S1D2E3H7.P2.H04 S1D2E3H7.P2.H05 S1D2E3H7.P2.H06
5S_rRNA      0.00          0.00               0.0          0
RN7SK        0.00          0.00               0.0          0
A1BG         0.00          0.00               0.0          0
A1BG-AS1     0.00          0.00               0.0          0
A1CF         0.00          0.77               0.0          0
A2M          0.00          0.00            7445.1          0
A2M-AS1      0.00          0.00               0.0          0
A2ML1        0.00          0.00               0.0          0
A2ML1-AS1    0.00          0.00               0.0          0
A2ML1-AS2    0.00          0.00               0.0          0
A3GALT2      0.00          4.67               0.0          0
A4GALT      22.94          0.00               0.0          0
A4GNT        0.00          0.00               0.0          0
AAAS         0.00          0.00               0.0          0
AACS       120.62          0.00               0.0          0
AADAC        0.00          0.00               0.0          0
AADACL2      0.00          0.00               0.0          0
AADACL3      0.00          0.00               0.0          0
AADACL4      0.00          0.00               0.0          0
AADAT        0.00          0.00               0.0          0
PRXL2C       0.00          0.00               0.0          0
AAGAB        8.22          0.00               0.0          0
AAK1         0.00          0.00               0.0          0
AAMDC        0.00          0.00               0.0          0
AAMP         0.00          0.00               0.0          0
AANAT        0.00          0.00               0.0          0
AAR2         0.00          0.00               0.0          0
AARD         0.00          0.00               0.0          0
AARS1        0.00          0.00               0.0          0
AARS2        0.00          0.00               0.0          0
⋮          ⋮               ⋮               ⋮               ⋮
ZSWIM1     0.00            0.00            0               0
ZSWIM2     0.00            0.00            0               0
ZSWIM3     0.00            0.00            0               0
ZSWIM4     0.00            0.00            0               0
ZSWIM5     1.47            0.94            0               0
ZSWIM6     0.00            0.00            0               0
ZSWIM7     0.00            0.00            0               0
ZSWIM8     0.00            0.00            0               0
ZSWIM8-AS1 0.00            0.00            0               0
ZUP1       0.00            0.00            0               0
ZW10       4.42            0.00            0               0
ZWILCH     0.00            0.00            0               0
ZWINT      0.00            0.00            0               0
ZXDA       0.00            0.00            0               0
ZXDB       0.00            0.00            0               0
ZXDC       0.00            0.00            0               0
ZYG11A     0.00            0.00            0               0
ZYG11B     0.00            0.00            0               0
ZYX        0.00            0.00            0               0
ZZEF1      0.00            0.00            0               0
ZZZ3       0.00            0.00            0               0
MIR1199    0.00            0.00            0               0
MIR1253    0.00            0.00            0               0
MIR125A    0.00            0.00            0               0
MIR150     0.00            0.00            0               0
MIR335     0.00            0.00            0               0
MIR490     0.71            0.13            0               0
MIR7515    0.00            0.00            0               0
MIR8072    0.00            0.00            0               0
snoU13     0.00            0.00            0               0
           S1D2E3H7.P2.H07 S1D2E3H7.P2.H08 S1D2E3H7.P2.H09 S1D2E3H7.P2.H10
5S_rRNA       0.00            0.00             0.00        0
RN7SK         0.00            0.00             0.00        0
A1BG          0.00            0.00             0.00        0
A1BG-AS1      0.00            0.00             0.00        0
A1CF          1.72            0.00             0.00        0
A2M           0.00            0.00             3.78        0
A2M-AS1       0.00            0.00             0.00        0
A2ML1         0.00            0.00             5.69        0
A2ML1-AS1     0.00            0.00             0.00        0
A2ML1-AS2     0.00            0.00             0.00        0
A3GALT2       0.00            0.00            16.05        0
A4GALT        0.00            0.00             0.00        0
A4GNT         0.00            0.00             0.00        0
AAAS          0.00            0.00             0.00        0
AACS          0.00         6195.41             0.00        0
AADAC         0.00            0.00             0.00        0
AADACL2       0.00            0.00             0.00        0
AADACL3       0.00            0.00             0.00        0
AADACL4       0.00            0.00             0.00        0
AADAT         0.00            0.00             0.00        0
PRXL2C        0.00            0.00             0.00        0
AAGAB       104.14            0.00             0.00        0
AAK1          0.00            0.00         11314.97        0
AAMDC         6.39            0.00             0.00        0
AAMP          0.00            0.00             0.00        0
AANAT      1184.68            0.00             0.00        0
AAR2          4.31            0.00             0.00        0
AARD          0.00            0.00             0.00        0
AARS1         0.00            0.00             0.00        0
AARS2         0.00            0.00             0.00        0
⋮          ⋮               ⋮               ⋮               ⋮
ZSWIM1     0.00            0                   0.00        0
ZSWIM2     0.00            0                   0.00        0
ZSWIM3     0.00            0                   0.00        0
ZSWIM4     0.00            0                   0.00        0
ZSWIM5     6.13            0                   0.00        0
ZSWIM6     0.00            0                   0.00        0
ZSWIM7     0.00            0                   0.00        0
ZSWIM8     0.00            0                   0.00        0
ZSWIM8-AS1 0.00            0                   0.00        0
ZUP1       4.48            0                   0.00        0
ZW10       0.00            0                   0.00        0
ZWILCH     0.00            0                   0.00        0
ZWINT      0.00            0                   0.00        0
ZXDA       0.00            0                   0.00        0
ZXDB       0.00            0                   0.00        0
ZXDC       0.00            0                   0.00        0
ZYG11A     8.48            0                   0.00        0
ZYG11B     0.00            0                   0.00        0
ZYX        0.00            0                   0.00        0
ZZEF1      0.00            0                   5.29        0
ZZZ3       0.00            0                   0.00        0
MIR1199    0.00            0                   0.00        0
MIR1253    0.00            0                   0.00        0
MIR125A    0.00            0                   0.00        0
MIR150     0.00            0                   0.00        0
MIR335     0.00            0                   0.00        0
MIR490     0.00            0                   0.70        0
MIR7515    0.00            0                   0.00        0
MIR8072    0.00            0                   0.00        0
snoU13     0.00            0               18501.96        0
           S1D2E3H7.P2.H11 S1D2E3H7.P2.H12
5S_rRNA     0.00             0.00
RN7SK       0.00            38.05
A1BG        0.00             0.00
A1BG-AS1    0.00             3.12
A1CF        0.00             0.31
A2M         0.00             0.97
A2M-AS1     0.00             0.00
A2ML1       0.00            70.12
A2ML1-AS1   0.00             2.48
A2ML1-AS2   0.00             0.00
A3GALT2     0.00             0.00
A4GALT      0.00             0.00
A4GNT       0.00             0.00
AAAS        0.00            37.86
AACS        0.00            10.68
AADAC       0.00            27.79
AADACL2     0.00             0.00
AADACL3     0.00           144.09
AADACL4     0.00             0.00
AADAT       0.00             0.00
PRXL2C      0.00             8.89
AAGAB      17.93             4.29
AAK1        0.00            11.73
AAMDC       1.66            46.55
AAMP        0.00             8.02
AANAT       0.00             0.00
AAR2        0.00             0.00
AARD        0.00           125.69
AARS1       0.00             1.21
AARS2       0.00             7.88
⋮          ⋮               ⋮
ZSWIM1      0.00              8.65
ZSWIM2      0.00              0.00
ZSWIM3      0.00              2.18
ZSWIM4      0.00              2.12
ZSWIM5      0.00              7.76
ZSWIM6      0.38              0.23
ZSWIM7      0.00              6.43
ZSWIM8      0.00             54.68
ZSWIM8-AS1  0.00              0.00
ZUP1        0.00              1.51
ZW10        0.00              2.25
ZWILCH      0.00              2.92
ZWINT       0.00              0.00
ZXDA        0.00              0.00
ZXDB        0.00              0.00
ZXDC        0.00             82.51
ZYG11A      0.00             23.56
ZYG11B      0.00             17.43
ZYX         0.00              0.00
ZZEF1       0.00            280.33
ZZZ3       18.47              0.22
MIR1199     0.00              0.00
MIR1253     0.00              0.00
MIR125A     0.00              0.00
MIR150      0.00              0.00
MIR335     64.46              0.00
MIR490      0.00              1.59
MIR7515     0.00             17.64
MIR8072     0.00              0.00
snoU13      0.00           4674.31

In [7]:
sc_meta <- fread(paste0(path.dir, 'GSE184357_metadata_fresh_postFilter.txt.gz')) %>%
            column_to_rownames('cell')  %>% mutate(Isolation_method_by_cell = 'Cell')
sc_meta

              sample age       location annotation
BT1126.P1.A01 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.A02 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.A04 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.A07 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.A08 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.A09 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.B01 BT1126 pediatric pontine  Microglia
BT1126.P1.B03 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.B04 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.B05 BT1126 pediatric pontine  OC-like
BT1126.P1.B06 BT1126 pediatric pontine  Microglia
BT1126.P1.B08 BT1126 pediatric pontine  S
BT1126.P1.B10 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.B11 BT1126 pediatric pontine  AC-like
BT1126.P1.C01 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.C02 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.C03 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.C04 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.C05 BT1126 pediatric pontine  Microglia
BT1126.P1.C07 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.C09 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.C10 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.C11 BT1126 pediatric pontine  S
BT1126.P1.C12 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.D01 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.D02 BT1126 pediatric pontine  OPC-like-3
BT1126.P1.D03 BT1126 pediatric pontine  Oligodendrocyte
BT1126.P1.D05 BT1126 pediatric pontine  OPC-like-2
BT1126.P1.D07 BT1126 pediatric pontine  OPC-like-3
BT1126.P1.D08 BT1126 pediatric pontine  OPC-like-2
⋮             ⋮      ⋮         ⋮        ⋮
MUV87.P2.F04  MUV87  pediatric pontine  OPC-like-2
MUV87.P2.F05  MUV87  pediatric pontine  OPC-like-2
MUV87.P2.F06  MUV87  pediatric pontine  AC-like
MUV87.P2.F07  MUV87  pediatric pontine  OPC-like-1
MUV87.P2.F08  MUV87  pediatric pontine  OPC-like-2
MUV87.P2.F09  MUV87  pediatric pontine  OPC-like-2
MUV87.P2.F10  MUV87  pediatric pontine  S
MUV87.P2.F11  MUV87  pediatric pontine  OPC-like-1
MUV87.P2.G01  MUV87  pediatric pontine  OPC-like-2
MUV87.P2.G02  MUV87  pediatric pontine  OPC-like-2
MUV87.P2.G03  MUV87  pediatric pontine  OPC-like-1
MUV87.P2.G04  MUV87  pediatric pontine  OPC-like-2
MUV87.P2.G05  MUV87  pediatric pontine  G2M
MUV87.P2.G06  MUV87  pediatric pontine  OPC-like-2
MUV87.P2.G07  MUV87  pediatric pontine  MES-like
MUV87.P2.G09  MUV87  pediatric pontine  OPC-like-1
MUV87.P2.G10  MUV87  pediatric pontine  OPC-like-2
MUV87.P2.G11  MUV87  pediatric pontine  OPC-like-3
MUV87.P2.G12  MUV87  pediatric pontine  S
MUV87.P2.H01  MUV87  pediatric pontine  OPC-like-3
MUV87.P2.H02  MUV87  pediatric pontine  OPC-like-2
MUV87.P2.H03  MUV87  pediatric pontine  OPC-like-2
MUV87.P2.H04  MUV87  pediatric pontine  OPC-like-1
MUV87.P2.H05  MUV87  pediatric pontine  OC-like
MUV87.P2.H06  MUV87  pediatric pontine  OPC-like-2
MUV87.P2.H07  MUV87  pediatric pontine  OPC-like-2
MUV87.P2.H08  MUV87  pediatric pontine  AC-like
MUV87.P2.H09  MUV87  pediatric pontine  OPC-like-2
MUV87.P2.H10  MUV87  pediatric pontine  AC-like
MUV87.P2.H11  MUV87  pediatric pontine  OC-like
              Isolation_method_by_cell
BT1126.P1.A01 Cell
BT1126.P1.A02 Cell
BT1126.P1.A04 Cell
BT1126.P1.A07 Cell
BT1126.P1.A08 Cell
BT1126.P1.A09 Cell
BT1126.P1.B01 Cell
BT1126.P1.B03 Cell
BT1126.P1.B04 Cell
BT1126.P1.B05 Cell
BT1126.P1.B06 Cell
BT1126.P1.B08 Cell
BT1126.P1.B10 Cell
BT1126.P1.B11 Cell
BT1126.P1.C01 Cell
BT1126.P1.C02 Cell
BT1126.P1.C03 Cell
BT1126.P1.C04 Cell
BT1126.P1.C05 Cell
BT1126.P1.C07 Cell
BT1126.P1.C09 Cell
BT1126.P1.C10 Cell
BT1126.P1.C11 Cell
BT1126.P1.C12 Cell
BT1126.P1.D01 Cell
BT1126.P1.D02 Cell
BT1126.P1.D03 Cell
BT1126.P1.D05 Cell
BT1126.P1.D07 Cell
BT1126.P1.D08 Cell
⋮             ⋮
MUV87.P2.F04  Cell
MUV87.P2.F05  Cell
MUV87.P2.F06  Cell
MUV87.P2.F07  Cell
MUV87.P2.F08  Cell
MUV87.P2.F09  Cell
MUV87.P2.F10  Cell
MUV87.P2.F11  Cell
MUV87.P2.G01  Cell
MUV87.P2.G02  Cell
MUV87.P2.G03  Cell
MUV87.P2.G04  Cell
MUV87.P2.G05  Cell
MUV87.P2.G06  Cell
MUV87.P2.G07  Cell
MUV87.P2.G09  Cell
MUV87.P2.G10  Cell
MUV87.P2.G11  Cell
MUV87.P2.G12  Cell
MUV87.P2.H01  Cell
MUV87.P2.H02  Cell
MUV87.P2.H03  Cell
MUV87.P2.H04  Cell
MUV87.P2.H05  Cell
MUV87.P2.H06  Cell
MUV87.P2.H07  Cell
MUV87.P2.H08  Cell
MUV87.P2.H09  Cell
MUV87.P2.H10  Cell
MUV87.P2.H11  Cell

In [8]:
sn_meta <- fread(paste0(path.dir, 'GSE184357_metadata_frozen_postFilter.txt.gz')) %>%
            column_to_rownames('cell') %>% mutate(Isolation_method_by_cell = 'Nuclei')
sn_meta

                sample   age       location annotation
MUV82.P1.A02    MUV82    adult     thalamic Myeloid
MUV82.P1.A05    MUV82    adult     thalamic Myeloid
MUV82.P1.A06    MUV82    adult     thalamic Oligodendrocyte
MUV82.P1.A07    MUV82    adult     thalamic T cell
MUV82.P1.A08    MUV82    adult     thalamic T cell
MUV82.P1.A09    MUV82    adult     thalamic Myeloid
MUV82.P1.A10    MUV82    adult     thalamic OPC-like-1
MUV82.P1.A11    MUV82    adult     thalamic Myeloid
MUV82.P1.B01    MUV82    adult     thalamic MES-like
MUV82.P1.B02    MUV82    adult     thalamic AC-like
MUV82.P1.B03    MUV82    adult     thalamic AC-like
MUV82.P1.B04    MUV82    adult     thalamic MES-like
MUV82.P1.B05    MUV82    adult     thalamic Myeloid
MUV82.P1.B06    MUV82    adult     thalamic MES-like
MUV82.P1.B07    MUV82    adult     thalamic T cell
MUV82.P1.B08    MUV82    adult     thalamic AC-like
MUV82.P1.B09    MUV82    adult     thalamic MES-like
MUV82.P1.B10    MUV82    adult     thalamic Myeloid
MUV82.P1.B11    MUV82    adult     thalamic MES-like
MUV82.P1.C01    MUV82    adult     thalamic Myeloid
MUV82.P1.C02    MUV82    adult     thalamic AC-like
MUV82.P1.C03    MUV82    adult     thalamic MES-like
MUV82.P1.C04    MUV82    adult     thalamic score-too-low
MUV82.P1.C05    MUV82    adult     thalamic Myeloid
MUV82.P1.C06    MUV82    adult     thalamic MES-like
MUV82.P1.C07    MUV82    adult     thalamic MES-like
MUV82.P1.C08    MUV82    adult     thalamic MES-like
MUV82.P1.C09    MUV82    adult     thalamic OPC-like-3
MUV82.P1.C10    MUV82    adult     thalamic Myeloid
MUV82.P1.C12    MUV82    adult     thalamic AC-like
⋮               ⋮        ⋮         ⋮        ⋮
pSCG1.P8.A10    pSCG1    pediatric spinal   Endothelia
pSCG1.P8.B04    pSCG1    pediatric spinal   OC-like
pSCG1.P8.B07    pSCG1    pediatric spinal   Myeloid
pSCG1.P8.B10    pSCG1    pediatric spinal   AC-like
pSCG1.P8.B11    pSCG1    pediatric spinal   AC-like
pSCG1.P8.C02    pSCG1    pediatric spinal   Oligodendrocyte
pSCG1.P8.C04    pSCG1    pediatric spinal   AC-like
pSCG1.P8.C07    pSCG1    pediatric spinal   OC-like
pSCG1.P8.C09    pSCG1    pediatric spinal   OC-like
pSCG1.P8.C12    pSCG1    pediatric spinal   frozen-OPC-like-b
pSCG1.P8.D05    pSCG1    pediatric spinal   frozen-OPC-like-b
pSCG1.P8.D06    pSCG1    pediatric spinal   Oligodendrocyte
pSCG1.P8.D07    pSCG1    pediatric spinal   OPC-like-1
pSCG1.P8.D09    pSCG1    pediatric spinal   Myeloid
pSCG1.P8.D11    pSCG1    pediatric spinal   Oligodendrocyte
pSCG1.P8.E02    pSCG1    pediatric spinal   Myeloid
pSCG1.P8.E04    pSCG1    pediatric spinal   OC-like
pSCG1.P8.E09    pSCG1    pediatric spinal   AC-like
pSCG1.P8.F08    pSCG1    pediatric spinal   AC-like
pSCG1.P8.F10    pSCG1    pediatric spinal   Myeloid
pSCG1.P8.G01    pSCG1    pediatric spinal   G2M
pSCG1.P8.G05    pSCG1    pediatric spinal   AC-like
pSCG1.P8.G09    pSCG1    pediatric spinal   Myeloid
pSCG1.P8.H03    pSCG1    pediatric spinal   Oligodendrocyte
pSCG1.P8.H06    pSCG1    pediatric spinal   AC-like
S1D2E3H7.P2.B06 S1D2E3H7 adult     thalamic T cell
S1D2E3H7.P2.E06 S1D2E3H7 adult     thalamic T cell
S1D2E3H7.P2.E07 S1D2E3H7 adult     thalamic T cell
S1D2E3H7.P2.F09 S1D2E3H7 adult     thalamic T cell
S1D2E3H7.P2.G06 S1D2E3H7 adult     thalamic T cell
                Isolation_method_by_cell
MUV82.P1.A02    Nuclei
MUV82.P1.A05    Nuclei
MUV82.P1.A06    Nuclei
MUV82.P1.A07    Nuclei
MUV82.P1.A08    Nuclei
MUV82.P1.A09    Nuclei
MUV82.P1.A10    Nuclei
MUV82.P1.A11    Nuclei
MUV82.P1.B01    Nuclei
MUV82.P1.B02    Nuclei
MUV82.P1.B03    Nuclei
MUV82.P1.B04    Nuclei
MUV82.P1.B05    Nuclei
MUV82.P1.B06    Nuclei
MUV82.P1.B07    Nuclei
MUV82.P1.B08    Nuclei
MUV82.P1.B09    Nuclei
MUV82.P1.B10    Nuclei
MUV82.P1.B11    Nuclei
MUV82.P1.C01    Nuclei
MUV82.P1.C02    Nuclei
MUV82.P1.C03    Nuclei
MUV82.P1.C04    Nuclei
MUV82.P1.C05    Nuclei
MUV82.P1.C06    Nuclei
MUV82.P1.C07    Nuclei
MUV82.P1.C08    Nuclei
MUV82.P1.C09    Nuclei
MUV82.P1.C10    Nuclei
MUV82.P1.C12    Nuclei
⋮               ⋮
pSCG1.P8.A10    Nuclei
pSCG1.P8.B04    Nuclei
pSCG1.P8.B07    Nuclei
pSCG1.P8.B10    Nuclei
pSCG1.P8.B11    Nuclei
pSCG1.P8.C02    Nuclei
pSCG1.P8.C04    Nuclei
pSCG1.P8.C07    Nuclei
pSCG1.P8.C09    Nuclei
pSCG1.P8.C12    Nuclei
pSCG1.P8.D05    Nuclei
pSCG1.P8.D06    Nuclei
pSCG1.P8.D07    Nuclei
pSCG1.P8.D09    Nuclei
pSCG1.P8.D11    Nuclei
pSCG1.P8.E02    Nuclei
pSCG1.P8.E04    Nuclei
pSCG1.P8.E09    Nuclei
pSCG1.P8.F08    Nuclei
pSCG1.P8.F10    Nuclei
pSCG1.P8.G01    Nuclei
pSCG1.P8.G05    Nuclei
pSCG1.P8.G09    Nuclei
pSCG1.P8.H03    Nuclei
pSCG1.P8.H06    Nuclei
S1D2E3H7.P2.B06 Nuclei
S1D2E3H7.P2.E06 Nuclei
S1D2E3H7.P2.E07 Nuclei
S1D2E3H7.P2.F09 Nuclei
S1D2E3H7.P2.G06 Nuclei

In [9]:
sc <-  CreateSeuratObject(sc_mtx, min.features = 0, min.cells = 0,
                          meta.data = sc_meta,
                          project = 'sc_Liu2022')
sc$ID <- gsub("\\..*","\\1",colnames(sc))
sc$Batch_for_correction <- 'SmartSeq2_cell_rna'

sn <-  CreateSeuratObject(sn_mtx, min.features = 0, min.cells = 0,
                          meta.data = sn_meta,
                          project = 'sn_Liu2022')
sn$Batch_for_correction <- 'SmartSeq2_nuclei_rna'
sn$ID <- gsub("\\..*","\\1",colnames(sn))
sc
sn

Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”
Warning message:
“Feature names cannot have underscores ('_'), replacing with dashes ('-')”

An object of class Seurat
32617 features across 8251 samples within 1 assay
Active assay: RNA (32617 features, 0 variable features)

An object of class Seurat
32617 features across 10176 samples within 1 assay
Active assay: RNA (32617 features, 0 variable features)

In [10]:
Liu2022 <- merge(sc, sn,
                 add.cell.ids = c('sc', 'sn'), # Some cell names are duplicated across objects provided
                 #avoid it by adding source
                 project = "Liu2022", 
                 merge.data = FALSE)
Liu2022$Original_annotation <- Liu2022$annotation
Liu2022$SampleID <- Liu2022$ID
Liu2022$Data <- 'RNA_only'
Liu2022
str(Liu2022)

An object of class Seurat
32617 features across 18427 samples within 1 assay
Active assay: RNA (32617 features, 0 variable features)

Formal class 'Seurat' [package "SeuratObject"] with 13 slots
  ..@ assays      :List of 1
  .. ..$ RNA:Formal class 'Assay' [package "SeuratObject"] with 8 slots
  .. .. .. ..@ counts       :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:92979757] 1 13 14 20 22 24 29 30 33 38 ...
  .. .. .. .. .. ..@ p       : int [1:18428] 0 5364 11213 13818 19224 24676 25274 31102 36453 43284 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 32617 18427
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:32617] "5S-rRNA" "RN7SK" "A1BG" "A1BG-AS1" ...
  .. .. .. .. .. .. ..$ : chr [1:18427] "sc_BT1126.P1.A01" "sc_BT1126.P1.A02" "sc_BT1126.P1.A03" "sc_BT1126.P1.A04" ...
  .. .. .. .. .. ..@ x       : num [1:92979757] 5.68 249.4 0.31 0.36 1.36 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ data         :Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  .. .. .. .. .. ..@ i       : int [1:92979757] 1 13 14 20 22 24 29 30 33 38 ...
  .. .. .. .. .. ..@ p       : int [1:18428] 0 5364 11213 13818 19224 24676 25274 31102 36453 43284 ...
  .. .. .. .. .. ..@ Dim     : int [1:2] 32617 18427
  .. .. .. .. .. ..@ Dimnames:List of 2
  .. .. .. .. .. .. ..$ : chr [1:32617] "5S-rRNA" "RN7SK" "A1BG" "A1BG-AS1" ...
  .. .. .. .. .. .. ..$ : chr [1:18427] "sc_BT1126.P1.A01" "sc_BT1126.P1.A02" "sc_BT1126.P1.A03" "sc_BT1126.P1.A04" ...
  .. .. .. .. .. ..@ x       : num [1:92979757] 5.68 249.4 0.31 0.36 1.36 ...
  .. .. .. .. .. ..@ factors : list()
  .. .. .. ..@ scale.data   : num[0 , 0 ]
  .. .. .. ..@ key          : chr "rna_"
  .. .. .. ..@ assay.orig   : NULL
  .. .. .. ..@ var.features : logi(0)
  .. .. .. ..@ meta.features:'data.frame':	32617 obs. of  0 variables
  .. .. .. ..@ misc         : list()
  ..@ meta.data   :'data.frame':	18427 obs. of  13 variables:
  .. ..$ orig.ident              : chr [1:18427] "sc_Liu2022" "sc_Liu2022" "sc_Liu2022" "sc_Liu2022" ...
  .. ..$ nCount_RNA              : num [1:18427] 1e+06 1e+06 1e+06 1e+06 1e+06 ...
  .. ..$ nFeature_RNA            : int [1:18427] 5364 5849 2605 5406 5452 598 5828 5351 6831 2242 ...
  .. ..$ sample                  : chr [1:18427] "BT1126" "BT1126" NA "BT1126" ...
  .. ..$ age                     : chr [1:18427] "pediatric" "pediatric" NA "pediatric" ...
  .. ..$ location                : chr [1:18427] "pontine" "pontine" NA "pontine" ...
  .. ..$ annotation              : chr [1:18427] "OPC-like-2" "OPC-like-2" NA "OPC-like-2" ...
  .. ..$ Isolation_method_by_cell: chr [1:18427] "Cell" "Cell" NA "Cell" ...
  .. ..$ ID                      : chr [1:18427] "BT1126" "BT1126" "BT1126" "BT1126" ...
  .. ..$ Batch_for_correction    : chr [1:18427] "SmartSeq2_cell_rna" "SmartSeq2_cell_rna" "SmartSeq2_cell_rna" "SmartSeq2_cell_rna" ...
  .. ..$ Original_annotation     : chr [1:18427] "OPC-like-2" "OPC-like-2" NA "OPC-like-2" ...
  .. ..$ SampleID                : chr [1:18427] "BT1126" "BT1126" "BT1126" "BT1126" ...
  .. ..$ Data                    : chr [1:18427] "RNA_only" "RNA_only" "RNA_only" "RNA_only" ...
  ..@ active.assay: chr "RNA"
  ..@ active.ident: Factor w/ 2 levels "sc_Liu2022","sn_Liu2022": 1 1 1 1 1 1 1 1 1 1 ...
  .. ..- attr(*, "names")= chr [1:18427] "sc_BT1126.P1.A01" "sc_BT1126.P1.A02" "sc_BT1126.P1.A03" "sc_BT1126.P1.A04" ...
  ..@ graphs      : list()
  ..@ neighbors   : list()
  ..@ reductions  : list()
  ..@ images      : list()
  ..@ project.name: chr "Liu2022"
  ..@ misc        : list()
  ..@ version     :Classes 'package_version', 'numeric_version'  hidden list of 1
  .. ..$ : int [1:3] 4 1 3
  ..@ commands    : list()
  ..@ tools       : list()

In [11]:
Liu2022$orig.ident <- NULL
Liu2022$sample <- NULL
Liu2022$age <- NULL
Liu2022$location <- NULL
Liu2022$annotation <- NULL

In [12]:
# Since we will only include pediatric patients (<21yo), the meatadata provided only contains ID for samples that meet that criteria  
# We filter out samples from older patients
Liu2022 <- subset(Liu2022, subset = ID %in% (meta_cohort %>% 
                     filter(Study == 'Liu2022') %>% pull(ID)))
Liu2022

An object of class Seurat
32617 features across 13823 samples within 1 assay
Active assay: RNA (32617 features, 0 variable features)

In [13]:
Liu2022@meta.data

                 nCount_RNA nFeature_RNA Isolation_method_by_cell ID
sc_BT1126.P1.A01 1000000.0  5364         Cell                     BT1126
sc_BT1126.P1.A02 1000000.1  5849         Cell                     BT1126
sc_BT1126.P1.A03 1000000.0  2605         NA                       BT1126
sc_BT1126.P1.A04 1000000.1  5406         Cell                     BT1126
sc_BT1126.P1.A05 1000000.2  5452         NA                       BT1126
sc_BT1126.P1.A06 1000000.0   598         NA                       BT1126
sc_BT1126.P1.A07 1000000.0  5828         Cell                     BT1126
sc_BT1126.P1.A08 1000000.1  5351         Cell                     BT1126
sc_BT1126.P1.A09 1000000.0  6831         Cell                     BT1126
sc_BT1126.P1.A10  999999.9  2242         NA                       BT1126
sc_BT1126.P1.A11 1000000.1   357         NA                       BT1126
sc_BT1126.P1.A12  999999.9  1972         NA                       BT1126
sc_BT1126.P1.B01 1000000.0  4042         Cell                     BT1126
sc_BT1126.P1.B02  999999.8  1894         NA                       BT1126
sc_BT1126.P1.B03 1000000.0  6108         Cell                     BT1126
sc_BT1126.P1.B04 1000000.2  6885         Cell                     BT1126
sc_BT1126.P1.B05 1000000.2  6322         Cell                     BT1126
sc_BT1126.P1.B06 1000000.1  5398         Cell                     BT1126
sc_BT1126.P1.B07 1000000.0  1006         NA                       BT1126
sc_BT1126.P1.B08  999999.8  6382         Cell                     BT1126
sc_BT1126.P1.B09  999999.9  1372         NA                       BT1126
sc_BT1126.P1.B10 1000000.1  7152         Cell                     BT1126
sc_BT1126.P1.B11 1000000.2  4748         Cell                     BT1126
sc_BT1126.P1.B12  999999.9  3181         NA                       BT1126
sc_BT1126.P1.C01 1000000.3  5780         Cell                     BT1126
sc_BT1126.P1.C02 1000000.0  5983         Cell                     BT1126
sc_BT1126.P1.C03  999999.8  6032         Cell                     BT1126
sc_BT1126.P1.C04 1000000.2  7392         Cell                     BT1126
sc_BT1126.P1.C05 1000000.0  4671         Cell                     BT1126
sc_BT1126.P1.C06 1000000.0   320         NA                       BT1126
⋮                ⋮          ⋮            ⋮                        ⋮
sn_pSCG1.P8.F07  886920.3    2032        NA                       pSCG1
sn_pSCG1.P8.F08  893300.1    5916        Nuclei                   pSCG1
sn_pSCG1.P8.F09  601174.9    4829        NA                       pSCG1
sn_pSCG1.P8.F10  827229.5    4575        Nuclei                   pSCG1
sn_pSCG1.P8.F11  593717.1    4590        NA                       pSCG1
sn_pSCG1.P8.F12  669557.4    4926        NA                       pSCG1
sn_pSCG1.P8.G01  764468.4    3619        Nuclei                   pSCG1
sn_pSCG1.P8.G02  727263.2    5081        NA                       pSCG1
sn_pSCG1.P8.G03  638018.0    7809        NA                       pSCG1
sn_pSCG1.P8.G04  856622.7    1239        NA                       pSCG1
sn_pSCG1.P8.G05  939296.1    7057        Nuclei                   pSCG1
sn_pSCG1.P8.G06  571221.4    1764        NA                       pSCG1
sn_pSCG1.P8.G07  869420.6    7422        NA                       pSCG1
sn_pSCG1.P8.G08  732465.0    7957        NA                       pSCG1
sn_pSCG1.P8.G09  926399.6    3904        Nuclei                   pSCG1
sn_pSCG1.P8.G10  456809.2    3051        NA                       pSCG1
sn_pSCG1.P8.G11  897108.7   10520        NA                       pSCG1
sn_pSCG1.P8.G12  164104.2    2351        NA                       pSCG1
sn_pSCG1.P8.H01  560222.0    9322        NA                       pSCG1
sn_pSCG1.P8.H02  226173.1    1730        NA                       pSCG1
sn_pSCG1.P8.H03  834794.1    4746        Nuclei                   pSCG1
sn_pSCG1.P8.H04  579271.0    1863        NA                       pSCG1
sn_pSCG1.P8.H05  608634.3    3068        NA                       pSCG1
sn_pSCG1.P8.H06  917113.9    5764        Nuclei                   pSCG1
sn_pSCG1.P8.H07  328442.2    3540        NA                       pSCG1
sn_pSCG1.P8.H08  547979.2    6586        NA                       pSCG1
sn_pSCG1.P8.H09  265167.0    2002        NA                       pSCG1
sn_pSCG1.P8.H10  664162.4    3093        NA                       pSCG1
sn_pSCG1.P8.H11  663377.8    2861        NA                       pSCG1
sn_pSCG1.P8.H12  746343.1    8199        NA                       pSCG1
                 Batch_for_correction Original_annotation SampleID Data
sc_BT1126.P1.A01 SmartSeq2_cell_rna   OPC-like-2          BT1126   RNA_only
sc_BT1126.P1.A02 SmartSeq2_cell_rna   OPC-like-2          BT1126   RNA_only
sc_BT1126.P1.A03 SmartSeq2_cell_rna   NA                  BT1126   RNA_only
sc_BT1126.P1.A04 SmartSeq2_cell_rna   OPC-like-2          BT1126   RNA_only
sc_BT1126.P1.A05 SmartSeq2_cell_rna   NA                  BT1126   RNA_only
sc_BT1126.P1.A06 SmartSeq2_cell_rna   NA                  BT1126   RNA_only
sc_BT1126.P1.A07 SmartSeq2_cell_rna   OPC-like-2          BT1126   RNA_only
sc_BT1126.P1.A08 SmartSeq2_cell_rna   OPC-like-2          BT1126   RNA_only
sc_BT1126.P1.A09 SmartSeq2_cell_rna   OPC-like-2          BT1126   RNA_only
sc_BT1126.P1.A10 SmartSeq2_cell_rna   NA                  BT1126   RNA_only
sc_BT1126.P1.A11 SmartSeq2_cell_rna   NA                  BT1126   RNA_only
sc_BT1126.P1.A12 SmartSeq2_cell_rna   NA                  BT1126   RNA_only
sc_BT1126.P1.B01 SmartSeq2_cell_rna   Microglia           BT1126   RNA_only
sc_BT1126.P1.B02 SmartSeq2_cell_rna   NA                  BT1126   RNA_only
sc_BT1126.P1.B03 SmartSeq2_cell_rna   OPC-like-2          BT1126   RNA_only
sc_BT1126.P1.B04 SmartSeq2_cell_rna   OPC-like-2          BT1126   RNA_only
sc_BT1126.P1.B05 SmartSeq2_cell_rna   OC-like             BT1126   RNA_only
sc_BT1126.P1.B06 SmartSeq2_cell_rna   Microglia           BT1126   RNA_only
sc_BT1126.P1.B07 SmartSeq2_cell_rna   NA                  BT1126   RNA_only
sc_BT1126.P1.B08 SmartSeq2_cell_rna   S                   BT1126   RNA_only
sc_BT1126.P1.B09 SmartSeq2_cell_rna   NA                  BT1126   RNA_only
sc_BT1126.P1.B10 SmartSeq2_cell_rna   OPC-like-2          BT1126   RNA_only
sc_BT1126.P1.B11 SmartSeq2_cell_rna   AC-like             BT1126   RNA_only
sc_BT1126.P1.B12 SmartSeq2_cell_rna   NA                  BT1126   RNA_only
sc_BT1126.P1.C01 SmartSeq2_cell_rna   OPC-like-2          BT1126   RNA_only
sc_BT1126.P1.C02 SmartSeq2_cell_rna   OPC-like-2          BT1126   RNA_only
sc_BT1126.P1.C03 SmartSeq2_cell_rna   OPC-like-2          BT1126   RNA_only
sc_BT1126.P1.C04 SmartSeq2_cell_rna   OPC-like-2          BT1126   RNA_only
sc_BT1126.P1.C05 SmartSeq2_cell_rna   Microglia           BT1126   RNA_only
sc_BT1126.P1.C06 SmartSeq2_cell_rna   NA                  BT1126   RNA_only
⋮                ⋮                    ⋮                   ⋮        ⋮
sn_pSCG1.P8.F07  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.F08  SmartSeq2_nuclei_rna AC-like             pSCG1    RNA_only
sn_pSCG1.P8.F09  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.F10  SmartSeq2_nuclei_rna Myeloid             pSCG1    RNA_only
sn_pSCG1.P8.F11  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.F12  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.G01  SmartSeq2_nuclei_rna G2M                 pSCG1    RNA_only
sn_pSCG1.P8.G02  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.G03  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.G04  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.G05  SmartSeq2_nuclei_rna AC-like             pSCG1    RNA_only
sn_pSCG1.P8.G06  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.G07  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.G08  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.G09  SmartSeq2_nuclei_rna Myeloid             pSCG1    RNA_only
sn_pSCG1.P8.G10  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.G11  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.G12  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.H01  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.H02  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.H03  SmartSeq2_nuclei_rna Oligodendrocyte     pSCG1    RNA_only
sn_pSCG1.P8.H04  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.H05  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.H06  SmartSeq2_nuclei_rna AC-like             pSCG1    RNA_only
sn_pSCG1.P8.H07  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.H08  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.H09  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.H10  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.H11  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only
sn_pSCG1.P8.H12  SmartSeq2_nuclei_rna NA                  pSCG1    RNA_only

In [14]:
saveRDS(Liu2022, '../data/Liu2022_no_filtered.rds')

Notes: <br>
- Sample AAA07653 has a typo in table S1. In the cell metadata is AAA007653 (an additional zero)
- Sample MUV7 is in Table S1 but it is not shown in any figure of the manuscript. We assume it was not included in the final paper.
- All the others were only profiled by in situ sequencing