In [ ]:
library(Signac)
library(Seurat)
library(dplyr)
library(sceasy)
library(reticulate)
use_condaenv('multi_integration')
library(future)

plan("multicore", workers = 8)
options(future.globals.maxSize = 100000 * 1024^3)

set.seed(1234)

Loading required package: SeuratObject

Loading required package: sp


Attaching package: ‘SeuratObject’


The following objects are masked from ‘package:base’:

    intersect, saveRDS


Loading Seurat v5 beta version
To maintain compatibility with previous workflows, new Seurat objects will use the previous object structure by default
To use new Seurat v5 assays: Please run: options(Seurat.object.assay.version = 'v5')


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: reticulate

### Load RNA data

In [ ]:
rna <- readRDS('/projects/0/einf2548/cruiz/dmg/data/merged_dmg_atlas_qc_filtered.rds')
rna
format(object.size(rna), units = "Mb")
format(object.size(rna), units = "Gb")

An object of class Seurat
38576 features across 409561 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

[1] "50529.1 Mb"

[1] "49.3 Gb"

In [ ]:
# Check condition and update values
rna$Batch_for_correction[rna$SampleID == 'GNG_region_11'] <- '10Xv1_nuclei_multiome'

In [ ]:
rna <- AddMetaData(rna, readRDS('/projects/0/einf2548/cruiz/dmg/data/iCNV_dmg_atlas.rds')) 

rna$cell_id <- paste0(rna$predicted.annotation_level_3, '_', rna$iCNV)

In [ ]:
rna$cell_id <- dplyr::recode(rna$cell_id,
                  `NPC-like_normal` = 'Stem_like_normal', 
                   `OPC_normal` = 'Stem_like_normal', 
                   `OPC-like_normal` = 'Stem_like_normal', 
                   `Endothelial_normal` = 'Endothelial', 
                   `TAM-BDM_normal` = 'TAM_BDM', 
                   `Mono_normal` = 'Mono', 
                   `Oligodendrocyte_normal` = 'Oligodendrocyte', 
                   `CD4/CD8_normal` = 'CD4_CD8', 
                   `MES-like_normal` = 'Differentiated_like_normal', 
                   `TAM-MG_normal` = 'TAM_MG', 
                   `B cell_normal` = 'B_cell', 
                   `DC_normal` = 'DC', 
                   `Mural cell_normal` = "Mural_cell", 
                   `Endothelial_tumor` = 'Endothelial', 
                   `TAM-BDM_tumor` = 'TAM_BDM', 
                   `Mono_tumor` = 'Mono', 
                   `Plasma B_normal` = 'Plasma', 
                   `Oligodendrocyte_tumor` = 'Oligodendrocyte', 
                   `Mural cell_tumor` = 'Mural_cell', 
                   `Plasma B_tumor` = 'Plasma', 
                   `MES-like_tumor`  = 'Differentiated_like_tumor', 
                   `CD4/CD8_tumor` = 'CD4_CD8', 
                   `OPC-like_tumor` = 'Stem_like_tumor', 
                   `AC-like_tumor` = 'Differentiated_like_tumor', 
                   `NPC-like_tumor` = 'Stem_like_tumor', 
                   `AC-like_normal` = 'Differentiated_like_normal', 
                   `TAM-MG_tumor` = 'TAM_MG', 
                   `B cell_tumor` = 'B_cell', 
                   `OPC_tumor` = 'Stem_like_tumor', 
                   `Neuron_normal` = 'Neuron', 
                   `Mast_tumor` = 'Mast', 
                   `Astrocyte_tumor` = 'Differentiated_like_tumor', 
                   `Neuron_tumor` = 'Neuron', 
                   `Astrocyte_normal` = 'Differentiated_like_normal', 
                   `DC_tumor` = 'DC', 
                   `Mast_normal` = 'Mast',
                   `NK_normal` = 'CD4_CD8')

In [ ]:
rna_only <- subset(rna, Batch_for_correction != "10Xv1_nuclei_multiome")
rna_multi <- subset(rna, Batch_for_correction == "10Xv1_nuclei_multiome")
rna_only
rna_multi

An object of class Seurat
38576 features across 322949 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

An object of class Seurat
38576 features across 86612 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

In [ ]:
rm(rna)
gc()

       used        (Mb)    gc trigger  (Mb)     max used    (Mb)
Ncells     9471815   505.9    16520452    882.3    16520452    882.3
Vcells 13017269789 99313.9 16789084404 128090.6 13266198152 101213.1

### Load ATAC data

In [ ]:
atac_only <- readRDS('data/atac_common_peak_set_dmg_atlas_qc_filtered_dbl_scores_merged.rds')
atac_only
atac_only <- subset(atac_only, combined > 0.05)
atac_only

An object of class Seurat
378298 features across 43608 samples within 1 assay
Active assay: ATAC (378298 features, 0 variable features)
 2 layers present: counts, data

In [ ]:
atac_multi <- readRDS('data/multiome_common_peak_set_dmg_atlas_qc_filtered_dbl_scores_merged.rds')
atac_multi
atac_multi <- subset(atac_multi, combined > 0.05)
atac_multi

An object of class Seurat
378298 features across 99736 samples within 1 assay
Active assay: ATAC (378298 features, 0 variable features)
 2 layers present: counts, data

In [ ]:
head(rownames(atac_only))

[1] "chr1-9729-10741"    "chr1-15764-16590"   "chr1-17055-17946"
[4] "chr1-28900-29821"   "chr1-180694-181903" "chr1-183749-184822"

#### Add metadata

##### ATAC only

In [ ]:
meta_cohort <- readxl::read_excel('../../data/dmg_atlas_metadata.xlsx',
                                  sheet = "Metadata")
meta_cohort

    Study     Institute Preservation_method ID
1   Ruiz2023  PMC       Cryo                T18-90532
2   Ruiz2023  PMC       Cryo                T19-90171
3   Ruiz2023  PMC       Cryo                T19-91014
4   Ruiz2023  PMC       Cryo                T20-01237
5   Ruiz2023  PMC       Cryo                T20-90151
6   Ruiz2023  PMC       Cryo                T20-90239
7   Ruiz2023  PMC       Cryo                T20-90296
8   Ruiz2023  PMC       Cryo                T20-93623
9   Ruiz2023  PMC       Cryo/Snap-frozen    T20-93210
10  Ruiz2023  PMC       Snap-frozen         T20-90372
11  Ruiz2023  PMC       Snap-frozen         T19-90627
12  Ruiz2023  PMC       Snap-frozen         T20-90005
13  Ruiz2023  PMC       Snap-frozen         T19-90673
14  Ruiz2023  PMC       Snap-frozen         T20-93369
15  Ruiz2023  PMC       Snap-frozen         T21-90517
16  Ruiz2023  PMC       Snap-frozen         T21-90581
17  Ruiz2023  PMC       Cryo                T21-90437
18  Ruiz2023  PMC       Snap-frozen         T21-90610
19  Ruiz2023  PMC       Snap-frozen         T21-90868
20  Ruiz2023  PMC       Snap-frozen         T21-91115
21  Ruiz2023  PMC       Snap-frozen         T21-90717
22  Ruiz2023  PMC       Snap-frozen         T21-90789
23  Ruiz2023  PMC       Snap-frozen         T21-90813
24  Ruiz2023  PMC       Snap-frozen         T21-91022
25  Ruiz2023  PMC       Snap-frozen         T21-91074
26  Ruiz2023  PMC       Snap-frozen         T21-91160
27  Ruiz2023  PMC       Snap-frozen         T22-90003
28  Ruiz2023  PMC       Snap-frozen         T22-90066
29  Ruiz2023  PMC       Snap-frozen         T22-90282
30  Ruiz2023  PMC       Snap-frozen         T22-90221
⋮   ⋮         ⋮         ⋮                   ⋮
71  Liu2022   N/A       Snap-frozen         SUDIPG45
72  Liu2022   N/A       Snap-frozen         SUDIPG31
73  Jessa2022 N/A       N/A                 P-6337_S-8821
74  Jessa2022 N/A       N/A                 P-6519_S-9084
75  Jessa2022 N/A       N/A                 P-6640_S-9581
76  Jessa2022 N/A       N/A                 P-6117_S-8370
77  Jessa2022 N/A       N/A                 P-6240_S-8628
78  Jessa2022 N/A       N/A                 P-6251_S-8496
79  Jessa2022 N/A       N/A                 P-1741_S-2756
80  Jessa2022 N/A       N/A                 P-6255_S-8500
81  Jessa2022 N/A       N/A                 P-6253_S-8498
82  Jessa2022 N/A       N/A                 P-1713_S-1713
83  Jessa2022 N/A       N/A                 P-6254_S-8499
84  Jessa2022 N/A       N/A                 P-1780_S-1780
85  Jessa2022 N/A       N/A                 P-2687_S-2688
86  Jessa2022 N/A       N/A                 P-1569_S-1569
87  Jessa2022 N/A       N/A                 P-1764_S-1766
88  Jessa2022 N/A       N/A                 P-1775_S-1775
89  Jessa2022 N/A       N/A                 P-4198_S-4459
90  Jessa2022 N/A       N/A                 P-3407_S-3447
91  Jessa2022 N/A       N/A                 P-6774_S-10146
92  Jessa2022 N/A       N/A                 P-1694_S-1694
93  Jessa2022 N/A       N/A                 P-1709_S-1709
94  Jessa2022 N/A       N/A                 P-1701_S-1701
95  Jessa2022 N/A       N/A                 P-1779_S-1781
96  Jessa2022 N/A       N/A                 P-4504_S-4916
97  Jessa2022 N/A       N/A                 P-6328_S-8672
98  Jessa2022 N/A       N/A                 P-5099_S-6218
99  Jessa2022 N/A       N/A                 P-5613_S-7162
100 Jessa2022 N/A       N/A                 P-3387_S-3411
    Diagnosis                           Tumor_type             Tumor_subtype
1   DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
2   DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
3   DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
4   DMG Spinal                          DMG H3 K27-altered     H3.3 K27-mutant
5   DMG Thalamus                        DMG H3 K27-altered     H3.3 K27-mutant
6   DMG Spinal                          DMG H3 K27-altered     H3.3 K27-mutant
7   DMG Pons                            DMG H3 K27-altered     H3.2 K27-mutant
8   DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
9   DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
10  DMG Cortex                          DMG H3 K27-altered     H3.3 K27-mutant
11  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
12  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
13  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
14  DMG Thalamus                        DMG H3 K27-altered     H3.3 K27-mutant
15  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
16  DMG Thalamus                        DMG H3 K27-altered     H3.1 K27-mutant
17  DMG Thalamus                        DMG H3 K27-altered     H3.3 K27-mutant
18  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
19  DMG Cortex                          DMG H3 K27-altered     H3.3 K27-mutant
20  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
21  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
22  ped HGG Pons, IDH & H3 wildtype     DpHGG H3-wt and IDH-wt H3-wt
23  DMG Thalamus                        DMG H3 K27-altered     H3.3 K27-mutant
24  DMG Pons & Cerebellum               DMG H3 K27-altered     H3.3 K27-mutant
25  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
26  DMG Thalamus                        DpHGG H3-wt and IDH-wt H3-wt
27  ped HGG Thalamus, IDH & H3 wildtype DpHGG H3-wt and IDH-wt H3-wt
28  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
29  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
30  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
⋮   ⋮                                   ⋮                      ⋮
71  DMG pons                            DMG H3 K27-altered     H3.3 K27-mutant
72  DMG pons                            DMG H3 K27-altered     H3.3 K27-mutant
73  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
74  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
75  DMG Thalamus                        DMG H3 K27-altered     H3.3 K27-mutant
76  DMG Thalamus                        DMG H3 K27-altered     H3.3 K27-mutant
77  ped HGG Pons, IDH & H3 wildtype     DpHGG H3-wt and IDH-wt H3-wt
78  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
79  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
80  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
81  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
82  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
83  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
84  DMG Pons                            DMG H3 K27-altered     H3.1 K27-mutant
85  DMG Pons                            DMG H3 K27-altered     H3.2 K27-mutant
86  DMG Cortex                          DMG H3 K27-altered     H3.3 K27-mutant
87  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
88  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
89  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
90  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
91  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
92  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
93  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
94  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
95  DMG Pons                            DMG H3 K27-altered     H3.3 K27-mutant
96  DMG Thalamus                        DMG H3 K27-altered     H3.3 K27-mutant
97  DMG Thalamus                        DMG H3 K27-altered     H3.3 K27-mutant
98  ped HGG Pons, IDH & H3 wildtype     DpHGG H3-wt and IDH-wt H3-wt
99  ped HGG Pons, IDH & H3 wildtype     DpHGG H3-wt and IDH-wt H3-wt
100 ped HGG Pons, IDH & H3 wildtype     DpHGG H3-wt and IDH-wt H3-wt
    Location            Source    Clinical_status    ⋯ PPM1D ACVR1 TSHR BRAF
1   Pons                Autopsy   Recurrence         ⋯ WT    WT    WT   WT
2   Pons                Autopsy   Recurrence         ⋯ WT    WT    WT   WT
3   Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
4   Spinal              Biopsy    Primary            ⋯ WT    WT    WT   WT
5   Thalamus            Biopsy    Recurrence         ⋯ WT    WT    WT   WT
6   Spinal              Biopsy    Recurrence         ⋯ WT    WT    WT   WT
7   Pons                Biopsy    Primary/Recurrence ⋯ WT    M     WT   WT
8   Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
9   Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
10  Cortex              Biopsy    Primary            ⋯ WT    WT    WT   WT
11  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
12  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
13  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
14  Thalamus            Debulking Primary            ⋯ WT    WT    WT   WT
15  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
16  Thalamus            Debulking Primary            ⋯ WT    WT    WT   WT
17  Thalamus            Biopsy    Primary            ⋯ WT    WT    WT   WT
18  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
19  Cortex              Debulking Primary            ⋯ WT    WT    WT   WT
20  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
21  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
22  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
23  Thalamus            Biopsy    Primary            ⋯ WT    WT    WT   WT
24  Pons and cerebellum Biopsy    Primary            ⋯ WT    WT    WT   WT
25  Pons                Biopsy    Primary            ⋯ WT    WT    WT   WT
26  Thalamus            Biopsy    Primary            ⋯ WT    WT    WT   WT
27  Thalamus            Biopsy    Primary            ⋯ WT    WT    WT   WT
28  Pons                Biopsy    Primary            ⋯ M     WT    WT   WT
29  Pons                Biopsy    Primary            ⋯ M     WT    WT   WT
30  Pons                Biopsy    Primary            ⋯ WT    WT    M    WT
⋮   ⋮                   ⋮         ⋮                  ⋱ ⋮     ⋮     ⋮    ⋮
71  Pons                N/A       Recurrence         ⋯ WT    WT    WT   WT
72  Pons                N/A       Recurrence         ⋯ WT    WT    WT   WT
73  Pons                N/A       N/A                ⋯ N/A   WT    N/A  N/A
74  Pons                N/A       N/A                ⋯ N/A   WT    N/A  N/A
75  Thalamus            N/A       N/A                ⋯ N/A   WT    N/A  N/A
76  Thalamus            N/A       N/A                ⋯ N/A   WT    N/A  M
77  Cortex              N/A       N/A                ⋯ N/A   WT    N/A  N/A
78  Pons                N/A       N/A                ⋯ N/A   M     N/A  N/A
79  Pons                N/A       N/A                ⋯ N/A   M     N/A  N/A
80  Pons                N/A       N/A                ⋯ N/A   WT    N/A  N/A
81  Pons                N/A       N/A                ⋯ N/A   M     N/A  N/A
82  Pons                N/A       N/A                ⋯ N/A   M     N/A  N/A
83  Pons                N/A       N/A                ⋯ N/A   M     N/A  N/A
84  Pons                N/A       N/A                ⋯ N/A   N/A   N/A  N/A
85  Pons                N/A       N/A                ⋯ N/A   M     N/A  N/A
86  Cortex              N/A       N/A                ⋯ N/A   WT    N/A  N/A
87  Pons                N/A       N/A                ⋯ N/A   WT    N/A  N/A
88  Pons                N/A       N/A                ⋯ N/A   WT    N/A  N/A
89  Pons                N/A       N/A                ⋯ N/A   WT    N/A  N/A
90  Pons                N/A       N/A                ⋯ N/A   WT    N/A  N/A
91  Pons                N/A       N/A                ⋯ N/A   WT    N/A  N/A
92  Pons                N/A       N/A                ⋯ N/A   N/A   N/A  N/A
93  Pons                N/A       N/A                ⋯ N/A   WT    N/A  M
94  Pons                N/A       N/A                ⋯ N/A   M     N/A  N/A
95  Pons                N/A       N/A                ⋯ N/A   N/A   N/A  N/A
96  Thalamus            N/A       N/A                ⋯ N/A   WT    N/A  N/A
97  Thalamus            N/A       N/A                ⋯ N/A   WT    N/A  N/A
98  Cortex              N/A       N/A                ⋯ N/A   WT    N/A  N/A
99  Cortex              N/A       N/A                ⋯ N/A   WT    N/A  N/A
100 Cortex              N/A       N/A                ⋯ N/A   WT    N/A  N/A
    GNAQ LMNA KIT ARID1A KRAS Other
1   WT   WT   WT  WT     WT   N/A
2   WT   WT   WT  WT     WT   N/A
3   WT   WT   WT  WT     WT   N/A
4   WT   WT   WT  WT     WT   N/A
5   WT   WT   WT  WT     WT   N/A
6   WT   WT   WT  WT     WT   N/A
7   WT   WT   WT  WT     WT   FGFR3 overexpression; TP53 inactivation
8   WT   WT   WT  WT     WT   RGMA-ERAS fusion
9   WT   WT   WT  WT     WT   N/A
10  WT   WT   WT  WT     WT   N/A
11  WT   WT   WT  WT     WT   N/A
12  WT   WT   WT  WT     WT   N/A
13  WT   WT   WT  WT     WT   CHIC2-PDGFRA fusion
14  WT   WT   WT  WT     WT   N/A
15  WT   WT   WT  WT     WT   N/A
16  WT   WT   WT  WT     WT   N/A
17  WT   WT   WT  WT     WT   N/A
18  WT   WT   WT  WT     WT   N/A
19  WT   WT   WT  WT     WT   N/A
20  WT   WT   WT  WT     WT   N/A
21  WT   WT   WT  WT     WT   N/A
22  WT   WT   WT  WT     WT   EGFR-MYC amplification
23  WT   WT   WT  WT     WT   N/A
24  WT   WT   WT  WT     WT   N/A
25  WT   WT   WT  WT     WT   N/A
26  WT   WT   WT  WT     WT   N/A
27  WT   WT   WT  WT     WT   N/A
28  WT   WT   WT  WT     WT   N/A
29  WT   WT   WT  WT     WT   N/A
30  WT   WT   WT  WT     WT   N/A
⋮   ⋮    ⋮    ⋮   ⋮      ⋮    ⋮
71  WT   WT   WT  WT     WT   N/A
72  WT   WT   WT  WT     WT   N/A
73  N/A  N/A  N/A N/A    N/A  N/A
74  N/A  N/A  N/A N/A    N/A  N/A
75  N/A  N/A  N/A N/A    N/A  N/A
76  N/A  N/A  N/A N/A    N/A  N/A
77  N/A  N/A  N/A N/A    N/A  N/A
78  N/A  N/A  N/A N/A    N/A  N/A
79  N/A  N/A  N/A N/A    N/A  N/A
80  N/A  N/A  N/A N/A    N/A  N/A
81  N/A  N/A  N/A N/A    N/A  N/A
82  N/A  N/A  N/A N/A    N/A  N/A
83  N/A  N/A  N/A N/A    N/A  N/A
84  N/A  N/A  N/A N/A    N/A  N/A
85  N/A  N/A  N/A N/A    N/A  N/A
86  N/A  N/A  N/A N/A    N/A  N/A
87  N/A  N/A  N/A N/A    N/A  N/A
88  N/A  N/A  N/A N/A    N/A  N/A
89  N/A  N/A  N/A N/A    N/A  N/A
90  N/A  N/A  N/A N/A    N/A  N/A
91  N/A  N/A  N/A N/A    N/A  N/A
92  N/A  N/A  N/A N/A    N/A  N/A
93  N/A  N/A  N/A N/A    N/A  N/A
94  N/A  N/A  N/A N/A    N/A  N/A
95  N/A  N/A  N/A N/A    N/A  N/A
96  N/A  N/A  N/A N/A    N/A  N/A
97  N/A  N/A  N/A N/A    N/A  N/A
98  N/A  N/A  N/A N/A    N/A  PDGFRA-FIP1L1 fusion
99  N/A  N/A  N/A N/A    N/A  N/A
100 N/A  N/A  N/A N/A    N/A  N/A

In [ ]:
integrated <- readRDS('data/cca_integrated_atac_multiome_dmg_atlas_no_doublets.rds')

In [ ]:
# Assuming you have a dataframe named "data" containing the column you want to rename
colnames(atac_only@meta.data) <- sub("p.value", "amulet_pvalue", colnames(atac_only@meta.data))
colnames(atac_only@meta.data) <- sub("q.value", "amulet_qvalue", colnames(atac_only@meta.data))
colnames(atac_only@meta.data) <- sub("combined", "dbl_combined_score", colnames(atac_only@meta.data))

head(atac_only@meta.data)

                                  orig.ident    total duplicate chimeric
atac_T19-91014_AAACGAAAGACCCTAT-1 SeuratProject 37892 15065      1
atac_T19-91014_AAACGAAAGCGTTGCC-1 SeuratProject 22601  6146      0
atac_T19-91014_AAACGAAAGTACAACA-1 SeuratProject 88086 16394     15
atac_T19-91014_AAACGAAAGTAGTGTA-1 SeuratProject 67957 14538     11
atac_T19-91014_AAACGAAAGTGAATAC-1 SeuratProject 21580  5723      1
atac_T19-91014_AAACGAAAGTGCCCTG-1 SeuratProject 28527  7851      0
                                  unmapped lowmapq mitochondrial nonprimary
atac_T19-91014_AAACGAAAGACCCTAT-1  438      3127   45              5
atac_T19-91014_AAACGAAAGCGTTGCC-1  246      1761    1              3
atac_T19-91014_AAACGAAAGTACAACA-1 1025     10885   82            198
atac_T19-91014_AAACGAAAGTAGTGTA-1  877      7296   22             43
atac_T19-91014_AAACGAAAGTGAATAC-1  213      2597    9             12
atac_T19-91014_AAACGAAAGTGCCCTG-1  319      2382   16              6
                                  passed_filters is__cell_barcode ⋯
atac_T19-91014_AAACGAAAGACCCTAT-1 19211          1                ⋯
atac_T19-91014_AAACGAAAGCGTTGCC-1 14444          1                ⋯
atac_T19-91014_AAACGAAAGTACAACA-1 59487          1                ⋯
atac_T19-91014_AAACGAAAGTAGTGTA-1 45170          1                ⋯
atac_T19-91014_AAACGAAAGTGAATAC-1 13025          1                ⋯
atac_T19-91014_AAACGAAAGTGCCCTG-1 17953          1                ⋯
                                  pct_reads_in_peaks blacklist_ratio high.tss
atac_T19-91014_AAACGAAAGACCCTAT-1 73.68174           0.005604587     High
atac_T19-91014_AAACGAAAGCGTTGCC-1 65.59817           0.007014953     High
atac_T19-91014_AAACGAAAGTACAACA-1 26.92857           0.009146758     High
atac_T19-91014_AAACGAAAGTAGTGTA-1 43.59088           0.006111504     High
atac_T19-91014_AAACGAAAGTGAATAC-1 63.17083           0.006865955     High
atac_T19-91014_AAACGAAAGTGCCCTG-1 42.65582           0.005032502     High
                                  nucleosome_group scDblFinder.score
atac_T19-91014_AAACGAAAGACCCTAT-1 NS < 4           0.002426961
atac_T19-91014_AAACGAAAGCGTTGCC-1 NS < 4           0.001284394
atac_T19-91014_AAACGAAAGTACAACA-1 NS < 4           0.982575774
atac_T19-91014_AAACGAAAGTAGTGTA-1 NS < 4           0.328079313
atac_T19-91014_AAACGAAAGTGAATAC-1 NS < 4           0.001355713
atac_T19-91014_AAACGAAAGTGCCCTG-1 NS < 4           0.015990626
                                  scDblFinder.class amulet_pvalue amulet_qvalue
atac_T19-91014_AAACGAAAGACCCTAT-1 singlet           7.109960e-01  1.000000e+00
atac_T19-91014_AAACGAAAGCGTTGCC-1 singlet           9.999999e-01  1.000000e+00
atac_T19-91014_AAACGAAAGTACAACA-1 doublet           5.340977e-01  1.000000e+00
atac_T19-91014_AAACGAAAGTAGTGTA-1 singlet           3.778549e-06  3.313147e-05
atac_T19-91014_AAACGAAAGTGAATAC-1 singlet           9.999999e-01  1.000000e+00
atac_T19-91014_AAACGAAAGTGCCCTG-1 singlet           9.999927e-01  1.000000e+00
                                  scDblFinder.p dbl_combined_score
atac_T19-91014_AAACGAAAGACCCTAT-1 0.99757304    0.95291788
atac_T19-91014_AAACGAAAGCGTTGCC-1 0.99871561    0.99999917
atac_T19-91014_AAACGAAAGTACAACA-1 0.01742423    0.05283217
atac_T19-91014_AAACGAAAGTAGTGTA-1 0.67192069    0.00558055
atac_T19-91014_AAACGAAAGTGAATAC-1 0.99864429    0.99999908
atac_T19-91014_AAACGAAAGTGCCCTG-1 0.98400937    0.99987135

In [ ]:
table(atac_only$SampleID)

         MUV1         MUV16         MUV35         MUV86 P-1764_S-1766
         6654          2645          6893          5506          1000
P-2687_S-2688 P-6253_S-8498 P-6255_S-8500      SUDIPG55     T19-91014
          461           709           257          1163          8742
    T20-90296
         9578

In [ ]:
atac_only$ID <- atac_only$SampleID
meta_id_cells <- data.frame(Cell = colnames(atac_only),
           ID = atac_only$ID,
           check.names = FALSE
          )
meta_id_cells

                                      Cell
atac_T19-91014_AAACGAAAGACCCTAT-1     atac_T19-91014_AAACGAAAGACCCTAT-1
atac_T19-91014_AAACGAAAGCGTTGCC-1     atac_T19-91014_AAACGAAAGCGTTGCC-1
atac_T19-91014_AAACGAAAGTACAACA-1     atac_T19-91014_AAACGAAAGTACAACA-1
atac_T19-91014_AAACGAAAGTAGTGTA-1     atac_T19-91014_AAACGAAAGTAGTGTA-1
atac_T19-91014_AAACGAAAGTGAATAC-1     atac_T19-91014_AAACGAAAGTGAATAC-1
atac_T19-91014_AAACGAAAGTGCCCTG-1     atac_T19-91014_AAACGAAAGTGCCCTG-1
atac_T19-91014_AAACGAAAGTGTAATG-1     atac_T19-91014_AAACGAAAGTGTAATG-1
atac_T19-91014_AAACGAACAAATGCTC-1     atac_T19-91014_AAACGAACAAATGCTC-1
atac_T19-91014_AAACGAACACGCCGAT-1     atac_T19-91014_AAACGAACACGCCGAT-1
atac_T19-91014_AAACGAACAGGTGTCC-1     atac_T19-91014_AAACGAACAGGTGTCC-1
atac_T19-91014_AAACGAAGTACGGAGT-1     atac_T19-91014_AAACGAAGTACGGAGT-1
atac_T19-91014_AAACGAAGTATCCCTC-1     atac_T19-91014_AAACGAAGTATCCCTC-1
atac_T19-91014_AAACGAAGTATCTCAG-1     atac_T19-91014_AAACGAAGTATCTCAG-1
atac_T19-91014_AAACGAAGTCAGACGA-1     atac_T19-91014_AAACGAAGTCAGACGA-1
atac_T19-91014_AAACGAAGTCTGGTCG-1     atac_T19-91014_AAACGAAGTCTGGTCG-1
atac_T19-91014_AAACGAAGTGAAACAT-1     atac_T19-91014_AAACGAAGTGAAACAT-1
atac_T19-91014_AAACGAATCGATGTAC-1     atac_T19-91014_AAACGAATCGATGTAC-1
atac_T19-91014_AAACTCGAGAGAATTC-1     atac_T19-91014_AAACTCGAGAGAATTC-1
atac_T19-91014_AAACTCGAGCACCATT-1     atac_T19-91014_AAACTCGAGCACCATT-1
atac_T19-91014_AAACTCGAGTGTCCCG-1     atac_T19-91014_AAACTCGAGTGTCCCG-1
atac_T19-91014_AAACTCGCAAATTCCG-1     atac_T19-91014_AAACTCGCAAATTCCG-1
atac_T19-91014_AAACTCGCAACGTAGG-1     atac_T19-91014_AAACTCGCAACGTAGG-1
atac_T19-91014_AAACTCGCAATCAGGG-1     atac_T19-91014_AAACTCGCAATCAGGG-1
atac_T19-91014_AAACTCGCAATCATCG-1     atac_T19-91014_AAACTCGCAATCATCG-1
atac_T19-91014_AAACTCGCAATTGCCA-1     atac_T19-91014_AAACTCGCAATTGCCA-1
atac_T19-91014_AAACTCGCACGCTGTG-1     atac_T19-91014_AAACTCGCACGCTGTG-1
atac_T19-91014_AAACTCGCACTCAGCG-1     atac_T19-91014_AAACTCGCACTCAGCG-1
atac_T19-91014_AAACTCGCACTTATGG-1     atac_T19-91014_AAACTCGCACTTATGG-1
atac_T19-91014_AAACTCGCAGAACAGC-1     atac_T19-91014_AAACTCGCAGAACAGC-1
atac_T19-91014_AAACTCGGTAAACGTA-1     atac_T19-91014_AAACTCGGTAAACGTA-1
⋮                                     ⋮
atac_P-6255_S-8500_TGCTCGTGTGAGCTAG-1 atac_P-6255_S-8500_TGCTCGTGTGAGCTAG-1
atac_P-6255_S-8500_TGCTTCGTCGATCTTT-1 atac_P-6255_S-8500_TGCTTCGTCGATCTTT-1
atac_P-6255_S-8500_TGCTTTAGTTATCGAC-1 atac_P-6255_S-8500_TGCTTTAGTTATCGAC-1
atac_P-6255_S-8500_TGGAAGGAGTGAATAC-1 atac_P-6255_S-8500_TGGAAGGAGTGAATAC-1
atac_P-6255_S-8500_TGGAAGGTCCAGGTAT-1 atac_P-6255_S-8500_TGGAAGGTCCAGGTAT-1
atac_P-6255_S-8500_TGGTCAAAGTAGGAAG-1 atac_P-6255_S-8500_TGGTCAAAGTAGGAAG-1
atac_P-6255_S-8500_TGGTCCTGTGTCCAGC-1 atac_P-6255_S-8500_TGGTCCTGTGTCCAGC-1
atac_P-6255_S-8500_TGTAAGCCAGGTCCTG-1 atac_P-6255_S-8500_TGTAAGCCAGGTCCTG-1
atac_P-6255_S-8500_TGTGACACAGCTGATT-1 atac_P-6255_S-8500_TGTGACACAGCTGATT-1
atac_P-6255_S-8500_TGTGTCCCAGGTGGTA-1 atac_P-6255_S-8500_TGTGTCCCAGGTGGTA-1
atac_P-6255_S-8500_TTACCCGAGCTACGCC-1 atac_P-6255_S-8500_TTACCCGAGCTACGCC-1
atac_P-6255_S-8500_TTACGTTTCTCTGAGA-1 atac_P-6255_S-8500_TTACGTTTCTCTGAGA-1
atac_P-6255_S-8500_TTACTCAAGCGGACTA-1 atac_P-6255_S-8500_TTACTCAAGCGGACTA-1
atac_P-6255_S-8500_TTACTTGGTCTGATTG-1 atac_P-6255_S-8500_TTACTTGGTCTGATTG-1
atac_P-6255_S-8500_TTAGCTTCAGTAACCT-1 atac_P-6255_S-8500_TTAGCTTCAGTAACCT-1
atac_P-6255_S-8500_TTATGTCGTTGGGAAC-1 atac_P-6255_S-8500_TTATGTCGTTGGGAAC-1
atac_P-6255_S-8500_TTCAACTTCGATATGC-1 atac_P-6255_S-8500_TTCAACTTCGATATGC-1
atac_P-6255_S-8500_TTCATCATCAATCGTG-1 atac_P-6255_S-8500_TTCATCATCAATCGTG-1
atac_P-6255_S-8500_TTCATTGTCTTGGCCT-1 atac_P-6255_S-8500_TTCATTGTCTTGGCCT-1
atac_P-6255_S-8500_TTCGCGTGTTAGTAGA-1 atac_P-6255_S-8500_TTCGCGTGTTAGTAGA-1
atac_P-6255_S-8500_TTCTAACAGTCAGGAC-1 atac_P-6255_S-8500_TTCTAACAGTCAGGAC-1
atac_P-6255_S-8500_TTGAGCAAGTTAGAGT-1 atac_P-6255_S-8500_TTGAGCAAGTTAGAGT-1
atac_P-6255_S-8500_TTGCACCGTATACGCT-1 atac_P-6255_S-8500_TTGCACCGTATACGCT-1
atac_P-6255_S-8500_TTGCGAAAGGCAAGCT-1 atac_P-6255_S-8500_TTGCGAAAGGCAAGCT-1
atac_P-6255_S-8500_TTGCGAAAGGCATGCA-1 atac_P-6255_S-8500_TTGCGAAAGGCATGCA-1
atac_P-6255_S-8500_TTGCTTAGTGTGTGCC-1 atac_P-6255_S-8500_TTGCTTAGTGTGTGCC-1
atac_P-6255_S-8500_TTGCTTATCCAACGCG-1 atac_P-6255_S-8500_TTGCTTATCCAACGCG-1
atac_P-6255_S-8500_TTTACGTTCAGGGTTT-1 atac_P-6255_S-8500_TTTACGTTCAGGGTTT-1
atac_P-6255_S-8500_TTTGGCCCACAGTTAC-1 atac_P-6255_S-8500_TTTGGCCCACAGTTAC-1
atac_P-6255_S-8500_TTTGTGTCAACGTAGG-1 atac_P-6255_S-8500_TTTGTGTCAACGTAGG-1
                                      ID
atac_T19-91014_AAACGAAAGACCCTAT-1     T19-91014
atac_T19-91014_AAACGAAAGCGTTGCC-1     T19-91014
atac_T19-91014_AAACGAAAGTACAACA-1     T19-91014
atac_T19-91014_AAACGAAAGTAGTGTA-1     T19-91014
atac_T19-91014_AAACGAAAGTGAATAC-1     T19-91014
atac_T19-91014_AAACGAAAGTGCCCTG-1     T19-91014
atac_T19-91014_AAACGAAAGTGTAATG-1     T19-91014
atac_T19-91014_AAACGAACAAATGCTC-1     T19-91014
atac_T19-91014_AAACGAACACGCCGAT-1     T19-91014
atac_T19-91014_AAACGAACAGGTGTCC-1     T19-91014
atac_T19-91014_AAACGAAGTACGGAGT-1     T19-91014
atac_T19-91014_AAACGAAGTATCCCTC-1     T19-91014
atac_T19-91014_AAACGAAGTATCTCAG-1     T19-91014
atac_T19-91014_AAACGAAGTCAGACGA-1     T19-91014
atac_T19-91014_AAACGAAGTCTGGTCG-1     T19-91014
atac_T19-91014_AAACGAAGTGAAACAT-1     T19-91014
atac_T19-91014_AAACGAATCGATGTAC-1     T19-91014
atac_T19-91014_AAACTCGAGAGAATTC-1     T19-91014
atac_T19-91014_AAACTCGAGCACCATT-1     T19-91014
atac_T19-91014_AAACTCGAGTGTCCCG-1     T19-91014
atac_T19-91014_AAACTCGCAAATTCCG-1     T19-91014
atac_T19-91014_AAACTCGCAACGTAGG-1     T19-91014
atac_T19-91014_AAACTCGCAATCAGGG-1     T19-91014
atac_T19-91014_AAACTCGCAATCATCG-1     T19-91014
atac_T19-91014_AAACTCGCAATTGCCA-1     T19-91014
atac_T19-91014_AAACTCGCACGCTGTG-1     T19-91014
atac_T19-91014_AAACTCGCACTCAGCG-1     T19-91014
atac_T19-91014_AAACTCGCACTTATGG-1     T19-91014
atac_T19-91014_AAACTCGCAGAACAGC-1     T19-91014
atac_T19-91014_AAACTCGGTAAACGTA-1     T19-91014
⋮                                     ⋮
atac_P-6255_S-8500_TGCTCGTGTGAGCTAG-1 P-6255_S-8500
atac_P-6255_S-8500_TGCTTCGTCGATCTTT-1 P-6255_S-8500
atac_P-6255_S-8500_TGCTTTAGTTATCGAC-1 P-6255_S-8500
atac_P-6255_S-8500_TGGAAGGAGTGAATAC-1 P-6255_S-8500
atac_P-6255_S-8500_TGGAAGGTCCAGGTAT-1 P-6255_S-8500
atac_P-6255_S-8500_TGGTCAAAGTAGGAAG-1 P-6255_S-8500
atac_P-6255_S-8500_TGGTCCTGTGTCCAGC-1 P-6255_S-8500
atac_P-6255_S-8500_TGTAAGCCAGGTCCTG-1 P-6255_S-8500
atac_P-6255_S-8500_TGTGACACAGCTGATT-1 P-6255_S-8500
atac_P-6255_S-8500_TGTGTCCCAGGTGGTA-1 P-6255_S-8500
atac_P-6255_S-8500_TTACCCGAGCTACGCC-1 P-6255_S-8500
atac_P-6255_S-8500_TTACGTTTCTCTGAGA-1 P-6255_S-8500
atac_P-6255_S-8500_TTACTCAAGCGGACTA-1 P-6255_S-8500
atac_P-6255_S-8500_TTACTTGGTCTGATTG-1 P-6255_S-8500
atac_P-6255_S-8500_TTAGCTTCAGTAACCT-1 P-6255_S-8500
atac_P-6255_S-8500_TTATGTCGTTGGGAAC-1 P-6255_S-8500
atac_P-6255_S-8500_TTCAACTTCGATATGC-1 P-6255_S-8500
atac_P-6255_S-8500_TTCATCATCAATCGTG-1 P-6255_S-8500
atac_P-6255_S-8500_TTCATTGTCTTGGCCT-1 P-6255_S-8500
atac_P-6255_S-8500_TTCGCGTGTTAGTAGA-1 P-6255_S-8500
atac_P-6255_S-8500_TTCTAACAGTCAGGAC-1 P-6255_S-8500
atac_P-6255_S-8500_TTGAGCAAGTTAGAGT-1 P-6255_S-8500
atac_P-6255_S-8500_TTGCACCGTATACGCT-1 P-6255_S-8500
atac_P-6255_S-8500_TTGCGAAAGGCAAGCT-1 P-6255_S-8500
atac_P-6255_S-8500_TTGCGAAAGGCATGCA-1 P-6255_S-8500
atac_P-6255_S-8500_TTGCTTAGTGTGTGCC-1 P-6255_S-8500
atac_P-6255_S-8500_TTGCTTATCCAACGCG-1 P-6255_S-8500
atac_P-6255_S-8500_TTTACGTTCAGGGTTT-1 P-6255_S-8500
atac_P-6255_S-8500_TTTGGCCCACAGTTAC-1 P-6255_S-8500
atac_P-6255_S-8500_TTTGTGTCAACGTAGG-1 P-6255_S-8500

In [ ]:
all(meta_id_cells$ID %in% meta_cohort$ID)

[1] TRUE

In [ ]:
atac_only_meta <- list(meta_id_cells, meta_cohort) %>% 
                    purrr::reduce(inner_join, by = 'ID') %>% 
                    distinct(Cell, .keep_all = TRUE) %>% 
                    tibble::column_to_rownames('Cell')
atac_only_meta

                                      ID            Study     Institute
atac_T19-91014_AAACGAAAGACCCTAT-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACGAAAGCGTTGCC-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACGAAAGTACAACA-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACGAAAGTAGTGTA-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACGAAAGTGAATAC-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACGAAAGTGCCCTG-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACGAAAGTGTAATG-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACGAACAAATGCTC-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACGAACACGCCGAT-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACGAACAGGTGTCC-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACGAAGTACGGAGT-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACGAAGTATCCCTC-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACGAAGTATCTCAG-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACGAAGTCAGACGA-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACGAAGTCTGGTCG-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACGAAGTGAAACAT-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACGAATCGATGTAC-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACTCGAGAGAATTC-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACTCGAGCACCATT-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACTCGAGTGTCCCG-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACTCGCAAATTCCG-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACTCGCAACGTAGG-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACTCGCAATCAGGG-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACTCGCAATCATCG-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACTCGCAATTGCCA-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACTCGCACGCTGTG-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACTCGCACTCAGCG-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACTCGCACTTATGG-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACTCGCAGAACAGC-1     T19-91014     Ruiz2023  PMC
atac_T19-91014_AAACTCGGTAAACGTA-1     T19-91014     Ruiz2023  PMC
⋮                                     ⋮             ⋮         ⋮
atac_P-6255_S-8500_TGCTCGTGTGAGCTAG-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TGCTTCGTCGATCTTT-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TGCTTTAGTTATCGAC-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TGGAAGGAGTGAATAC-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TGGAAGGTCCAGGTAT-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TGGTCAAAGTAGGAAG-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TGGTCCTGTGTCCAGC-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TGTAAGCCAGGTCCTG-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TGTGACACAGCTGATT-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TGTGTCCCAGGTGGTA-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTACCCGAGCTACGCC-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTACGTTTCTCTGAGA-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTACTCAAGCGGACTA-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTACTTGGTCTGATTG-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTAGCTTCAGTAACCT-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTATGTCGTTGGGAAC-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTCAACTTCGATATGC-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTCATCATCAATCGTG-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTCATTGTCTTGGCCT-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTCGCGTGTTAGTAGA-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTCTAACAGTCAGGAC-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTGAGCAAGTTAGAGT-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTGCACCGTATACGCT-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTGCGAAAGGCAAGCT-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTGCGAAAGGCATGCA-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTGCTTAGTGTGTGCC-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTGCTTATCCAACGCG-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTTACGTTCAGGGTTT-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTTGGCCCACAGTTAC-1 P-6255_S-8500 Jessa2022 N/A
atac_P-6255_S-8500_TTTGTGTCAACGTAGG-1 P-6255_S-8500 Jessa2022 N/A
                                      Preservation_method Diagnosis
atac_T19-91014_AAACGAAAGACCCTAT-1     Cryo                DMG Pons
atac_T19-91014_AAACGAAAGCGTTGCC-1     Cryo                DMG Pons
atac_T19-91014_AAACGAAAGTACAACA-1     Cryo                DMG Pons
atac_T19-91014_AAACGAAAGTAGTGTA-1     Cryo                DMG Pons
atac_T19-91014_AAACGAAAGTGAATAC-1     Cryo                DMG Pons
atac_T19-91014_AAACGAAAGTGCCCTG-1     Cryo                DMG Pons
atac_T19-91014_AAACGAAAGTGTAATG-1     Cryo                DMG Pons
atac_T19-91014_AAACGAACAAATGCTC-1     Cryo                DMG Pons
atac_T19-91014_AAACGAACACGCCGAT-1     Cryo                DMG Pons
atac_T19-91014_AAACGAACAGGTGTCC-1     Cryo                DMG Pons
atac_T19-91014_AAACGAAGTACGGAGT-1     Cryo                DMG Pons
atac_T19-91014_AAACGAAGTATCCCTC-1     Cryo                DMG Pons
atac_T19-91014_AAACGAAGTATCTCAG-1     Cryo                DMG Pons
atac_T19-91014_AAACGAAGTCAGACGA-1     Cryo                DMG Pons
atac_T19-91014_AAACGAAGTCTGGTCG-1     Cryo                DMG Pons
atac_T19-91014_AAACGAAGTGAAACAT-1     Cryo                DMG Pons
atac_T19-91014_AAACGAATCGATGTAC-1     Cryo                DMG Pons
atac_T19-91014_AAACTCGAGAGAATTC-1     Cryo                DMG Pons
atac_T19-91014_AAACTCGAGCACCATT-1     Cryo                DMG Pons
atac_T19-91014_AAACTCGAGTGTCCCG-1     Cryo                DMG Pons
atac_T19-91014_AAACTCGCAAATTCCG-1     Cryo                DMG Pons
atac_T19-91014_AAACTCGCAACGTAGG-1     Cryo                DMG Pons
atac_T19-91014_AAACTCGCAATCAGGG-1     Cryo                DMG Pons
atac_T19-91014_AAACTCGCAATCATCG-1     Cryo                DMG Pons
atac_T19-91014_AAACTCGCAATTGCCA-1     Cryo                DMG Pons
atac_T19-91014_AAACTCGCACGCTGTG-1     Cryo                DMG Pons
atac_T19-91014_AAACTCGCACTCAGCG-1     Cryo                DMG Pons
atac_T19-91014_AAACTCGCACTTATGG-1     Cryo                DMG Pons
atac_T19-91014_AAACTCGCAGAACAGC-1     Cryo                DMG Pons
atac_T19-91014_AAACTCGGTAAACGTA-1     Cryo                DMG Pons
⋮                                     ⋮                   ⋮
atac_P-6255_S-8500_TGCTCGTGTGAGCTAG-1 N/A                 DMG Pons
atac_P-6255_S-8500_TGCTTCGTCGATCTTT-1 N/A                 DMG Pons
atac_P-6255_S-8500_TGCTTTAGTTATCGAC-1 N/A                 DMG Pons
atac_P-6255_S-8500_TGGAAGGAGTGAATAC-1 N/A                 DMG Pons
atac_P-6255_S-8500_TGGAAGGTCCAGGTAT-1 N/A                 DMG Pons
atac_P-6255_S-8500_TGGTCAAAGTAGGAAG-1 N/A                 DMG Pons
atac_P-6255_S-8500_TGGTCCTGTGTCCAGC-1 N/A                 DMG Pons
atac_P-6255_S-8500_TGTAAGCCAGGTCCTG-1 N/A                 DMG Pons
atac_P-6255_S-8500_TGTGACACAGCTGATT-1 N/A                 DMG Pons
atac_P-6255_S-8500_TGTGTCCCAGGTGGTA-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTACCCGAGCTACGCC-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTACGTTTCTCTGAGA-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTACTCAAGCGGACTA-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTACTTGGTCTGATTG-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTAGCTTCAGTAACCT-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTATGTCGTTGGGAAC-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTCAACTTCGATATGC-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTCATCATCAATCGTG-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTCATTGTCTTGGCCT-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTCGCGTGTTAGTAGA-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTCTAACAGTCAGGAC-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTGAGCAAGTTAGAGT-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTGCACCGTATACGCT-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTGCGAAAGGCAAGCT-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTGCGAAAGGCATGCA-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTGCTTAGTGTGTGCC-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTGCTTATCCAACGCG-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTTACGTTCAGGGTTT-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTTGGCCCACAGTTAC-1 N/A                 DMG Pons
atac_P-6255_S-8500_TTTGTGTCAACGTAGG-1 N/A                 DMG Pons
                                      Tumor_type         Tumor_subtype
atac_T19-91014_AAACGAAAGACCCTAT-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACGAAAGCGTTGCC-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACGAAAGTACAACA-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACGAAAGTAGTGTA-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACGAAAGTGAATAC-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACGAAAGTGCCCTG-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACGAAAGTGTAATG-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACGAACAAATGCTC-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACGAACACGCCGAT-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACGAACAGGTGTCC-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACGAAGTACGGAGT-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACGAAGTATCCCTC-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACGAAGTATCTCAG-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACGAAGTCAGACGA-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACGAAGTCTGGTCG-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACGAAGTGAAACAT-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACGAATCGATGTAC-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACTCGAGAGAATTC-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACTCGAGCACCATT-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACTCGAGTGTCCCG-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACTCGCAAATTCCG-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACTCGCAACGTAGG-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACTCGCAATCAGGG-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACTCGCAATCATCG-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACTCGCAATTGCCA-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACTCGCACGCTGTG-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACTCGCACTCAGCG-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACTCGCACTTATGG-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACTCGCAGAACAGC-1     DMG H3 K27-altered H3.3 K27-mutant
atac_T19-91014_AAACTCGGTAAACGTA-1     DMG H3 K27-altered H3.3 K27-mutant
⋮                                     ⋮                  ⋮
atac_P-6255_S-8500_TGCTCGTGTGAGCTAG-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TGCTTCGTCGATCTTT-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TGCTTTAGTTATCGAC-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TGGAAGGAGTGAATAC-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TGGAAGGTCCAGGTAT-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TGGTCAAAGTAGGAAG-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TGGTCCTGTGTCCAGC-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TGTAAGCCAGGTCCTG-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TGTGACACAGCTGATT-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TGTGTCCCAGGTGGTA-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTACCCGAGCTACGCC-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTACGTTTCTCTGAGA-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTACTCAAGCGGACTA-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTACTTGGTCTGATTG-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTAGCTTCAGTAACCT-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTATGTCGTTGGGAAC-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTCAACTTCGATATGC-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTCATCATCAATCGTG-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTCATTGTCTTGGCCT-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTCGCGTGTTAGTAGA-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTCTAACAGTCAGGAC-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTGAGCAAGTTAGAGT-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTGCACCGTATACGCT-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTGCGAAAGGCAAGCT-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTGCGAAAGGCATGCA-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTGCTTAGTGTGTGCC-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTGCTTATCCAACGCG-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTTACGTTCAGGGTTT-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTTGGCCCACAGTTAC-1 DMG H3 K27-altered H3.1 K27-mutant
atac_P-6255_S-8500_TTTGTGTCAACGTAGG-1 DMG H3 K27-altered H3.1 K27-mutant
                                      Location Source Clinical_status ⋯ PPM1D
atac_T19-91014_AAACGAAAGACCCTAT-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACGAAAGCGTTGCC-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACGAAAGTACAACA-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACGAAAGTAGTGTA-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACGAAAGTGAATAC-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACGAAAGTGCCCTG-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACGAAAGTGTAATG-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACGAACAAATGCTC-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACGAACACGCCGAT-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACGAACAGGTGTCC-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACGAAGTACGGAGT-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACGAAGTATCCCTC-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACGAAGTATCTCAG-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACGAAGTCAGACGA-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACGAAGTCTGGTCG-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACGAAGTGAAACAT-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACGAATCGATGTAC-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACTCGAGAGAATTC-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACTCGAGCACCATT-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACTCGAGTGTCCCG-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACTCGCAAATTCCG-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACTCGCAACGTAGG-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACTCGCAATCAGGG-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACTCGCAATCATCG-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACTCGCAATTGCCA-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACTCGCACGCTGTG-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACTCGCACTCAGCG-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACTCGCACTTATGG-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACTCGCAGAACAGC-1     Pons     Biopsy Primary         ⋯ WT
atac_T19-91014_AAACTCGGTAAACGTA-1     Pons     Biopsy Primary         ⋯ WT
⋮                                     ⋮        ⋮      ⋮               ⋱ ⋮
atac_P-6255_S-8500_TGCTCGTGTGAGCTAG-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TGCTTCGTCGATCTTT-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TGCTTTAGTTATCGAC-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TGGAAGGAGTGAATAC-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TGGAAGGTCCAGGTAT-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TGGTCAAAGTAGGAAG-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TGGTCCTGTGTCCAGC-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TGTAAGCCAGGTCCTG-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TGTGACACAGCTGATT-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TGTGTCCCAGGTGGTA-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTACCCGAGCTACGCC-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTACGTTTCTCTGAGA-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTACTCAAGCGGACTA-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTACTTGGTCTGATTG-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTAGCTTCAGTAACCT-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTATGTCGTTGGGAAC-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTCAACTTCGATATGC-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTCATCATCAATCGTG-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTCATTGTCTTGGCCT-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTCGCGTGTTAGTAGA-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTCTAACAGTCAGGAC-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTGAGCAAGTTAGAGT-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTGCACCGTATACGCT-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTGCGAAAGGCAAGCT-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTGCGAAAGGCATGCA-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTGCTTAGTGTGTGCC-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTGCTTATCCAACGCG-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTTACGTTCAGGGTTT-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTTGGCCCACAGTTAC-1 Pons     N/A    N/A             ⋯ N/A
atac_P-6255_S-8500_TTTGTGTCAACGTAGG-1 Pons     N/A    N/A             ⋯ N/A
                                      ACVR1 TSHR BRAF GNAQ LMNA KIT ARID1A KRAS
atac_T19-91014_AAACGAAAGACCCTAT-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACGAAAGCGTTGCC-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACGAAAGTACAACA-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACGAAAGTAGTGTA-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACGAAAGTGAATAC-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACGAAAGTGCCCTG-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACGAAAGTGTAATG-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACGAACAAATGCTC-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACGAACACGCCGAT-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACGAACAGGTGTCC-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACGAAGTACGGAGT-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACGAAGTATCCCTC-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACGAAGTATCTCAG-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACGAAGTCAGACGA-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACGAAGTCTGGTCG-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACGAAGTGAAACAT-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACGAATCGATGTAC-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACTCGAGAGAATTC-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACTCGAGCACCATT-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACTCGAGTGTCCCG-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACTCGCAAATTCCG-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACTCGCAACGTAGG-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACTCGCAATCAGGG-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACTCGCAATCATCG-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACTCGCAATTGCCA-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACTCGCACGCTGTG-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACTCGCACTCAGCG-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACTCGCACTTATGG-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACTCGCAGAACAGC-1     WT    WT   WT   WT   WT   WT  WT     WT
atac_T19-91014_AAACTCGGTAAACGTA-1     WT    WT   WT   WT   WT   WT  WT     WT
⋮                                     ⋮     ⋮    ⋮    ⋮    ⋮    ⋮   ⋮      ⋮

In [ ]:
atac_only <- AddMetaData(atac_only, atac_only_meta)
atac_only <- AddMetaData(atac_only, FetchData(subset(integrated, 
                                                     dataset == 'ATAC'), 
                                              'predicted.id')
                         )
atac_only$orig.ident <- NULL
atac_only$Batch_for_correction <- recode(atac_only$Sc_platform_ATAC,
                                        `10x_v1` = '10Xv1_nuclei_atac',
                                        `10X_v1.1` = '10X_v1.1_nuceli_atac')
atac_only$cell_id <- atac_only$predicted.id
atac_only@meta.data

                                      total  duplicate chimeric unmapped
atac_T19-91014_AAACGAAAGACCCTAT-1     37892  15065      1        438
atac_T19-91014_AAACGAAAGCGTTGCC-1     22601   6146      0        246
atac_T19-91014_AAACGAAAGTACAACA-1     88086  16394     15       1025
atac_T19-91014_AAACGAAAGTAGTGTA-1     67957  14538     11        877
atac_T19-91014_AAACGAAAGTGAATAC-1     21580   5723      1        213
atac_T19-91014_AAACGAAAGTGCCCTG-1     28527   7851      0        319
atac_T19-91014_AAACGAAAGTGTAATG-1     27213   9888      2        323
atac_T19-91014_AAACGAACAAATGCTC-1     32533   8763      0        352
atac_T19-91014_AAACGAACACGCCGAT-1     17835   5161      3        213
atac_T19-91014_AAACGAACAGGTGTCC-1     23349   5489      2        242
atac_T19-91014_AAACGAAGTACGGAGT-1     66244  12557      6        786
atac_T19-91014_AAACGAAGTATCCCTC-1     20966   4675      1        164
atac_T19-91014_AAACGAAGTATCTCAG-1     40695  10281      2        501
atac_T19-91014_AAACGAAGTCAGACGA-1     10269   1979      1        139
atac_T19-91014_AAACGAAGTCTGGTCG-1     60666  15628      8        725
atac_T19-91014_AAACGAAGTGAAACAT-1     24766  10011      1        283
atac_T19-91014_AAACGAATCGATGTAC-1     47801  14673      3        458
atac_T19-91014_AAACTCGAGAGAATTC-1     16882   3724      1        213
atac_T19-91014_AAACTCGAGCACCATT-1     79073  19773      2        912
atac_T19-91014_AAACTCGAGTGTCCCG-1     76434  18632     36        899
atac_T19-91014_AAACTCGCAAATTCCG-1     67224  25553      4        811
atac_T19-91014_AAACTCGCAACGTAGG-1     55655  16261      5        706
atac_T19-91014_AAACTCGCAATCAGGG-1     86552  33617     10       1027
atac_T19-91014_AAACTCGCAATCATCG-1     68951  21303     11        903
atac_T19-91014_AAACTCGCAATTGCCA-1     80096  23900      6        910
atac_T19-91014_AAACTCGCACGCTGTG-1     18795   4639      0        315
atac_T19-91014_AAACTCGCACTCAGCG-1     86064  33600      3       1237
atac_T19-91014_AAACTCGCACTTATGG-1     73650  20307      5        979
atac_T19-91014_AAACTCGCAGAACAGC-1     26137   7734      5        309
atac_T19-91014_AAACTCGGTAAACGTA-1     47269  14885      5        560
⋮                                     ⋮      ⋮         ⋮        ⋮
atac_P-6255_S-8500_TGCTCGTGTGAGCTAG-1 215086  90302    167      2002
atac_P-6255_S-8500_TGCTTCGTCGATCTTT-1 116029  50939     80      2596
atac_P-6255_S-8500_TGCTTTAGTTATCGAC-1 311658 182138    182      2543
atac_P-6255_S-8500_TGGAAGGAGTGAATAC-1 216494 104308    123      1291
atac_P-6255_S-8500_TGGAAGGTCCAGGTAT-1 450059 158083    380      3299
atac_P-6255_S-8500_TGGTCAAAGTAGGAAG-1 332466 137186    536      2989
atac_P-6255_S-8500_TGGTCCTGTGTCCAGC-1 339004 134615    481      2493
atac_P-6255_S-8500_TGTAAGCCAGGTCCTG-1 306744 159263    238      2538
atac_P-6255_S-8500_TGTGACACAGCTGATT-1  93432  31698     61       789
atac_P-6255_S-8500_TGTGTCCCAGGTGGTA-1 248715 121652    207      2316
atac_P-6255_S-8500_TTACCCGAGCTACGCC-1 213935  93389    190      1319
atac_P-6255_S-8500_TTACGTTTCTCTGAGA-1 126137  51124     96      1159
atac_P-6255_S-8500_TTACTCAAGCGGACTA-1 181870  79245    151      1102
atac_P-6255_S-8500_TTACTTGGTCTGATTG-1 316101 120421    390      2374
atac_P-6255_S-8500_TTAGCTTCAGTAACCT-1 480647 145634    578      3856
atac_P-6255_S-8500_TTATGTCGTTGGGAAC-1 292821  93520    407      2435
atac_P-6255_S-8500_TTCAACTTCGATATGC-1 292454 123547    231      1833
atac_P-6255_S-8500_TTCATCATCAATCGTG-1  65743  22363     31       350
atac_P-6255_S-8500_TTCATTGTCTTGGCCT-1 101613  28069     85      1123
atac_P-6255_S-8500_TTCGCGTGTTAGTAGA-1 335744 140292    336      3411
atac_P-6255_S-8500_TTCTAACAGTCAGGAC-1 238983 104760    180      1044
atac_P-6255_S-8500_TTGAGCAAGTTAGAGT-1 213228 106491    147      2068
atac_P-6255_S-8500_TTGCACCGTATACGCT-1 299194 176697    186      2304
atac_P-6255_S-8500_TTGCGAAAGGCAAGCT-1 276585 109747    249      1956
atac_P-6255_S-8500_TTGCGAAAGGCATGCA-1 284788 103871    363      1832
atac_P-6255_S-8500_TTGCTTAGTGTGTGCC-1 193582  70134    237      1594
atac_P-6255_S-8500_TTGCTTATCCAACGCG-1 112271  14497     47      1177
atac_P-6255_S-8500_TTTACGTTCAGGGTTT-1 257636 105526    247      1828
atac_P-6255_S-8500_TTTGGCCCACAGTTAC-1 173919  64116    122       897
atac_P-6255_S-8500_TTTGTGTCAACGTAGG-1 188218  87651    139      1635
                                      lowmapq mitochondrial nonprimary
atac_T19-91014_AAACGAAAGACCCTAT-1      3127    45             5
atac_T19-91014_AAACGAAAGCGTTGCC-1      1761     1             3
atac_T19-91014_AAACGAAAGTACAACA-1     10885    82           198
atac_T19-91014_AAACGAAAGTAGTGTA-1      7296    22            43
atac_T19-91014_AAACGAAAGTGAATAC-1      2597     9            12
atac_T19-91014_AAACGAAAGTGCCCTG-1      2382    16             6
atac_T19-91014_AAACGAAAGTGTAATG-1      2030    71             9
atac_T19-91014_AAACGAACAAATGCTC-1      2536   206            14
atac_T19-91014_AAACGAACACGCCGAT-1      1943    74            16
atac_T19-91014_AAACGAACAGGTGTCC-1      1534    40             5
atac_T19-91014_AAACGAAGTACGGAGT-1      6822    55            33
atac_T19-91014_AAACGAAGTATCCCTC-1      1312    11             0
atac_T19-91014_AAACGAAGTATCTCAG-1      4589    47            57
atac_T19-91014_AAACGAAGTCAGACGA-1       857     2             2
atac_T19-91014_AAACGAAGTCTGGTCG-1      4527    66            11
atac_T19-91014_AAACGAAGTGAAACAT-1      2095   210            10
atac_T19-91014_AAACGAATCGATGTAC-1      2818    21             4
atac_T19-91014_AAACTCGAGAGAATTC-1      2541    17             6
atac_T19-91014_AAACTCGAGCACCATT-1      6372    33            14
atac_T19-91014_AAACTCGAGTGTCCCG-1     11817    44           146
atac_T19-91014_AAACTCGCAAATTCCG-1      5010   194            28
atac_T19-91014_AAACTCGCAACGTAGG-1      3740     4            20
atac_T19-91014_AAACTCGCAATCAGGG-1      6047   143            51
atac_T19-91014_AAACTCGCAATCATCG-1      6793    93            13
atac_T19-91014_AAACTCGCAATTGCCA-1      5951    19            22
atac_T19-91014_AAACTCGCACGCTGTG-1      1308     1             5
atac_T19-91014_AAACTCGCACTCAGCG-1      8778   149            83
atac_T19-91014_AAACTCGCACTTATGG-1      7122   318            62
atac_T19-91014_AAACTCGCAGAACAGC-1      2425     9            13
atac_T19-91014_AAACTCGGTAAACGTA-1      3728    65            16
⋮                                     ⋮       ⋮             ⋮
atac_P-6255_S-8500_TGCTCGTGTGAGCTAG-1 15949   12690          229
atac_P-6255_S-8500_TGCTTCGTCGATCTTT-1 12780   27571           47
atac_P-6255_S-8500_TGCTTTAGTTATCGAC-1 28012   16114          442
atac_P-6255_S-8500_TGGAAGGAGTGAATAC-1 12031     687          190
atac_P-6255_S-8500_TGGAAGGTCCAGGTAT-1 41515   52555          797
atac_P-6255_S-8500_TGGTCAAAGTAGGAAG-1 22721   13194          409
atac_P-6255_S-8500_TGGTCCTGTGTCCAGC-1 27323   16670          648
atac_P-6255_S-8500_TGTAAGCCAGGTCCTG-1 20760   38401          370
atac_P-6255_S-8500_TGTGACACAGCTGATT-1  6213    1954           99
atac_P-6255_S-8500_TGTGTCCCAGGTGGTA-1 17306   15005          108
atac_P-6255_S-8500_TTACCCGAGCTACGCC-1 16959   12814          361
atac_P-6255_S-8500_TTACGTTTCTCTGAGA-1  8102    5734          100
atac_P-6255_S-8500_TTACTCAAGCGGACTA-1 13998    3592          392
atac_P-6255_S-8500_TTACTTGGTCTGATTG-1 26856   47094          484
atac_P-6255_S-8500_TTAGCTTCAGTAACCT-1 45184   19907         1590
atac_P-6255_S-8500_TTATGTCGTTGGGAAC-1 22547   30491          306
atac_P-6255_S-8500_TTCAACTTCGATATGC-1 28044   29441          998
atac_P-6255_S-8500_TTCATCATCAATCGTG-1  6639    8051           54
atac_P-6255_S-8500_TTCATTGTCTTGGCCT-1  9694   10148          255
atac_P-6255_S-8500_TTCGCGTGTTAGTAGA-1 23175   17888          356
atac_P-6255_S-8500_TTCTAACAGTCAGGAC-1 21192   11425          459
atac_P-6255_S-8500_TTGAGCAAGTTAGAGT-1 14504    5689          206
atac_P-6255_S-8500_TTGCACCGTATACGCT-1 24123    6414          210
atac_P-6255_S-8500_TTGCGAAAGGCAAGCT-1 22309   19191          451
atac_P-6255_S-8500_TTGCGAAAGGCATGCA-1 26416   43364          555
atac_P-6255_S-8500_TTGCTTAGTGTGTGCC-1 16514     239          550
atac_P-6255_S-8500_TTGCTTATCCAACGCG-1 10542    9459          402
atac_P-6255_S-8500_TTTACGTTCAGGGTTT-1 33853    6801         1374
atac_P-6255_S-8500_TTTGGCCCACAGTTAC-1 13928   22706          156
atac_P-6255_S-8500_TTTGTGTCAACGTAGG-1 17154    9335          464
                                      passed_filters is__cell_barcode
atac_T19-91014_AAACGAAAGACCCTAT-1     19211          1
atac_T19-91014_AAACGAAAGCGTTGCC-1     14444          1
atac_T19-91014_AAACGAAAGTACAACA-1     59487          1
atac_T19-91014_AAACGAAAGTAGTGTA-1     45170          1
atac_T19-91014_AAACGAAAGTGAATAC-1     13025          1
atac_T19-91014_AAACGAAAGTGCCCTG-1     17953          1
atac_T19-91014_AAACGAAAGTGTAATG-1     14890          1
atac_T19-91014_AAACGAACAAATGCTC-1     20662          1
atac_T19-91014_AAACGAACACGCCGAT-1     10425          1
atac_T19-91014_AAACGAACAGGTGTCC-1     16037          1
atac_T19-91014_AAACGAAGTACGGAGT-1     45985          1
atac_T19-91014_AAACGAAGTATCCCTC-1     14803          1
atac_T19-91014_AAACGAAGTATCTCAG-1     25218          1
atac_T19-91014_AAACGAAGTCAGACGA-1      7289          1
atac_T19-91014_AAACGAAGTCTGGTCG-1     39701          1
atac_T19-91014_AAACGAAGTGAAACAT-1     12156          1
atac_T19-91014_AAACGAATCGATGTAC-1     29824          1
atac_T19-91014_AAACTCGAGAGAATTC-1     10380          1
atac_T19-91014_AAACTCGAGCACCATT-1     51967          1
atac_T19-91014_AAACTCGAGTGTCCCG-1     44860          1
atac_T19-91014_AAACTCGCAAATTCCG-1     35624          1
atac_T19-91014_AAACTCGCAACGTAGG-1     34919          1
atac_T19-91014_AAACTCGCAATCAGGG-1     45657          1
atac_T19-91014_AAACTCGCAATCATCG-1     39835          1
atac_T19-91014_AAACTCGCAATTGCCA-1     49288          1
atac_T19-91014_AAACTCGCACGCTGTG-1     12527          1
atac_T19-91014_AAACTCGCACTCAGCG-1     42214          1
atac_T19-91014_AAACTCGCACTTATGG-1     44857          1
atac_T19-91014_AAACTCGCAGAACAGC-1     15642          1
atac_T19-91014_AAACTCGGTAAACGTA-1     28010          1
⋮                                     ⋮              ⋮
atac_P-6255_S-8500_TGCTCGTGTGAGCTAG-1  93747         1
atac_P-6255_S-8500_TGCTTCGTCGATCTTT-1  22016         1
atac_P-6255_S-8500_TGCTTTAGTTATCGAC-1  82227         1
atac_P-6255_S-8500_TGGAAGGAGTGAATAC-1  97864         1
atac_P-6255_S-8500_TGGAAGGTCCAGGTAT-1 193430         1
atac_P-6255_S-8500_TGGTCAAAGTAGGAAG-1 155431         1
atac_P-6255_S-8500_TGGTCCTGTGTCCAGC-1 156774         1
atac_P-6255_S-8500_TGTAAGCCAGGTCCTG-1  85174         1
atac_P-6255_S-8500_TGTGACACAGCTGATT-1  52618         1
atac_P-6255_S-8500_TGTGTCCCAGGTGGTA-1  92121         1
atac_P-6255_S-8500_TTACCCGAGCTACGCC-1  88903         1
atac_P-6255_S-8500_TTACGTTTCTCTGAGA-1  59822         1
atac_P-6255_S-8500_TTACTCAAGCGGACTA-1  83390         1
atac_P-6255_S-8500_TTACTTGGTCTGATTG-1 118482         1
atac_P-6255_S-8500_TTAGCTTCAGTAACCT-1 263898         1
atac_P-6255_S-8500_TTATGTCGTTGGGAAC-1 143115         1
atac_P-6255_S-8500_TTCAACTTCGATATGC-1 108360         1
atac_P-6255_S-8500_TTCATCATCAATCGTG-1  28255         1
atac_P-6255_S-8500_TTCATTGTCTTGGCCT-1  52239         1
atac_P-6255_S-8500_TTCGCGTGTTAGTAGA-1 150286         1
atac_P-6255_S-8500_TTCTAACAGTCAGGAC-1  99923         1
atac_P-6255_S-8500_TTGAGCAAGTTAGAGT-1  84123         1
atac_P-6255_S-8500_TTGCACCGTATACGCT-1  89260         1
atac_P-6255_S-8500_TTGCGAAAGGCAAGCT-1 122682         1
atac_P-6255_S-8500_TTGCGAAAGGCATGCA-1 108387         1
atac_P-6255_S-8500_TTGCTTAGTGTGTGCC-1 104314         1
atac_P-6255_S-8500_TTGCTTATCCAACGCG-1  76147         1
atac_P-6255_S-8500_TTTACGTTCAGGGTTT-1 108007         1
atac_P-6255_S-8500_TTTGGCCCACAGTTAC-1  71994         1
atac_P-6255_S-8500_TTTGTGTCAACGTAGG-1  71840         1
                                      excluded_reason ⋯ BRAF GNAQ LMNA KIT
atac_T19-91014_AAACGAAAGACCCTAT-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACGAAAGCGTTGCC-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACGAAAGTACAACA-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACGAAAGTAGTGTA-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACGAAAGTGAATAC-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACGAAAGTGCCCTG-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACGAAAGTGTAATG-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACGAACAAATGCTC-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACGAACACGCCGAT-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACGAACAGGTGTCC-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACGAAGTACGGAGT-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACGAAGTATCCCTC-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACGAAGTATCTCAG-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACGAAGTCAGACGA-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACGAAGTCTGGTCG-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACGAAGTGAAACAT-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACGAATCGATGTAC-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACTCGAGAGAATTC-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACTCGAGCACCATT-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACTCGAGTGTCCCG-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACTCGCAAATTCCG-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACTCGCAACGTAGG-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACTCGCAATCAGGG-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACTCGCAATCATCG-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACTCGCAATTGCCA-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACTCGCACGCTGTG-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACTCGCACTCAGCG-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACTCGCACTTATGG-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACTCGCAGAACAGC-1     0               ⋯ WT   WT   WT   WT
atac_T19-91014_AAACTCGGTAAACGTA-1     0               ⋯ WT   WT   WT   WT
⋮                                     ⋮               ⋱ ⋮    ⋮    ⋮    ⋮
atac_P-6255_S-8500_TGCTCGTGTGAGCTAG-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TGCTTCGTCGATCTTT-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TGCTTTAGTTATCGAC-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TGGAAGGAGTGAATAC-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TGGAAGGTCCAGGTAT-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TGGTCAAAGTAGGAAG-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TGGTCCTGTGTCCAGC-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TGTAAGCCAGGTCCTG-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TGTGACACAGCTGATT-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TGTGTCCCAGGTGGTA-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTACCCGAGCTACGCC-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTACGTTTCTCTGAGA-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTACTCAAGCGGACTA-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTACTTGGTCTGATTG-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTAGCTTCAGTAACCT-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTATGTCGTTGGGAAC-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTCAACTTCGATATGC-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTCATCATCAATCGTG-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTCATTGTCTTGGCCT-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTCGCGTGTTAGTAGA-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTCTAACAGTCAGGAC-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTGAGCAAGTTAGAGT-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTGCACCGTATACGCT-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTGCGAAAGGCAAGCT-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTGCGAAAGGCATGCA-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTGCTTAGTGTGTGCC-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTGCTTATCCAACGCG-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTTACGTTCAGGGTTT-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTTGGCCCACAGTTAC-1 0               ⋯ N/A  N/A  N/A  N/A
atac_P-6255_S-8500_TTTGTGTCAACGTAGG-1 0               ⋯ N/A  N/A  N/A  N/A
                                      ARID1A KRAS Other
atac_T19-91014_AAACGAAAGACCCTAT-1     WT     WT   N/A
atac_T19-91014_AAACGAAAGCGTTGCC-1     WT     WT   N/A
atac_T19-91014_AAACGAAAGTACAACA-1     WT     WT   N/A
atac_T19-91014_AAACGAAAGTAGTGTA-1     WT     WT   N/A
atac_T19-91014_AAACGAAAGTGAATAC-1     WT     WT   N/A
atac_T19-91014_AAACGAAAGTGCCCTG-1     WT     WT   N/A
atac_T19-91014_AAACGAAAGTGTAATG-1     WT     WT   N/A
atac_T19-91014_AAACGAACAAATGCTC-1     WT     WT   N/A
atac_T19-91014_AAACGAACACGCCGAT-1     WT     WT   N/A
atac_T19-91014_AAACGAACAGGTGTCC-1     WT     WT   N/A
atac_T19-91014_AAACGAAGTACGGAGT-1     WT     WT   N/A
atac_T19-91014_AAACGAAGTATCCCTC-1     WT     WT   N/A
atac_T19-91014_AAACGAAGTATCTCAG-1     WT     WT   N/A
atac_T19-91014_AAACGAAGTCAGACGA-1     WT     WT   N/A
atac_T19-91014_AAACGAAGTCTGGTCG-1     WT     WT   N/A
atac_T19-91014_AAACGAAGTGAAACAT-1     WT     WT   N/A
atac_T19-91014_AAACGAATCGATGTAC-1     WT     WT   N/A
atac_T19-91014_AAACTCGAGAGAATTC-1     WT     WT   N/A
atac_T19-91014_AAACTCGAGCACCATT-1     WT     WT   N/A
atac_T19-91014_AAACTCGAGTGTCCCG-1     WT     WT   N/A
atac_T19-91014_AAACTCGCAAATTCCG-1     WT     WT   N/A
atac_T19-91014_AAACTCGCAACGTAGG-1     WT     WT   N/A
atac_T19-91014_AAACTCGCAATCAGGG-1     WT     WT   N/A
atac_T19-91014_AAACTCGCAATCATCG-1     WT     WT   N/A
atac_T19-91014_AAACTCGCAATTGCCA-1     WT     WT   N/A
atac_T19-91014_AAACTCGCACGCTGTG-1     WT     WT   N/A
atac_T19-91014_AAACTCGCACTCAGCG-1     WT     WT   N/A
atac_T19-91014_AAACTCGCACTTATGG-1     WT     WT   N/A
atac_T19-91014_AAACTCGCAGAACAGC-1     WT     WT   N/A
atac_T19-91014_AAACTCGGTAAACGTA-1     WT     WT   N/A
⋮                                     ⋮      ⋮    ⋮
atac_P-6255_S-8500_TGCTCGTGTGAGCTAG-1 N/A    N/A  N/A
atac_P-6255_S-8500_TGCTTCGTCGATCTTT-1 N/A    N/A  N/A
atac_P-6255_S-8500_TGCTTTAGTTATCGAC-1 N/A    N/A  N/A
atac_P-6255_S-8500_TGGAAGGAGTGAATAC-1 N/A    N/A  N/A
atac_P-6255_S-8500_TGGAAGGTCCAGGTAT-1 N/A    N/A  N/A
atac_P-6255_S-8500_TGGTCAAAGTAGGAAG-1 N/A    N/A  N/A
atac_P-6255_S-8500_TGGTCCTGTGTCCAGC-1 N/A    N/A  N/A
atac_P-6255_S-8500_TGTAAGCCAGGTCCTG-1 N/A    N/A  N/A
atac_P-6255_S-8500_TGTGACACAGCTGATT-1 N/A    N/A  N/A
atac_P-6255_S-8500_TGTGTCCCAGGTGGTA-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTACCCGAGCTACGCC-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTACGTTTCTCTGAGA-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTACTCAAGCGGACTA-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTACTTGGTCTGATTG-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTAGCTTCAGTAACCT-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTATGTCGTTGGGAAC-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTCAACTTCGATATGC-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTCATCATCAATCGTG-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTCATTGTCTTGGCCT-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTCGCGTGTTAGTAGA-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTCTAACAGTCAGGAC-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTGAGCAAGTTAGAGT-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTGCACCGTATACGCT-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTGCGAAAGGCAAGCT-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTGCGAAAGGCATGCA-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTGCTTAGTGTGTGCC-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTGCTTATCCAACGCG-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTTACGTTCAGGGTTT-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTTGGCCCACAGTTAC-1 N/A    N/A  N/A
atac_P-6255_S-8500_TTTGTGTCAACGTAGG-1 N/A    N/A  N/A
                                      predicted.id
atac_T19-91014_AAACGAAAGACCCTAT-1     Stem_like_tumor
atac_T19-91014_AAACGAAAGCGTTGCC-1     TAM_MG
atac_T19-91014_AAACGAAAGTACAACA-1     Stem_like_tumor
atac_T19-91014_AAACGAAAGTAGTGTA-1     Stem_like_tumor
atac_T19-91014_AAACGAAAGTGAATAC-1     Oligodendrocyte

##### Multiome

In [ ]:
# Assuming you have a dataframe named "data" containing the column you want to rename
colnames(atac_multi@meta.data) <- sub("p.value", "amulet_pvalue", colnames(atac_multi@meta.data))
colnames(atac_multi@meta.data) <- sub("q.value", "amulet_qvalue", colnames(atac_multi@meta.data))
colnames(atac_multi@meta.data) <- sub("combined", "dbl_combined_score", colnames(atac_multi@meta.data))

head(atac_multi@meta.data)

                                 orig.ident    gex_barcode
GNG_region_11_AAACAGCCAAAGCGGC-1 SeuratProject AAACAGCCAAAGCGGC-1
GNG_region_11_AAACAGCCAGGTTCAC-1 SeuratProject AAACAGCCAGGTTCAC-1
GNG_region_11_AAACATGCAACTGGCT-1 SeuratProject AAACATGCAACTGGCT-1
GNG_region_11_AAACATGCACGAACAG-1 SeuratProject AAACATGCACGAACAG-1
GNG_region_11_AAACATGCAGGCCAAA-1 SeuratProject AAACATGCAGGCCAAA-1
GNG_region_11_AAACCAACACACAATT-1 SeuratProject AAACCAACACACAATT-1
                                 atac_barcode       is_cell excluded_reason
GNG_region_11_AAACAGCCAAAGCGGC-1 ACAGCGGGTGGATTAG-1 0       2
GNG_region_11_AAACAGCCAGGTTCAC-1 ACAGCGGGTCCTGACA-1 1       0
GNG_region_11_AAACATGCAACTGGCT-1 CATTTAGGTCTTGACG-1 1       0
GNG_region_11_AAACATGCACGAACAG-1 CATTTAGGTCACACTG-1 1       0
GNG_region_11_AAACATGCAGGCCAAA-1 CATTTAGGTTGAGGTA-1 0       2
GNG_region_11_AAACCAACACACAATT-1 CTTTATCGTCGGTTTG-1 1       0
                                 gex_raw_reads gex_mapped_reads
GNG_region_11_AAACAGCCAAAGCGGC-1   4828          4639
GNG_region_11_AAACAGCCAGGTTCAC-1  11573         10964
GNG_region_11_AAACATGCAACTGGCT-1   3339          3187
GNG_region_11_AAACATGCACGAACAG-1  15407         14885
GNG_region_11_AAACATGCAGGCCAAA-1 127096        122482
GNG_region_11_AAACCAACACACAATT-1  15095         14589
                                 gex_conf_intergenic_reads
GNG_region_11_AAACAGCCAAAGCGGC-1  410
GNG_region_11_AAACAGCCAGGTTCAC-1 1090
GNG_region_11_AAACATGCAACTGGCT-1  234
GNG_region_11_AAACATGCACGAACAG-1  969
GNG_region_11_AAACATGCAGGCCAAA-1 9153
GNG_region_11_AAACCAACACACAATT-1  986
                                 gex_conf_exonic_reads gex_conf_intronic_reads
GNG_region_11_AAACAGCCAAAGCGGC-1  1182                  2776
GNG_region_11_AAACAGCCAGGTTCAC-1  1980                  5696
GNG_region_11_AAACATGCAACTGGCT-1   648                  2149
GNG_region_11_AAACATGCACGAACAG-1  6106                  7092
GNG_region_11_AAACATGCAGGCCAAA-1 26593                 80542
GNG_region_11_AAACCAACACACAATT-1  3928                  8756
                                 ⋯ pct_reads_in_peaks blacklist_ratio high.tss
GNG_region_11_AAACAGCCAAAGCGGC-1 ⋯ 13.180516          0.011647727     Low
GNG_region_11_AAACAGCCAGGTTCAC-1 ⋯ 24.829869          0.004587156     High
GNG_region_11_AAACATGCAACTGGCT-1 ⋯ 16.735623          0.001241465     High
GNG_region_11_AAACATGCACGAACAG-1 ⋯ 18.917511          0.011389680     High
GNG_region_11_AAACATGCAGGCCAAA-1 ⋯  7.329515          0.018049883     High
GNG_region_11_AAACCAACACACAATT-1 ⋯ 18.005190          0.008573655     High
                                 nucleosome_group scDblFinder.score
GNG_region_11_AAACAGCCAAAGCGGC-1 NS < 4           0.020549510
GNG_region_11_AAACAGCCAGGTTCAC-1 NS < 4           0.120021418
GNG_region_11_AAACATGCAACTGGCT-1 NS < 4           0.001335426
GNG_region_11_AAACATGCACGAACAG-1 NS < 4           0.202490866
GNG_region_11_AAACATGCAGGCCAAA-1 NS < 4           0.037750602
GNG_region_11_AAACCAACACACAATT-1 NS < 4           0.195009470
                                 scDblFinder.class amulet_pvalue amulet_qvalue
GNG_region_11_AAACAGCCAAAGCGGC-1 singlet           1.000000e+00  1.000000e+00
GNG_region_11_AAACAGCCAGGTTCAC-1 singlet           1.000000e+00  1.000000e+00
GNG_region_11_AAACATGCAACTGGCT-1 singlet           1.000000e+00  1.000000e+00
GNG_region_11_AAACATGCACGAACAG-1 singlet           9.999859e-01  1.000000e+00
GNG_region_11_AAACATGCAGGCCAAA-1 singlet           4.135571e-56  9.657695e-55
GNG_region_11_AAACCAACACACAATT-1 singlet           1.000000e+00  1.000000e+00
                                 scDblFinder.p dbl_combined_score
GNG_region_11_AAACAGCCAAAGCGGC-1 0.9794505     0.999787397
GNG_region_11_AAACAGCCAGGTTCAC-1 0.8799786     0.992490629
GNG_region_11_AAACATGCAACTGGCT-1 0.9986646     0.999999108
GNG_region_11_AAACATGCACGAACAG-1 0.7975091     0.977952592
GNG_region_11_AAACATGCAGGCCAAA-1 0.9622494     0.007646262
GNG_region_11_AAACCAACACACAATT-1 0.8049905     0.979612910

In [ ]:
table(atac_multi$SampleID)

 GNG_region_11  P-1694_S-1694  P-1701_S-1701  P-1709_S-1709  P-1764_S-1766
          7216           5079          12982          19181           8693
 P-1779_S-1781  P-1780_S-1780  P-6253_S-8498  P-6337_S-8821  P-6640_S-9581
         10523           8518           6892           4365           6849
P-6774_S-10146
          9438

In [ ]:
atac_multi$ID <- dplyr::recode(atac_multi$SampleID, GNG_region_11 = 'GNG')
table(atac_multi$ID)

           GNG  P-1694_S-1694  P-1701_S-1701  P-1709_S-1709  P-1764_S-1766
          7216           5079          12982          19181           8693
 P-1779_S-1781  P-1780_S-1780  P-6253_S-8498  P-6337_S-8821  P-6640_S-9581
         10523           8518           6892           4365           6849
P-6774_S-10146
          9438

In [ ]:
meta_id_cells <- data.frame(Cell = colnames(atac_multi),
           ID = atac_multi$ID,
           check.names = FALSE
          )
meta_id_cells

                                           Cell
GNG_region_11_AAACAGCCAAAGCGGC-1           GNG_region_11_AAACAGCCAAAGCGGC-1
GNG_region_11_AAACAGCCAGGTTCAC-1           GNG_region_11_AAACAGCCAGGTTCAC-1
GNG_region_11_AAACATGCAACTGGCT-1           GNG_region_11_AAACATGCAACTGGCT-1
GNG_region_11_AAACATGCACGAACAG-1           GNG_region_11_AAACATGCACGAACAG-1
GNG_region_11_AAACATGCAGGCCAAA-1           GNG_region_11_AAACATGCAGGCCAAA-1
GNG_region_11_AAACCAACACACAATT-1           GNG_region_11_AAACCAACACACAATT-1
GNG_region_11_AAACCAACACGTTACA-1           GNG_region_11_AAACCAACACGTTACA-1
GNG_region_11_AAACCAACATCATGTG-1           GNG_region_11_AAACCAACATCATGTG-1
GNG_region_11_AAACCAACATGATTGT-1           GNG_region_11_AAACCAACATGATTGT-1
GNG_region_11_AAACCGAAGCCTCTGT-1           GNG_region_11_AAACCGAAGCCTCTGT-1
GNG_region_11_AAACCGCGTATGGTGC-1           GNG_region_11_AAACCGCGTATGGTGC-1
GNG_region_11_AAACCGGCAATGCCCG-1           GNG_region_11_AAACCGGCAATGCCCG-1
GNG_region_11_AAACCGGCAGAACCGA-1           GNG_region_11_AAACCGGCAGAACCGA-1
GNG_region_11_AAACCGGCAGGCCTTG-1           GNG_region_11_AAACCGGCAGGCCTTG-1
GNG_region_11_AAACCGGCAGGCTACT-1           GNG_region_11_AAACCGGCAGGCTACT-1
GNG_region_11_AAACGCGCAAATTCGT-1           GNG_region_11_AAACGCGCAAATTCGT-1
GNG_region_11_AAACGCGCAATGAGGT-1           GNG_region_11_AAACGCGCAATGAGGT-1
GNG_region_11_AAACGCGCAGGAATCG-1           GNG_region_11_AAACGCGCAGGAATCG-1
GNG_region_11_AAACGCGCAGTTATCG-1           GNG_region_11_AAACGCGCAGTTATCG-1
GNG_region_11_AAACGCGCATAAGGAC-1           GNG_region_11_AAACGCGCATAAGGAC-1
GNG_region_11_AAACGGATCACCAATA-1           GNG_region_11_AAACGGATCACCAATA-1
GNG_region_11_AAACGGATCAGTTCCC-1           GNG_region_11_AAACGGATCAGTTCCC-1
GNG_region_11_AAACGGATCATTAGCA-1           GNG_region_11_AAACGGATCATTAGCA-1
GNG_region_11_AAACGGATCCTGGTCT-1           GNG_region_11_AAACGGATCCTGGTCT-1
GNG_region_11_AAACGGATCGGCTAGC-1           GNG_region_11_AAACGGATCGGCTAGC-1
GNG_region_11_AAACGGATCGTTACTT-1           GNG_region_11_AAACGGATCGTTACTT-1
GNG_region_11_AAACGTACAAATGCCC-1           GNG_region_11_AAACGTACAAATGCCC-1
GNG_region_11_AAACGTACAACTAGGG-1           GNG_region_11_AAACGTACAACTAGGG-1
GNG_region_11_AAACGTACAAGTGTTT-1           GNG_region_11_AAACGTACAAGTGTTT-1
GNG_region_11_AAACGTACAATAACCT-1           GNG_region_11_AAACGTACAATAACCT-1
⋮                                          ⋮
multiome_P-6774_S-10146_TTTGTCTAGGAACGCG-1 multiome_P-6774_S-10146_TTTGTCTAGGAACGCG-1
multiome_P-6774_S-10146_TTTGTCTAGGAGTCTT-1 multiome_P-6774_S-10146_TTTGTCTAGGAGTCTT-1
multiome_P-6774_S-10146_TTTGTCTAGGCAACAA-1 multiome_P-6774_S-10146_TTTGTCTAGGCAACAA-1
multiome_P-6774_S-10146_TTTGTGAAGACAGGCG-1 multiome_P-6774_S-10146_TTTGTGAAGACAGGCG-1
multiome_P-6774_S-10146_TTTGTGAAGATGGAGC-1 multiome_P-6774_S-10146_TTTGTGAAGATGGAGC-1
multiome_P-6774_S-10146_TTTGTGAAGCAGCTCA-1 multiome_P-6774_S-10146_TTTGTGAAGCAGCTCA-1
multiome_P-6774_S-10146_TTTGTGAAGCCGCAGT-1 multiome_P-6774_S-10146_TTTGTGAAGCCGCAGT-1
multiome_P-6774_S-10146_TTTGTGAAGTATTGTG-1 multiome_P-6774_S-10146_TTTGTGAAGTATTGTG-1
multiome_P-6774_S-10146_TTTGTGAAGTTAGCTA-1 multiome_P-6774_S-10146_TTTGTGAAGTTAGCTA-1
multiome_P-6774_S-10146_TTTGTGGCAAGCTAAA-1 multiome_P-6774_S-10146_TTTGTGGCAAGCTAAA-1
multiome_P-6774_S-10146_TTTGTGGCAAGGAATC-1 multiome_P-6774_S-10146_TTTGTGGCAAGGAATC-1
multiome_P-6774_S-10146_TTTGTGGCAAGGTACG-1 multiome_P-6774_S-10146_TTTGTGGCAAGGTACG-1
multiome_P-6774_S-10146_TTTGTGGCAATTAACC-1 multiome_P-6774_S-10146_TTTGTGGCAATTAACC-1
multiome_P-6774_S-10146_TTTGTGGCACCTCGCT-1 multiome_P-6774_S-10146_TTTGTGGCACCTCGCT-1
multiome_P-6774_S-10146_TTTGTGGCACGTAATT-1 multiome_P-6774_S-10146_TTTGTGGCACGTAATT-1
multiome_P-6774_S-10146_TTTGTGGCACTTGTTC-1 multiome_P-6774_S-10146_TTTGTGGCACTTGTTC-1
multiome_P-6774_S-10146_TTTGTGGCAGCAAATA-1 multiome_P-6774_S-10146_TTTGTGGCAGCAAATA-1
multiome_P-6774_S-10146_TTTGTGGCAGCAACAG-1 multiome_P-6774_S-10146_TTTGTGGCAGCAACAG-1
multiome_P-6774_S-10146_TTTGTGGCATGCTATG-1 multiome_P-6774_S-10146_TTTGTGGCATGCTATG-1
multiome_P-6774_S-10146_TTTGTGGCATTATGAC-1 multiome_P-6774_S-10146_TTTGTGGCATTATGAC-1
multiome_P-6774_S-10146_TTTGTGTTCAAGTGAG-1 multiome_P-6774_S-10146_TTTGTGTTCAAGTGAG-1
multiome_P-6774_S-10146_TTTGTGTTCCTAGTAA-1 multiome_P-6774_S-10146_TTTGTGTTCCTAGTAA-1
multiome_P-6774_S-10146_TTTGTGTTCTAATTGG-1 multiome_P-6774_S-10146_TTTGTGTTCTAATTGG-1
multiome_P-6774_S-10146_TTTGTTGGTAGGATTT-1 multiome_P-6774_S-10146_TTTGTTGGTAGGATTT-1
multiome_P-6774_S-10146_TTTGTTGGTCATTGTC-1 multiome_P-6774_S-10146_TTTGTTGGTCATTGTC-1
multiome_P-6774_S-10146_TTTGTTGGTTGCATCT-1 multiome_P-6774_S-10146_TTTGTTGGTTGCATCT-1
multiome_P-6774_S-10146_TTTGTTGGTTGGATAT-1 multiome_P-6774_S-10146_TTTGTTGGTTGGATAT-1
multiome_P-6774_S-10146_TTTGTTGGTTGGCCGA-1 multiome_P-6774_S-10146_TTTGTTGGTTGGCCGA-1
multiome_P-6774_S-10146_TTTGTTGGTTGTAACG-1 multiome_P-6774_S-10146_TTTGTTGGTTGTAACG-1
multiome_P-6774_S-10146_TTTGTTGGTTTATCGC-1 multiome_P-6774_S-10146_TTTGTTGGTTTATCGC-1
                                           ID
GNG_region_11_AAACAGCCAAAGCGGC-1           GNG
GNG_region_11_AAACAGCCAGGTTCAC-1           GNG
GNG_region_11_AAACATGCAACTGGCT-1           GNG
GNG_region_11_AAACATGCACGAACAG-1           GNG
GNG_region_11_AAACATGCAGGCCAAA-1           GNG
GNG_region_11_AAACCAACACACAATT-1           GNG
GNG_region_11_AAACCAACACGTTACA-1           GNG
GNG_region_11_AAACCAACATCATGTG-1           GNG
GNG_region_11_AAACCAACATGATTGT-1           GNG
GNG_region_11_AAACCGAAGCCTCTGT-1           GNG
GNG_region_11_AAACCGCGTATGGTGC-1           GNG
GNG_region_11_AAACCGGCAATGCCCG-1           GNG
GNG_region_11_AAACCGGCAGAACCGA-1           GNG
GNG_region_11_AAACCGGCAGGCCTTG-1           GNG
GNG_region_11_AAACCGGCAGGCTACT-1           GNG
GNG_region_11_AAACGCGCAAATTCGT-1           GNG
GNG_region_11_AAACGCGCAATGAGGT-1           GNG
GNG_region_11_AAACGCGCAGGAATCG-1           GNG
GNG_region_11_AAACGCGCAGTTATCG-1           GNG
GNG_region_11_AAACGCGCATAAGGAC-1           GNG
GNG_region_11_AAACGGATCACCAATA-1           GNG
GNG_region_11_AAACGGATCAGTTCCC-1           GNG
GNG_region_11_AAACGGATCATTAGCA-1           GNG
GNG_region_11_AAACGGATCCTGGTCT-1           GNG
GNG_region_11_AAACGGATCGGCTAGC-1           GNG
GNG_region_11_AAACGGATCGTTACTT-1           GNG
GNG_region_11_AAACGTACAAATGCCC-1           GNG
GNG_region_11_AAACGTACAACTAGGG-1           GNG
GNG_region_11_AAACGTACAAGTGTTT-1           GNG
GNG_region_11_AAACGTACAATAACCT-1           GNG
⋮                                          ⋮
multiome_P-6774_S-10146_TTTGTCTAGGAACGCG-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTCTAGGAGTCTT-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTCTAGGCAACAA-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGAAGACAGGCG-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGAAGATGGAGC-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGAAGCAGCTCA-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGAAGCCGCAGT-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGAAGTATTGTG-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGAAGTTAGCTA-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGGCAAGCTAAA-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGGCAAGGAATC-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGGCAAGGTACG-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGGCAATTAACC-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGGCACCTCGCT-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGGCACGTAATT-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGGCACTTGTTC-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGGCAGCAAATA-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGGCAGCAACAG-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGGCATGCTATG-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGGCATTATGAC-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGTTCAAGTGAG-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGTTCCTAGTAA-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTGTTCTAATTGG-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTTGGTAGGATTT-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTTGGTCATTGTC-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTTGGTTGCATCT-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTTGGTTGGATAT-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTTGGTTGGCCGA-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTTGGTTGTAACG-1 P-6774_S-10146
multiome_P-6774_S-10146_TTTGTTGGTTTATCGC-1 P-6774_S-10146

In [ ]:
all(meta_id_cells$ID %in% meta_cohort$ID)

[1] TRUE

In [ ]:
atac_multi_meta <- list(meta_id_cells, meta_cohort) %>% 
                    purrr::reduce(inner_join, by = 'ID') %>% 
                    distinct(Cell, .keep_all = TRUE) %>% 
                    tibble::column_to_rownames('Cell')
atac_multi_meta

                                           ID             Study     Institute
GNG_region_11_AAACAGCCAAAGCGGC-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACAGCCAGGTTCAC-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACATGCAACTGGCT-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACATGCACGAACAG-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACATGCAGGCCAAA-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACCAACACACAATT-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACCAACACGTTACA-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACCAACATCATGTG-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACCAACATGATTGT-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACCGAAGCCTCTGT-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACCGCGTATGGTGC-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACCGGCAATGCCCG-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACCGGCAGAACCGA-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACCGGCAGGCCTTG-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACCGGCAGGCTACT-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACGCGCAAATTCGT-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACGCGCAATGAGGT-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACGCGCAGGAATCG-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACGCGCAGTTATCG-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACGCGCATAAGGAC-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACGGATCACCAATA-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACGGATCAGTTCCC-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACGGATCATTAGCA-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACGGATCCTGGTCT-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACGGATCGGCTAGC-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACGGATCGTTACTT-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACGTACAAATGCCC-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACGTACAACTAGGG-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACGTACAAGTGTTT-1           GNG            Ruiz2023  UMCG
GNG_region_11_AAACGTACAATAACCT-1           GNG            Ruiz2023  UMCG
⋮                                          ⋮              ⋮         ⋮
multiome_P-6774_S-10146_TTTGTCTAGGAACGCG-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTCTAGGAGTCTT-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTCTAGGCAACAA-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGAAGACAGGCG-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGAAGATGGAGC-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGAAGCAGCTCA-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGAAGCCGCAGT-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGAAGTATTGTG-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGAAGTTAGCTA-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGGCAAGCTAAA-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGGCAAGGAATC-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGGCAAGGTACG-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGGCAATTAACC-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGGCACCTCGCT-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGGCACGTAATT-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGGCACTTGTTC-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGGCAGCAAATA-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGGCAGCAACAG-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGGCATGCTATG-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGGCATTATGAC-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGTTCAAGTGAG-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGTTCCTAGTAA-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTGTTCTAATTGG-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTTGGTAGGATTT-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTTGGTCATTGTC-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTTGGTTGCATCT-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTTGGTTGGATAT-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTTGGTTGGCCGA-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTTGGTTGTAACG-1 P-6774_S-10146 Jessa2022 N/A
multiome_P-6774_S-10146_TTTGTTGGTTTATCGC-1 P-6774_S-10146 Jessa2022 N/A
                                           Preservation_method Diagnosis
GNG_region_11_AAACAGCCAAAGCGGC-1           Snap-frozen         DMG Pons
GNG_region_11_AAACAGCCAGGTTCAC-1           Snap-frozen         DMG Pons
GNG_region_11_AAACATGCAACTGGCT-1           Snap-frozen         DMG Pons
GNG_region_11_AAACATGCACGAACAG-1           Snap-frozen         DMG Pons
GNG_region_11_AAACATGCAGGCCAAA-1           Snap-frozen         DMG Pons
GNG_region_11_AAACCAACACACAATT-1           Snap-frozen         DMG Pons
GNG_region_11_AAACCAACACGTTACA-1           Snap-frozen         DMG Pons
GNG_region_11_AAACCAACATCATGTG-1           Snap-frozen         DMG Pons
GNG_region_11_AAACCAACATGATTGT-1           Snap-frozen         DMG Pons
GNG_region_11_AAACCGAAGCCTCTGT-1           Snap-frozen         DMG Pons
GNG_region_11_AAACCGCGTATGGTGC-1           Snap-frozen         DMG Pons
GNG_region_11_AAACCGGCAATGCCCG-1           Snap-frozen         DMG Pons
GNG_region_11_AAACCGGCAGAACCGA-1           Snap-frozen         DMG Pons
GNG_region_11_AAACCGGCAGGCCTTG-1           Snap-frozen         DMG Pons
GNG_region_11_AAACCGGCAGGCTACT-1           Snap-frozen         DMG Pons
GNG_region_11_AAACGCGCAAATTCGT-1           Snap-frozen         DMG Pons
GNG_region_11_AAACGCGCAATGAGGT-1           Snap-frozen         DMG Pons
GNG_region_11_AAACGCGCAGGAATCG-1           Snap-frozen         DMG Pons
GNG_region_11_AAACGCGCAGTTATCG-1           Snap-frozen         DMG Pons
GNG_region_11_AAACGCGCATAAGGAC-1           Snap-frozen         DMG Pons
GNG_region_11_AAACGGATCACCAATA-1           Snap-frozen         DMG Pons
GNG_region_11_AAACGGATCAGTTCCC-1           Snap-frozen         DMG Pons
GNG_region_11_AAACGGATCATTAGCA-1           Snap-frozen         DMG Pons
GNG_region_11_AAACGGATCCTGGTCT-1           Snap-frozen         DMG Pons
GNG_region_11_AAACGGATCGGCTAGC-1           Snap-frozen         DMG Pons
GNG_region_11_AAACGGATCGTTACTT-1           Snap-frozen         DMG Pons
GNG_region_11_AAACGTACAAATGCCC-1           Snap-frozen         DMG Pons
GNG_region_11_AAACGTACAACTAGGG-1           Snap-frozen         DMG Pons
GNG_region_11_AAACGTACAAGTGTTT-1           Snap-frozen         DMG Pons
GNG_region_11_AAACGTACAATAACCT-1           Snap-frozen         DMG Pons
⋮                                          ⋮                   ⋮
multiome_P-6774_S-10146_TTTGTCTAGGAACGCG-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTCTAGGAGTCTT-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTCTAGGCAACAA-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGAAGACAGGCG-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGAAGATGGAGC-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGAAGCAGCTCA-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGAAGCCGCAGT-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGAAGTATTGTG-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGAAGTTAGCTA-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGGCAAGCTAAA-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGGCAAGGAATC-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGGCAAGGTACG-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGGCAATTAACC-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGGCACCTCGCT-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGGCACGTAATT-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGGCACTTGTTC-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGGCAGCAAATA-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGGCAGCAACAG-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGGCATGCTATG-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGGCATTATGAC-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGTTCAAGTGAG-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGTTCCTAGTAA-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTGTTCTAATTGG-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTTGGTAGGATTT-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTTGGTCATTGTC-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTTGGTTGCATCT-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTTGGTTGGATAT-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTTGGTTGGCCGA-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTTGGTTGTAACG-1 N/A                 DMG Pons
multiome_P-6774_S-10146_TTTGTTGGTTTATCGC-1 N/A                 DMG Pons
                                           Tumor_type         Tumor_subtype
GNG_region_11_AAACAGCCAAAGCGGC-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACAGCCAGGTTCAC-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACATGCAACTGGCT-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACATGCACGAACAG-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACATGCAGGCCAAA-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACCAACACACAATT-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACCAACACGTTACA-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACCAACATCATGTG-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACCAACATGATTGT-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACCGAAGCCTCTGT-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACCGCGTATGGTGC-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACCGGCAATGCCCG-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACCGGCAGAACCGA-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACCGGCAGGCCTTG-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACCGGCAGGCTACT-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACGCGCAAATTCGT-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACGCGCAATGAGGT-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACGCGCAGGAATCG-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACGCGCAGTTATCG-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACGCGCATAAGGAC-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACGGATCACCAATA-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACGGATCAGTTCCC-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACGGATCATTAGCA-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACGGATCCTGGTCT-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACGGATCGGCTAGC-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACGGATCGTTACTT-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACGTACAAATGCCC-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACGTACAACTAGGG-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACGTACAAGTGTTT-1           DMG H3 K27-altered H3.3 K27-mutant
GNG_region_11_AAACGTACAATAACCT-1           DMG H3 K27-altered H3.3 K27-mutant
⋮                                          ⋮                  ⋮
multiome_P-6774_S-10146_TTTGTCTAGGAACGCG-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTCTAGGAGTCTT-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTCTAGGCAACAA-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGAAGACAGGCG-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGAAGATGGAGC-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGAAGCAGCTCA-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGAAGCCGCAGT-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGAAGTATTGTG-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGAAGTTAGCTA-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGGCAAGCTAAA-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGGCAAGGAATC-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGGCAAGGTACG-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGGCAATTAACC-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGGCACCTCGCT-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGGCACGTAATT-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGGCACTTGTTC-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGGCAGCAAATA-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGGCAGCAACAG-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGGCATGCTATG-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGGCATTATGAC-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGTTCAAGTGAG-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGTTCCTAGTAA-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTGTTCTAATTGG-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTTGGTAGGATTT-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTTGGTCATTGTC-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTTGGTTGCATCT-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTTGGTTGGATAT-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTTGGTTGGCCGA-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTTGGTTGTAACG-1 DMG H3 K27-altered H3.3 K27-mutant
multiome_P-6774_S-10146_TTTGTTGGTTTATCGC-1 DMG H3 K27-altered H3.3 K27-mutant
                                           Location Source  Clinical_status ⋯
GNG_region_11_AAACAGCCAAAGCGGC-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACAGCCAGGTTCAC-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACATGCAACTGGCT-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACATGCACGAACAG-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACATGCAGGCCAAA-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACCAACACACAATT-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACCAACACGTTACA-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACCAACATCATGTG-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACCAACATGATTGT-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACCGAAGCCTCTGT-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACCGCGTATGGTGC-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACCGGCAATGCCCG-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACCGGCAGAACCGA-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACCGGCAGGCCTTG-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACCGGCAGGCTACT-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACGCGCAAATTCGT-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACGCGCAATGAGGT-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACGCGCAGGAATCG-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACGCGCAGTTATCG-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACGCGCATAAGGAC-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACGGATCACCAATA-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACGGATCAGTTCCC-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACGGATCATTAGCA-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACGGATCCTGGTCT-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACGGATCGGCTAGC-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACGGATCGTTACTT-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACGTACAAATGCCC-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACGTACAACTAGGG-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACGTACAAGTGTTT-1           Pons     Autopsy Recurrence      ⋯
GNG_region_11_AAACGTACAATAACCT-1           Pons     Autopsy Recurrence      ⋯
⋮                                          ⋮        ⋮       ⋮               ⋱
multiome_P-6774_S-10146_TTTGTCTAGGAACGCG-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTCTAGGAGTCTT-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTCTAGGCAACAA-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGAAGACAGGCG-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGAAGATGGAGC-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGAAGCAGCTCA-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGAAGCCGCAGT-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGAAGTATTGTG-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGAAGTTAGCTA-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGGCAAGCTAAA-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGGCAAGGAATC-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGGCAAGGTACG-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGGCAATTAACC-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGGCACCTCGCT-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGGCACGTAATT-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGGCACTTGTTC-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGGCAGCAAATA-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGGCAGCAACAG-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGGCATGCTATG-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGGCATTATGAC-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGTTCAAGTGAG-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGTTCCTAGTAA-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTGTTCTAATTGG-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTTGGTAGGATTT-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTTGGTCATTGTC-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTTGGTTGCATCT-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTTGGTTGGATAT-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTTGGTTGGCCGA-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTTGGTTGTAACG-1 Pons     N/A     N/A             ⋯
multiome_P-6774_S-10146_TTTGTTGGTTTATCGC-1 Pons     N/A     N/A             ⋯
                                           PPM1D ACVR1 TSHR BRAF GNAQ LMNA KIT
GNG_region_11_AAACAGCCAAAGCGGC-1           WT    WT    WT   WT   WT   WT   WT
GNG_region_11_AAACAGCCAGGTTCAC-1           WT    WT    WT   WT   WT   WT   WT
GNG_region_11_AAACATGCAACTGGCT-1           WT    WT    WT   WT   WT   WT   WT
GNG_region_11_AAACATGCACGAACAG-1           WT    WT    WT   WT   WT   WT   WT
GNG_region_11_AAACATGCAGGCCAAA-1           WT    WT    WT   WT   WT   WT   WT
GNG_region_11_AAACCAACACACAATT-1           WT    WT    WT   WT   WT   WT   WT
GNG_region_11_AAACCAACACGTTACA-1           WT    WT    WT   WT   WT   WT   WT
GNG_region_11_AAACCAACATCATGTG-1           WT    WT    WT   WT   WT   WT   WT
GNG_region_11_AAACCAACATGATTGT-1           WT    WT    WT   WT   WT   WT   WT
GNG_region_11_AAACCGAAGCCTCTGT-1           WT    WT    WT   WT   WT   WT   WT
GNG_region_11_AAACCGCGTATGGTGC-1           WT    WT    WT   WT   WT   WT   WT
GNG_region_11_AAACCGGCAATGCCCG-1           WT    WT    WT   WT   WT   WT   WT
GNG_region_11_AAACCGGCAGAACCGA-1           WT    WT    WT   WT   WT   WT   WT
GNG_region_11_AAACCGGCAGGCCTTG-1           WT    WT    WT   WT   WT   WT   WT
GNG_region_11_AAACCGGCAGGCTACT-1           WT    WT    WT   WT   WT   WT   WT
GNG_region_11_AAACGCGCAAATTCGT-1           WT    WT    WT   WT   WT   WT   WT

In [ ]:
atac_multi <- AddMetaData(atac_multi, atac_multi_meta)
atac_multi <- AddMetaData(atac_multi, FetchData(subset(integrated, 
                                                     dataset == 'Multiome'), 
                                              'predicted.id')
                         )
atac_multi$cell_id <- atac_multi$predicted.id
atac_multi$Batch_for_correction <- '10Xv1_nuclei_multiome'
atac_multi$orig.ident <- NULL
atac_multi@meta.data

                                           gex_barcode
GNG_region_11_AAACAGCCAAAGCGGC-1           AAACAGCCAAAGCGGC-1
GNG_region_11_AAACAGCCAGGTTCAC-1           AAACAGCCAGGTTCAC-1
GNG_region_11_AAACATGCAACTGGCT-1           AAACATGCAACTGGCT-1
GNG_region_11_AAACATGCACGAACAG-1           AAACATGCACGAACAG-1
GNG_region_11_AAACATGCAGGCCAAA-1           AAACATGCAGGCCAAA-1
GNG_region_11_AAACCAACACACAATT-1           AAACCAACACACAATT-1
GNG_region_11_AAACCAACACGTTACA-1           AAACCAACACGTTACA-1
GNG_region_11_AAACCAACATCATGTG-1           AAACCAACATCATGTG-1
GNG_region_11_AAACCAACATGATTGT-1           AAACCAACATGATTGT-1
GNG_region_11_AAACCGAAGCCTCTGT-1           AAACCGAAGCCTCTGT-1
GNG_region_11_AAACCGCGTATGGTGC-1           AAACCGCGTATGGTGC-1
GNG_region_11_AAACCGGCAATGCCCG-1           AAACCGGCAATGCCCG-1
GNG_region_11_AAACCGGCAGAACCGA-1           AAACCGGCAGAACCGA-1
GNG_region_11_AAACCGGCAGGCCTTG-1           AAACCGGCAGGCCTTG-1
GNG_region_11_AAACCGGCAGGCTACT-1           AAACCGGCAGGCTACT-1
GNG_region_11_AAACGCGCAAATTCGT-1           AAACGCGCAAATTCGT-1
GNG_region_11_AAACGCGCAATGAGGT-1           AAACGCGCAATGAGGT-1
GNG_region_11_AAACGCGCAGGAATCG-1           AAACGCGCAGGAATCG-1
GNG_region_11_AAACGCGCAGTTATCG-1           AAACGCGCAGTTATCG-1
GNG_region_11_AAACGCGCATAAGGAC-1           AAACGCGCATAAGGAC-1
GNG_region_11_AAACGGATCACCAATA-1           AAACGGATCACCAATA-1
GNG_region_11_AAACGGATCAGTTCCC-1           AAACGGATCAGTTCCC-1
GNG_region_11_AAACGGATCATTAGCA-1           AAACGGATCATTAGCA-1
GNG_region_11_AAACGGATCCTGGTCT-1           AAACGGATCCTGGTCT-1
GNG_region_11_AAACGGATCGGCTAGC-1           AAACGGATCGGCTAGC-1
GNG_region_11_AAACGGATCGTTACTT-1           AAACGGATCGTTACTT-1
GNG_region_11_AAACGTACAAATGCCC-1           AAACGTACAAATGCCC-1
GNG_region_11_AAACGTACAACTAGGG-1           AAACGTACAACTAGGG-1
GNG_region_11_AAACGTACAAGTGTTT-1           AAACGTACAAGTGTTT-1
GNG_region_11_AAACGTACAATAACCT-1           AAACGTACAATAACCT-1
⋮                                          ⋮
multiome_P-6774_S-10146_TTTGTCTAGGAACGCG-1 TTTGTCTAGGAACGCG-1
multiome_P-6774_S-10146_TTTGTCTAGGAGTCTT-1 TTTGTCTAGGAGTCTT-1
multiome_P-6774_S-10146_TTTGTCTAGGCAACAA-1 TTTGTCTAGGCAACAA-1
multiome_P-6774_S-10146_TTTGTGAAGACAGGCG-1 TTTGTGAAGACAGGCG-1
multiome_P-6774_S-10146_TTTGTGAAGATGGAGC-1 TTTGTGAAGATGGAGC-1
multiome_P-6774_S-10146_TTTGTGAAGCAGCTCA-1 TTTGTGAAGCAGCTCA-1
multiome_P-6774_S-10146_TTTGTGAAGCCGCAGT-1 TTTGTGAAGCCGCAGT-1
multiome_P-6774_S-10146_TTTGTGAAGTATTGTG-1 TTTGTGAAGTATTGTG-1
multiome_P-6774_S-10146_TTTGTGAAGTTAGCTA-1 TTTGTGAAGTTAGCTA-1
multiome_P-6774_S-10146_TTTGTGGCAAGCTAAA-1 TTTGTGGCAAGCTAAA-1
multiome_P-6774_S-10146_TTTGTGGCAAGGAATC-1 TTTGTGGCAAGGAATC-1
multiome_P-6774_S-10146_TTTGTGGCAAGGTACG-1 TTTGTGGCAAGGTACG-1
multiome_P-6774_S-10146_TTTGTGGCAATTAACC-1 TTTGTGGCAATTAACC-1
multiome_P-6774_S-10146_TTTGTGGCACCTCGCT-1 TTTGTGGCACCTCGCT-1
multiome_P-6774_S-10146_TTTGTGGCACGTAATT-1 TTTGTGGCACGTAATT-1
multiome_P-6774_S-10146_TTTGTGGCACTTGTTC-1 TTTGTGGCACTTGTTC-1
multiome_P-6774_S-10146_TTTGTGGCAGCAAATA-1 TTTGTGGCAGCAAATA-1
multiome_P-6774_S-10146_TTTGTGGCAGCAACAG-1 TTTGTGGCAGCAACAG-1
multiome_P-6774_S-10146_TTTGTGGCATGCTATG-1 TTTGTGGCATGCTATG-1
multiome_P-6774_S-10146_TTTGTGGCATTATGAC-1 TTTGTGGCATTATGAC-1
multiome_P-6774_S-10146_TTTGTGTTCAAGTGAG-1 TTTGTGTTCAAGTGAG-1
multiome_P-6774_S-10146_TTTGTGTTCCTAGTAA-1 TTTGTGTTCCTAGTAA-1
multiome_P-6774_S-10146_TTTGTGTTCTAATTGG-1 TTTGTGTTCTAATTGG-1
multiome_P-6774_S-10146_TTTGTTGGTAGGATTT-1 TTTGTTGGTAGGATTT-1
multiome_P-6774_S-10146_TTTGTTGGTCATTGTC-1 TTTGTTGGTCATTGTC-1
multiome_P-6774_S-10146_TTTGTTGGTTGCATCT-1 TTTGTTGGTTGCATCT-1
multiome_P-6774_S-10146_TTTGTTGGTTGGATAT-1 TTTGTTGGTTGGATAT-1
multiome_P-6774_S-10146_TTTGTTGGTTGGCCGA-1 TTTGTTGGTTGGCCGA-1
multiome_P-6774_S-10146_TTTGTTGGTTGTAACG-1 TTTGTTGGTTGTAACG-1
multiome_P-6774_S-10146_TTTGTTGGTTTATCGC-1 TTTGTTGGTTTATCGC-1
                                           atac_barcode       is_cell
GNG_region_11_AAACAGCCAAAGCGGC-1           ACAGCGGGTGGATTAG-1 0
GNG_region_11_AAACAGCCAGGTTCAC-1           ACAGCGGGTCCTGACA-1 1
GNG_region_11_AAACATGCAACTGGCT-1           CATTTAGGTCTTGACG-1 1
GNG_region_11_AAACATGCACGAACAG-1           CATTTAGGTCACACTG-1 1
GNG_region_11_AAACATGCAGGCCAAA-1           CATTTAGGTTGAGGTA-1 0
GNG_region_11_AAACCAACACACAATT-1           CTTTATCGTCGGTTTG-1 1
GNG_region_11_AAACCAACACGTTACA-1           CTTTATCGTTACAGCT-1 0
GNG_region_11_AAACCAACATCATGTG-1           CTTTATCGTCCCGGAT-1 0
GNG_region_11_AAACCAACATGATTGT-1           CTTTATCGTAGGTTAG-1 0
GNG_region_11_AAACCGAAGCCTCTGT-1           TGACTATTCGCGTTAC-1 1
GNG_region_11_AAACCGCGTATGGTGC-1           AATAGCTCAGTATTGG-1 0
GNG_region_11_AAACCGGCAATGCCCG-1           ATTGACCGTTGAGTCT-1 0
GNG_region_11_AAACCGGCAGAACCGA-1           ATTGACCGTTAATCGC-1 1
GNG_region_11_AAACCGGCAGGCCTTG-1           ATTGACCGTCATGAAG-1 1
GNG_region_11_AAACCGGCAGGCTACT-1           ATTGACCGTTTGTAGC-1 0
GNG_region_11_AAACGCGCAAATTCGT-1           ATAACCCGTACTTATG-1 1
GNG_region_11_AAACGCGCAATGAGGT-1           ATAACCCGTCGCAATT-1 1
GNG_region_11_AAACGCGCAGGAATCG-1           ATAACCCGTATCCGTG-1 0
GNG_region_11_AAACGCGCAGTTATCG-1           ATAACCCGTTTATTCC-1 0
GNG_region_11_AAACGCGCATAAGGAC-1           ATAACCCGTACAATGG-1 1
GNG_region_11_AAACGGATCACCAATA-1           GAGGCCTAGCAAACAC-1 1
GNG_region_11_AAACGGATCAGTTCCC-1           GAGGCCTAGAGCAAGA-1 1
GNG_region_11_AAACGGATCATTAGCA-1           GAGGCCTAGCTATATC-1 0
GNG_region_11_AAACGGATCCTGGTCT-1           GAGGCCTAGGTTGTAA-1 0
GNG_region_11_AAACGGATCGGCTAGC-1           GAGGCCTAGTCCTGCG-1 1
GNG_region_11_AAACGGATCGTTACTT-1           GAGGCCTAGGGACTTG-1 1
GNG_region_11_AAACGTACAAATGCCC-1           GCGCTTAGTATTACTG-1 1
GNG_region_11_AAACGTACAACTAGGG-1           GCGCTTAGTTAGTTGC-1 1
GNG_region_11_AAACGTACAAGTGTTT-1           GCGCTTAGTGATGCAA-1 1
GNG_region_11_AAACGTACAATAACCT-1           GCGCTTAGTCGAGGCA-1 1
⋮                                          ⋮                  ⋮
multiome_P-6774_S-10146_TTTGTCTAGGAACGCG-1 TGTCAATTCCAGGATG-1 0
multiome_P-6774_S-10146_TTTGTCTAGGAGTCTT-1 TGTCAATTCGATAAGC-1 1
multiome_P-6774_S-10146_TTTGTCTAGGCAACAA-1 TGTCAATTCAGGACCA-1 0
multiome_P-6774_S-10146_TTTGTGAAGACAGGCG-1 GTAGGTGTCACTATGT-1 1
multiome_P-6774_S-10146_TTTGTGAAGATGGAGC-1 GTAGGTGTCGCAACTC-1 1
multiome_P-6774_S-10146_TTTGTGAAGCAGCTCA-1 GTAGGTGTCTTGCTGA-1 0
multiome_P-6774_S-10146_TTTGTGAAGCCGCAGT-1 GTAGGTGTCAATTAGG-1 0
multiome_P-6774_S-10146_TTTGTGAAGTATTGTG-1 GTAGGTGTCAGGAGCC-1 0
multiome_P-6774_S-10146_TTTGTGAAGTTAGCTA-1 GTAGGTGTCGATATTC-1 1
multiome_P-6774_S-10146_TTTGTGGCAAGCTAAA-1 GTTTGGTGTAATCGCT-1 0
multiome_P-6774_S-10146_TTTGTGGCAAGGAATC-1 GTTTGGTGTCAACCGC-1 0
multiome_P-6774_S-10146_TTTGTGGCAAGGTACG-1 GTTTGGTGTCTAGCGC-1 1
multiome_P-6774_S-10146_TTTGTGGCAATTAACC-1 GTTTGGTGTATCGGCC-1 1
multiome_P-6774_S-10146_TTTGTGGCACCTCGCT-1 GTTTGGTGTTGGGTTT-1 0
multiome_P-6774_S-10146_TTTGTGGCACGTAATT-1 GTTTGGTGTTCCTCAC-1 1
multiome_P-6774_S-10146_TTTGTGGCACTTGTTC-1 GTTTGGTGTGGTTACT-1 1
multiome_P-6774_S-10146_TTTGTGGCAGCAAATA-1 GTTTGGTGTTGCGTGC-1 1
multiome_P-6774_S-10146_TTTGTGGCAGCAACAG-1 GTTTGGTGTAATCCAC-1 0
multiome_P-6774_S-10146_TTTGTGGCATGCTATG-1 GTTTGGTGTCACCAGC-1 1
multiome_P-6774_S-10146_TTTGTGGCATTATGAC-1 GTTTGGTGTTGGGTAA-1 1
multiome_P-6774_S-10146_TTTGTGTTCAAGTGAG-1 GTTCTCAAGCAGCTCT-1 0
multiome_P-6774_S-10146_TTTGTGTTCCTAGTAA-1 GTTCTCAAGTGCTCCG-1 0
multiome_P-6774_S-10146_TTTGTGTTCTAATTGG-1 GTTCTCAAGCTATCGC-1 1
multiome_P-6774_S-10146_TTTGTTGGTAGGATTT-1 CGTACTTCATATTGCC-1 1
multiome_P-6774_S-10146_TTTGTTGGTCATTGTC-1 CGTACTTCAATTGCCT-1 1
multiome_P-6774_S-10146_TTTGTTGGTTGCATCT-1 CGTACTTCATTTGTGC-1 1
multiome_P-6774_S-10146_TTTGTTGGTTGGATAT-1 CGTACTTCAATGTCAG-1 0
multiome_P-6774_S-10146_TTTGTTGGTTGGCCGA-1 CGTACTTCAAACCTAG-1 0
multiome_P-6774_S-10146_TTTGTTGGTTGTAACG-1 CGTACTTCAGGTTATG-1 1
multiome_P-6774_S-10146_TTTGTTGGTTTATCGC-1 CGTACTTCAAGGCCAT-1 0
                                           excluded_reason gex_raw_reads
GNG_region_11_AAACAGCCAAAGCGGC-1           2                 4828
GNG_region_11_AAACAGCCAGGTTCAC-1           0                11573
GNG_region_11_AAACATGCAACTGGCT-1           0                 3339
GNG_region_11_AAACATGCACGAACAG-1           0                15407
GNG_region_11_AAACATGCAGGCCAAA-1           2               127096
GNG_region_11_AAACCAACACACAATT-1           0                15095
GNG_region_11_AAACCAACACGTTACA-1           2                26907
GNG_region_11_AAACCAACATCATGTG-1           2                 2426
GNG_region_11_AAACCAACATGATTGT-1           2                 7023
GNG_region_11_AAACCGAAGCCTCTGT-1           0                33901
GNG_region_11_AAACCGCGTATGGTGC-1           2                10327
GNG_region_11_AAACCGGCAATGCCCG-1           2                10925
GNG_region_11_AAACCGGCAGAACCGA-1           0                31567
GNG_region_11_AAACCGGCAGGCCTTG-1           0                86977
GNG_region_11_AAACCGGCAGGCTACT-1           2                13919
GNG_region_11_AAACGCGCAAATTCGT-1           0                10625
GNG_region_11_AAACGCGCAATGAGGT-1           0                12376
GNG_region_11_AAACGCGCAGGAATCG-1           2                 1917
GNG_region_11_AAACGCGCAGTTATCG-1           2                 7080
GNG_region_11_AAACGCGCATAAGGAC-1           0                 9101
GNG_region_11_AAACGGATCACCAATA-1           0                23276
GNG_region_11_AAACGGATCAGTTCCC-1           0                69343
GNG_region_11_AAACGGATCATTAGCA-1           2                11976
GNG_region_11_AAACGGATCCTGGTCT-1           0                   18
GNG_region_11_AAACGGATCGGCTAGC-1           0                21965
GNG_region_11_AAACGGATCGTTACTT-1           0               162552
GNG_region_11_AAACGTACAAATGCCC-1           0                96707
GNG_region_11_AAACGTACAACTAGGG-1           0                12616
GNG_region_11_AAACGTACAAGTGTTT-1           0                  896
GNG_region_11_AAACGTACAATAACCT-1           0                 6588
⋮                                          ⋮               ⋮
multiome_P-6774_S-10146_TTTGTCTAGGAACGCG-1 2                52595
multiome_P-6774_S-10146_TTTGTCTAGGAGTCTT-1 0                30833
multiome_P-6774_S-10146_TTTGTCTAGGCAACAA-1 2               185241
multiome_P-6774_S-10146_TTTGTGAAGACAGGCG-1 0                28168
multiome_P-6774_S-10146_TTTGTGAAGATGGAGC-1 0                 3092
multiome_P-6774_S-10146_TTTGTGAAGCAGCTCA-1 2                 4617
multiome_P-6774_S-10146_TTTGTGAAGCCGCAGT-1 2                41386
multiome_P-6774_S-10146_TTTGTGAAGTATTGTG-1 2                68717
multiome_P-6774_S-10146_TTTGTGAAGTTAGCTA-1 0                 5244
multiome_P-6774_S-10146_TTTGTGGCAAGCTAAA-1 2                43327
multiome_P-6774_S-10146_TTTGTGGCAAGGAATC-1 2                 7768
multiome_P-6774_S-10146_TTTGTGGCAAGGTACG-1 0                13713
multiome_P-6774_S-10146_TTTGTGGCAATTAACC-1 0                32333
multiome_P-6774_S-10146_TTTGTGGCACCTCGCT-1 2               124741
multiome_P-6774_S-10146_TTTGTGGCACGTAATT-1 0                 8046
multiome_P-6774_S-10146_TTTGTGGCACTTGTTC-1 0                 2087
multiome_P-6774_S-10146_TTTGTGGCAGCAAATA-1 0                13441
multiome_P-6774_S-10146_TTTGTGGCAGCAACAG-1 2                13973
multiome_P-6774_S-10146_TTTGTGGCATGCTATG-1 0                  795
multiome_P-6774_S-10146_TTTGTGGCATTATGAC-1 0                43842
multiome_P-6774_S-10146_TTTGTGTTCAAGTGAG-1 2                 4721
multiome_P-6774_S-10146_TTTGTGTTCCTAGTAA-1 2                37291
multiome_P-6774_S-10146_TTTGTGTTCTAATTGG-1 0               151247
multiome_P-6774_S-10146_TTTGTTGGTAGGATTT-1 0                26764
multiome_P-6774_S-10146_TTTGTTGGTCATTGTC-1 0               158680
multiome_P-6774_S-10146_TTTGTTGGTTGCATCT-1 0                 4566
multiome_P-6774_S-10146_TTTGTTGGTTGGATAT-1 2                 2415
multiome_P-6774_S-10146_TTTGTTGGTTGGCCGA-1 2               624825
multiome_P-6774_S-10146_TTTGTTGGTTGTAACG-1 0                 7814
multiome_P-6774_S-10146_TTTGTTGGTTTATCGC-1 2               130709
                                           gex_mapped_reads
GNG_region_11_AAACAGCCAAAGCGGC-1             4639
GNG_region_11_AAACAGCCAGGTTCAC-1            10964
GNG_region_11_AAACATGCAACTGGCT-1             3187
GNG_region_11_AAACATGCACGAACAG-1            14885
GNG_region_11_AAACATGCAGGCCAAA-1           122482
GNG_region_11_AAACCAACACACAATT-1            14589
GNG_region_11_AAACCAACACGTTACA-1            26106
GNG_region_11_AAACCAACATCATGTG-1             2322
GNG_region_11_AAACCAACATGATTGT-1             6821
GNG_region_11_AAACCGAAGCCTCTGT-1            32687
GNG_region_11_AAACCGCGTATGGTGC-1            10016
GNG_region_11_AAACCGGCAATGCCCG-1            10591
GNG_region_11_AAACCGGCAGAACCGA-1            30509
GNG_region_11_AAACCGGCAGGCCTTG-1            84170
GNG_region_11_AAACCGGCAGGCTACT-1            13468
GNG_region_11_AAACGCGCAAATTCGT-1            10291
GNG_region_11_AAACGCGCAATGAGGT-1            11902
GNG_region_11_AAACGCGCAGGAATCG-1             1770
GNG_region_11_AAACGCGCAGTTATCG-1             6827
GNG_region_11_AAACGCGCATAAGGAC-1             8780
GNG_region_11_AAACGGATCACCAATA-1            22253
GNG_region_11_AAACGGATCAGTTCCC-1            66887
GNG_region_11_AAACGGATCATTAGCA-1            11517
GNG_region_11_AAACGGATCCTGGTCT-1               17
GNG_region_11_AAACGGATCGGCTAGC-1            21255
GNG_region_11_AAACGGATCGTTACTT-1           156651
GNG_region_11_AAACGTACAAATGCCC-1            93158
GNG_region_11_AAACGTACAACTAGGG-1            12202
GNG_region_11_AAACGTACAAGTGTTT-1              825
GNG_region_11_AAACGTACAATAACCT-1             6262
⋮                                          ⋮
multiome_P-6774_S-10146_TTTGTCTAGGAACGCG-1  49815
multiome_P-6774_S-10146_TTTGTCTAGGAGTCTT-1  29317
multiome_P-6774_S-10146_TTTGTCTAGGCAACAA-1 176773
multiome_P-6774_S-10146_TTTGTGAAGACAGGCG-1  26870
multiome_P-6774_S-10146_TTTGTGAAGATGGAGC-1   2909
multiome_P-6774_S-10146_TTTGTGAAGCAGCTCA-1   4383
multiome_P-6774_S-10146_TTTGTGAAGCCGCAGT-1  39726
multiome_P-6774_S-10146_TTTGTGAAGTATTGTG-1  65618
multiome_P-6774_S-10146_TTTGTGAAGTTAGCTA-1   4879
multiome_P-6774_S-10146_TTTGTGGCAAGCTAAA-1  41378
multiome_P-6774_S-10146_TTTGTGGCAAGGAATC-1   7358
multiome_P-6774_S-10146_TTTGTGGCAAGGTACG-1  13045
multiome_P-6774_S-10146_TTTGTGGCAATTAACC-1  30544
multiome_P-6774_S-10146_TTTGTGGCACCTCGCT-1 119511
multiome_P-6774_S-10146_TTTGTGGCACGTAATT-1   7635
multiome_P-6774_S-10146_TTTGTGGCACTTGTTC-1   1951
multiome_P-6774_S-10146_TTTGTGGCAGCAAATA-1  12690
multiome_P-6774_S-10146_TTTGTGGCAGCAACAG-1  13340
multiome_P-6774_S-10146_TTTGTGGCATGCTATG-1    712
multiome_P-6774_S-10146_TTTGTGGCATTATGAC-1  41910
multiome_P-6774_S-10146_TTTGTGTTCAAGTGAG-1   4472
multiome_P-6774_S-10146_TTTGTGTTCCTAGTAA-1  35634
multiome_P-6774_S-10146_TTTGTGTTCTAATTGG-1 145090
multiome_P-6774_S-10146_TTTGTTGGTAGGATTT-1  25507
multiome_P-6774_S-10146_TTTGTTGGTCATTGTC-1 151855
multiome_P-6774_S-10146_TTTGTTGGTTGCATCT-1   4251
multiome_P-6774_S-10146_TTTGTTGGTTGGATAT-1   2289
multiome_P-6774_S-10146_TTTGTTGGTTGGCCGA-1 595816
multiome_P-6774_S-10146_TTTGTTGGTTGTAACG-1   7385
multiome_P-6774_S-10146_TTTGTTGGTTTATCGC-1 125011
                                           gex_conf_intergenic_reads
GNG_region_11_AAACAGCCAAAGCGGC-1             410
GNG_region_11_AAACAGCCAGGTTCAC-1            1090
GNG_region_11_AAACATGCAACTGGCT-1             234
GNG_region_11_AAACATGCACGAACAG-1             969
GNG_region_11_AAACATGCAGGCCAAA-1            9153
GNG_region_11_AAACCAACACACAATT-1             986
GNG_region_11_AAACCAACACGTTACA-1            1387
GNG_region_11_AAACCAACATCATGTG-1             167
GNG_region_11_AAACCAACATGATTGT-1             320
GNG_region_11_AAACCGAAGCCTCTGT-1            2484
GNG_region_11_AAACCGCGTATGGTGC-1             758
GNG_region_11_AAACCGGCAATGCCCG-1             592
GNG_region_11_AAACCGGCAGAACCGA-1            2415
GNG_region_11_AAACCGGCAGGCCTTG-1            6252
GNG_region_11_AAACCGGCAGGCTACT-1            1247
GNG_region_11_AAACGCGCAAATTCGT-1             471
GNG_region_11_AAACGCGCAATGAGGT-1            1169
GNG_region_11_AAACGCGCAGGAATCG-1             308
GNG_region_11_AAACGCGCAGTTATCG-1             371
GNG_region_11_AAACGCGCATAAGGAC-1             812
GNG_region_11_AAACGGATCACCAATA-1            2073
GNG_region_11_AAACGGATCAGTTCCC-1            5741
GNG_region_11_AAACGGATCATTAGCA-1            1050
GNG_region_11_AAACGGATCCTGGTCT-1               0
GNG_region_11_AAACGGATCGGCTAGC-1            1708
GNG_region_11_AAACGGATCGTTACTT-1           11422
GNG_region_11_AAACGTACAAATGCCC-1            5333
GNG_region_11_AAACGTACAACTAGGG-1             816
GNG_region_11_AAACGTACAAGTGTTT-1              79
GNG_region_11_AAACGTACAATAACCT-1             393
⋮                                          ⋮
multiome_P-6774_S-10146_TTTGTCTAGGAACGCG-1  2903
multiome_P-6774_S-10146_TTTGTCTAGGAGTCTT-1  1197
multiome_P-6774_S-10146_TTTGTCTAGGCAACAA-1  8597
multiome_P-6774_S-10146_TTTGTGAAGACAGGCG-1   946
multiome_P-6774_S-10146_TTTGTGAAGATGGAGC-1   246
multiome_P-6774_S-10146_TTTGTGAAGCAGCTCA-1   261
multiome_P-6774_S-10146_TTTGTGAAGCCGCAGT-1  2259
multiome_P-6774_S-10146_TTTGTGAAGTATTGTG-1  4512
multiome_P-6774_S-10146_TTTGTGAAGTTAGCTA-1   387
multiome_P-6774_S-10146_TTTGTGGCAAGCTAAA-1  2928
multiome_P-6774_S-10146_TTTGTGGCAAGGAATC-1   455
multiome_P-6774_S-10146_TTTGTGGCAAGGTACG-1  1143
multiome_P-6774_S-10146_TTTGTGGCAATTAACC-1  1861
multiome_P-6774_S-10146_TTTGTGGCACCTCGCT-1  7010
multiome_P-6774_S-10146_TTTGTGGCACGTAATT-1   469
multiome_P-6774_S-10146_TTTGTGGCACTTGTTC-1   277
multiome_P-6774_S-10146_TTTGTGGCAGCAAATA-1   826
multiome_P-6774_S-10146_TTTGTGGCAGCAACAG-1   785
multiome_P-6774_S-10146_TTTGTGGCATGCTATG-1   110
multiome_P-6774_S-10146_TTTGTGGCATTATGAC-1  2844
multiome_P-6774_S-10146_TTTGTGTTCAAGTGAG-1   204
multiome_P-6774_S-10146_TTTGTGTTCCTAGTAA-1  1944
multiome_P-6774_S-10146_TTTGTGTTCTAATTGG-1  7298
multiome_P-6774_S-10146_TTTGTTGGTAGGATTT-1  1254
multiome_P-6774_S-10146_TTTGTTGGTCATTGTC-1  9351
multiome_P-6774_S-10146_TTTGTTGGTTGCATCT-1   389
multiome_P-6774_S-10146_TTTGTTGGTTGGATAT-1   192
multiome_P-6774_S-10146_TTTGTTGGTTGGCCGA-1 35934
multiome_P-6774_S-10146_TTTGTTGGTTGTAACG-1   838
multiome_P-6774_S-10146_TTTGTTGGTTTATCGC-1  6827
                                           gex_conf_exonic_reads
GNG_region_11_AAACAGCCAAAGCGGC-1            1182
GNG_region_11_AAACAGCCAGGTTCAC-1            1980
GNG_region_11_AAACATGCAACTGGCT-1             648
GNG_region_11_AAACATGCACGAACAG-1            6106
GNG_region_11_AAACATGCAGGCCAAA-1           26593
GNG_region_11_AAACCAACACACAATT-1            3928
GNG_region_11_AAACCAACACGTTACA-1            6439
GNG_region_11_AAACCAACATCATGTG-1             554
GNG_region_11_AAACCAACATGATTGT-1            2345
GNG_region_11_AAACCGAAGCCTCTGT-1            5642
GNG_region_11_AAACCGCGTATGGTGC-1            4021
GNG_region_11_AAACCGGCAATGCCCG-1            3443
GNG_region_11_AAACCGGCAGAACCGA-1            8735
GNG_region_11_AAACCGGCAGGCCTTG-1           29158
GNG_region_11_AAACCGGCAGGCTACT-1            3919
GNG_region_11_AAACGCGCAAATTCGT-1            3204
GNG_region_11_AAACGCGCAATGAGGT-1            3909
GNG_region_11_AAACGCGCAGGAATCG-1             369
GNG_region_11_AAACGCGCAGTTATCG-1            1663
GNG_region_11_AAACGCGCATAAGGAC-1            1910
GNG_region_11_AAACGGATCACCAATA-1            5491
GNG_region_11_AAACGGATCAGTTCCC-1           11428
GNG_region_11_AAACGGATCATTAGCA-1            2505
GNG_region_11_AAACGGATCCTGGTCT-1               3
GNG_region_11_AAACGGATCGGCTAGC-1            8147
GNG_region_11_AAACGGATCGTTACTT-1           32944
GNG_region_11_AAACGTACAAATGCCC-1           26105
GNG_region_11_AAACGTACAACTAGGG-1            4075
GNG_region_11_AAACGTACAAGTGTTT-1             189
GNG_region_11_AAACGTACAATAACCT-1            1282
⋮                                          ⋮
multiome_P-6774_S-10146_TTTGTCTAGGAACGCG-1  7817
multiome_P-6774_S-10146_TTTGTCTAGGAGTCTT-1  4424
multiome_P-6774_S-10146_TTTGTCTAGGCAACAA-1 35375
multiome_P-6774_S-10146_TTTGTGAAGACAGGCG-1  4042
multiome_P-6774_S-10146_TTTGTGAAGATGGAGC-1   669
multiome_P-6774_S-10146_TTTGTGAAGCAGCTCA-1   753
multiome_P-6774_S-10146_TTTGTGAAGCCGCAGT-1  6296

### Subset for testing

#### RNA

In [ ]:
# only include 10x generated data
rna_only <- subset(rna_only, Study %in% c('Filbin2018', 'Liu2022'), invert = TRUE)

# Subset
n_cells <- nrow(rna_only@meta.data)
n_sample <- round(n_cells * 0.1)
sampled_cells <- sample(Cells(rna_only), n_sample)
rna_only_subset <- subset(rna_only, cells = sampled_cells)
rna_only_subset

An object of class Seurat
38576 features across 31118 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

In [ ]:
sceasy::convertFormat(rna_only_subset, from="seurat", to="anndata",
                      assay = "RNA", 
                      drop_single_values = FALSE,
                      main_layer = "counts",
                      outFile='data/subset_rna_only_dmg_atlas.h5ad')

saveRDS(rna_only_subset, 'data/subset_rna_only_dmg_atlas.rds')

Warning message:
“`invoke()` is deprecated as of rlang 0.4.0.
Please use `exec()` or `inject()` instead.
This warning is displayed once every 8 hours.”

AnnData object with n_obs × n_vars = 31118 × 19248
    obs: 'nCount_RNA', 'nFeature_RNA', 'nCount_RAW', 'nFeature_RAW', 'DF.class', 'DF.score', 'scDblFinder.class', 'scDblFinder.score', 'ID', 'SampleID', 'Data', 'percent_mito', 'percent_ribo', 'percent_mito_ribo', 'log10GenesPerUMI', 'nFeature_Diff', 'nCount_Diff', 'Batch_for_correction', 'scDblFinder.clusters.class', 'scDblFinder.clusters.score', 'scDblFinder.class.clusters', 'doublet.combn.fisher', 'doublet.combn.mean', 'doublet.combn.fisher.class', 'doublet.combn.mean.class', 'Study', 'Original_annotation', 'Isolation_method_by_cell', 'Cell_type_granular_mouse_correlations', 'Cell_type_mouse_correlations', 'Cell_type_consensus_Jessa2022', 'Malignant_normal_consensus_Jessa2022', 'Institute', 'Preservation_method', 'Diagnosis', 'Tumor_type', 'Tumor_subtype', 'Location', 'Source', 'Clinical_status', 'Isolation_method', 'Sc_platform_RNA', 'Sc_platform_ATAC', 'Sc_multiome', 'Raw_data_available', 'Counts', 'Genome_version', 'Paired_sample', 'Multisector', 'Gender', 'Age_years', 'Dexamethasone_prior_surgery', 'Survival', 'Survival_months', 'Mitosis', 'Ki67', 'Methylation_array', 'H3F3A', 'H3C3', 'HIST1H3B', 'HIST2H3C', 'TP53', 'EGFR', 'PDGFRA', 'SUFU', 'NF1', 'pTERT', 'PIK3CA', 'PIK3R1', 'ATRX', 'PTEN', 'ASXL1', 'BCOR', 'BCORL1', 'SMC1A', 'WT1', 'PPM1D', 'ACVR1', 'TSHR', 'BRAF', 'GNAQ', 'LMNA', 'KIT', 'ARID1A', 'KRAS', 'Other', 'RNA_snn_res.0.8', 'seurat_clusters', 'predicted.annotation_level_1.score', 'predicted.annotation_level_1', 'predicted.annotation_level_2.score', 'predicted.annotation_level_2', 'predicted.annotation_level_3.score', 'predicted.annotation_level_3', 'predicted.annotation_level_4.score', 'predicted.annotation_level_4', 'iCNV', 'cell_id'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'vst.variable'
    obsm: 'X_pca', 'X_umap', 'X_ref.pca', 'X_ref.umap'

#### ATAC

In [ ]:
# Subset
n_cells <- nrow(atac_only@meta.data)
n_sample <- round(n_cells * 0.5)
sampled_cells <- sample(Cells(atac_only), n_sample)
atac_only_subset <- subset(atac_only, cells = sampled_cells)
atac_only_subset

An object of class Seurat
378298 features across 21804 samples within 1 assay
Active assay: ATAC (378298 features, 0 variable features)
 2 layers present: counts, data

In [ ]:
saveRDS(atac_only_subset, 'data/subset_atac_only_dmg_atlas.rds')

In [ ]:
# change nomenclature of the features to match other down stream tools in python
rownames(atac_only_subset@assays$ATAC@counts) <- sub("-", ":", 
                                                     rownames(atac_only_subset@assays$ATAC@counts))
rownames(atac_only_subset@assays$ATAC@data) <- sub("-", ":", 
                                                   rownames(atac_only_subset@assays$ATAC@data))
rownames(atac_only_subset@assays$ATAC@meta.features) <- sub("-", ":", 
                                                     rownames(atac_only_subset@assays$ATAC@meta.features))

In [ ]:
sceasy::convertFormat(atac_only_subset, from="seurat", to="anndata",
                      assay = "ATAC", 
                      drop_single_values = FALSE,
                      main_layer = "counts",
                      outFile='data/subset_atac_only_dmg_atlas.h5ad')

AnnData object with n_obs × n_vars = 21804 × 378298
    obs: 'total', 'duplicate', 'chimeric', 'unmapped', 'lowmapq', 'mitochondrial', 'nonprimary', 'passed_filters', 'is__cell_barcode', 'excluded_reason', 'TSS_fragments', 'DNase_sensitive_region_fragments', 'enhancer_region_fragments', 'promoter_region_fragments', 'on_target_fragments', 'blacklist_region_fragments', 'peak_region_fragments', 'peak_region_cutsites', 'nCount_ATAC', 'nFeature_ATAC', 'SampleID', 'nucleosome_signal', 'nucleosome_percentile', 'TSS.enrichment', 'TSS.percentile', 'pct_reads_in_peaks', 'blacklist_ratio', 'high.tss', 'nucleosome_group', 'scDblFinder.score', 'scDblFinder.class', 'amulet_pvalue', 'amulet_qvalue', 'scDblFinder.p', 'dbl_combined_score', 'ID', 'Study', 'Institute', 'Preservation_method', 'Diagnosis', 'Tumor_type', 'Tumor_subtype', 'Location', 'Source', 'Clinical_status', 'Isolation_method', 'Sc_platform_RNA', 'Sc_platform_ATAC', 'Sc_multiome', 'Raw_data_available', 'Counts', 'Genome_version', 'Paired_sample', 'Multisector', 'Gender', 'Age_years', 'Dexamethasone_prior_surgery', 'Survival', 'Survival_months', 'Mitosis', 'Ki67', 'Methylation_array', 'H3F3A', 'H3C3', 'HIST1H3B', 'HIST2H3C', 'TP53', 'EGFR', 'PDGFRA', 'SUFU', 'NF1', 'pTERT', 'PIK3CA', 'PIK3R1', 'ATRX', 'PTEN', 'ASXL1', 'BCOR', 'BCORL1', 'SMC1A', 'WT1', 'PPM1D', 'ACVR1', 'TSHR', 'BRAF', 'GNAQ', 'LMNA', 'KIT', 'ARID1A', 'KRAS', 'Other', 'predicted.id', 'Batch_for_correction', 'cell_id'
    var: 'count', 'percentile'

#### Multiome

Sicne some cells are only present in one of the two assays, we will initiallty only test on those that have paired information

In [ ]:
# Get the cell names present in obj1 but not in obj2
cells_only_in_rna <- setdiff(rownames(rna_multi@meta.data), rownames(atac_multi@meta.data))

# Get the cell names present in obj2 but not in obj1
cells_only_in_atac <- setdiff(rownames(atac_multi@meta.data), rownames(rna_multi@meta.data))

# Print the results
print(paste("Cell names present in rna but not in atac:", length(cells_only_in_rna)))
# print(cells_only_in_rna)

print(paste("Cell names present in atac but not in rna:", length(cells_only_in_atac)))
# print(cells_only_in_atac)

[1] "Cell names present in rna but not in atac: 27028"
[1] "Cell names present in atac but not in rna: 40152"

In [ ]:
common_cells <- intersect(rownames(rna_multi@meta.data), rownames(atac_multi@meta.data))

rna_multi <- subset(rna_multi, cells = common_cells)
atac_multi <- subset(atac_multi, cells = common_cells)
rna_multi
atac_multi
gc()

An object of class Seurat
38576 features across 59584 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

An object of class Seurat
378298 features across 59584 samples within 1 assay
Active assay: ATAC (378298 features, 0 variable features)
 2 layers present: counts, data

       used        (Mb)     gc trigger  (Mb)     max used    (Mb)
Ncells    11415703    609.7    16520452    882.3    16520452    882.3
Vcells 21785007777 166206.5 36144084056 275757.5 30069779978 229414.3

In [ ]:
# Subset
n_cells <- nrow(rna_multi@meta.data)
n_sample <- round(n_cells * 0.3)
sampled_cells <- sample(Cells(rna_multi), n_sample)
rna_multi_subset <- subset(rna_multi, cells = sampled_cells)
rna_multi_subset
atac_multi_subset <- subset(atac_multi, cells = sampled_cells)
atac_multi_subset

An object of class Seurat
38576 features across 17875 samples within 6 assays
Active assay: RNA (19248 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 5 other assays present: RAW, prediction.score.annotation_level_1, prediction.score.annotation_level_2, prediction.score.annotation_level_3, prediction.score.annotation_level_4
 4 dimensional reductions calculated: pca, umap, ref.pca, ref.umap

An object of class Seurat
378298 features across 17875 samples within 1 assay
Active assay: ATAC (378298 features, 0 variable features)
 2 layers present: counts, data

In [ ]:
sceasy::convertFormat(rna_multi_subset, from="seurat", to="anndata",
                      assay = "RNA", 
                      drop_single_values = FALSE,
                      main_layer = "counts",
                      outFile='data/subset_rna_multi_dmg_atlas.h5ad')

saveRDS(rna_multi_subset, 'data/subset_rna_multi_dmg_atlas.rds')

AnnData object with n_obs × n_vars = 17875 × 19248
    obs: 'nCount_RNA', 'nFeature_RNA', 'nCount_RAW', 'nFeature_RAW', 'DF.class', 'DF.score', 'scDblFinder.class', 'scDblFinder.score', 'ID', 'SampleID', 'Data', 'percent_mito', 'percent_ribo', 'percent_mito_ribo', 'log10GenesPerUMI', 'nFeature_Diff', 'nCount_Diff', 'Batch_for_correction', 'scDblFinder.clusters.class', 'scDblFinder.clusters.score', 'scDblFinder.class.clusters', 'doublet.combn.fisher', 'doublet.combn.mean', 'doublet.combn.fisher.class', 'doublet.combn.mean.class', 'Study', 'Original_annotation', 'Isolation_method_by_cell', 'Cell_type_granular_mouse_correlations', 'Cell_type_mouse_correlations', 'Cell_type_consensus_Jessa2022', 'Malignant_normal_consensus_Jessa2022', 'Institute', 'Preservation_method', 'Diagnosis', 'Tumor_type', 'Tumor_subtype', 'Location', 'Source', 'Clinical_status', 'Isolation_method', 'Sc_platform_RNA', 'Sc_platform_ATAC', 'Sc_multiome', 'Raw_data_available', 'Counts', 'Genome_version', 'Paired_sample', 'Multisector', 'Gender', 'Age_years', 'Dexamethasone_prior_surgery', 'Survival', 'Survival_months', 'Mitosis', 'Ki67', 'Methylation_array', 'H3F3A', 'H3C3', 'HIST1H3B', 'HIST2H3C', 'TP53', 'EGFR', 'PDGFRA', 'SUFU', 'NF1', 'pTERT', 'PIK3CA', 'PIK3R1', 'ATRX', 'PTEN', 'ASXL1', 'BCOR', 'BCORL1', 'SMC1A', 'WT1', 'PPM1D', 'ACVR1', 'TSHR', 'BRAF', 'GNAQ', 'LMNA', 'KIT', 'ARID1A', 'KRAS', 'Other', 'RNA_snn_res.0.8', 'seurat_clusters', 'predicted.annotation_level_1.score', 'predicted.annotation_level_1', 'predicted.annotation_level_2.score', 'predicted.annotation_level_2', 'predicted.annotation_level_3.score', 'predicted.annotation_level_3', 'predicted.annotation_level_4.score', 'predicted.annotation_level_4', 'iCNV', 'cell_id', 'predicted.id'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'vst.variable'
    obsm: 'X_pca', 'X_umap', 'X_ref.pca', 'X_ref.umap'

In [ ]:
saveRDS(atac_multi_subset, 'data/subset_atac_multi_dmg_atlas.rds')

In [ ]:
# change nomenclature of the features to match other down stream tools in python
rownames(atac_multi_subset@assays$ATAC@counts) <- sub("-", ":", 
                                                     rownames(atac_multi_subset@assays$ATAC@counts))
rownames(atac_multi_subset@assays$ATAC@data) <- sub("-", ":", 
                                                   rownames(atac_multi_subset@assays$ATAC@data))
rownames(atac_multi_subset@assays$ATAC@meta.features) <- sub("-", ":", 
                                                   rownames(atac_multi_subset@assays$ATAC@meta.features))

In [ ]:
# to avoid later copnflits with cell_id coming from RAN and ATAC we chnage the ATAC predictions
# to the labels assigned in the RNA counterpart

atac_multi_subset <- AddMetaData(atac_multi_subset, FetchData(rna_multi_subset, 'cell_id'))

sceasy::convertFormat(atac_multi_subset, from="seurat", to="anndata",
                      assay = "ATAC", 
                      drop_single_values = FALSE,
                      main_layer = "counts",
                      outFile='data/subset_atac_multi_dmg_atlas.h5ad')

AnnData object with n_obs × n_vars = 17875 × 378298
    obs: 'gex_barcode', 'atac_barcode', 'is_cell', 'excluded_reason', 'gex_raw_reads', 'gex_mapped_reads', 'gex_conf_intergenic_reads', 'gex_conf_exonic_reads', 'gex_conf_intronic_reads', 'gex_conf_exonic_unique_reads', 'gex_conf_exonic_antisense_reads', 'gex_conf_exonic_dup_reads', 'gex_exonic_umis', 'gex_conf_intronic_unique_reads', 'gex_conf_intronic_antisense_reads', 'gex_conf_intronic_dup_reads', 'gex_intronic_umis', 'gex_conf_txomic_unique_reads', 'gex_umis_count', 'gex_genes_count', 'atac_raw_reads', 'atac_unmapped_reads', 'atac_lowmapq', 'atac_dup_reads', 'atac_chimeric_reads', 'atac_mitochondrial_reads', 'passed_filters', 'atac_TSS_fragments', 'atac_peak_region_fragments', 'atac_peak_region_cutsites', 'nCount_ATAC', 'nFeature_ATAC', 'SampleID', 'nucleosome_signal', 'nucleosome_percentile', 'TSS.enrichment', 'TSS.percentile', 'pct_reads_in_peaks', 'blacklist_ratio', 'high.tss', 'nucleosome_group', 'scDblFinder.score', 'scDblFinder.class', 'amulet_pvalue', 'amulet_qvalue', 'scDblFinder.p', 'dbl_combined_score', 'ID', 'Study', 'Institute', 'Preservation_method', 'Diagnosis', 'Tumor_type', 'Tumor_subtype', 'Location', 'Source', 'Clinical_status', 'Isolation_method', 'Sc_platform_RNA', 'Sc_platform_ATAC', 'Sc_multiome', 'Raw_data_available', 'Counts', 'Genome_version', 'Paired_sample', 'Multisector', 'Gender', 'Age_years', 'Dexamethasone_prior_surgery', 'Survival', 'Survival_months', 'Mitosis', 'Ki67', 'Methylation_array', 'H3F3A', 'H3C3', 'HIST1H3B', 'HIST2H3C', 'TP53', 'EGFR', 'PDGFRA', 'SUFU', 'NF1', 'pTERT', 'PIK3CA', 'PIK3R1', 'ATRX', 'PTEN', 'ASXL1', 'BCOR', 'BCORL1', 'SMC1A', 'WT1', 'PPM1D', 'ACVR1', 'TSHR', 'BRAF', 'GNAQ', 'LMNA', 'KIT', 'ARID1A', 'KRAS', 'Other', 'predicted.id', 'cell_id', 'Batch_for_correction'
    var: 'count', 'percentile'

In [ ]:
sessionInfo()

R version 4.2.3 (2023-03-15)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: Rocky Linux 8.7 (Green Obsidian)

Matrix products: default
BLAS/LAPACK: /gpfs/home3/cruiz2/miniconda3/envs/r_python/lib/libopenblasp-r0.3.21.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] future_1.32.0           sceasy_0.0.7            reticulate_1.28
[4] dplyr_1.1.1             Seurat_4.9.9.9041       SeuratObject_4.9.9.9083
[7] sp_1.6-0                Signac_1.9.0.9000

loaded via a namespace (and not attached):
  [1] readxl_1.4.2                uuid_1.1-0
  [3] spam_2.9-1                  fastmatch_1.1-3
  [5] plyr_1.8.8                  igraph_1.4.1
  [7] repr_1.1.6                  lazyeval_0.2.2
  [9] splines_4.2.3               RcppHNSW_0.4.1
 [11] BiocParallel_1.32.6         listenv_0.9.0
 [13] scattermore_0.8             GenomeInfoDb_1.34.9
 [15] ggplot2_3.4.1               digest_0.6.31
 [17] yulab.utils_0.0.6           htmltools_0.5.5
 [19] viridis_0.6.2               ggalluvial_0.12.5
 [21] fansi_1.0.4                 magrittr_2.0.3
 [23] tensor_1.5                  cluster_2.1.4
 [25] ROCR_1.0-11                 globals_0.16.2
 [27] Biostrings_2.66.0           matrixStats_0.63.0
 [29] timechange_0.2.0            spatstat.sparse_3.0-1
 [31] colorspace_2.1-0            rappdirs_0.3.3
 [33] ggrepel_0.9.3               crayon_1.5.2
 [35] RCurl_1.98-1.12             jsonlite_1.8.4
 [37] progressr_0.13.0            spatstat.data_3.0-1
 [39] survival_3.5-5              zoo_1.8-11
 [41] glue_1.6.2                  polyclip_1.10-4
 [43] gtable_0.3.3                zlibbioc_1.44.0
 [45] XVector_0.38.0              leiden_0.4.3
 [47] DelayedArray_0.24.0         SingleCellExperiment_1.20.1
 [49] future.apply_1.10.0         BiocGenerics_0.44.0
 [51] abind_1.4-5                 scales_1.2.1
 [53] pheatmap_1.0.12             SCpubr_1.1.2.9000
 [55] spatstat.random_3.1-4       miniUI_0.1.1.1
 [57] Rcpp_1.0.10                 viridisLite_0.4.1
 [59] xtable_1.8-4                gridGraphics_0.5-1
 [61] dotCall64_1.0-2             stats4_4.2.3
 [63] dittoSeq_1.11.0             htmlwidgets_1.6.2
 [65] httr_1.4.5                  RColorBrewer_1.1-3
 [67] ellipsis_0.3.2              ica_1.0-3
 [69] farver_2.1.1                pkgconfig_2.0.3
 [71] uwot_0.1.14                 deldir_1.0-6
 [73] here_1.0.1                  utf8_1.2.3
 [75] ggplotify_0.1.0             labeling_0.4.2
 [77] tidyselect_1.2.0            rlang_1.1.0
 [79] reshape2_1.4.4              later_1.3.0
 [81] cellranger_1.1.0            munsell_0.5.0
 [83] tools_4.2.3                 cli_3.6.1
 [85] generics_0.1.3              ggridges_0.5.4
 [87] evaluate_0.20               stringr_1.5.0
 [89] fastmap_1.1.1               goftest_1.2-3
 [91] fitdistrplus_1.1-8          purrr_1.0.1
 [93] RANN_2.6.1                  pbapply_1.7-0
 [95] nlme_3.1-162                mime_0.12
 [97] ggrastr_1.0.1               RcppRoll_0.3.0
 [99] compiler_4.2.3              beeswarm_0.4.0
[101] plotly_4.10.1               png_0.1-8
[103] spatstat.utils_3.0-2        tibble_3.2.1
[105] stringi_1.7.12              RSpectra_0.16-1
[107] forcats_1.0.0               lattice_0.20-45
[109] IRdisplay_1.1               Matrix_1.5-3
[111] vctrs_0.6.1                 pillar_1.9.0
[113] lifecycle_1.0.3             spatstat.geom_3.1-0
[115] lmtest_0.9-40               RcppAnnoy_0.0.20
[117] data.table_1.14.8           cowplot_1.1.1
[119] bitops_1.0-7                irlba_2.3.5.1
[121] httpuv_1.6.9                patchwork_1.1.2
[123] GenomicRanges_1.50.2        R6_2.5.1
[125] promises_1.2.0.1            KernSmooth_2.23-20
[127] gridExtra_2.3               vipor_0.4.5
[129] IRanges_2.32.0              parallelly_1.35.0
[131] codetools_0.2-19            assertthat_0.2.1
[133] fastDummies_1.6.3           MASS_7.3-58.3
[135] SummarizedExperiment_1.28.0 rprojroot_2.0.3
[137] withr_2.5.0                 sctransform_0.3.5
[139] Rsamtools_2.14.0            S4Vectors_0.36.2
[141] GenomeInfoDbData_1.2.9      parallel_4.2.3
[143] grid_4.2.3                  IRkernel_1.3.2
[145] tidyr_1.3.0                 MatrixGenerics_1.10.0
[147] Cairo_1.6-0                 Rtsne_0.16
[149] pbdZMQ_0.3-9                spatstat.explore_3.1-0
[151] Biobase_2.58.0              shiny_1.7.4
[153] lubridate_1.9.2             base64enc_0.1-3
[155] ggbeeswarm_0.7.1