`conda activate scenicplus`

In [1]:
import os

import anndata as ad
import scanpy as sc
import pandas as pd
import numpy as np
import os
from matplotlib import rcParams
import matplotlib.pyplot as plt

import seaborn as sns

In [2]:
import scatac_fragment_tools

In [3]:
adata = sc.read('/projects/0/einf2548/cruiz/dmg/notebooks/scATAC/data/Mannens2024/Pool_peaks_subset.h5ad')
adata

/home/cruiz2/miniconda3/envs/scenicplus/lib/python3.11/site-packages/anndata/__init__.py:51: FutureWarning: `anndata.read` is deprecated, use `anndata.read_h5ad` instead. `ad.read` will be removed in mid 2024.
  warnings.warn(

AnnData object with n_obs × n_vars = 180724 × 410863
    obs: 'Age', 'Agetext', 'Ageunit', 'All_fc_analysis_id', 'Analysis', 'Chemistry', 'Class', 'ClusterName', 'Clusters', 'Clusters_main', 'Cmobarcodes', 'Comment', 'Datecaptured', 'Donor', 'DoubletFinderFlag', 'DoubletFinderScore', 'Editat', 'Editby', 'FRIP', 'FRtss', 'Fragments_in_peaks', 'GA_colsum', 'GA_pooled_colsum', 'Id', 'Label', 'Method', 'NBins', 'NPeaks', 'Name', 'Neuronprop', 'Numpooledanimals', 'Outliers', 'Plugdate', 'Project', 'PseudoAge', 'Roi', 'SEX', 'Sampleok', 'Sex', 'Shortname', 'Species', 'Split', 'Splits', 'Strain', 'SubClusters', 'TSS_fragments', 'Tissue', 'Transcriptome', 'Y', 'barcode', 'chimeric', 'duplicate', 'excluded_reason', 'is__cell_barcode', 'lowmapq', 'mitochondrial', 'passed_filters', 'peak_region_cutsites', 'peak_region_fragments', 'preClusters', 'regions', 'total', 'unmapped', 'Coarse'
    var: 'Annotation', 'Chr', 'CpG%', 'Detailed Annotation', 'Distance to TSS', 'End', 'Entrez ID', 'Focus Ratio-Region Size', 'GC%', 'Gene Alias', 'Gene Description', 'Gene Name', 'Gene Type', 'ID', 'NCells', 'Nearest Ensembl', 'Nearest PromoterID', 'Nearest Refseq', 'Nearest Unigene', 'Peak Score', 'Start', 'Strand', 'Valid', 'pos', 'preCluster_mu', 'preCluster_residuals', 'preCluster_sd', 'precluster_mu', 'precluster_sd'
    uns: 'Coarse_colors'
    obsm: 'Embedding', 'LSI', 'LSI_b', 'LSI_main', 'TSNE', 'TSNE_1', 'TSNE_10', 'TSNE_2', 'TSNE_3', 'TSNE_4', 'TSNE_5', 'TSNE_bin', 'TSNE_main', 'TSNE_old', 'UMAP', 'UMAP3D', 'UMAP3D_main', 'UMAP_main', 'X_umap'
    layers: 'Counts'

In [4]:
adata.obs['Coarse'].value_counts()

Endothelial    10000
Neuron         10000
Glioblast      10000
Mural          10000
Microglia      10000
Neuron_Gly     10000
Neuron_HB      10000
Neuron_Int     10000
Neuron_CB      10000
PreOPC         10000
RG             10000
Neuron_Tel     10000
Neuron_Purk    10000
Neuron_MB      10000
Floor_plate     8402
IPC             8350
Roof_plate      7178
OPC             6262
Neuron_GABA     3198
Neuron_DA       2288
Schwann         1836
COP             1159
Neuron_DRG      1019
PVM              784
Lymphoid         248
Name: Coarse, dtype: int64

In [5]:
adata.obs['Class'].value_counts()

Neuron         94855
Radial_glia    42466
Oligo          12371
Immune         11032
Vascular       10597
Fibroblast      9403
Name: Class, dtype: int64

In [6]:
adata.obs['ClusterName'].value_counts()

Floor_plate         8402
VZ_prog             7636
Roof_plate          7178
PreOPC              6886
Neur_Int_LGE_CGE    5429
                    ...
Gbl_HB_3             135
VLMC_MGP_1           122
End_early_2           92
Gbl_late              73
VLMC_SLC6A13_3        53
Name: ClusterName, Length: 135, dtype: int64

In [7]:
# Define the maximum number of cells per cell type
max_cells_per_celltype = 1000

# Convert adata.obs to a DataFrame and include the 'Coarse' column
metadata_df = adata.obs.copy()

# Add a barcode or identifier column if not already present
metadata_df['barcode'] = metadata_df.index

# Group by the 'Coarse' column and sample cells
sampled_metadata = (metadata_df
                    .groupby('Coarse')
                    .apply(lambda x: x.sample(n=min(len(x), max_cells_per_celltype), random_state=42))
                    .reset_index(drop=True))

# Subset the AnnData object with the sampled barcodes
adata_subset = adata[sampled_metadata['barcode'], :].copy()
adata_subset

AnnData object with n_obs × n_vars = 24032 × 410863
    obs: 'Age', 'Agetext', 'Ageunit', 'All_fc_analysis_id', 'Analysis', 'Chemistry', 'Class', 'ClusterName', 'Clusters', 'Clusters_main', 'Cmobarcodes', 'Comment', 'Datecaptured', 'Donor', 'DoubletFinderFlag', 'DoubletFinderScore', 'Editat', 'Editby', 'FRIP', 'FRtss', 'Fragments_in_peaks', 'GA_colsum', 'GA_pooled_colsum', 'Id', 'Label', 'Method', 'NBins', 'NPeaks', 'Name', 'Neuronprop', 'Numpooledanimals', 'Outliers', 'Plugdate', 'Project', 'PseudoAge', 'Roi', 'SEX', 'Sampleok', 'Sex', 'Shortname', 'Species', 'Split', 'Splits', 'Strain', 'SubClusters', 'TSS_fragments', 'Tissue', 'Transcriptome', 'Y', 'barcode', 'chimeric', 'duplicate', 'excluded_reason', 'is__cell_barcode', 'lowmapq', 'mitochondrial', 'passed_filters', 'peak_region_cutsites', 'peak_region_fragments', 'preClusters', 'regions', 'total', 'unmapped', 'Coarse'
    var: 'Annotation', 'Chr', 'CpG%', 'Detailed Annotation', 'Distance to TSS', 'End', 'Entrez ID', 'Focus Ratio-Region Size', 'GC%', 'Gene Alias', 'Gene Description', 'Gene Name', 'Gene Type', 'ID', 'NCells', 'Nearest Ensembl', 'Nearest PromoterID', 'Nearest Refseq', 'Nearest Unigene', 'Peak Score', 'Start', 'Strand', 'Valid', 'pos', 'preCluster_mu', 'preCluster_residuals', 'preCluster_sd', 'precluster_mu', 'precluster_sd'
    uns: 'Coarse_colors'
    obsm: 'Embedding', 'LSI', 'LSI_b', 'LSI_main', 'TSNE', 'TSNE_1', 'TSNE_10', 'TSNE_2', 'TSNE_3', 'TSNE_4', 'TSNE_5', 'TSNE_bin', 'TSNE_main', 'TSNE_old', 'UMAP', 'UMAP3D', 'UMAP3D_main', 'UMAP_main', 'X_umap'
    layers: 'Counts'

In [10]:
adata_subset.obs['Coarse'].value_counts()

COP            1000
Endothelial    1000
Floor_plate    1000
Glioblast      1000
IPC            1000
Microglia      1000
Mural          1000
Neuron         1000
Neuron_CB      1000
Neuron_Purk    1000
Neuron_DA      1000
Neuron_DRG     1000
Neuron_GABA    1000
Neuron_Gly     1000
Neuron_HB      1000
Neuron_Int     1000
Neuron_MB      1000
Roof_plate     1000
Neuron_Tel     1000
OPC            1000
PreOPC         1000
Schwann        1000
RG             1000
PVM             784
Lymphoid        248
Name: Coarse, dtype: int64

In [11]:
# Create the data as a dictionary
data = {
    'sample': ['fetal'],
    'path_to_fragment_file': ['/projects/0/einf2548/cruiz/dmg/public_data/Mannens2024/compiled_fragments/compiled_filtered_fragments.tsv.sorted.gz']
}

# Convert the dictionary to a DataFrame
df = pd.DataFrame(data)
df

# Save the DataFrame to a TSV file
df.to_csv('data/Mannens2024/sample_to_fragment.tsv', sep='\t', index=False)

print("TSV file 'sample_to_fragment.tsv' has been created.")

TSV file 'sample_to_fragment.tsv' has been created.

In [12]:
df

  sample                              path_to_fragment_file
0  fetal  /projects/0/einf2548/cruiz/dmg/public_data/Man...

In [13]:
import pandas as pd

# Assuming `adata` is your AnnData object
sample = 'fetal'

# Extract cell_type from adata.obs['Coarse']
cell_types = adata_subset.obs['Coarse']

# Extract cell barcodes from adata.obs_names
cell_barcodes = adata_subset.obs_names+'-1'

# Create a DataFrame for the required information
df = pd.DataFrame({
    'sample': sample,
    'cell_type': cell_types,
    'cell_barcode': cell_barcodes
})

# Save the DataFrame to a TSV file
df.to_csv('data/Mannens2024/cell_type_to_cell_barcode.tsv', sep='\t', index=False)

print("TSV file 'cell_type_to_cell_barcode.tsv' has been created.")

TSV file 'cell_type_to_cell_barcode.tsv' has been created.

In [14]:
df

                          sample cell_type                 cell_barcode
CellID
10X242_2:TACGCAATCCATGTTT  fetal       COP  10X242_2:TACGCAATCCATGTTT-1
10X315_4:TACGCCTAGCTAGCAG  fetal       COP  10X315_4:TACGCCTAGCTAGCAG-1
10X315_4:TGCTTCGAGAGCCACA  fetal       COP  10X315_4:TGCTTCGAGAGCCACA-1
10X347_3:CCAATGAAGTAGCAAT  fetal       COP  10X347_3:CCAATGAAGTAGCAAT-1
10X369_3:AAACTCGGTATTCGAC  fetal       COP  10X369_3:AAACTCGGTATTCGAC-1
...                          ...       ...                          ...
10X250_4:TTTGTGTAGAGATTAC  fetal   Schwann  10X250_4:TTTGTGTAGAGATTAC-1
10X315_4:GATCGTAAGCCCATTA  fetal   Schwann  10X315_4:GATCGTAAGCCCATTA-1
10X406_5:TCAACAATCTAATCCT  fetal   Schwann  10X406_5:TCAACAATCTAATCCT-1
10X365_4:TTGTGCGAGGTCCTGA  fetal   Schwann  10X365_4:TTGTGCGAGGTCCTGA-1
10X364_4:ACTTCCGGTACAACGG  fetal   Schwann  10X364_4:ACTTCCGGTACAACGG-1

[24032 rows x 3 columns]

In [15]:
df['cell_type'].value_counts()

COP            1000
Endothelial    1000
Floor_plate    1000
Glioblast      1000
IPC            1000
Microglia      1000
Mural          1000
Neuron         1000
Neuron_CB      1000
Neuron_Purk    1000
Neuron_DA      1000
Neuron_DRG     1000
Neuron_GABA    1000
Neuron_Gly     1000
Neuron_HB      1000
Neuron_Int     1000
Neuron_MB      1000
Roof_plate     1000
Neuron_Tel     1000
OPC            1000
PreOPC         1000
Schwann        1000
RG             1000
PVM             784
Lymphoid        248
Name: cell_type, dtype: int64

In [ ]:
!scatac_fragment_tools split \
    -f /projects/0/einf2548/cruiz/dmg/notebooks/scATAC/data/Mannens2024/sample_to_fragment.tsv \
    -b /projects/0/einf2548/cruiz/dmg/notebooks/scATAC/data/Mannens2024/cell_type_to_cell_barcode.tsv \
    -c /projects/0/einf2548/cruiz/hg38.chrom.sizes \
    -o /projects/0/einf2548/cruiz/dmg/notebooks/scATAC/pycistopic_fetal/pseudobulk_bed_files \
    -n 32 \
    -v

Splitting fragments ...
Processing contig chr1
Processing contig chr10
Skipping contig chr10_GL383545v1_alt because it is not in the fragments file
Skipping contig chr10_GL383546v1_alt because it is not in the fragments file
Skipping contig chr10_KI270824v1_alt because it is not in the fragments file
Skipping contig chr10_KI270825v1_alt because it is not in the fragments file
Processing contig chr11
Skipping contig chr11_GL383547v1_alt because it is not in the fragments file
Skipping contig chr11_JH159136v1_alt because it is not in the fragments file
Skipping contig chr11_JH159137v1_alt because it is not in the fragments file
Skipping contig chr11_KI270721v1_random because it is not in the fragments file
Skipping contig chr11_KI270826v1_alt because it is not in the fragments file
Skipping contig chr11_KI270827v1_alt because it is not in the fragments file
Skipping contig chr11_KI270829v1_alt because it is not in the fragments file
Skipping contig chr11_KI270830v1_alt because it is not in the fragments file
Skipping contig chr11_KI270831v1_alt because it is not in the fragments file
Skipping contig chr11_KI270832v1_alt because it is not in the fragments file
Skipping contig chr11_KI270902v1_alt because it is not in the fragments file
Skipping contig chr11_KI270903v1_alt because it is not in the fragments file
Skipping contig chr11_KI270927v1_alt because it is not in the fragments file
Processing contig chr12
Skipping contig chr12_GL383549v1_alt because it is not in the fragments file
Skipping contig chr12_GL383550v2_alt because it is not in the fragments file
Skipping contig chr12_GL383551v1_alt because it is not in the fragments file
Skipping contig chr12_GL383552v1_alt because it is not in the fragments file
Skipping contig chr12_GL383553v2_alt because it is not in the fragments file
Skipping contig chr12_GL877875v1_alt because it is not in the fragments file
Skipping contig chr12_GL877876v1_alt because it is not in the fragments file
Skipping contig chr12_KI270833v1_alt because it is not in the fragments file
Skipping contig chr12_KI270834v1_alt because it is not in the fragments file
Skipping contig chr12_KI270835v1_alt because it is not in the fragments file
Skipping contig chr12_KI270836v1_alt because it is not in the fragments file
Skipping contig chr12_KI270837v1_alt because it is not in the fragments file
Skipping contig chr12_KI270904v1_alt because it is not in the fragments file
Processing contig chr13
Skipping contig chr13_KI270838v1_alt because it is not in the fragments file
Skipping contig chr13_KI270839v1_alt because it is not in the fragments file
Skipping contig chr13_KI270840v1_alt because it is not in the fragments file
Skipping contig chr13_KI270841v1_alt because it is not in the fragments file
Skipping contig chr13_KI270842v1_alt because it is not in the fragments file
Skipping contig chr13_KI270843v1_alt because it is not in the fragments file
Processing contig chr14
Processing contig chr14_GL000009v2_random
Processing contig chr14_GL000194v1_random
Processing contig chr14_GL000225v1_random
Skipping contig chr14_KI270722v1_random because it is not in the fragments file
Skipping contig chr14_KI270723v1_random because it is not in the fragments file
Skipping contig chr14_KI270724v1_random because it is not in the fragments file
Skipping contig chr14_KI270725v1_random because it is not in the fragments file
Skipping contig chr14_KI270726v1_random because it is not in the fragments file
Skipping contig chr14_KI270844v1_alt because it is not in the fragments file
Skipping contig chr14_KI270845v1_alt because it is not in the fragments file
Skipping contig chr14_KI270846v1_alt because it is not in the fragments file
Skipping contig chr14_KI270847v1_alt because it is not in the fragments file
Processing contig chr15
Skipping contig chr15_GL383554v1_alt because it is not in the fragments file
Skipping contig chr15_GL383555v2_alt because it is not in the fragments file
Skipping contig chr15_KI270727v1_random because it is not in the fragments file
Skipping contig chr15_KI270848v1_alt because it is not in the fragments file
Skipping contig chr15_KI270849v1_alt because it is not in the fragments file
Skipping contig chr15_KI270850v1_alt because it is not in the fragments file
Skipping contig chr15_KI270851v1_alt because it is not in the fragments file
Skipping contig chr15_KI270852v1_alt because it is not in the fragments file
Skipping contig chr15_KI270905v1_alt because it is not in the fragments file
Skipping contig chr15_KI270906v1_alt because it is not in the fragments file
Processing contig chr16
Skipping contig chr16_GL383556v1_alt because it is not in the fragments file
Skipping contig chr16_GL383557v1_alt because it is not in the fragments file
Skipping contig chr16_KI270728v1_random because it is not in the fragments file
Skipping contig chr16_KI270853v1_alt because it is not in the fragments file
Skipping contig chr16_KI270854v1_alt because it is not in the fragments file
Skipping contig chr16_KI270855v1_alt because it is not in the fragments file
Skipping contig chr16_KI270856v1_alt because it is not in the fragments file
Processing contig chr17
Skipping contig chr17_GL000205v2_random because it is not in the fragments file
Skipping contig chr17_GL000258v2_alt because it is not in the fragments file
Skipping contig chr17_GL383563v3_alt because it is not in the fragments file
Skipping contig chr17_GL383564v2_alt because it is not in the fragments file
Skipping contig chr17_GL383565v1_alt because it is not in the fragments file
Skipping contig chr17_GL383566v1_alt because it is not in the fragments file
Skipping contig chr17_JH159146v1_alt because it is not in the fragments file
Skipping contig chr17_JH159147v1_alt because it is not in the fragments file
Skipping contig chr17_JH159148v1_alt because it is not in the fragments file
Skipping contig chr17_KI270729v1_random because it is not in the fragments file
Skipping contig chr17_KI270730v1_random because it is not in the fragments file
Skipping contig chr17_KI270857v1_alt because it is not in the fragments file
Skipping contig chr17_KI270858v1_alt because it is not in the fragments file
Skipping contig chr17_KI270859v1_alt because it is not in the fragments file
Skipping contig chr17_KI270860v1_alt because it is not in the fragments file
Skipping contig chr17_KI270861v1_alt because it is not in the fragments file
Skipping contig chr17_KI270862v1_alt because it is not in the fragments file
Skipping contig chr17_KI270907v1_alt because it is not in the fragments file
Skipping contig chr17_KI270908v1_alt because it is not in the fragments file
Skipping contig chr17_KI270909v1_alt because it is not in the fragments file
Skipping contig chr17_KI270910v1_alt because it is not in the fragments file
Processing contig chr18
Skipping contig chr18_GL383567v1_alt because it is not in the fragments file
Skipping contig chr18_GL383568v1_alt because it is not in the fragments file
Skipping contig chr18_GL383569v1_alt because it is not in the fragments file
Skipping contig chr18_GL383570v1_alt because it is not in the fragments file
Skipping contig chr18_GL383571v1_alt because it is not in the fragments file
Skipping contig chr18_GL383572v1_alt because it is not in the fragments file
Skipping contig chr18_KI270863v1_alt because it is not in the fragments file
Skipping contig chr18_KI270864v1_alt because it is not in the fragments file
Skipping contig chr18_KI270911v1_alt because it is not in the fragments file
Skipping contig chr18_KI270912v1_alt because it is not in the fragments file
Processing contig chr19
Skipping contig chr19_GL000209v2_alt because it is not in the fragments file
Skipping contig chr19_GL383573v1_alt because it is not in the fragments file
Skipping contig chr19_GL383574v1_alt because it is not in the fragments file
Skipping contig chr19_GL383575v2_alt because it is not in the fragments file
Skipping contig chr19_GL383576v1_alt because it is not in the fragments file
Skipping contig chr19_GL949746v1_alt because it is not in the fragments file
Skipping contig chr19_GL949747v2_alt because it is not in the fragments file
Skipping contig chr19_GL949748v2_alt because it is not in the fragments file
Skipping contig chr19_GL949749v2_alt because it is not in the fragments file
Skipping contig chr19_GL949750v2_alt because it is not in the fragments file
Skipping contig chr19_GL949751v2_alt because it is not in the fragments file
Skipping contig chr19_GL949752v1_alt because it is not in the fragments file
Skipping contig chr19_GL949753v2_alt because it is not in the fragments file
Skipping contig chr19_KI270865v1_alt because it is not in the fragments file
Skipping contig chr19_KI270866v1_alt because it is not in the fragments file
Skipping contig chr19_KI270867v1_alt because it is not in the fragments file
Skipping contig chr19_KI270868v1_alt because it is not in the fragments file
Skipping contig chr19_KI270882v1_alt because it is not in the fragments file
Skipping contig chr19_KI270883v1_alt because it is not in the fragments file
Skipping contig chr19_KI270884v1_alt because it is not in the fragments file
Skipping contig chr19_KI270885v1_alt because it is not in the fragments file
Skipping contig chr19_KI270886v1_alt because it is not in the fragments file
Skipping contig chr19_KI270887v1_alt because it is not in the fragments file
Skipping contig chr19_KI270888v1_alt because it is not in the fragments file
Skipping contig chr19_KI270889v1_alt because it is not in the fragments file
Skipping contig chr19_KI270890v1_alt because it is not in the fragments file
Skipping contig chr19_KI270891v1_alt because it is not in the fragments file
Skipping contig chr19_KI270914v1_alt because it is not in the fragments file
Skipping contig chr19_KI270915v1_alt because it is not in the fragments file
Skipping contig chr19_KI270916v1_alt because it is not in the fragments file
Skipping contig chr19_KI270917v1_alt because it is not in the fragments file
Skipping contig chr19_KI270918v1_alt because it is not in the fragments file
Skipping contig chr19_KI270919v1_alt because it is not in the fragments file
Skipping contig chr19_KI270920v1_alt because it is not in the fragments file
Skipping contig chr19_KI270921v1_alt because it is not in the fragments file
Skipping contig chr19_KI270922v1_alt because it is not in the fragments file
Skipping contig chr19_KI270923v1_alt because it is not in the fragments file
Skipping contig chr19_KI270929v1_alt because it is not in the fragments file
Skipping contig chr19_KI270930v1_alt because it is not in the fragments file
Skipping contig chr19_KI270931v1_alt because it is not in the fragments file
Skipping contig chr19_KI270932v1_alt because it is not in the fragments file
Skipping contig chr19_KI270933v1_alt because it is not in the fragments file
Skipping contig chr19_KI270938v1_alt because it is not in the fragments file
Skipping contig chr1_GL383518v1_alt because it is not in the fragments file
Skipping contig chr1_GL383519v1_alt because it is not in the fragments file
Skipping contig chr1_GL383520v2_alt because it is not in the fragments file
Skipping contig chr1_KI270706v1_random because it is not in the fragments file
Skipping contig chr1_KI270707v1_random because it is not in the fragments file
Skipping contig chr1_KI270708v1_random because it is not in the fragments file
Skipping contig chr1_KI270709v1_random because it is not in the fragments file
Skipping contig chr1_KI270710v1_random because it is not in the fragments file
Skipping contig chr1_KI270711v1_random because it is not in the fragments file
Skipping contig chr1_KI270712v1_random because it is not in the fragments file
Skipping contig chr1_KI270713v1_random because it is not in the fragments file
Skipping contig chr1_KI270714v1_random because it is not in the fragments file
Skipping contig chr1_KI270759v1_alt because it is not in the fragments file
Skipping contig chr1_KI270760v1_alt because it is not in the fragments file
Skipping contig chr1_KI270761v1_alt because it is not in the fragments file
Skipping contig chr1_KI270762v1_alt because it is not in the fragments file
Skipping contig chr1_KI270763v1_alt because it is not in the fragments file
Skipping contig chr1_KI270764v1_alt because it is not in the fragments file
Skipping contig chr1_KI270765v1_alt because it is not in the fragments file
Skipping contig chr1_KI270766v1_alt because it is not in the fragments file
Skipping contig chr1_KI270892v1_alt because it is not in the fragments file
Processing contig chr2
Processing contig chr20
Skipping contig chr20_GL383577v2_alt because it is not in the fragments file
Skipping contig chr20_KI270869v1_alt because it is not in the fragments file
Skipping contig chr20_KI270870v1_alt because it is not in the fragments file
Skipping contig chr20_KI270871v1_alt because it is not in the fragments file
Processing contig chr21
Skipping contig chr21_GL383578v2_alt because it is not in the fragments file
Skipping contig chr21_GL383579v2_alt because it is not in the fragments file
Skipping contig chr21_GL383580v2_alt because it is not in the fragments file
Skipping contig chr21_GL383581v2_alt because it is not in the fragments file
Skipping contig chr21_KI270872v1_alt because it is not in the fragments file
Skipping contig chr21_KI270873v1_alt because it is not in the fragments file
Skipping contig chr21_KI270874v1_alt because it is not in the fragments file
Processing contig chr22
Skipping contig chr22_GL383582v2_alt because it is not in the fragments file
Skipping contig chr22_GL383583v2_alt because it is not in the fragments file
Skipping contig chr22_KB663609v1_alt because it is not in the fragments file
Skipping contig chr22_KI270731v1_random because it is not in the fragments file
Skipping contig chr22_KI270732v1_random because it is not in the fragments file
Skipping contig chr22_KI270733v1_random because it is not in the fragments file
Skipping contig chr22_KI270734v1_random because it is not in the fragments file
Skipping contig chr22_KI270735v1_random because it is not in the fragments file
Skipping contig chr22_KI270736v1_random because it is not in the fragments file
Skipping contig chr22_KI270737v1_random because it is not in the fragments file
Skipping contig chr22_KI270738v1_random because it is not in the fragments file
Skipping contig chr22_KI270739v1_random because it is not in the fragments file
Skipping contig chr22_KI270875v1_alt because it is not in the fragments file
Skipping contig chr22_KI270876v1_alt because it is not in the fragments file
Skipping contig chr22_KI270877v1_alt because it is not in the fragments file
Skipping contig chr22_KI270878v1_alt because it is not in the fragments file
Skipping contig chr22_KI270879v1_alt because it is not in the fragments file
Skipping contig chr22_KI270928v1_alt because it is not in the fragments file
Skipping contig chr2_GL383521v1_alt because it is not in the fragments file
Skipping contig chr2_GL383522v1_alt because it is not in the fragments file
Skipping contig chr2_GL582966v2_alt because it is not in the fragments file
Skipping contig chr2_KI270715v1_random because it is not in the fragments file
Skipping contig chr2_KI270716v1_random because it is not in the fragments file
Skipping contig chr2_KI270767v1_alt because it is not in the fragments file
Skipping contig chr2_KI270768v1_alt because it is not in the fragments file
Skipping contig chr2_KI270769v1_alt because it is not in the fragments file
Skipping contig chr2_KI270770v1_alt because it is not in the fragments file
Skipping contig chr2_KI270771v1_alt because it is not in the fragments file
Skipping contig chr2_KI270772v1_alt because it is not in the fragments file
Skipping contig chr2_KI270773v1_alt because it is not in the fragments file
Skipping contig chr2_KI270774v1_alt because it is not in the fragments file
Skipping contig chr2_KI270775v1_alt because it is not in the fragments file
Skipping contig chr2_KI270776v1_alt because it is not in the fragments file
Skipping contig chr2_KI270893v1_alt because it is not in the fragments file
Skipping contig chr2_KI270894v1_alt because it is not in the fragments file
Processing contig chr3
Skipping contig chr3_GL000221v1_random because it is not in the fragments file
Skipping contig chr3_GL383526v1_alt because it is not in the fragments file
Skipping contig chr3_JH636055v2_alt because it is not in the fragments file
Skipping contig chr3_KI270777v1_alt because it is not in the fragments file
Skipping contig chr3_KI270778v1_alt because it is not in the fragments file
Skipping contig chr3_KI270779v1_alt because it is not in the fragments file
Skipping contig chr3_KI270780v1_alt because it is not in the fragments file
Skipping contig chr3_KI270781v1_alt because it is not in the fragments file
Skipping contig chr3_KI270782v1_alt because it is not in the fragments file
Skipping contig chr3_KI270783v1_alt because it is not in the fragments file
Skipping contig chr3_KI270784v1_alt because it is not in the fragments file
Skipping contig chr3_KI270895v1_alt because it is not in the fragments file
Skipping contig chr3_KI270924v1_alt because it is not in the fragments file
Skipping contig chr3_KI270934v1_alt because it is not in the fragments file
Skipping contig chr3_KI270935v1_alt because it is not in the fragments file
Skipping contig chr3_KI270936v1_alt because it is not in the fragments file
Skipping contig chr3_KI270937v1_alt because it is not in the fragments file
Processing contig chr4
Skipping contig chr4_GL000008v2_random because it is not in the fragments file
Skipping contig chr4_GL000257v2_alt because it is not in the fragments file
Skipping contig chr4_GL383527v1_alt because it is not in the fragments file
Skipping contig chr4_GL383528v1_alt because it is not in the fragments file
Skipping contig chr4_KI270785v1_alt because it is not in the fragments file
Skipping contig chr4_KI270786v1_alt because it is not in the fragments file
Skipping contig chr4_KI270787v1_alt because it is not in the fragments file
Skipping contig chr4_KI270788v1_alt because it is not in the fragments file
Skipping contig chr4_KI270789v1_alt because it is not in the fragments file
Skipping contig chr4_KI270790v1_alt because it is not in the fragments file
Skipping contig chr4_KI270896v1_alt because it is not in the fragments file
Skipping contig chr4_KI270925v1_alt because it is not in the fragments file
Processing contig chr5
Skipping contig chr5_GL000208v1_random because it is not in the fragments file
Skipping contig chr5_GL339449v2_alt because it is not in the fragments file
Skipping contig chr5_GL383530v1_alt because it is not in the fragments file
Skipping contig chr5_GL383531v1_alt because it is not in the fragments file
Skipping contig chr5_GL383532v1_alt because it is not in the fragments file
Skipping contig chr5_GL949742v1_alt because it is not in the fragments file
Skipping contig chr5_KI270791v1_alt because it is not in the fragments file
Skipping contig chr5_KI270792v1_alt because it is not in the fragments file
Skipping contig chr5_KI270793v1_alt because it is not in the fragments file
Skipping contig chr5_KI270794v1_alt because it is not in the fragments file
Skipping contig chr5_KI270795v1_alt because it is not in the fragments file
Skipping contig chr5_KI270796v1_alt because it is not in the fragments file
Skipping contig chr5_KI270897v1_alt because it is not in the fragments file
Skipping contig chr5_KI270898v1_alt because it is not in the fragments file
Processing contig chr6
Skipping contig chr6_GL000250v2_alt because it is not in the fragments file
Skipping contig chr6_GL000251v2_alt because it is not in the fragments file
Skipping contig chr6_GL000252v2_alt because it is not in the fragments file
Skipping contig chr6_GL000253v2_alt because it is not in the fragments file
Skipping contig chr6_GL000254v2_alt because it is not in the fragments file

In [1]:
!scatac_fragment_tools split \
    -f /projects/0/einf2548/cruiz/dmg/notebooks/scATAC/data/Mannens2024/sample_to_fragment.tsv \
    -b /projects/0/einf2548/cruiz/dmg/notebooks/scATAC/data/Mannens2024/cell_type_to_cell_barcode.tsv \
    -c /projects/0/einf2548/cruiz/hg38.chrom.sizes \
    -o /projects/0/einf2548/cruiz/dmg/notebooks/scATAC/pycistopic_fetal/pseudobulk_bed_files \
    -n 32 \
    -v

Splitting fragments ...
Processing contig chr1
Processing contig chr10
Skipping contig chr10_GL383545v1_alt because it is not in the fragments file
Skipping contig chr10_GL383546v1_alt because it is not in the fragments file
Skipping contig chr10_KI270824v1_alt because it is not in the fragments file
Skipping contig chr10_KI270825v1_alt because it is not in the fragments file
Processing contig chr11
Skipping contig chr11_GL383547v1_alt because it is not in the fragments file
Skipping contig chr11_JH159136v1_alt because it is not in the fragments file
Skipping contig chr11_JH159137v1_alt because it is not in the fragments file
Skipping contig chr11_KI270721v1_random because it is not in the fragments file
Skipping contig chr11_KI270826v1_alt because it is not in the fragments file
Skipping contig chr11_KI270827v1_alt because it is not in the fragments file
Skipping contig chr11_KI270829v1_alt because it is not in the fragments file
Skipping contig chr11_KI270830v1_alt because it is not in the fragments file
Skipping contig chr11_KI270831v1_alt because it is not in the fragments file
Skipping contig chr11_KI270832v1_alt because it is not in the fragments file
Skipping contig chr11_KI270902v1_alt because it is not in the fragments file
Skipping contig chr11_KI270903v1_alt because it is not in the fragments file
Skipping contig chr11_KI270927v1_alt because it is not in the fragments file
Processing contig chr12
Skipping contig chr12_GL383549v1_alt because it is not in the fragments file
Skipping contig chr12_GL383550v2_alt because it is not in the fragments file
Skipping contig chr12_GL383551v1_alt because it is not in the fragments file
Skipping contig chr12_GL383552v1_alt because it is not in the fragments file
Skipping contig chr12_GL383553v2_alt because it is not in the fragments file
Skipping contig chr12_GL877875v1_alt because it is not in the fragments file
Skipping contig chr12_GL877876v1_alt because it is not in the fragments file
Skipping contig chr12_KI270833v1_alt because it is not in the fragments file
Skipping contig chr12_KI270834v1_alt because it is not in the fragments file
Skipping contig chr12_KI270835v1_alt because it is not in the fragments file
Skipping contig chr12_KI270836v1_alt because it is not in the fragments file
Skipping contig chr12_KI270837v1_alt because it is not in the fragments file
Skipping contig chr12_KI270904v1_alt because it is not in the fragments file
Processing contig chr13
Skipping contig chr13_KI270838v1_alt because it is not in the fragments file
Skipping contig chr13_KI270839v1_alt because it is not in the fragments file
Skipping contig chr13_KI270840v1_alt because it is not in the fragments file
Skipping contig chr13_KI270841v1_alt because it is not in the fragments file
Skipping contig chr13_KI270842v1_alt because it is not in the fragments file
Skipping contig chr13_KI270843v1_alt because it is not in the fragments file
Processing contig chr14
Processing contig chr14_GL000009v2_random
Processing contig chr14_GL000194v1_random
Processing contig chr14_GL000225v1_random
Skipping contig chr14_KI270722v1_random because it is not in the fragments file
Skipping contig chr14_KI270723v1_random because it is not in the fragments file
Skipping contig chr14_KI270724v1_random because it is not in the fragments file
Skipping contig chr14_KI270725v1_random because it is not in the fragments file
Skipping contig chr14_KI270726v1_random because it is not in the fragments file
Skipping contig chr14_KI270844v1_alt because it is not in the fragments file
Skipping contig chr14_KI270845v1_alt because it is not in the fragments file
Skipping contig chr14_KI270846v1_alt because it is not in the fragments file
Skipping contig chr14_KI270847v1_alt because it is not in the fragments file
Processing contig chr15
Skipping contig chr15_GL383554v1_alt because it is not in the fragments file
Skipping contig chr15_GL383555v2_alt because it is not in the fragments file
Skipping contig chr15_KI270727v1_random because it is not in the fragments file
Skipping contig chr15_KI270848v1_alt because it is not in the fragments file
Skipping contig chr15_KI270849v1_alt because it is not in the fragments file
Skipping contig chr15_KI270850v1_alt because it is not in the fragments file
Skipping contig chr15_KI270851v1_alt because it is not in the fragments file
Skipping contig chr15_KI270852v1_alt because it is not in the fragments file
Skipping contig chr15_KI270905v1_alt because it is not in the fragments file
Skipping contig chr15_KI270906v1_alt because it is not in the fragments file
Processing contig chr16
Skipping contig chr16_GL383556v1_alt because it is not in the fragments file
Skipping contig chr16_GL383557v1_alt because it is not in the fragments file
Skipping contig chr16_KI270728v1_random because it is not in the fragments file
Skipping contig chr16_KI270853v1_alt because it is not in the fragments file
Skipping contig chr16_KI270854v1_alt because it is not in the fragments file
Skipping contig chr16_KI270855v1_alt because it is not in the fragments file
Skipping contig chr16_KI270856v1_alt because it is not in the fragments file
Processing contig chr17
Skipping contig chr17_GL000205v2_random because it is not in the fragments file
Skipping contig chr17_GL000258v2_alt because it is not in the fragments file
Skipping contig chr17_GL383563v3_alt because it is not in the fragments file
Skipping contig chr17_GL383564v2_alt because it is not in the fragments file
Skipping contig chr17_GL383565v1_alt because it is not in the fragments file
Skipping contig chr17_GL383566v1_alt because it is not in the fragments file
Skipping contig chr17_JH159146v1_alt because it is not in the fragments file
Skipping contig chr17_JH159147v1_alt because it is not in the fragments file
Skipping contig chr17_JH159148v1_alt because it is not in the fragments file
Skipping contig chr17_KI270729v1_random because it is not in the fragments file
Skipping contig chr17_KI270730v1_random because it is not in the fragments file
Skipping contig chr17_KI270857v1_alt because it is not in the fragments file
Skipping contig chr17_KI270858v1_alt because it is not in the fragments file
Skipping contig chr17_KI270859v1_alt because it is not in the fragments file
Skipping contig chr17_KI270860v1_alt because it is not in the fragments file
Skipping contig chr17_KI270861v1_alt because it is not in the fragments file
Skipping contig chr17_KI270862v1_alt because it is not in the fragments file
Skipping contig chr17_KI270907v1_alt because it is not in the fragments file
Skipping contig chr17_KI270908v1_alt because it is not in the fragments file
Skipping contig chr17_KI270909v1_alt because it is not in the fragments file
Skipping contig chr17_KI270910v1_alt because it is not in the fragments file
Processing contig chr18
Skipping contig chr18_GL383567v1_alt because it is not in the fragments file
Skipping contig chr18_GL383568v1_alt because it is not in the fragments file
Skipping contig chr18_GL383569v1_alt because it is not in the fragments file
Skipping contig chr18_GL383570v1_alt because it is not in the fragments file
Skipping contig chr18_GL383571v1_alt because it is not in the fragments file
Skipping contig chr18_GL383572v1_alt because it is not in the fragments file
Skipping contig chr18_KI270863v1_alt because it is not in the fragments file
Skipping contig chr18_KI270864v1_alt because it is not in the fragments file
Skipping contig chr18_KI270911v1_alt because it is not in the fragments file
Skipping contig chr18_KI270912v1_alt because it is not in the fragments file
Processing contig chr19
Skipping contig chr19_GL000209v2_alt because it is not in the fragments file
Skipping contig chr19_GL383573v1_alt because it is not in the fragments file
Skipping contig chr19_GL383574v1_alt because it is not in the fragments file
Skipping contig chr19_GL383575v2_alt because it is not in the fragments file
Skipping contig chr19_GL383576v1_alt because it is not in the fragments file
Skipping contig chr19_GL949746v1_alt because it is not in the fragments file
Skipping contig chr19_GL949747v2_alt because it is not in the fragments file
Skipping contig chr19_GL949748v2_alt because it is not in the fragments file
Skipping contig chr19_GL949749v2_alt because it is not in the fragments file
Skipping contig chr19_GL949750v2_alt because it is not in the fragments file
Skipping contig chr19_GL949751v2_alt because it is not in the fragments file
Skipping contig chr19_GL949752v1_alt because it is not in the fragments file
Skipping contig chr19_GL949753v2_alt because it is not in the fragments file
Skipping contig chr19_KI270865v1_alt because it is not in the fragments file
Skipping contig chr19_KI270866v1_alt because it is not in the fragments file
Skipping contig chr19_KI270867v1_alt because it is not in the fragments file
Skipping contig chr19_KI270868v1_alt because it is not in the fragments file
Skipping contig chr19_KI270882v1_alt because it is not in the fragments file
Skipping contig chr19_KI270883v1_alt because it is not in the fragments file
Skipping contig chr19_KI270884v1_alt because it is not in the fragments file
Skipping contig chr19_KI270885v1_alt because it is not in the fragments file
Skipping contig chr19_KI270886v1_alt because it is not in the fragments file
Skipping contig chr19_KI270887v1_alt because it is not in the fragments file
Skipping contig chr19_KI270888v1_alt because it is not in the fragments file
Skipping contig chr19_KI270889v1_alt because it is not in the fragments file
Skipping contig chr19_KI270890v1_alt because it is not in the fragments file
Skipping contig chr19_KI270891v1_alt because it is not in the fragments file
Skipping contig chr19_KI270914v1_alt because it is not in the fragments file
Skipping contig chr19_KI270915v1_alt because it is not in the fragments file
Skipping contig chr19_KI270916v1_alt because it is not in the fragments file
Skipping contig chr19_KI270917v1_alt because it is not in the fragments file
Skipping contig chr19_KI270918v1_alt because it is not in the fragments file
Skipping contig chr19_KI270919v1_alt because it is not in the fragments file
Skipping contig chr19_KI270920v1_alt because it is not in the fragments file
Skipping contig chr19_KI270921v1_alt because it is not in the fragments file
Skipping contig chr19_KI270922v1_alt because it is not in the fragments file
Skipping contig chr19_KI270923v1_alt because it is not in the fragments file
Skipping contig chr19_KI270929v1_alt because it is not in the fragments file
Skipping contig chr19_KI270930v1_alt because it is not in the fragments file
Skipping contig chr19_KI270931v1_alt because it is not in the fragments file
Skipping contig chr19_KI270932v1_alt because it is not in the fragments file
Skipping contig chr19_KI270933v1_alt because it is not in the fragments file
Skipping contig chr19_KI270938v1_alt because it is not in the fragments file
Skipping contig chr1_GL383518v1_alt because it is not in the fragments file
Skipping contig chr1_GL383519v1_alt because it is not in the fragments file
Skipping contig chr1_GL383520v2_alt because it is not in the fragments file
Skipping contig chr1_KI270706v1_random because it is not in the fragments file
Skipping contig chr1_KI270707v1_random because it is not in the fragments file
Skipping contig chr1_KI270708v1_random because it is not in the fragments file
Skipping contig chr1_KI270709v1_random because it is not in the fragments file
Skipping contig chr1_KI270710v1_random because it is not in the fragments file
Skipping contig chr1_KI270711v1_random because it is not in the fragments file
Skipping contig chr1_KI270712v1_random because it is not in the fragments file
Skipping contig chr1_KI270713v1_random because it is not in the fragments file
Skipping contig chr1_KI270714v1_random because it is not in the fragments file
Skipping contig chr1_KI270759v1_alt because it is not in the fragments file
Skipping contig chr1_KI270760v1_alt because it is not in the fragments file
Skipping contig chr1_KI270761v1_alt because it is not in the fragments file
Skipping contig chr1_KI270762v1_alt because it is not in the fragments file
Skipping contig chr1_KI270763v1_alt because it is not in the fragments file
Skipping contig chr1_KI270764v1_alt because it is not in the fragments file
Skipping contig chr1_KI270765v1_alt because it is not in the fragments file
Skipping contig chr1_KI270766v1_alt because it is not in the fragments file
Skipping contig chr1_KI270892v1_alt because it is not in the fragments file
Processing contig chr2
Processing contig chr20
Skipping contig chr20_GL383577v2_alt because it is not in the fragments file
Skipping contig chr20_KI270869v1_alt because it is not in the fragments file
Skipping contig chr20_KI270870v1_alt because it is not in the fragments file
Skipping contig chr20_KI270871v1_alt because it is not in the fragments file
Processing contig chr21
Skipping contig chr21_GL383578v2_alt because it is not in the fragments file
Skipping contig chr21_GL383579v2_alt because it is not in the fragments file
Skipping contig chr21_GL383580v2_alt because it is not in the fragments file
Skipping contig chr21_GL383581v2_alt because it is not in the fragments file
Skipping contig chr21_KI270872v1_alt because it is not in the fragments file
Skipping contig chr21_KI270873v1_alt because it is not in the fragments file
Skipping contig chr21_KI270874v1_alt because it is not in the fragments file
Processing contig chr22
Skipping contig chr22_GL383582v2_alt because it is not in the fragments file
Skipping contig chr22_GL383583v2_alt because it is not in the fragments file
Skipping contig chr22_KB663609v1_alt because it is not in the fragments file
Skipping contig chr22_KI270731v1_random because it is not in the fragments file
Skipping contig chr22_KI270732v1_random because it is not in the fragments file
Skipping contig chr22_KI270733v1_random because it is not in the fragments file
Skipping contig chr22_KI270734v1_random because it is not in the fragments file
Skipping contig chr22_KI270735v1_random because it is not in the fragments file
Skipping contig chr22_KI270736v1_random because it is not in the fragments file
Skipping contig chr22_KI270737v1_random because it is not in the fragments file
Skipping contig chr22_KI270738v1_random because it is not in the fragments file
Skipping contig chr22_KI270739v1_random because it is not in the fragments file
Skipping contig chr22_KI270875v1_alt because it is not in the fragments file
Skipping contig chr22_KI270876v1_alt because it is not in the fragments file
Skipping contig chr22_KI270877v1_alt because it is not in the fragments file
Skipping contig chr22_KI270878v1_alt because it is not in the fragments file
Skipping contig chr22_KI270879v1_alt because it is not in the fragments file
Skipping contig chr22_KI270928v1_alt because it is not in the fragments file
Skipping contig chr2_GL383521v1_alt because it is not in the fragments file
Skipping contig chr2_GL383522v1_alt because it is not in the fragments file
Skipping contig chr2_GL582966v2_alt because it is not in the fragments file
Skipping contig chr2_KI270715v1_random because it is not in the fragments file
Skipping contig chr2_KI270716v1_random because it is not in the fragments file
Skipping contig chr2_KI270767v1_alt because it is not in the fragments file
Skipping contig chr2_KI270768v1_alt because it is not in the fragments file
Skipping contig chr2_KI270769v1_alt because it is not in the fragments file
Skipping contig chr2_KI270770v1_alt because it is not in the fragments file
Skipping contig chr2_KI270771v1_alt because it is not in the fragments file
Skipping contig chr2_KI270772v1_alt because it is not in the fragments file
Skipping contig chr2_KI270773v1_alt because it is not in the fragments file
Skipping contig chr2_KI270774v1_alt because it is not in the fragments file
Skipping contig chr2_KI270775v1_alt because it is not in the fragments file
Skipping contig chr2_KI270776v1_alt because it is not in the fragments file
Skipping contig chr2_KI270893v1_alt because it is not in the fragments file
Skipping contig chr2_KI270894v1_alt because it is not in the fragments file
Processing contig chr3
Skipping contig chr3_GL000221v1_random because it is not in the fragments file
Skipping contig chr3_GL383526v1_alt because it is not in the fragments file
Skipping contig chr3_JH636055v2_alt because it is not in the fragments file
Skipping contig chr3_KI270777v1_alt because it is not in the fragments file
Skipping contig chr3_KI270778v1_alt because it is not in the fragments file
Skipping contig chr3_KI270779v1_alt because it is not in the fragments file
Skipping contig chr3_KI270780v1_alt because it is not in the fragments file
Skipping contig chr3_KI270781v1_alt because it is not in the fragments file
Skipping contig chr3_KI270782v1_alt because it is not in the fragments file
Skipping contig chr3_KI270783v1_alt because it is not in the fragments file
Skipping contig chr3_KI270784v1_alt because it is not in the fragments file
Skipping contig chr3_KI270895v1_alt because it is not in the fragments file
Skipping contig chr3_KI270924v1_alt because it is not in the fragments file
Skipping contig chr3_KI270934v1_alt because it is not in the fragments file
Skipping contig chr3_KI270935v1_alt because it is not in the fragments file
Skipping contig chr3_KI270936v1_alt because it is not in the fragments file
Skipping contig chr3_KI270937v1_alt because it is not in the fragments file
Processing contig chr4
Skipping contig chr4_GL000008v2_random because it is not in the fragments file
Skipping contig chr4_GL000257v2_alt because it is not in the fragments file
Skipping contig chr4_GL383527v1_alt because it is not in the fragments file
Skipping contig chr4_GL383528v1_alt because it is not in the fragments file
Skipping contig chr4_KI270785v1_alt because it is not in the fragments file
Skipping contig chr4_KI270786v1_alt because it is not in the fragments file
Skipping contig chr4_KI270787v1_alt because it is not in the fragments file
Skipping contig chr4_KI270788v1_alt because it is not in the fragments file
Skipping contig chr4_KI270789v1_alt because it is not in the fragments file
Skipping contig chr4_KI270790v1_alt because it is not in the fragments file
Skipping contig chr4_KI270896v1_alt because it is not in the fragments file
Skipping contig chr4_KI270925v1_alt because it is not in the fragments file
Processing contig chr5
Skipping contig chr5_GL000208v1_random because it is not in the fragments file
Skipping contig chr5_GL339449v2_alt because it is not in the fragments file
Skipping contig chr5_GL383530v1_alt because it is not in the fragments file
Skipping contig chr5_GL383531v1_alt because it is not in the fragments file
Skipping contig chr5_GL383532v1_alt because it is not in the fragments file
Skipping contig chr5_GL949742v1_alt because it is not in the fragments file
Skipping contig chr5_KI270791v1_alt because it is not in the fragments file
Skipping contig chr5_KI270792v1_alt because it is not in the fragments file
Skipping contig chr5_KI270793v1_alt because it is not in the fragments file
Skipping contig chr5_KI270794v1_alt because it is not in the fragments file
Skipping contig chr5_KI270795v1_alt because it is not in the fragments file
Skipping contig chr5_KI270796v1_alt because it is not in the fragments file
Skipping contig chr5_KI270897v1_alt because it is not in the fragments file
Skipping contig chr5_KI270898v1_alt because it is not in the fragments file
Processing contig chr6
Skipping contig chr6_GL000250v2_alt because it is not in the fragments file
Skipping contig chr6_GL000251v2_alt because it is not in the fragments file
Skipping contig chr6_GL000252v2_alt because it is not in the fragments file
Skipping contig chr6_GL000253v2_alt because it is not in the fragments file
Skipping contig chr6_GL000254v2_alt because it is not in the fragments file