`conda activate r_4.3.3`

In [ ]:
library(ArchR)
set.seed(1)

Loading required package: ggplot2

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: GenomicRanges

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors


Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Loading required package: GenomeInfoDb

Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians


Loading required package: data.table


Attaching package: ‘data.table’


The following object is masked from ‘package:SummarizedExperiment’:

    shift


The following object is masked from ‘package:GenomicRanges’:

    shift


The following object is masked from ‘package:IRanges’:

    shift


The following objects are masked from ‘package:S4Vectors’:

    first, second


Loading required package: Matrix


Attaching package: ‘Matrix’


The following object is masked from ‘package:S4Vectors’:

    expand


Loading required package: rhdf5

Loading required package: magrittr


Attaching package: ‘magrittr’


The following object is masked from ‘package:GenomicRanges’:

    subtract

In [ ]:
library(parallel)

In [ ]:
# Configure
addArchRThreads(threads = 32)
addArchRGenome('hg38')

In [ ]:
proj <- loadArchRProject('./ArchR_malignant_FINAL/')

Successfully loaded ArchRProject!


                                                   / |
                                                 /    \
            .                                  /      |.
            \\\                              /        |.
              \\\                          /           `|.
                \\\                      /              |.
                  \                    /                |\
                  \\#####\           /                  ||
                ==###########>      /                   ||
                 \\##==......\    /                     ||
            ______ =       =|__ /__                     ||      \\\
        ,--' ,----`-,__ ___/'  --,-`-===================##========>
       \               '        ##_______ _____ ,--,__,=##,__   ///
        ,    __==    ___,-,__,--'#'  ==='      `-'    | ##,-/
        -,____,---'       \\####\\________________,--\\_##,/
           ___      .______        ______  __    __  .______
          /   \     |   _  \      /      ||  |  |  | |   _  \
         /  ^  \    |  |_)  |    |  ,----'|  |__|  | |  |_)  |
        /  /_\  \   |      /     |  |     |   __   | |      /
       /  _____  \  |  |\  \\___ |  `----.|  |  |  | |  |\  \\___.
      /__/     \__\ | _| `._____| \______||__|  |__| | _| `._____|

In [ ]:
# SVD, Clustering, UMAP
proj <- addIterativeLSI(ArchRProj = proj, useMatrix = "TileMatrix",
                       name = "IterativeLSI", force=TRUE)

Checking Inputs...

ArchR logging to : ArchRLogs/ArchR-addIterativeLSI-3f9ce54060e437-Date-2024-08-22_Time-13-56-28.067311.log
If there is an issue, please report to github with logFile!

2024-08-22 13:56:29.607439 : Computing Total Across All Features, 0.009 mins elapsed.

2024-08-22 13:56:42.771481 : Computing Top Features, 0.229 mins elapsed.

###########
2024-08-22 13:56:43.741347 : Running LSI (1 of 2) on Top Features, 0.245 mins elapsed.
###########

2024-08-22 13:56:43.82685 : Sampling Cells (N = 10013) for Estimated LSI, 0.246 mins elapsed.

2024-08-22 13:56:43.829701 : Creating Sampled Partial Matrix, 0.247 mins elapsed.

2024-08-22 13:56:57.121918 : Computing Estimated LSI (projectAll = FALSE), 0.468 mins elapsed.

2024-08-22 13:57:10.521924 : Identifying Clusters, 0.691 mins elapsed.

Warning message:
“Data is of class matrix. Coercing to dgCMatrix.”
2024-08-22 13:57:24.379517 : Identified 6 Clusters, 0.922 mins elapsed.

2024-08-22 13:57:24.398614 : Saving LSI Iteration, 0.923 mins elapsed.

Length of unique values greater than palette, interpolating..

************************************************************
2024-08-22 13:57:32.33926 : ERROR Found in .saveIteration for
LogFile = ArchRLogs/ArchR-addIterativeLSI-3f9ce54060e437-Date-2024-08-22_Time-13-56-28.067311.log

<simpleError in g$grobs[[legend]]: no such index at level 2
>

************************************************************

2024-08-22 13:57:32.345893 : Creating Cluster Matrix on the total Group Features, 1.055 mins elapsed.

2024-08-22 13:57:45.947261 : Computing Variable Features, 1.282 mins elapsed.

###########
2024-08-22 13:57:46.102574 : Running LSI (2 of 2) on Variable Features, 1.284 mins elapsed.
###########

2024-08-22 13:57:46.141373 : Creating Partial Matrix, 1.285 mins elapsed.

2024-08-22 13:58:23.570467 : Computing LSI, 1.909 mins elapsed.

2024-08-22 13:59:06.872426 : Finished Running IterativeLSI, 2.631 mins elapsed.

In [ ]:
# Gene scores with selected features
# Artificial black list to exclude all non variable features
chrs <- getChromSizes(proj)
var_features <- proj@reducedDims[["IterativeLSI"]]$LSIFeatures
var_features_gr <- GRanges(var_features$seqnames, IRanges(var_features$start, var_features$start + 500))
blacklist <- setdiff(chrs, var_features_gr)
proj <- addGeneScoreMatrix(proj, matrixName='GeneScoreMatrix', force=TRUE, blacklist=blacklist)

ArchR logging to : ArchRLogs/ArchR-addGeneScoreMatrix-3f9ce527a8227-Date-2024-08-22_Time-13-59-07.034844.log
If there is an issue, please report to github with logFile!

2024-08-22 13:59:07.346603 : Batch Execution w/ safelapply!, 0 mins elapsed.

ArchR logging successful to : ArchRLogs/ArchR-addGeneScoreMatrix-3f9ce527a8227-Date-2024-08-22_Time-13-59-07.034844.log

In [ ]:
# Peaks using NFR fragments
proj <- addClusters(input = proj, reducedDims = "IterativeLSI", force = TRUE)
proj <- addGroupCoverages(proj, maxFragmentLength=147, force = TRUE)

ArchR logging to : ArchRLogs/ArchR-addClusters-2adf55a04cbb-Date-2024-08-22_Time-14-20-40.539781.log
If there is an issue, please report to github with logFile!

Overriding previous entry for Clusters

2024-08-22 14:20:44.882398 : Running Seurats FindClusters (Stuart et al. Cell 2019), 0.068 mins elapsed.

Warning message:
“Data is of class matrix. Coercing to dgCMatrix.”
Computing nearest neighbor graph

Computing SNN

Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 83921
Number of edges: 3096803

Running Louvain algorithm...
Maximum modularity in 10 random starts: 0.9444
Number of communities: 49
Elapsed time: 15 seconds

20 singletons identified. 29 final clusters.

2024-08-22 14:22:28.673632 : Testing Biased Clusters, 1.798 mins elapsed.

2024-08-22 14:22:29.219011 : Testing Outlier Clusters, 1.807 mins elapsed.

2024-08-22 14:22:29.226612 : Identified more clusters than maxClusters allowed (n = 0). Merging clusters to maxClusters (n = 25).
If this is not desired set maxClusters = NULL!, 1.808 mins elapsed.

2024-08-22 14:22:29.288585 : Assigning Cluster Names to 25 Clusters, 1.809 mins elapsed.

2024-08-22 14:22:29.744345 : Finished addClusters, 1.816 mins elapsed.

ArchR logging to : ArchRLogs/ArchR-addGroupCoverages-2adf57e38238-Date-2024-08-22_Time-14-22-29.750371.log
If there is an issue, please report to github with logFile!

C1 (1 of 25) : CellGroups N = 2

C2 (2 of 25) : CellGroups N = 2

C3 (3 of 25) : CellGroups N = 2

C4 (4 of 25) : CellGroups N = 2

C5 (5 of 25) : CellGroups N = 2

C6 (6 of 25) : CellGroups N = 2

C7 (7 of 25) : CellGroups N = 2

C8 (8 of 25) : CellGroups N = 3

C9 (9 of 25) : CellGroups N = 2

C10 (10 of 25) : CellGroups N = 2

C11 (11 of 25) : CellGroups N = 2

C12 (12 of 25) : CellGroups N = 5

C13 (13 of 25) : CellGroups N = 5

C14 (14 of 25) : CellGroups N = 3

C15 (15 of 25) : CellGroups N = 2

C16 (16 of 25) : CellGroups N = 5

C17 (17 of 25) : CellGroups N = 2

C18 (18 of 25) : CellGroups N = 3

C19 (19 of 25) : CellGroups N = 2

C20 (20 of 25) : CellGroups N = 2

C21 (21 of 25) : CellGroups N = 2

C22 (22 of 25) : CellGroups N = 2

C23 (23 of 25) : CellGroups N = 2

C24 (24 of 25) : CellGroups N = 4

C25 (25 of 25) : CellGroups N = 2

2024-08-22 14:22:49.817195 : Creating Coverage Files!, 0.334 mins elapsed.

2024-08-22 14:22:49.819994 : Batch Execution w/ safelapply!, 0.334 mins elapsed.

2024-08-22 14:44:58.823478 : Adding Kmer Bias to Coverage Files!, 22.485 mins elapsed.

Completed Kmer Bias Calculation

Adding Kmer Bias (1 of 64)

Adding Kmer Bias (2 of 64)

Adding Kmer Bias (3 of 64)

Adding Kmer Bias (4 of 64)

Adding Kmer Bias (5 of 64)

Adding Kmer Bias (6 of 64)

Adding Kmer Bias (7 of 64)

Adding Kmer Bias (8 of 64)

Adding Kmer Bias (9 of 64)

Adding Kmer Bias (10 of 64)

Adding Kmer Bias (11 of 64)

Adding Kmer Bias (12 of 64)

Adding Kmer Bias (13 of 64)

Adding Kmer Bias (14 of 64)

Adding Kmer Bias (15 of 64)

Adding Kmer Bias (16 of 64)

Adding Kmer Bias (17 of 64)

Adding Kmer Bias (18 of 64)

Adding Kmer Bias (19 of 64)

Adding Kmer Bias (20 of 64)

Adding Kmer Bias (21 of 64)

Adding Kmer Bias (22 of 64)

Adding Kmer Bias (23 of 64)

Adding Kmer Bias (24 of 64)

Adding Kmer Bias (25 of 64)

Adding Kmer Bias (26 of 64)

Adding Kmer Bias (27 of 64)

Adding Kmer Bias (28 of 64)

Adding Kmer Bias (29 of 64)

Adding Kmer Bias (30 of 64)

Adding Kmer Bias (31 of 64)

Adding Kmer Bias (32 of 64)

Adding Kmer Bias (33 of 64)

Adding Kmer Bias (34 of 64)

Adding Kmer Bias (35 of 64)

Adding Kmer Bias (36 of 64)

Adding Kmer Bias (37 of 64)

Adding Kmer Bias (38 of 64)

Adding Kmer Bias (39 of 64)

Adding Kmer Bias (40 of 64)

Adding Kmer Bias (41 of 64)

Adding Kmer Bias (42 of 64)

Adding Kmer Bias (43 of 64)

Adding Kmer Bias (44 of 64)

Adding Kmer Bias (45 of 64)

Adding Kmer Bias (46 of 64)

Adding Kmer Bias (47 of 64)

Adding Kmer Bias (48 of 64)

Adding Kmer Bias (49 of 64)

Adding Kmer Bias (50 of 64)

Adding Kmer Bias (51 of 64)

Adding Kmer Bias (52 of 64)

Adding Kmer Bias (53 of 64)

Adding Kmer Bias (54 of 64)

Adding Kmer Bias (55 of 64)

Adding Kmer Bias (56 of 64)

Adding Kmer Bias (57 of 64)

Adding Kmer Bias (58 of 64)

Adding Kmer Bias (59 of 64)

Adding Kmer Bias (60 of 64)

Adding Kmer Bias (61 of 64)

Adding Kmer Bias (62 of 64)

Adding Kmer Bias (63 of 64)

Adding Kmer Bias (64 of 64)

2024-08-22 14:56:50.015394 : Finished Creation of Coverage Files!, 34.338 mins elapsed.

ArchR logging successful to : ArchRLogs/ArchR-addGroupCoverages-2adf57e38238-Date-2024-08-22_Time-14-22-29.750371.log

In [ ]:
pathToMacs2 <- '/hpc/pmc_stunnenberg/cruiz/miniconda3/envs/python2/bin/macs2'
proj <- addReproduciblePeakSet(proj, pathToMacs2 = pathToMacs2, plot = FALSE)
# Counts
proj <- addPeakMatrix(proj, maxFragmentLength=147, ceiling=10^9)

ArchR logging to : ArchRLogs/ArchR-addReproduciblePeakSet-2adf6e0eef78-Date-2024-08-22_Time-15-36-38.114949.log
If there is an issue, please report to github with logFile!

Calling Peaks with Macs2

2024-08-22 15:36:38.349465 : Peak Calling Parameters!, 0.004 mins elapsed.

    Group nCells nCellsUsed nReplicates nMin nMax maxPeaks
C1     C1   3815        551           2   51  500   150000
C2     C2     37         34           2   21   24    17000
C3     C3   1677        565           2   65  500   150000
C4     C4   1831        540           2   40  500   150000
C5     C5   2076        540           2   40  500   150000
C6     C6    882        540           2   40  500   150000
C7     C7   1841        540           2   40  500   150000
C8     C8   1140        684           3   89  500   150000
C9     C9    924        540           2   40  500   150000
C10   C10  16809        542           2   42  500   150000
C11   C11    936        540           2   40  500   150000
C12   C12   2541       1917           5  230  463   150000
C13   C13  12543       1720           5  109  500   150000
C14   C14    817        677           3   43  500   150000
C15   C15   1303        540           2   40  500   150000
C16   C16   5600       1365           5   79  500   150000
C17   C17    725        540           2   40  500   150000
C18   C18   5580        642           3   54  500   150000
C19   C19    233        233           2   40  193   116500
C20   C20   1045        578           2   78  500   150000
C21   C21   5697        553           2   53  500   150000
C22   C22   3846        548           2   48  500   150000
C23   C23    217        217           2   40  177   108500
C24   C24   7610        744           4   50  500   150000
C25   C25   4196        540           2   40  500   150000

2024-08-22 15:36:38.361624 : Batching Peak Calls!, 0.004 mins elapsed.

2024-08-22 15:36:38.392397 : Batch Execution w/ safelapply!, 0 mins elapsed.

2024-08-22 16:04:50.049873 : Identifying Reproducible Peaks!, 28.199 mins elapsed.

2024-08-22 16:05:45.677058 : Creating Union Peak Set!, 29.126 mins elapsed.

Converged after 10 iterations!

2024-08-22 16:05:52.310374 : Finished Creating Union Peak Set (377577)!, 29.237 mins elapsed.

ArchR logging to : ArchRLogs/ArchR-addPeakMatrix-2adf2d4fc40e-Date-2024-08-22_Time-16-05-52.317007.log
If there is an issue, please report to github with logFile!

2024-08-22 16:05:52.749644 : Batch Execution w/ safelapply!, 0 mins elapsed.

ArchR logging successful to : ArchRLogs/ArchR-addPeakMatrix-2adf2d4fc40e-Date-2024-08-22_Time-16-05-52.317007.log

In [ ]:
meta <- readRDS('metadata_mp.rds')

# Define the pattern and replacement
pattern <- "(.*)_(.*)$"
replacement <- "\\1#\\2"

# Apply the pattern and replacement using sub
rownames(meta) <- sub(pattern, replacement, rownames(meta))
meta

                                           total  duplicate chimeric unmapped
atac_T19-91014#AAACGAAAGACCCTAT-1           37892 15065      1        438
atac_T19-91014#AAACGAAAGTGTAATG-1           27213  9888      2        323
atac_T19-91014#AAACGAACAAATGCTC-1           32533  8763      0        352
atac_T19-91014#AAACGAACACGCCGAT-1           17835  5161      3        213
atac_T19-91014#AAACGAAGTACGGAGT-1           66244 12557      6        786
atac_T19-91014#AAACGAAGTATCCCTC-1           20966  4675      1        164
atac_T19-91014#AAACGAAGTATCTCAG-1           40695 10281      2        501
atac_T19-91014#AAACGAAGTCAGACGA-1           10269  1979      1        139
atac_T19-91014#AAACGAAGTGAAACAT-1           24766 10011      1        283
atac_T19-91014#AAACGAATCGATGTAC-1           47801 14673      3        458
atac_T19-91014#AAACTCGAGAGAATTC-1           16882  3724      1        213
atac_T19-91014#AAACTCGAGTGTCCCG-1           76434 18632     36        899
atac_T19-91014#AAACTCGCAACGTAGG-1           55655 16261      5        706
atac_T19-91014#AAACTCGCACGCTGTG-1           18795  4639      0        315
atac_T19-91014#AAACTCGCAGAACAGC-1           26137  7734      5        309
atac_T19-91014#AAACTCGGTAAACGTA-1           47269 14885      5        560
atac_T19-91014#AAACTCGGTAGCATGG-1           47913 12557      6        649
atac_T19-91014#AAACTCGTCCATGACA-1          118170 40251     12       1293
atac_T19-91014#AAACTCGTCTGCGTCT-1           25872 10515      0        333
atac_T19-91014#AAACTGCAGGAGTACC-1          101848 23566     10        980
atac_T19-91014#AAACTGCAGGCGCTTC-1           89931 11359     20        921
atac_T19-91014#AAACTGCAGTAGTGTA-1           36335 14061      1        421
atac_T19-91014#AAACTGCAGTCGTATC-1           19222  3870      0        217
atac_T19-91014#AAACTGCAGTTCGACT-1           21204  5422      3        281
atac_T19-91014#AAACTGCCAGAACAGC-1           39908 11058      4        395
atac_T19-91014#AAACTGCCATTAGCCA-1           34351 10415      4        431
atac_T19-91014#AAACTGCGTACGGTTT-1           42421 13668      7        471
atac_T19-91014#AAACTGCGTAGCCATT-1           21657  6009      1        286
atac_T19-91014#AAACTGCGTAGCGGTA-1           42602 11041     12        518
atac_T19-91014#AAACTGCGTCAAATCC-1           26815  6811      0        272
⋮                                          ⋮      ⋮         ⋮        ⋮
multiome_P-6774_S-10146#TTTGGTAAGCCTGATG-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGGTAAGGATTGAG-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGGTAAGGGTGGAT-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGGTAAGTTGTCCC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGGTGCAACTGGCT-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGGTGCACATACTG-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGGTGCACTTCATC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGGTGCAGCAATAA-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTCCCAACCCTCC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTCCCACTAAATC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTCCCATGGCCCA-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTCTAGGAGTCTT-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTCTAGGCAACAA-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTGAAGATGGAGC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTGAAGCCGCAGT-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTGAAGTTAGCTA-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTGGCAAGGAATC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTGGCAAGGTACG-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTGGCACCTCGCT-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTGGCACGTAATT-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTGGCACTTGTTC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTGGCAGCAAATA-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTGGCAGCAACAG-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTGGCATGCTATG-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTGGCATTATGAC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTGTTCCTAGTAA-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTTGGTAGGATTT-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTTGGTTGGATAT-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTTGGTTGTAACG-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTTGTTGGTTTATCGC-1 NaN    NaN       NaN      NaN
                                           lowmapq mitochondrial nonprimary
atac_T19-91014#AAACGAAAGACCCTAT-1           3127    45             5
atac_T19-91014#AAACGAAAGTGTAATG-1           2030    71             9
atac_T19-91014#AAACGAACAAATGCTC-1           2536   206            14
atac_T19-91014#AAACGAACACGCCGAT-1           1943    74            16
atac_T19-91014#AAACGAAGTACGGAGT-1           6822    55            33
atac_T19-91014#AAACGAAGTATCCCTC-1           1312    11             0
atac_T19-91014#AAACGAAGTATCTCAG-1           4589    47            57
atac_T19-91014#AAACGAAGTCAGACGA-1            857     2             2
atac_T19-91014#AAACGAAGTGAAACAT-1           2095   210            10
atac_T19-91014#AAACGAATCGATGTAC-1           2818    21             4
atac_T19-91014#AAACTCGAGAGAATTC-1           2541    17             6
atac_T19-91014#AAACTCGAGTGTCCCG-1          11817    44           146
atac_T19-91014#AAACTCGCAACGTAGG-1           3740     4            20
atac_T19-91014#AAACTCGCACGCTGTG-1           1308     1             5
atac_T19-91014#AAACTCGCAGAACAGC-1           2425     9            13
atac_T19-91014#AAACTCGGTAAACGTA-1           3728    65            16
atac_T19-91014#AAACTCGGTAGCATGG-1           2849     7             8
atac_T19-91014#AAACTCGTCCATGACA-1          12048   122           293
atac_T19-91014#AAACTCGTCTGCGTCT-1           1948    62            22
atac_T19-91014#AAACTGCAGGAGTACC-1          12115    97            65
atac_T19-91014#AAACTGCAGGCGCTTC-1           9778   151            77
atac_T19-91014#AAACTGCAGTAGTGTA-1           3509    52            34
atac_T19-91014#AAACTGCAGTCGTATC-1           1352    29             7
atac_T19-91014#AAACTGCAGTTCGACT-1           1913   150             3
atac_T19-91014#AAACTGCCAGAACAGC-1           2516    12            10
atac_T19-91014#AAACTGCCATTAGCCA-1           2966   268            50
atac_T19-91014#AAACTGCGTACGGTTT-1           2890     7             8
atac_T19-91014#AAACTGCGTAGCCATT-1           1985    16            10
atac_T19-91014#AAACTGCGTAGCGGTA-1           4266   146             5
atac_T19-91014#AAACTGCGTCAAATCC-1           2088    87             6
⋮                                          ⋮       ⋮             ⋮
multiome_P-6774_S-10146#TTTGGTAAGCCTGATG-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGGTAAGGATTGAG-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGGTAAGGGTGGAT-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGGTAAGTTGTCCC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGGTGCAACTGGCT-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGGTGCACATACTG-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGGTGCACTTCATC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGGTGCAGCAATAA-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTCCCAACCCTCC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTCCCACTAAATC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTCCCATGGCCCA-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTCTAGGAGTCTT-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTCTAGGCAACAA-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTGAAGATGGAGC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTGAAGCCGCAGT-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTGAAGTTAGCTA-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTGGCAAGGAATC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTGGCAAGGTACG-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTGGCACCTCGCT-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTGGCACGTAATT-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTGGCACTTGTTC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTGGCAGCAAATA-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTGGCAGCAACAG-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTGGCATGCTATG-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTGGCATTATGAC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTGTTCCTAGTAA-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTTGGTAGGATTT-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTTGGTTGGATAT-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTTGGTTGTAACG-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTTGTTGGTTTATCGC-1 NaN     NaN           NaN
                                           passed_filters is__cell_barcode
atac_T19-91014#AAACGAAAGACCCTAT-1          19211          1
atac_T19-91014#AAACGAAAGTGTAATG-1          14890          1
atac_T19-91014#AAACGAACAAATGCTC-1          20662          1
atac_T19-91014#AAACGAACACGCCGAT-1          10425          1
atac_T19-91014#AAACGAAGTACGGAGT-1          45985          1
atac_T19-91014#AAACGAAGTATCCCTC-1          14803          1
atac_T19-91014#AAACGAAGTATCTCAG-1          25218          1
atac_T19-91014#AAACGAAGTCAGACGA-1           7289          1
atac_T19-91014#AAACGAAGTGAAACAT-1          12156          1
atac_T19-91014#AAACGAATCGATGTAC-1          29824          1
atac_T19-91014#AAACTCGAGAGAATTC-1          10380          1
atac_T19-91014#AAACTCGAGTGTCCCG-1          44860          1
atac_T19-91014#AAACTCGCAACGTAGG-1          34919          1
atac_T19-91014#AAACTCGCACGCTGTG-1          12527          1
atac_T19-91014#AAACTCGCAGAACAGC-1          15642          1
atac_T19-91014#AAACTCGGTAAACGTA-1          28010          1
atac_T19-91014#AAACTCGGTAGCATGG-1          31837          1
atac_T19-91014#AAACTCGTCCATGACA-1          64151          1
atac_T19-91014#AAACTCGTCTGCGTCT-1          12992          1
atac_T19-91014#AAACTGCAGGAGTACC-1          65015          1
atac_T19-91014#AAACTGCAGGCGCTTC-1          67625          1
atac_T19-91014#AAACTGCAGTAGTGTA-1          18257          1
atac_T19-91014#AAACTGCAGTCGTATC-1          13747          1
atac_T19-91014#AAACTGCAGTTCGACT-1          13432          1
atac_T19-91014#AAACTGCCAGAACAGC-1          25913          1
atac_T19-91014#AAACTGCCATTAGCCA-1          20217          1
atac_T19-91014#AAACTGCGTACGGTTT-1          25370          1
atac_T19-91014#AAACTGCGTAGCCATT-1          13350          1
atac_T19-91014#AAACTGCGTAGCGGTA-1          26614          1
atac_T19-91014#AAACTGCGTCAAATCC-1          17551          1
⋮                                          ⋮              ⋮
multiome_P-6774_S-10146#TTTGGTAAGCCTGATG-1 15768          NaN
multiome_P-6774_S-10146#TTTGGTAAGGATTGAG-1 12412          NaN
multiome_P-6774_S-10146#TTTGGTAAGGGTGGAT-1 18707          NaN
multiome_P-6774_S-10146#TTTGGTAAGTTGTCCC-1 18129          NaN
multiome_P-6774_S-10146#TTTGGTGCAACTGGCT-1 21516          NaN
multiome_P-6774_S-10146#TTTGGTGCACATACTG-1 18350          NaN
multiome_P-6774_S-10146#TTTGGTGCACTTCATC-1 11574          NaN
multiome_P-6774_S-10146#TTTGGTGCAGCAATAA-1 23060          NaN
multiome_P-6774_S-10146#TTTGTCCCAACCCTCC-1 19379          NaN
multiome_P-6774_S-10146#TTTGTCCCACTAAATC-1 31700          NaN
multiome_P-6774_S-10146#TTTGTCCCATGGCCCA-1 32602          NaN
multiome_P-6774_S-10146#TTTGTCTAGGAGTCTT-1 11530          NaN
multiome_P-6774_S-10146#TTTGTCTAGGCAACAA-1 11947          NaN
multiome_P-6774_S-10146#TTTGTGAAGATGGAGC-1 12217          NaN
multiome_P-6774_S-10146#TTTGTGAAGCCGCAGT-1 21463          NaN
multiome_P-6774_S-10146#TTTGTGAAGTTAGCTA-1 26209          NaN
multiome_P-6774_S-10146#TTTGTGGCAAGGAATC-1 20441          NaN
multiome_P-6774_S-10146#TTTGTGGCAAGGTACG-1 11446          NaN
multiome_P-6774_S-10146#TTTGTGGCACCTCGCT-1 34517          NaN
multiome_P-6774_S-10146#TTTGTGGCACGTAATT-1 24198          NaN
multiome_P-6774_S-10146#TTTGTGGCACTTGTTC-1  8277          NaN
multiome_P-6774_S-10146#TTTGTGGCAGCAAATA-1 16441          NaN
multiome_P-6774_S-10146#TTTGTGGCAGCAACAG-1 15111          NaN
multiome_P-6774_S-10146#TTTGTGGCATGCTATG-1 18696          NaN
multiome_P-6774_S-10146#TTTGTGGCATTATGAC-1 17253          NaN
multiome_P-6774_S-10146#TTTGTGTTCCTAGTAA-1 18200          NaN
multiome_P-6774_S-10146#TTTGTTGGTAGGATTT-1 29320          NaN
multiome_P-6774_S-10146#TTTGTTGGTTGGATAT-1  7108          NaN
multiome_P-6774_S-10146#TTTGTTGGTTGTAACG-1 17184          NaN
multiome_P-6774_S-10146#TTTGTTGGTTTATCGC-1 38130          NaN
                                           excluded_reason ⋯ louvain_1_3
atac_T19-91014#AAACGAAAGACCCTAT-1          0               ⋯ 16
atac_T19-91014#AAACGAAAGTGTAATG-1          0               ⋯ 16
atac_T19-91014#AAACGAACAAATGCTC-1          0               ⋯ 1
atac_T19-91014#AAACGAACACGCCGAT-1          0               ⋯ 16
atac_T19-91014#AAACGAAGTACGGAGT-1          0               ⋯ 16
atac_T19-91014#AAACGAAGTATCCCTC-1          0               ⋯ 1
atac_T19-91014#AAACGAAGTATCTCAG-1          0               ⋯ 17
atac_T19-91014#AAACGAAGTCAGACGA-1          0               ⋯ 16
atac_T19-91014#AAACGAAGTGAAACAT-1          0               ⋯ 16
atac_T19-91014#AAACGAATCGATGTAC-1          0               ⋯ 1
atac_T19-91014#AAACTCGAGAGAATTC-1          0               ⋯ 16
atac_T19-91014#AAACTCGAGTGTCCCG-1          0               ⋯ 16
atac_T19-91014#AAACTCGCAACGTAGG-1          0               ⋯ 7
atac_T19-91014#AAACTCGCACGCTGTG-1          0               ⋯ 17
atac_T19-91014#AAACTCGCAGAACAGC-1          0               ⋯ 17
atac_T19-91014#AAACTCGGTAAACGTA-1          0               ⋯ 20
atac_T19-91014#AAACTCGGTAGCATGG-1          0               ⋯ 16
atac_T19-91014#AAACTCGTCCATGACA-1          0               ⋯ 7
atac_T19-91014#AAACTCGTCTGCGTCT-1          0               ⋯ 16
atac_T19-91014#AAACTGCAGGAGTACC-1          0               ⋯ 15
atac_T19-91014#AAACTGCAGGCGCTTC-1          0               ⋯ 16
atac_T19-91014#AAACTGCAGTAGTGTA-1          0               ⋯ 15
atac_T19-91014#AAACTGCAGTCGTATC-1          0               ⋯ 15
atac_T19-91014#AAACTGCAGTTCGACT-1          0               ⋯ 20
atac_T19-91014#AAACTGCCAGAACAGC-1          0               ⋯ 1
atac_T19-91014#AAACTGCCATTAGCCA-1          0               ⋯ 1
atac_T19-91014#AAACTGCGTACGGTTT-1          0               ⋯ 1
atac_T19-91014#AAACTGCGTAGCCATT-1          0               ⋯ 16
atac_T19-91014#AAACTGCGTAGCGGTA-1          0               ⋯ 3
atac_T19-91014#AAACTGCGTCAAATCC-1          0               ⋯ 1
⋮                                          ⋮               ⋱ ⋮
multiome_P-6774_S-10146#TTTGGTAAGCCTGATG-1 0               ⋯ 5
multiome_P-6774_S-10146#TTTGGTAAGGATTGAG-1 0               ⋯ 5
multiome_P-6774_S-10146#TTTGGTAAGGGTGGAT-1 0               ⋯ 4
multiome_P-6774_S-10146#TTTGGTAAGTTGTCCC-1 2               ⋯ 5
multiome_P-6774_S-10146#TTTGGTGCAACTGGCT-1 0               ⋯ 5
multiome_P-6774_S-10146#TTTGGTGCACATACTG-1 0               ⋯ 5
multiome_P-6774_S-10146#TTTGGTGCACTTCATC-1 2               ⋯ 5
multiome_P-6774_S-10146#TTTGGTGCAGCAATAA-1 0               ⋯ 5
multiome_P-6774_S-10146#TTTGTCCCAACCCTCC-1 0               ⋯ 5
multiome_P-6774_S-10146#TTTGTCCCACTAAATC-1 0               ⋯ 9
multiome_P-6774_S-10146#TTTGTCCCATGGCCCA-1 2               ⋯ 5
multiome_P-6774_S-10146#TTTGTCTAGGAGTCTT-1 0               ⋯ 5
multiome_P-6774_S-10146#TTTGTCTAGGCAACAA-1 2               ⋯ 4
multiome_P-6774_S-10146#TTTGTGAAGATGGAGC-1 0               ⋯ 4
multiome_P-6774_S-10146#TTTGTGAAGCCGCAGT-1 2               ⋯ 5
multiome_P-6774_S-10146#TTTGTGAAGTTAGCTA-1 0               ⋯ 5
multiome_P-6774_S-10146#TTTGTGGCAAGGAATC-1 2               ⋯ 23
multiome_P-6774_S-10146#TTTGTGGCAAGGTACG-1 0               ⋯ 21
multiome_P-6774_S-10146#TTTGTGGCACCTCGCT-1 2               ⋯ 4
multiome_P-6774_S-10146#TTTGTGGCACGTAATT-1 0               ⋯ 5
multiome_P-6774_S-10146#TTTGTGGCACTTGTTC-1 0               ⋯ 11
multiome_P-6774_S-10146#TTTGTGGCAGCAAATA-1 0               ⋯ 5
multiome_P-6774_S-10146#TTTGTGGCAGCAACAG-1 2               ⋯ 23
multiome_P-6774_S-10146#TTTGTGGCATGCTATG-1 0               ⋯ 12
multiome_P-6774_S-10146#TTTGTGGCATTATGAC-1 0               ⋯ 5
multiome_P-6774_S-10146#TTTGTGTTCCTAGTAA-1 2               ⋯ 5
multiome_P-6774_S-10146#TTTGTTGGTAGGATTT-1 0               ⋯ 5
multiome_P-6774_S-10146#TTTGTTGGTTGGATAT-1 2               ⋯ 5
multiome_P-6774_S-10146#TTTGTTGGTTGTAACG-1 0               ⋯ 5
multiome_P-6774_S-10146#TTTGTTGGTTTATCGC-1 2               ⋯ 4
                                           louvain_1_5 louvain_1_8 louvain_2
atac_T19-91014#AAACGAAAGACCCTAT-1          18          19          18
atac_T19-91014#AAACGAAAGTGTAATG-1          18          19          18
atac_T19-91014#AAACGAACAAATGCTC-1          1           20          16
atac_T19-91014#AAACGAACACGCCGAT-1          18          19          18
atac_T19-91014#AAACGAAGTACGGAGT-1          18          19          18
atac_T19-91014#AAACGAAGTATCCCTC-1          1           20          16
atac_T19-91014#AAACGAAGTATCTCAG-1          15          18          20
atac_T19-91014#AAACGAAGTCAGACGA-1          18          19          18
atac_T19-91014#AAACGAAGTGAAACAT-1          18          19          18
atac_T19-91014#AAACGAATCGATGTAC-1          19          20          16
atac_T19-91014#AAACTCGAGAGAATTC-1          18          19          18
atac_T19-91014#AAACTCGAGTGTCCCG-1          18          19          18
atac_T19-91014#AAACTCGCAACGTAGG-1          6           8           7
atac_T19-91014#AAACTCGCACGCTGTG-1          21          18          20
atac_T19-91014#AAACTCGCAGAACAGC-1          15          18          20
atac_T19-91014#AAACTCGGTAAACGTA-1          15          22          21
atac_T19-91014#AAACTCGGTAGCATGG-1          18          19          18
atac_T19-91014#AAACTCGTCCATGACA-1          6           8           7
atac_T19-91014#AAACTCGTCTGCGTCT-1          18          19          18
atac_T19-91014#AAACTGCAGGAGTACC-1          14          16          17
atac_T19-91014#AAACTGCAGGCGCTTC-1          18          2           18
atac_T19-91014#AAACTGCAGTAGTGTA-1          14          16          17
atac_T19-91014#AAACTGCAGTCGTATC-1          14          16          17
atac_T19-91014#AAACTGCAGTTCGACT-1          15          22          21
atac_T19-91014#AAACTGCCAGAACAGC-1          1           20          16
atac_T19-91014#AAACTGCCATTAGCCA-1          1           20          16
atac_T19-91014#AAACTGCGTACGGTTT-1          1           20          16
atac_T19-91014#AAACTGCGTAGCCATT-1          18          19          18
atac_T19-91014#AAACTGCGTAGCGGTA-1          3           2           1
atac_T19-91014#AAACTGCGTCAAATCC-1          1           20          16
⋮                                          ⋮           ⋮           ⋮
multiome_P-6774_S-10146#TTTGGTAAGCCTGATG-1 5           5           5
multiome_P-6774_S-10146#TTTGGTAAGGATTGAG-1 5           5           5
multiome_P-6774_S-10146#TTTGGTAAGGGTGGAT-1 17          17          23
multiome_P-6774_S-10146#TTTGGTAAGTTGTCCC-1 5           5           5
multiome_P-6774_S-10146#TTTGGTGCAACTGGCT-1 5           5           5
multiome_P-6774_S-10146#TTTGGTGCACATACTG-1 5           5           5
multiome_P-6774_S-10146#TTTGGTGCACTTCATC-1 5           5           5
multiome_P-6774_S-10146#TTTGGTGCAGCAATAA-1 5           5           5
multiome_P-6774_S-10146#TTTGTCCCAACCCTCC-1 5           5           5
multiome_P-6774_S-10146#TTTGTCCCACTAAATC-1 12          11          10
multiome_P-6774_S-10146#TTTGTCCCATGGCCCA-1 5           5           5
multiome_P-6774_S-10146#TTTGTCTAGGAGTCTT-1 5           5           5
multiome_P-6774_S-10146#TTTGTCTAGGCAACAA-1 17          17          23
multiome_P-6774_S-10146#TTTGTGAAGATGGAGC-1 17          17          23
multiome_P-6774_S-10146#TTTGTGAAGCCGCAGT-1 5           5           5
multiome_P-6774_S-10146#TTTGTGAAGTTAGCTA-1 5           5           5
multiome_P-6774_S-10146#TTTGTGGCAAGGAATC-1 17          17          23

In [ ]:
# Step 1: Create a new column for rownames
meta$rownames_col <- rownames(meta)

cellsAtlas <- proj$cellNames
# Step 2: Subset the dataframe based on the desired order
reordered_meta <- meta[match(cellsAtlas, meta$rownames_col), ]

# Step 3: Remove the column containing rownames
reordered_meta$rownames_col <- NULL

reordered_meta

                                           total  duplicate chimeric unmapped
atac_MUV1#CCCTAACCATGGAGGT-1               124697 4651       8       2051
atac_MUV1#GGGTCTGTCGGAGTTT-1               122083 4803      11       2213
atac_MUV1#GTGTCCTGTGAGTCGA-1               120397 5377       8       2192
atac_MUV1#AGCTGATCATGTATCG-1               112203 6126      16       2204
atac_MUV1#GTGTCAAGTATCGCGC-1               106030 3618      28       1759
atac_MUV1#CAAAGCTCAGCGTGAA-1               110002 5461      21       1919
atac_MUV1#ATCCTGCCATTCGTCC-1               105518 3587      17       1751
atac_MUV1#TCCAGAACACACATGT-1               108735 4566      15       1938
atac_MUV1#GAGATTCCACGTTGTA-1               104994 4461      27       2027
atac_MUV1#TTGAGCACATAGCAGG-1               106143 4538       8       1910
atac_MUV1#TGCACCTCAGACTAAA-1               101999 5594      14       1735
atac_MUV1#TTGTTCACAAGGACCA-1                95729 4314      11       1615
atac_MUV1#GCACGGTCAGTTACAC-1                90325 4557      10       1397
atac_MUV1#TTACCGCGTCATGAGG-1                91160 3494      17       1519
atac_MUV1#TTGCGGGAGAACGTCG-1                93997 3946      17       1644
atac_MUV1#TAGGTGTAGGGTTCTT-1                90340 3671       9       1776
atac_MUV1#TAATCGGCATGGTTTG-1                98463 7513      38       2256
atac_MUV1#CACCACTAGGAAGGTA-1                84424 5247      15       1404
atac_MUV1#TTAGCTTTCCCACTAC-1                79725 4287      30       1459
atac_MUV1#CAGTATGCACTGATTG-1                79683 3032      12       1488
atac_MUV1#CTTGCCACATGGCCCA-1                80199 3869      14       1449
atac_MUV1#AACTGTGTCGTGAACT-1                74277 3914       9       1307
atac_MUV1#GAACCGCAGTTCCCGG-1                71770 3569       8       1030
atac_MUV1#CATAACGTCGTATAGC-1                68393 4454       0        964
atac_MUV1#CATTCCGTCGAGGTAG-1                70114 5629      14       1214
atac_MUV1#CGCAATAAGACGTCAG-1                65289 4134       6       1076
atac_MUV1#ATGTTTCTCTGTTTAC-1                66732 3013       9       1417
atac_MUV1#TCAAGCATCGTGCTGG-1                65204 4556      14       1115
atac_MUV1#GCGAGTCGTAAGTCTC-1                66334 3007       8       1281
atac_MUV1#TAGCCCTCACGGCCAT-1                67756 4276      23       1294
⋮                                          ⋮      ⋮         ⋮        ⋮
multiome_P-6774_S-10146#AACTTAGTCAAGCGCC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TCGCCCATCCCTGGAA-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#CAGCCTTTCACATTGA-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#GCTAAGAAGCAACAAG-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#AAGTCTATCTACCTAT-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#GCCAATAGTCCACAAA-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#GTACAATGTGGTTCCC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#GTGTTCCTCATTTAGG-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTAGGATGTCATTGAG-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#GGGCATTGTTATCCTA-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#CAGAACCGTGTAACCA-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#AGCAGGTAGCGTGCAC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#GGTCTTTGTTAAGCTG-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#ATCGCTTGTACGGTAC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#ACGTTACAGTTACTTC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TTATGCGCAGAAATGC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#AGAATCTGTTCAAGAT-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TCTCAAGCATGTCAAT-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#AACTTAGTCCTGTTCA-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#CCTTGTTCAGTTAGCC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#GCGCTAGGTTGCGGAT-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#GCTGATCCAATAGCCC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TGCTAACAGAACCTGT-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#TATCGCACATATTGAC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#ATTTAGCCATGTCAAT-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#CACAATATCTAACCTT-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#GATCGATTCATTTGTC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#GCTATCCTCGATAACC-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#AATTGCTCAGCTAATT-1 NaN    NaN       NaN      NaN
multiome_P-6774_S-10146#CTAAAGCTCCTTGAGG-1 NaN    NaN       NaN      NaN
                                           lowmapq mitochondrial nonprimary
atac_MUV1#CCCTAACCATGGAGGT-1               21081     73          208
atac_MUV1#GGGTCTGTCGGAGTTT-1               22104     34          186
atac_MUV1#GTGTCCTGTGAGTCGA-1               21577     38          117
atac_MUV1#AGCTGATCATGTATCG-1               17882    414          105
atac_MUV1#GTGTCAAGTATCGCGC-1               15555    219           97
atac_MUV1#CAAAGCTCAGCGTGAA-1               15981   1961           61
atac_MUV1#ATCCTGCCATTCGTCC-1               17431     43          154
atac_MUV1#TCCAGAACACACATGT-1               19875     48          211
atac_MUV1#GAGATTCCACGTTGTA-1               16157   1106           84
atac_MUV1#TTGAGCACATAGCAGG-1               18945     95          172
atac_MUV1#TGCACCTCAGACTAAA-1               15733     33          256
atac_MUV1#TTGTTCACAAGGACCA-1               17171     87          146
atac_MUV1#GCACGGTCAGTTACAC-1               12097     20          149
atac_MUV1#TTACCGCGTCATGAGG-1               14475     81          101
atac_MUV1#TTGCGGGAGAACGTCG-1               16639    254          150
atac_MUV1#TAGGTGTAGGGTTCTT-1               14421     79          129
atac_MUV1#TAATCGGCATGGTTTG-1               16113   4706           91
atac_MUV1#CACCACTAGGAAGGTA-1               12872    103          113
atac_MUV1#TTAGCTTTCCCACTAC-1               10923    240           57
atac_MUV1#CAGTATGCACTGATTG-1               13834    225          132
atac_MUV1#CTTGCCACATGGCCCA-1               13691     33          213
atac_MUV1#AACTGTGTCGTGAACT-1                9862    285           36
atac_MUV1#GAACCGCAGTTCCCGG-1                9723     24           16
atac_MUV1#CATAACGTCGTATAGC-1               10072     14           36
atac_MUV1#CATTCCGTCGAGGTAG-1                9885    573           55
atac_MUV1#CGCAATAAGACGTCAG-1                8076    197           27
atac_MUV1#ATGTTTCTCTGTTTAC-1               11461     41          147
atac_MUV1#TCAAGCATCGTGCTGG-1                8557    515           13
atac_MUV1#GCGAGTCGTAAGTCTC-1               11483     39          137
atac_MUV1#TAGCCCTCACGGCCAT-1               10208   1640           29
⋮                                          ⋮       ⋮             ⋮
multiome_P-6774_S-10146#AACTTAGTCAAGCGCC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TCGCCCATCCCTGGAA-1 NaN     NaN           NaN
multiome_P-6774_S-10146#CAGCCTTTCACATTGA-1 NaN     NaN           NaN
multiome_P-6774_S-10146#GCTAAGAAGCAACAAG-1 NaN     NaN           NaN
multiome_P-6774_S-10146#AAGTCTATCTACCTAT-1 NaN     NaN           NaN
multiome_P-6774_S-10146#GCCAATAGTCCACAAA-1 NaN     NaN           NaN
multiome_P-6774_S-10146#GTACAATGTGGTTCCC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#GTGTTCCTCATTTAGG-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTAGGATGTCATTGAG-1 NaN     NaN           NaN
multiome_P-6774_S-10146#GGGCATTGTTATCCTA-1 NaN     NaN           NaN
multiome_P-6774_S-10146#CAGAACCGTGTAACCA-1 NaN     NaN           NaN
multiome_P-6774_S-10146#AGCAGGTAGCGTGCAC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#GGTCTTTGTTAAGCTG-1 NaN     NaN           NaN
multiome_P-6774_S-10146#ATCGCTTGTACGGTAC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#ACGTTACAGTTACTTC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TTATGCGCAGAAATGC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#AGAATCTGTTCAAGAT-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TCTCAAGCATGTCAAT-1 NaN     NaN           NaN
multiome_P-6774_S-10146#AACTTAGTCCTGTTCA-1 NaN     NaN           NaN
multiome_P-6774_S-10146#CCTTGTTCAGTTAGCC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#GCGCTAGGTTGCGGAT-1 NaN     NaN           NaN
multiome_P-6774_S-10146#GCTGATCCAATAGCCC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TGCTAACAGAACCTGT-1 NaN     NaN           NaN
multiome_P-6774_S-10146#TATCGCACATATTGAC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#ATTTAGCCATGTCAAT-1 NaN     NaN           NaN
multiome_P-6774_S-10146#CACAATATCTAACCTT-1 NaN     NaN           NaN
multiome_P-6774_S-10146#GATCGATTCATTTGTC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#GCTATCCTCGATAACC-1 NaN     NaN           NaN
multiome_P-6774_S-10146#AATTGCTCAGCTAATT-1 NaN     NaN           NaN
multiome_P-6774_S-10146#CTAAAGCTCCTTGAGG-1 NaN     NaN           NaN
                                           passed_filters is__cell_barcode
atac_MUV1#CCCTAACCATGGAGGT-1               96625          1
atac_MUV1#GGGTCTGTCGGAGTTT-1               92732          1
atac_MUV1#GTGTCCTGTGAGTCGA-1               91088          1
atac_MUV1#AGCTGATCATGTATCG-1               85456          1
atac_MUV1#GTGTCAAGTATCGCGC-1               84754          1
atac_MUV1#CAAAGCTCAGCGTGAA-1               84598          1
atac_MUV1#ATCCTGCCATTCGTCC-1               82535          1
atac_MUV1#TCCAGAACACACATGT-1               82082          1
atac_MUV1#GAGATTCCACGTTGTA-1               81132          1
atac_MUV1#TTGAGCACATAGCAGG-1               80475          1
atac_MUV1#TGCACCTCAGACTAAA-1               78634          1
atac_MUV1#TTGTTCACAAGGACCA-1               72385          1
atac_MUV1#GCACGGTCAGTTACAC-1               72095          1
atac_MUV1#TTACCGCGTCATGAGG-1               71473          1
atac_MUV1#TTGCGGGAGAACGTCG-1               71347          1
atac_MUV1#TAGGTGTAGGGTTCTT-1               70255          0
atac_MUV1#TAATCGGCATGGTTTG-1               67746          1
atac_MUV1#CACCACTAGGAAGGTA-1               64670          1
atac_MUV1#TTAGCTTTCCCACTAC-1               62729          1
atac_MUV1#CAGTATGCACTGATTG-1               60960          1
atac_MUV1#CTTGCCACATGGCCCA-1               60930          1
atac_MUV1#AACTGTGTCGTGAACT-1               58864          1
atac_MUV1#GAACCGCAGTTCCCGG-1               57400          1
atac_MUV1#CATAACGTCGTATAGC-1               52853          1
atac_MUV1#CATTCCGTCGAGGTAG-1               52744          1
atac_MUV1#CGCAATAAGACGTCAG-1               51773          1
atac_MUV1#ATGTTTCTCTGTTTAC-1               50644          1
atac_MUV1#TCAAGCATCGTGCTGG-1               50434          1
atac_MUV1#GCGAGTCGTAAGTCTC-1               50379          1
atac_MUV1#TAGCCCTCACGGCCAT-1               50286          1
⋮                                          ⋮              ⋮
multiome_P-6774_S-10146#AACTTAGTCAAGCGCC-1 2291           NaN
multiome_P-6774_S-10146#TCGCCCATCCCTGGAA-1 2265           NaN
multiome_P-6774_S-10146#CAGCCTTTCACATTGA-1 2239           NaN
multiome_P-6774_S-10146#GCTAAGAAGCAACAAG-1 2244           NaN
multiome_P-6774_S-10146#AAGTCTATCTACCTAT-1 2218           NaN
multiome_P-6774_S-10146#GCCAATAGTCCACAAA-1 2181           NaN
multiome_P-6774_S-10146#GTACAATGTGGTTCCC-1 2173           NaN
multiome_P-6774_S-10146#GTGTTCCTCATTTAGG-1 2173           NaN
multiome_P-6774_S-10146#TTAGGATGTCATTGAG-1 2148           NaN
multiome_P-6774_S-10146#GGGCATTGTTATCCTA-1 2109           NaN
multiome_P-6774_S-10146#CAGAACCGTGTAACCA-1 2023           NaN
multiome_P-6774_S-10146#AGCAGGTAGCGTGCAC-1 1955           NaN
multiome_P-6774_S-10146#GGTCTTTGTTAAGCTG-1 1721           NaN
multiome_P-6774_S-10146#ATCGCTTGTACGGTAC-1 1688           NaN
multiome_P-6774_S-10146#ACGTTACAGTTACTTC-1 1652           NaN
multiome_P-6774_S-10146#TTATGCGCAGAAATGC-1 1640           NaN
multiome_P-6774_S-10146#AGAATCTGTTCAAGAT-1  872           NaN
multiome_P-6774_S-10146#TCTCAAGCATGTCAAT-1  836           NaN
multiome_P-6774_S-10146#AACTTAGTCCTGTTCA-1  819           NaN
multiome_P-6774_S-10146#CCTTGTTCAGTTAGCC-1  770           NaN
multiome_P-6774_S-10146#GCGCTAGGTTGCGGAT-1  759           NaN
multiome_P-6774_S-10146#GCTGATCCAATAGCCC-1  754           NaN
multiome_P-6774_S-10146#TGCTAACAGAACCTGT-1  754           NaN
multiome_P-6774_S-10146#TATCGCACATATTGAC-1  746           NaN
multiome_P-6774_S-10146#ATTTAGCCATGTCAAT-1  694           NaN
multiome_P-6774_S-10146#CACAATATCTAACCTT-1  667           NaN
multiome_P-6774_S-10146#GATCGATTCATTTGTC-1  643           NaN
multiome_P-6774_S-10146#GCTATCCTCGATAACC-1  627           NaN
multiome_P-6774_S-10146#AATTGCTCAGCTAATT-1  610           NaN
multiome_P-6774_S-10146#CTAAAGCTCCTTGAGG-1  512           NaN
                                           excluded_reason ⋯ louvain_1_3
atac_MUV1#CCCTAACCATGGAGGT-1               0               ⋯ 23
atac_MUV1#GGGTCTGTCGGAGTTT-1               0               ⋯ 23
atac_MUV1#GTGTCCTGTGAGTCGA-1               0               ⋯ 23
atac_MUV1#AGCTGATCATGTATCG-1               0               ⋯ 9
atac_MUV1#GTGTCAAGTATCGCGC-1               0               ⋯ 23
atac_MUV1#CAAAGCTCAGCGTGAA-1               0               ⋯ 1
atac_MUV1#ATCCTGCCATTCGTCC-1               0               ⋯ 23
atac_MUV1#TCCAGAACACACATGT-1               0               ⋯ 1
atac_MUV1#GAGATTCCACGTTGTA-1               0               ⋯ 23
atac_MUV1#TTGAGCACATAGCAGG-1               0               ⋯ 23
atac_MUV1#TGCACCTCAGACTAAA-1               0               ⋯ 1
atac_MUV1#TTGTTCACAAGGACCA-1               0               ⋯ 23
atac_MUV1#GCACGGTCAGTTACAC-1               0               ⋯ 13
atac_MUV1#TTACCGCGTCATGAGG-1               0               ⋯ 23
atac_MUV1#TTGCGGGAGAACGTCG-1               0               ⋯ 23
atac_MUV1#TAGGTGTAGGGTTCTT-1               1               ⋯ 23
atac_MUV1#TAATCGGCATGGTTTG-1               0               ⋯ 1
atac_MUV1#CACCACTAGGAAGGTA-1               0               ⋯ 23
atac_MUV1#TTAGCTTTCCCACTAC-1               0               ⋯ 3
atac_MUV1#CAGTATGCACTGATTG-1               0               ⋯ 23
atac_MUV1#CTTGCCACATGGCCCA-1               0               ⋯ 23
atac_MUV1#AACTGTGTCGTGAACT-1               0               ⋯ 4
atac_MUV1#GAACCGCAGTTCCCGG-1               0               ⋯ 23
atac_MUV1#CATAACGTCGTATAGC-1               0               ⋯ 4
atac_MUV1#CATTCCGTCGAGGTAG-1               0               ⋯ 3
atac_MUV1#CGCAATAAGACGTCAG-1               0               ⋯ 3
atac_MUV1#ATGTTTCTCTGTTTAC-1               0               ⋯ 23
atac_MUV1#TCAAGCATCGTGCTGG-1               0               ⋯ 1
atac_MUV1#GCGAGTCGTAAGTCTC-1               0               ⋯ 23
atac_MUV1#TAGCCCTCACGGCCAT-1               0               ⋯ 1
⋮                                          ⋮               ⋱ ⋮
multiome_P-6774_S-10146#AACTTAGTCAAGCGCC-1 0               ⋯ 5
multiome_P-6774_S-10146#TCGCCCATCCCTGGAA-1 0               ⋯ 5
multiome_P-6774_S-10146#CAGCCTTTCACATTGA-1 0               ⋯ 5
multiome_P-6774_S-10146#GCTAAGAAGCAACAAG-1 0               ⋯ 5
multiome_P-6774_S-10146#AAGTCTATCTACCTAT-1 0               ⋯ 5
multiome_P-6774_S-10146#GCCAATAGTCCACAAA-1 0               ⋯ 5
multiome_P-6774_S-10146#GTACAATGTGGTTCCC-1 0               ⋯ 10
multiome_P-6774_S-10146#GTGTTCCTCATTTAGG-1 0               ⋯ 5
multiome_P-6774_S-10146#TTAGGATGTCATTGAG-1 0               ⋯ 5
multiome_P-6774_S-10146#GGGCATTGTTATCCTA-1 0               ⋯ 3
multiome_P-6774_S-10146#CAGAACCGTGTAACCA-1 0               ⋯ 21
multiome_P-6774_S-10146#AGCAGGTAGCGTGCAC-1 0               ⋯ 2
multiome_P-6774_S-10146#GGTCTTTGTTAAGCTG-1 0               ⋯ 9
multiome_P-6774_S-10146#ATCGCTTGTACGGTAC-1 0               ⋯ 3
multiome_P-6774_S-10146#ACGTTACAGTTACTTC-1 0               ⋯ 4
multiome_P-6774_S-10146#TTATGCGCAGAAATGC-1 0               ⋯ 10
multiome_P-6774_S-10146#AGAATCTGTTCAAGAT-1 0               ⋯ 6
multiome_P-6774_S-10146#TCTCAAGCATGTCAAT-1 0               ⋯ 20
multiome_P-6774_S-10146#AACTTAGTCCTGTTCA-1 0               ⋯ 6
multiome_P-6774_S-10146#CCTTGTTCAGTTAGCC-1 0               ⋯ 6
multiome_P-6774_S-10146#GCGCTAGGTTGCGGAT-1 0               ⋯ 6
multiome_P-6774_S-10146#GCTGATCCAATAGCCC-1 0               ⋯ 10
multiome_P-6774_S-10146#TGCTAACAGAACCTGT-1 0               ⋯ 6
multiome_P-6774_S-10146#TATCGCACATATTGAC-1 0               ⋯ 6
multiome_P-6774_S-10146#ATTTAGCCATGTCAAT-1 0               ⋯ 3
multiome_P-6774_S-10146#CACAATATCTAACCTT-1 0               ⋯ 6
multiome_P-6774_S-10146#GATCGATTCATTTGTC-1 0               ⋯ 19
multiome_P-6774_S-10146#GCTATCCTCGATAACC-1 0               ⋯ 6
multiome_P-6774_S-10146#AATTGCTCAGCTAATT-1 0               ⋯ 3
multiome_P-6774_S-10146#CTAAAGCTCCTTGAGG-1 0               ⋯ 16
                                           louvain_1_5 louvain_1_8 louvain_2
atac_MUV1#CCCTAACCATGGAGGT-1               17          17          23
atac_MUV1#GGGTCTGTCGGAGTTT-1               17          17          23
atac_MUV1#GTGTCCTGTGAGTCGA-1               17          17          23
atac_MUV1#AGCTGATCATGTATCG-1               17          11          10
atac_MUV1#GTGTCAAGTATCGCGC-1               17          17          23
atac_MUV1#CAAAGCTCAGCGTGAA-1               1           3           6
atac_MUV1#ATCCTGCCATTCGTCC-1               17          17          23
atac_MUV1#TCCAGAACACACATGT-1               1           3           6
atac_MUV1#GAGATTCCACGTTGTA-1               17          17          23
atac_MUV1#TTGAGCACATAGCAGG-1               17          17          23
atac_MUV1#TGCACCTCAGACTAAA-1               1           3           6
atac_MUV1#TTGTTCACAAGGACCA-1               17          17          23
atac_MUV1#GCACGGTCAGTTACAC-1               13          13          23
atac_MUV1#TTACCGCGTCATGAGG-1               17          17          23
atac_MUV1#TTGCGGGAGAACGTCG-1               17          17          23
atac_MUV1#TAGGTGTAGGGTTCTT-1               17          17          23
atac_MUV1#TAATCGGCATGGTTTG-1               1           3           7
atac_MUV1#CACCACTAGGAAGGTA-1               17          17          23
atac_MUV1#TTAGCTTTCCCACTAC-1               3           2           1
atac_MUV1#CAGTATGCACTGATTG-1               17          17          23
atac_MUV1#CTTGCCACATGGCCCA-1               17          17          23
atac_MUV1#AACTGTGTCGTGAACT-1               17          17          23
atac_MUV1#GAACCGCAGTTCCCGG-1               17          17          23
atac_MUV1#CATAACGTCGTATAGC-1               17          17          23
atac_MUV1#CATTCCGTCGAGGTAG-1               3           2           1
atac_MUV1#CGCAATAAGACGTCAG-1               23          25          25
atac_MUV1#ATGTTTCTCTGTTTAC-1               17          17          23
atac_MUV1#TCAAGCATCGTGCTGG-1               1           3           6
atac_MUV1#GCGAGTCGTAAGTCTC-1               17          17          23
atac_MUV1#TAGCCCTCACGGCCAT-1               1           3           7
⋮                                          ⋮           ⋮           ⋮
multiome_P-6774_S-10146#AACTTAGTCAAGCGCC-1 5           5           5
multiome_P-6774_S-10146#TCGCCCATCCCTGGAA-1 8           7           9
multiome_P-6774_S-10146#CAGCCTTTCACATTGA-1 5           5           5
multiome_P-6774_S-10146#GCTAAGAAGCAACAAG-1 5           5           5
multiome_P-6774_S-10146#AAGTCTATCTACCTAT-1 5           5           5
multiome_P-6774_S-10146#GCCAATAGTCCACAAA-1 5           5           5
multiome_P-6774_S-10146#GTACAATGTGGTTCCC-1 8           7           9
multiome_P-6774_S-10146#GTGTTCCTCATTTAGG-1 5           5           5
multiome_P-6774_S-10146#TTAGGATGTCATTGAG-1 5           7           9
multiome_P-6774_S-10146#GGGCATTGTTATCCTA-1 3           2           1
multiome_P-6774_S-10146#CAGAACCGTGTAACCA-1 22          24          24
multiome_P-6774_S-10146#AGCAGGTAGCGTGCAC-1 5           5           5
multiome_P-6774_S-10146#GGTCTTTGTTAAGCTG-1 12          11          10
multiome_P-6774_S-10146#ATCGCTTGTACGGTAC-1 3           2           1
multiome_P-6774_S-10146#ACGTTACAGTTACTTC-1 17          17          23
multiome_P-6774_S-10146#TTATGCGCAGAAATGC-1 8           7           26
multiome_P-6774_S-10146#AGAATCTGTTCAAGAT-1 9           10          11

In [ ]:
proj$MP <- reordered_meta$MP

## Export

In [ ]:
proj_name <- 'ArchR_malignant_seacells'

In [ ]:
dir.create(sprintf("%s/export", proj_name))
write.csv(getReducedDims(proj), sprintf('%s/export/svd.csv', proj_name), quote=FALSE)
write.csv(getCellColData(proj), sprintf('%s/export/cell_metadata.csv', proj_name), quote=FALSE)

In [ ]:
# Gene scores
gene.scores <- getMatrixFromProject(proj)
scores <- assays(gene.scores)[['GeneScoreMatrix']]
scores <- as.matrix(scores)
rownames(scores) <- rowData(gene.scores)$name
write.csv(scores, sprintf('%s/export/gene_scores.csv', proj_name), quote=FALSE)

ArchR logging to : ArchRLogs/ArchR-getMatrixFromProject-2adf50faf8df-Date-2024-08-22_Time-16-21-02.856503.log
If there is an issue, please report to github with logFile!

2024-08-22 16:22:11.104338 : Organizing colData, 1.137 mins elapsed.

2024-08-22 16:22:12.823112 : Organizing rowData, 1.166 mins elapsed.

2024-08-22 16:22:12.83337 : Organizing rowRanges, 1.166 mins elapsed.

2024-08-22 16:22:12.839598 : Organizing Assays (1 of 1), 1.166 mins elapsed.

2024-08-22 16:22:29.839011 : Constructing SummarizedExperiment, 1.45 mins elapsed.

2024-08-22 16:22:30.683867 : Finished Matrix Creation, 1.464 mins elapsed.

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 15.6 GiB”

In [ ]:
# Peak counts
peaks <- getPeakSet(proj)
peak.counts <- getMatrixFromProject(proj, 'PeakMatrix')

# Reorder peaks
# Chromosome order
chr_order <- sort(seqlevels(peaks))
reordered_features <- list()
for(chr in chr_order)
    reordered_features[[chr]] = peaks[seqnames(peaks) == chr]
reordered_features <- Reduce("c", reordered_features)

# Export counts
dir.create(sprintf("%s/export/peak_counts", proj_name))
counts <- assays(peak.counts)[['PeakMatrix']]
writeMM(counts, sprintf('%s/export/peak_counts/counts.mtx', proj_name))
write.csv(colnames(peak.counts), sprintf('%s/export/peak_counts/cells.csv', proj_name), quote=FALSE)
names(reordered_features) <- sprintf("Peak%d", 1:length(reordered_features))
write.csv(as.data.frame(reordered_features), sprintf('%s/export/peak_counts/peaks.csv', proj_name), quote=FALSE)

ArchR logging to : ArchRLogs/ArchR-getMatrixFromProject-2adf727c6f26-Date-2024-08-22_Time-16-44-42.0764.log
If there is an issue, please report to github with logFile!

2024-08-22 16:45:56.592337 : Organizing colData, 1.242 mins elapsed.

2024-08-22 16:45:57.394065 : Organizing rowData, 1.255 mins elapsed.

2024-08-22 16:45:57.421411 : Organizing rowRanges, 1.256 mins elapsed.

2024-08-22 16:45:57.451494 : Organizing Assays (1 of 1), 1.256 mins elapsed.

2024-08-22 16:46:18.237191 : Constructing SummarizedExperiment, 1.603 mins elapsed.

2024-08-22 16:46:19.539053 : Finished Matrix Creation, 1.624 mins elapsed.

NULL